### ISSUE TITLE
Invalid Docbook XML Ids

### ISSUE THREAD

**Issue by simonthum** [asciidoctor/asciidoctor#1112]
Hi,

I am getting e.g.

book.xml:356: validity error : xml:id : attribute value service-handling-package is not an
NCName
<section xml:id="service-handling-package">

meaning that either asciidoctor is falsely accepting dashes in section identifiers, or is missing the mangling from input  to output character range for Docbook.

Related to #928 and #930

**Comment by mojavelinux** [comment]
As it turns out, it's really DocBook that is being overly restrictive here. HTML5 allows an ID to have just about any character. So if we warned, it would make no sense for people not converting to DocBook.

Asciidoctor already removes characters which are not NCNames. If you decide to set the prefix to something other than underscore, then you have introduce the possibility that it will generate invalid IDs for DocBook. We can document this (which I plan to do), but there is no change I see that the processor should do.
