### ISSUE TITLE
code blocks with mismatched start/end lines never end

### ISSUE THREAD

**Issue by peff** [asciidoctor/asciidoctor#1133]
Given an input like:

```
-------
some preformatted content
--------

some regular content
```

where the start and end lines are not identical (the first has seven hyphens, while the latter has eight), we don't end the block at the ending line (and `some regular content` is part of the preformatted block). AFAIK, the behavior here is not explicitly documented by AsciiDoc, but regular AsciiDoc does end the block.

Git's documentation has run into this. It renders fine using AsciiDoc, but not on the git-scm.com site, which uses AsciiDoctor. A specific example is in https://github.com/git/git-scm.com/issues/447.

**Comment by mojavelinux** [comment]
Related to #923.

**Comment by mojavelinux** [comment]
OPEN QUESTION: should we warn if a comment block is open?

I think an unterminated comment block is a valid scenario and thus there should be no warning. An unterminated comment block simply means to disable the rest of the document.

**Comment by mojavelinux** [comment]
Actually, both Ruby and Java show an error when a multi-line docstring is unterminated. So maybe we should consider this an error in AsciiDoc as well.

**Comment by elextr** [comment]
In the formal syntax I consider _any_ unterminated block at end of file to be an error, especially as the length of delimiters must match, as that makes it relatively easy to accidentally make a mismatch.

Certainly the risk is minimised by users following the idiom of always using only four characters for delimiters, but that makes it even more likely for error if the user is forced to use more than four characters to avoid a clash with the block content, since it will only occur occasionally.

AFAIK all languages with delimited constructs consider it an error if the construct is not closed at end of input.  Usually this is not because an implementation couldn't be made to cope with a missing delimiter, but because it almost always indicates a user error.

**Comment by mojavelinux** [comment]
Agreed.

**Comment by elextr** [comment]
Also note my implementation has an opt-out warning of a possible closing delimiter that has a length mismatch.

**Comment by mojavelinux** [comment]
I almost enabled that switch in Asciidoctor. But I simply cannot find any good justification for why the delimiters would be mismatched. Given everything we do enforce, it seems very strange not to enforce that...and it just encourages bad behavior IMO. That's why I'll continue to enforce exact matches in Asciidoctor (the different now that we warn when there's a problem).

**Comment by elextr** [comment]
Oh, I didn't mean that the mismatched delimiter was accepted, I totally agree that they should match, just that you can get a warning which indicates where the possible closing delimiter is when you get the "unterminated block" error at end of input.

**Comment by mojavelinux** [comment]
Ah! Now I understand. In that case, :+1:

**Comment by mojavelinux** [comment]
The PR for this one is ready to go. It reports an error (to the logger) if any delimited block is unterminated, including comment blocks.

The error message currently reports the last line of file rather than where block started. Reporting where the block started will need to be the subject of a future enhancement (since we don't currently record that information). But we don't want that to hold up reporting the information we do know. cc: @graphitefriction

**Comment by elextr** [comment]
Good idea to go ahead first.

Identifying what is unterminated is tricky.  

Consider:
```
text 1
----
text 2
-----------
text 3
----
text 4
----
text 5
```
I intended text 2 and 4 to be in delimited blocks and text 1 3 and 5 to be outside, but I miscounted one delimiter (badly miscounted to make it obvious).

So it will be parsed as text 2 a line of dashes and text 3 in a delimited block, text 1 and text 4 outside a block, and text 5 in an unterminated block, even though its the block starting before text 2 that is unterminated.

Thats why I don't try to identify which block is unterminated, and instead give a warning on lines that might have been intended to be terminators, but which are the wrong length so they are treated as text.

**Comment by mojavelinux** [comment]
Yep, that's a trade-off of having a semi-structured language. When there's a syntax error, there's multiple ways to look at it.

What I mean by reporting the start is where we started capturing the current block. That doesn't necessarily equate to where the author intended it to start, but would at least provide enough forensic for the human to figure it out. AsciiDoc is definitely a language that requires participation from the author ;)
