### ISSUE TITLE
Set an option to configure number of whitespaces in indent (support tabsize attribute)

### ISSUE THREAD

**Issue by lordofthejars** [asciidoctor/asciidoctor#1170]
When using indent in code block, by default Asciidoctor transforms tabs to 4 spaces. Sometimes you may want to change tabs to 2 spaces for example.

It may be interesting to have a way (document attribute, code block parameter, ...) to set the number of spaces to be used.

**Comment by mojavelinux** [comment]
Related issue for reference: #841

**Comment by mojavelinux** [comment]
Although it's tempting to rename the attribute to `tabstop`, I think we should stick with `tabsize` to stay in alignment with AsciiDoc Python (and avoid confusion). The name is clear enough.

**Comment by mojavelinux** [comment]
Here's the related fix in Asciidoctor PDF: https://github.com/asciidoctor/asciidoctor-pdf/pull/244

**Comment by mojavelinux** [comment]
With the fix for this issue, tabs are always replaced with spaces in verbatim blocks (but not literal paragraphs) if the `tabsize` attribute is set on the document. It's no longer required to use the `indent` property to enable tab expansion.

If you want to disable tab expansion, don't set the `tabsize` attribute on the document or set the `tabsize` attribute on the block to 0 (or less).
