### ISSUE TITLE
incompatible character encodings: UTF-8 and US-ASCII

### ISSUE THREAD

**Issue by John0079** [asciidoctor/asciidoctor#1191]
when i enter the commands ：
  %asciidoctor manual.txt
 it appears err information, like following:
 incompatible character encodings: UTF-8 and US-ASCII
  Use --trace for backtrace
 i don't konw why, in fact this commands is executed on other computers well,  my computer system is WinXP, the ruby installtion package is rubyinstaller-1.9.3-p550

**Comment by oncletom** [comment]
I am facing this issue while setting the `toc-title` attribute. For example:

```bash
docker run -i --rm -e LANG=C.UTF-8 -v /path/to/docs:/documents asciidoctor/docker-asciidoctor sh -c "asciidoctor \
            -a data-uri \
            -a toc \
            -a toclevels=4 \
            -a toc-title='Table des matières'"

**Comment by mojavelinux** [comment]
@oncletom I see what the problem is in your case. We are not re-encoding attribute values passed from the commandline, which leads to an encoding mismatch. I'll look for places this needs to be corrected.

In the meantime, there are two ways to solve your issue:

1. Move the `toc-title` entry into the document
2. Change the `LANG` to `LANG=en_US.UTF-8` or `LANG=fr_FR.UTF-8`

By using `C.UTF-8`, it actually puts Ruby into US-ASCII mode, which causes all sorts of problems. You can see this by running `asciidoctor -V`. It's best to be specific about the language.

**Comment by mojavelinux** [comment]
That turned out to be a relative easy fix. We were accepting strings from the commandline but not re-encoding them in the case Ruby is not running in external UTF-8 (just like we do with files). I patched it up.

**Comment by oncletom** [comment]
:+1: ace! Thank you :-)

**Comment by oncletom** [comment]
@batmat I ended up building my own asciidoctor docker image, more minimalist as it does not require 3 or 4 different languages platforms to run a build (https://github.com/oncletom/asciidoctor).

**Comment by mojavelinux** [comment]
> Gonna see if there's a dedicated place to file that. Thanks!

See https://github.com/asciidoctor/docker-asciidoctor

**Comment by batmat** [comment]
@mojavelinux was already done, actually see below my previous comment. Thanks

**Comment by mojavelinux** [comment]
@batmat Super! Thanks!

**Comment by lfarah** [comment]
Hey @nerk, thank you so much! I'm not using asciidoctor but this helped me setting up [Danger](https://danger.systems/)
