### ISSUE TITLE
Add built-in attribute for C++ named cpp

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#1208]
The text `C++` is tricky text to type in AsciiDoc because it often gets misinterpreted as passthrough text (or regular monospace in compat mode) when there's another occurrence of `++` on the same line. This problem is usually solved by aliasing the text `C++` to an attribute and using an attribute reference instead.

```
:cpp: C++

{cpp} is a programming language.
```

Since the text `C++` is common in technical content, we should go ahead and provide this alias out of the box for convenience.

This proposed change addresses a question that came up in #1083.

**Comment by tkruse** [comment]
Hi,

I also had this problem when transforming html to asciidoc. I now look for a solution that helps to fix this problem:

```
<h1>Google C++ Style Guide</h1>
<p>C++ is the main development language  used by
many of Google's open-source projects. As every C++
programmer knows...</p>
```

still yields:
```
Google C++ Style Guide
----------------------

C++ is the main development language used by many of Google's
open-source projects. As every C++ programmer knows, 
```

so what do I need to do here to get reasonable output? I can search&replace ```C++``` -> {cpp} in the result, but this will mess up the title because the dashes do not match the line length. I look for an automated solution, of course. I can also modify the input html I guess, I will assume that is the solution unless you have a better one.

**Comment by tkruse** [comment]
hm, that also does not work, because it yields \{cpp} in the result.

**Comment by tkruse** [comment]
sorry, this should go to pandoc tracker

**Comment by MisterDA** [comment]
Could it be possible to add a word-joiner or a non-breaking space between the characters of `C++`? I got a paragraph where the first `C+` would be at the end of the line, and the last `+` on the following line.

**Comment by mojavelinux** [comment]
If you need that kind of customization, you can redefine the `cpp` attribute. The built-in attributes are just defaults.

In the future, please ask questions in the project chat at https://chat.asciidoctor.org rather than commenting on closed issues. Thanks.
