### ISSUE TITLE
Allow docinfo footer files to be in AsciiDoc syntax

### ISSUE THREAD

**Issue by kendall** [asciidoctor/asciidoctor#1240]
I want my foo-docinfo-footer.ad instead of foo-docinfo-footer.html because I want to re-use variables in my doc in the footer and, yeah, because HTML is the devil.

Sniffing the file extension should be sufficient for most cases.

**Comment by mojavelinux** [comment]
This is related to something I mentioned in #848. We'll eventually need a way to specify which extensions are AsciiDoc (sort of like a mime type) so that behavior that relies on AsciiDoc extensions can be tailored.

**Comment by mojavelinux** [comment]
This can now be accomplished using a DocinfoProcessor, which gives you a hook into the docinfo mechanism. I might try to prototype this as a DocinfoProcessor, even if we integrate the feature into core. For an example, see https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/lib/license-url-docinfoprocessor.rb.

**Comment by mojavelinux** [comment]
Keep in mind that you can use attribute references in HTML and XML docinfo files. There's also a way to control which substitutions are applied. See #405.

**Comment by mojavelinux** [comment]
I've added a sample extension to the lab. In doing so, I think I worked out what needs to happen to get this to work.

See https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/lib/asciidoc-docinfoprocessor.rb

**Comment by mojavelinux** [comment]
I did some prototyping on this issue and I've decided to defer it until at least 1.5.4. The reason is two fold. First, I've determined that we still have unanswered design questions to solve, so I don't want to rush through a fix before we get it right. Second, and more important, this functionality can already be achieved using a DocinfoProcessor. I've pushed a reference implementation to the extensions-lab.

The design issues are as follows:

1. Should we render the docinfo like an AsciiDoc table cell?
2. Should we look for the same AsciiDoc extension as the main file?
3. Should it be possible to disable this feature in case you want to handle it using a DocinfoProcessor instead?

**Comment by mojavelinux** [comment]
Given that there are many ways that an AsciiDoc file can be processed, I think this works best as an extension. The extension has access to the document model and can pass on whatever information is relevant for the use case. Putting something into core is likely going to be too generic to be useful. If, later, we decide that we can all agree that there is one true way for an AsciiDoc docinfo file to work, then we can reconsider.

**Comment by mojavelinux** [comment]
Marked as relocated since this functionality is available via the extensions lab.
