### ISSUE TITLE
Document how to get link text in quote citation

### ISSUE THREAD

**Issue by kytrinyx** [asciidoctor/asciidoctor#1254]
When creating a block quote, I'm attempting to add a link to a particular URL while providing specific link text:

```asciidoc
:doctype: article

[quote,Michael Feathers, author of http://www.amazon.com/Working-Effectively-Legacy-Michael-Feathers/dp/0131177052[Working Effectively with Legacy Code]]
____
Clean code was written by someone who cares.
____
```

The generated HTML is:

![citation](https://cloud.githubusercontent.com/assets/276834/5598328/aa2fa8b4-92b4-11e4-844a-5b63a4c00012.png)

Am I missing some syntax in order to use the link text?

**Comment by mojavelinux** [comment]
I have good news, @kytrinyx. There's support for this specifically for this use case. If you add single quotes around the attribute value, that gives Asciidoctor the hint to apply normal substitutions (just like paragraph text).

```
[quote,Michael Feathers, 'author of http://www.amazon.com/Working-Effectively-Legacy-Michael-Feathers/dp/0131177052[Working Effectively with Legacy Code]']
____
Clean code was written by someone who cares.
____
```

This hint doesn't apply universally in AsciiDoc, but I plan to propose an issue to make it a standard notation (or some other way to force substitution to be applied to a block attribute value). We also need to document this feature :)

**Comment by kytrinyx** [comment]
Sweet, thanks!

**Comment by kytrinyx** [comment]
There are two different block include files: `x-block.adoc` and `ex-block.adoc`. What is the difference between the two?

**Comment by mojavelinux** [comment]
I can only claim 303 (See Other) or 409 (Conflict)...or insanity if there were an HTTP code for that :)

To be consistent with the naming pattern currently employed, it should be `ex-block.adoc` where `ex` is short for "example". (Btw, I plan to expand these file names since clarity for new eyes is clearly better than conciseness in this case).

**Comment by kytrinyx** [comment]
I think `ex-block.adoc` is sufficiently clear, the confusing bit was that there were two of them.

Would it be awful if I consolidated both into the `ex-block.adoc` file?

**Comment by mojavelinux** [comment]
I would say consolidate them, but I think the actual operation is rename because I'm not seeing `ex-block.adoc` when I look at the source repository. Are you sure it isn't a residual file?

https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/_includes/ex-block.adoc

One thing's for certain. We want to end up with one file and we want it to be named `ex-block.adoc`. We'll start with the end goal in mind :) Thanks!

**Comment by mojavelinux** [comment]
Documented by @kytrinyx in PR https://github.com/asciidoctor/asciidoctor.org/pull/337.

**Comment by kytrinyx** [comment]
... it turns out I was looking at `ex-quote.adoc` and `x-block.adoc`.

**Comment by mimoo** [comment]
what's the best way to add a link that will show up printed though? A footnote in the [quote] ?

**Comment by mojavelinux** [comment]
If you have a new question, please open a new issue.
