### ISSUE TITLE
Code within tables

### ISSUE THREAD

**Issue by taqtiqa-mark** [asciidoctor/asciidoctor#1266]
Either I'm poking all the corner cases... 
Is the following is an example worth including in the docs?

```asciidoc
:source-highlighter: coderay

.Table with column style e,a,m
[cols="e,a,m"]
|===
| Emphasized (e) | Asciidoc (a) | Monospaced (m)

.2+| Asciidoctor | [source,SQL]
----
select *
from a.b c
where c.displayed = TRUE
----
                         | It is just code.

.2+| Asciidoctor |      NOTE: WE told you....
                 | ...it is just code
|===
```
Which generates this image:

![Uploading 2015-01-13 13_55_57-asciidoctor-code-in-table.png . . .]()

**Comment by mojavelinux** [comment]
I'm not quite sure what you are proposing. Are you saying:

a. this content produces the result you expect and it should become an example in the docs or
b. this content does not produce the result you expect and the docs to help you achieve the result you want?

If it's (b), it's probably because you are repeating the Asciidoctor cell which already spans 2 rows.

In general, we recommend starting AsciiDoc cell content on a new line (hard break after the pipe). I do want to add that recommendation to the docs.

We also strongly recommend putting each cell on it's own line because trying to align the cell content in the AsciiDoc source usually becomes a distraction to both editing and revising. For example, I'd write it as:

```
.Table with column style e,a,m
[cols="e,a,m"]
|===
| Emphasized (e) | Asciidoc (a) | Monospaced (m)

.2+|Asciidoctor
|
[source,SQL]
----
select *
from a.b c
where c.displayed = TRUE
----
|It is just code.

//|Asciidoctor (continued)
a|
NOTE: WE told you....
m| ...it is just code
|===
```

You'll notice there is a bug in Asciidoctor calculating which formatting to apply to cells in a row that includes a cell that spans more than one row. I believe that's already filed as #989. If you can confirm that's your issue, I'll mark this as a duplicate.

**Comment by taqtiqa-mark** [comment]
Closing. Duplicates #989, which also suggests a workaround - place the markdown text in the first row of a spanned set.

**Comment by mojavelinux** [comment]
:+1:
