### ISSUE TITLE
How to set the 'quiet' option on the Ruby API

### ISSUE THREAD

**Issue by rebelwarrior** [asciidoctor/asciidoctor#1269]
I have not been able to figure out how to set the quiet option to suppress the warnings on the outputs. 
I've tried this:
`Asciidoctor.convert string, safe: 'safe', verbose: 0, quiet: true`
Neither of these options seem to work

**Comment by mojavelinux** [comment]
That option isn't currently available via the Ruby API. However, you can perform the work that the commandline option performs, which you can see here.

* https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/cli/options.rb#L116
* https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/cli/invoker.rb#L35

The long story short is that the reason we can't offer the option on the Ruby API yet is because the current strategy is to set a global variable that disables all warning statements in Ruby. In order to have fine-grained control, we first need to resolve #44.

**Comment by rebelwarrior** [comment]
I see....
Well I'll just overwrite the method that calls asciidoc to simply return the string given for test purposes. 

That way I can at least avoid the cluttering of warnings on my tests. 

But please implement this feature in the future.

**Comment by mojavelinux** [comment]
> But please implement this feature in the future.

Absolutely. If it wasn't clear, that's precisely why we need to do #44.

**Comment by rebelwarrior** [comment]
Thank you very much!

**Comment by mojavelinux** [comment]
:+1:

**Comment by mojavelinux** [comment]
It appears that this issue and #769 are duplicates. I'm going to close this one. Please post additional comments to #769.
