### ISSUE TITLE
Can someone point me to the docs for generating indexes?

### ISSUE THREAD

**Issue by davidfavor** [asciidoctor/asciidoctor#1283]
I've looked through the docs + I'm missing where index generation is described.

Thanks.

**Comment by rockyallen** [comment]
According to 
http://asciidoctor.org/docs/user-manual/#user-index
Asciidoctor can't do it yet.
You could always output to DocBook instead, which has excellent index support.
You might get a better response on the discussion list:
http://discuss.asciidoctor.org

**Comment by mojavelinux** [comment]
@rockyallen Exactly correct.

#450 is where we are tracking native support for generating the index in the HTML5 backend. Currently, you have to use a2x (or fopub) to output to HTML5 with an index (though it looks very different than the normal Asciidoctor HTML output). Since that route passes through the DocBook toolchain, it generates the index in the HTML5.

I've updated the docs to mention this point. I'm going to close since we have an issue to track this already.
