### ISSUE TITLE
admonitions italicized incorrectly in some cases

### ISSUE THREAD

**Issue by dmd** [asciidoctor/asciidoctor#1299]
```
== Test title

:icons: font

WARNING: this is a warning
```

asciidoctor will cause the warning admonition icon to be italicized, which I do not believe to be correct behavior.

**Comment by mojavelinux** [comment]
There's actually a good reason for this. Though, when I explain it, you might not like the practice.

When font-based icons came onto the scene, a common practice emerged to use the `<i>` element to mean "icon", thus overloading its meaning. Of course, that requires the use of CSS to reverse the default styling. The Font Awesome and Asciidoctor stylesheets handle this for us.

Therefore, if you separate the HTML from the Font Awesome stylesheet, you need to reintroduce this style clearing.

In which case does the icon appear italicized for you?

**Comment by dmd** [comment]
It's just weird to me that this:

```
:icons: font

== Test title

WARNING: this is a warning
```

and this:

```
== Test title

:icons: font

WARNING: this is a warning
```

generate different outputs.

**Comment by mojavelinux** [comment]
Aha! That's because `icons` is a document-level attribute that affects the document template. Therefore, it must be defined in the header of the document or it doesn't pass the information at the right time. Now I can totally see why you get highlighted icons. You are missing some of the HTML necessary to make the icons load properly.

In other words, the location of the `icons` attribute is semantic. It matters.

I suppose we shouldn't generate icons at all if it's not in the header, but we can at least consider the current behavior if you set `icons` mid-way in the document to be unspecified / undefined.

**Comment by dmd** [comment]
Ok, that's fair.

**Comment by dmd** [comment]
Do you want to document that somewhere, or just close?

**Comment by mojavelinux** [comment]
I just updated the documentation to clarify that it must be specified in the header.

http://asciidoctor.org/docs/user-manual/#admonition-icons

Ideally, we should have a dedicated subsection about enabling font-based icons (similar to the section we have for enabling the source highlighter). If you want to improve that section, please feel free to do so.

We should probably consider adding a section in the user manual that itemizes all the icons that can only be set in the document header. I think that would be useful.

**Comment by mojavelinux** [comment]
Either way, I think we can close this issue here because if we proceed, it should be in the asciidoctor.org repo.
