### ISSUE TITLE
sourceDir Absolute Vs Relative Paths

### ISSUE THREAD

**Issue by lgriffin** [asciidoctor/asciidoctor#1307]
Hi all,

I have been looking at this for a few hours and came across a report on something similar https://github.com/asciidoctor/asciidoctor/issues/1175

My issue however is about the use of absolute Vs relative paths, this may be working as intended however I want to document it just in case.

The setup from the bug report above recommends sourceDir set as:

```xml
<sourceDir>${project.build.sourceDirectory}</sourceDir>
```

That allows me resolve down to the full path from my C drive right down to the /src/main/java folder.

When I include it in my asciidoc file as follows:
```
[source,java]
.Example.java
----
include::{sourceDir}/com/lgriffin/Example.java[]
----
```
And render it, I get the following appearing in a code box:

```
link:C:\Users\lgriffin\Documents\workspace\sample\src\main\java\com\lgriffin\Example.java[]
```
So it just provides the link to the absolute path. If I change my attribute for sourceDir to use the relative path which is as follows:

```xml
<sourceDir>../java</sourceDir>
```

It processes the code block as it should and renders the Example.java file (or any tags I specify) without any issues.

I'm wondering is this a bug?

**Comment by mojavelinux** [comment]
This issue seems to be with the Asciidoctor Maven plugin. Could you file the issue at https://github.com/asciidoctor/asciidoctor-maven-plugin?

I can't determine if this is a bug or not. Usually a link is rendered if the safe mode is set too high (in brief, it refuses to resolve includes). However, the fact that the behavior changes when you change the path tells me it might be something else. Hard to say at this point.

**Comment by lgriffin** [comment]
Hey,

Apologies for the delay, issue is now opened in the asciidoctor-maven-plugin.

Thanks for taking the time to reply.

Leigh.
