### ISSUE TITLE
getting an underline

### ISSUE THREAD

**Issue by dmd** [asciidoctor/asciidoctor#1311]
```
:under: [underline]#&#12288;&#12288;&#12288;&#12288;&#12288;#

{under}
```

Expected result:  A 5-ideographic-space-wide underline.

Actual result: the text `[underline]#　　　　　#`

Note, this works fine if you just do the code itself (without doing it as a variable) -- so I guess I'm clearly not understanding something about the various passes in which asciidoctor interprets this stuff.

Is there a way to get an underline? (E.g., for a signature line or something like that.)

**Comment by mojavelinux** [comment]
In order to do what you are trying to do, you need to apply the quote substitution on the attribute value when you set it. This is because the order of substitution normally is that quotes come before attributes, so you need to alter the order.

```
:under: pass:q[[underline]#&#12288;&#12288;&#12288;&#12288;&#12288;#]

{under}
```

However, the more correct way to do this (semantically) is to use an inline macro the creates a signature underline.

```
Sign here: signature-line:[width=25]
```

Then you can "draw" the signature line in whatever way is appropriate for the backend. It's a bit more work, but it makes for cleaner AsciiDoc IMO.

**Comment by dmd** [comment]
It's definitely not clear to me how to register an inline macro when I'm using the command line asciidoctor tool.

**Comment by mojavelinux** [comment]
The inline macro just has to be defined in a Ruby file. Then, you include that Ruby file using the `-r` flag. Something like:

```
$ asciidoctor -r myextension.rb doc.adoc
```

We definitely need a proper tutorial for this. It's high on the priority list for me. Now that I'm back home, I can focus on getting it started.
