### ISSUE TITLE
Cannot use custom template for :toc: 

### ISSUE THREAD

**Issue by S0lll0s** [asciidoctor/asciidoctor#1312]
I have tried the template names `outline.html.erb`, `block_outline.html.erb`, `toc.html.erb` and `block_toc.html.erb`; none of them had any effect. I have verified that templates are read by overriding using `document.html.erb`.

Why can't I override `outline` or `toc`? They are defined just like `document` is in `asciidoctor/lib/asciidoctor/converter/html5.rb`.

**Comment by sethwoodworth** [comment]
The [backend templates for html5](https://github.com/asciidoctor/asciidoctor-backends/blob/master/erb/html5/block_toc.html.erb) call back to the `html5.rb` converter to the [`outline` method](https://github.com/asciidoctor/asciidoctor/blob/d5862cf8da967ea4f58924d575ce52c3250ab3d7/lib/asciidoctor/converter/html5.rb#L269)  this method hardcodes `<ul>` elements.  This, breaks the HTMLbook spec when I am trying to output HTMLbook via [htmlbook-asciidoctor](https://github.com/oreillymedia/asciidoctor-htmlbook)

**Comment by mojavelinux** [comment]
You should be able to override the outline by creating a template named `block_outline` (erb: block_outline.html.erb, slim: block_outline.html.slim, haml: block_outline.html.haml). While it's true that Asciidoctor calls back into the `outline` method of the built-in html5 converter if this template is missing, it will not perform this dispatch if it finds a template with the name `block_outline`. (Make sure you are using Asciidoctor 1.5, ideally 1.5.2).

@sethwoodworth, what you're seeing likely happens in htmlbook-asciidoctor because the outline is not being called correctly. It should be using the following API:

```
converter.convert self, 'outline'
```

That will look for the `block_outline` template (actually `outline` works too as the `block_` prefix is optional).

(Though I don't see where the outline is used in the htmlbook-asciidoctor templates).

If you continue to have issues, please provide a link to a set of templates I can test. Perhaps there is something different in our setup.

**Comment by mojavelinux** [comment]
To clarify, while the block_toc.html.erb calls back to outline, that in turn looks for block_outline.html.erb. Only if it doesn't find that template does it use the built-in method. This is how every template works. If it is missing, the built-in method gets called.

**Comment by S0lll0s** [comment]
That is exactly what I tried and changes nothing in the output. I am using `:toc: right` in the header. My template directory definiteley works, I can create a `document.html.erb` and that works.

**Comment by mojavelinux** [comment]
I can only guess what might be the problem without an example. Could you provide access to the templates or a similar set of templates that demonstrates the issue?

**Comment by S0lll0s** [comment]
I do not have any templates (yet), I want to create some. I write `test` into one, for the document.html.erb that (obviously) turns the whole output into just "test". If I write `test` into `outline.html.erb` nothing changes at all. I am doing all this in love2d-book/love2d-book, but it shouldn't matter really.

**Comment by S0lll0s** [comment]
I just checked the asciidoctor source, and from your post above I would guess that [line 695](https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/converter/html5.rb#L695) in the html5 converter is wrong:

    def preamble node
      #some other stuff
      "#{outline node.document}"
    end

should be

    "#{converter.convert self, 'outline', node.document}"

right?

**Comment by mojavelinux** [comment]
Aha! Now it makes sense. Yes, one of the templates has to invoke the call to the outline converter. It doesn't get called independently. I was assuming you were starting with the existing document.html.erb template, which has this call.

The toc can appear in multiple places in the output, which is why this call appears in several places. Since you are using `:toc: right`, you are using the document-level placement. Therefore, in your document.html.erb template, you need to have the following invocation:

```
<%= converter.convert self, 'outline' %>
```

If you want to support the `toc` macro, then you need to have the following invocation inside the block_toc.html.erb template:

```
<%= converter.convert @document, 'outline' %>
```

It's best to use the erb templates from asciidoctor-backends as a reference.

**Comment by mojavelinux** [comment]
Only when this invocation is made does Asciidoctor look for the outline.html.erb template.

(As I mentioned before, the `block_` prefix in template names is optional).

**Comment by S0lll0s** [comment]
Oh, I didn't know `asciidoctor-backends` existed. So I just copy `backends/erb/html5` and add a `block_outline.html.erb`? Great, going to try it out tomorrow or somewhen.

**Comment by mojavelinux** [comment]
Excellent!

For reference, I'll leave the link to html5 erb templates in the aciidoctor-backends repository: https://github.com/asciidoctor/asciidoctor-backends/tree/master/erb/html5

**Comment by S0lll0s** [comment]
I can't figure out how to write the template correctly, this is what I have so far:

    <%#encoding:UTF-8%><%
      sectnumlevels = (@document.attr 'sectnumlevels', 3).to_i
      toclevels = (@document.attr 'toclevels', 2).to_i

      slevel = (first_section = sections[0]).level
      slevel = 1 if slevel == 0 && first_section.special
    %><ul class="sectlevel<%= slevel %>">
      <% sections.each do |section|
        if section.numbered && !section.caption && section.level <= sectnumlevels
          section_num = "#{section.sectnum}"
        end
        if section.level < @document.attr('toclevels', 2) %>
          <li><a href="#<%= section.id %>"><%= section.captioned_title %></a>
            <%= converter.convert @document, 'outline', :toclevels => toclevels, :secnumlevels => sectnumlevels %>
          </li>
        <% else %>
          <li><a href="#<%= section.id %>"><%= section.captioned_title %></a></li>
        <% end %>
      <% end %>
    </ul>

That is basically a 1:1 erb adaption of [HTML5Converter#outline](https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/converter/html5.rb#L270). The problem is that I can't figure out how to do the recursive part, I either get a bunch of gibberish on stdout or "stack level too deep", because I cannot find a way to pass a node to the template.

Also how do I access the options that are passed via `convert_with_options`?

**Comment by S0lll0s** [comment]
Oh, I found a `block_outline` in the slim and haml examples. For future reference:

    <%= converter.convert section, 'outline', :toclevels => toclevels %>

**Comment by jirutka** [comment]
HTML/ERB templates are unmaintained, not tested and very outdated, so I don't recommend them as a reference or starting point for a custom backend. The most up to date and well tested are HTML/Slim templates.

**Comment by mojavelinux** [comment]
> HTML/ERB templates are unmaintained, not tested and very outdated, so I don't recommend them as a reference or starting point for a custom backend.

These points are becoming more true by the day, though it's not quite that grim as I had been manually maintaining them up to the 1.5.0 release.

It's clear that certain people / teams prefer ERB. We can think what we want about that choice, but it's still an important factor for the evaluation of Asciidoctor. Therefore, I've proposed that we trim the backend down to a handful of templates that we do maintain and test.

https://github.com/asciidoctor/asciidoctor-backends/issues/118

I think the README (once we get it in place) is a good place to advocate for the use of slim or haml (preferably slim) over ERB.

**Comment by mojavelinux** [comment]
Ooops, we do have a README for asciidoctor-backends. Then I'll add this point to the ERB issue so we remember to update it.
