### ISSUE TITLE
include block content by lines breaks the block

### ISSUE THREAD

**Issue by DavidGamba** [asciidoctor/asciidoctor#1319]
I have a song that is in a single adoc document:

my-song.adoc
````
.My song title (instructions for music)
____
First line +
Second line.

First line second stanza +
Second line.
____
````

For a tutorial, I want to include only the first stanza of the song so I tried:

include::my-song.adoc[lines=1..4]

However that causes the included content to be:
````
.My song title (instructions for music)
____
First line +
Second line.
````

And you end up with an unclosed block. 

I wish asciidoctor had a directive to read the file, be aware that the lines included are part of a block and then automatically close it. The current lines directive is useful mostly for code.

One workaround is to do this:
````
include::my-song.adoc[lines=1..4]
____
````
But that breaks my syntax checker and looks awfully hackish. 

I am aware of the alternatives to make this work, like using the included content within a block (using lines or tags). Something like:

````
.include::my-song.adoc[lines=1]
____
include::my-song.adoc[lines=3..4]
____
````

But just having block aware include instruction would be nicer!

**Comment by mojavelinux** [comment]
What you describe is just the current nature of includes. I recommend using tags instead of line numbers to get what you want. (You could also consider using a custom include processor or even a custom block macro to get more mileage out of this functionality).

The idea of including by document structure is something I've been thinking about for awhile. Perhaps the following issue (I finally got around to filing) addresses this need? https://github.com/asciidoctor/asciidoctor/issues/1328

One an unrelated note, you could write your song as follows:

```
.My song title (instructions for music)
[verse]
____
First line
Second line.

First line second stanza
Second line.
____
```

Then you don't need the `+` at the end of lines.

**Comment by mojavelinux** [comment]
If you like #1328, perhaps we can close this issue and continue the discussion there?

**Comment by DavidGamba** [comment]
Thanks, #1328 is exactly what I am looking for. As for the `verse` block, I appreciate it, it helps a lot, I was looking for an alternative to the quote formatting in the docs and was about to settle for `[%hardbreaks]` but `verse` is way better.

**Comment by mojavelinux** [comment]
Nice!
