### ISSUE TITLE
Embedded Vimeo/YouTube videos don't display

### ISSUE THREAD

**Issue by crydalch** [asciidoctor/asciidoctor#1320]
It appears that Asciidoctor is omitting *https* in the link is the cause; when I add that, the videos display properly.

https://gist.github.com/crydalch/6a240344125ece78d73a

Loving Asciidoctor! Thank you for the hard work!

**Comment by mojavelinux** [comment]
I wonder if the situation has changed from what I describe here:

https://github.com/asciidoctor/asciidoctor.org/issues/197

If so, that's encouraging.

**Comment by crydalch** [comment]
Cool, it looks like it works now! I just served the page with a Ruby server (like you showed), and the videos all show up and seem to play just fine:

![screenshot-area-2015-04-30-115156](https://cloud.githubusercontent.com/assets/458856/7420199/653b82aa-ef2f-11e4-9448-91a972c98666.png)

**Comment by mojavelinux** [comment]
Cool! It looks like YouTube now works properly for local files without having to use a web server! This change seemed to happen when they dropped Flash in favor of HTML5 (as reported in this new post http://www.theverge.com/2015/1/27/7926001/youtube-drops-flash-for-html5-video-default).

I was going to use the `asset-uri-scheme` as the prefix instead of hardcoding `https` so it's still possible to control the scheme in some way.

**Comment by mojavelinux** [comment]
Merged!

**Comment by crydalch** [comment]
Awesome, that's great, thanks so much!
