### ISSUE TITLE
More than two xref macros in a paragraph gets confused if the anchors being linked to have underscores.

### ISSUE THREAD

**Issue by danhaywood** [asciidoctor/asciidoctor#1349]
This paragraph fails to render properly (as html):

yada yada xref:__a_id_reference_services_api_manpage_a_code_backgroundservice_code[`BackgroundService`] yada yada yada
xref:__a_id_reference_services_spi_manpage_a_code_backgroundcommandservice_code[`BackgroundCommandService`] 
yada yada yada

The xref: macro doesn't convert to a hyperlink, and a bunch of the text that I do see is in italics.  What it "feels like" is that the xref: macro is doing an eager ("[^[]+") rather than lazy ("[^[]+?") regex for characters up to the "[".

asciidoctor 1.5.3.

**Comment by mojavelinux** [comment]
It's actually a bit more complicated than that. I'll try to break it down carefully.

The problem is happening before the xref is processed. The problem is that the matching double underscores is recognized as an unconstrained emphasis. Unconstrained formatting is completely unaware of context and blindly tramples the xref syntax. Thus, the xref syntax has no chance here.

The workaround is to escape one of the double underscores so that the parser doesn't match it.

```
yada yada xref:\__id_backgroundservice[BackgroundService] yada yada yada
xref:__id_backgroundcommandservice[BackgroundCommandService]
yada yada yada
```

(You can't escape them both because of how Asciidoctor correctly handles escapes. See https://github.com/asciidoctor/asciidoctor/issues/901).

In general, we recommend avoiding the use of repeating underscore characters when creating IDs. That brings us to the real issue at hand here. If you look closely at the ID, what you'll see is that it's replacing XML special characters with underscore. Likely, the original section text is:

```
<a id="reference_services_api_manpage"></a> <code>backgroundservice</code>
```

A quick fix is to change the auto-generated ID separator:

```
:idseparator: -
```

Then, the ID you get will be:

```
_-a-id-reference-services-api-manpage-a-code-backgroundservice-code
```

But this still sucks because the ID is just horrible. We should be stripping XML tags before generating the ID so that the ID is based on the content, not the markup. What we are looking for is:

```
_backgroundservice
```

See #794.

Another reasonable solution is to assign an id to sections that use markup in the title.

```
[[_reference_services_api_manpage]]
== `BackgroundService`
```

I strongly recommend against putting the anchor in the section title (e.g., `[[_reference_services_api_manpage]] BackgroundService`). It's must better to put it above the section title.

**Comment by danhaywood** [comment]
Thanks for this great answer, Dan.  I think I'll either use the escape, or I notice there's also :idprefix which if set to "-" would give an anchor of "-_" rather than "__"; a bit ugly, but I'd be happy with to avoid having to remember whether to escape or not.

The tip about putting anchors above the headings also really useful, thanks.

You left the ticket open, but I'm closing it as I'm happy with your solutions.  Thx.

**Comment by mojavelinux** [comment]
>  I notice there's also :idprefix 

Indeed. For more info, see http://asciidoctor.org/docs/user-manual/#title-id-and-prefix (though that section could stand to give a bit more detail).

> I'm closing it as I'm happy with your solutions.

:+1: 

If you have any more trouble, don't hesitate to ask follow-up questions.

**Comment by jxxcarlson** [comment]
I believe that this is similar to the issue in Asciidoctor-LaTeX in which to carets ^ ^ mess things up.

**Comment by mojavelinux** [comment]
> I believe that this is similar to the issue in Asciidoctor-LaTeX in which to carets ^ ^ mess things up.

Somewhat similar, though the situation in Asciidoctor LaTeX can be solved in a straightforward way because we do know the context.
