### ISSUE TITLE
Require asciidoctor library with a relative path in asciidoctor command line is causing issue in Debian package

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor#1364]
See: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=788051

We can workaround this issue by replacing:

```ruby
require File.join File.dirname(__FILE__), '../lib/asciidoctor'
```
https://github.com/asciidoctor/asciidoctor/blob/v1.5.2/bin/asciidoctor#L5

by:
```ruby
require 'asciidoctor'
```

Note that Debian package can apply patch to the source code to replace this line (so we don't need to release another version)

**Comment by Mogztter** [comment]
I made this change on the `v1.5.2` tag and all tests are running fine. But when I do the same change and build the Debian package, one test fail:

```
  1) Failure:
MiniTest::Unit::TestCase::TestInvoker#test_should_force_default_external_encoding_to_UTF_8 [/«PKGBUILDDIR»/test/invoker_test.rb:504]:
Failed assertion, no message given.

1522 tests, 5241 assertions, 1 failures, 0 errors, 0 skips
rake aborted!
Command failed with status (1): [ruby -w -I"lib:test" -I"/usr/lib/ruby/vendor_ruby" "/usr/lib/ruby/vendor_ruby/rake/rake_test_loader.rb" "test/**/*_test.rb" ]

Tasks: TOP => default => test
(See full trace by running task with --trace)
ERROR: Test "ruby2.1" failed. Exiting.
```

I also tried to replace with `require '/usr/lib/ruby/vendor_ruby/asciidoctor'` in the Debian package but I get the same error.

**Comment by mojavelinux** [comment]
@Mogztter It's not enough to change the require statement. You'd also have to modify the LOAD_PATH . We switched to using a relative require statement since asciidoctor.rb deals with modifying the LOAD_PATH. Obviously, it's a problem that we are now breaking things on Debian.

It's actually kind of strange the way that Debian is handling the executable. Fedora is doing what RubyGems normally does, which is to use a shim file that loads the script from the bin directory in the gem installation.

```ruby
#!/usr/bin/ruby
#
# This file was generated by RubyGems.
#
# The application 'asciidoctor' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require 'rubygems'

version = ">= 0"

if ARGV.first
  str = ARGV.first
  str = str.dup.force_encoding("BINARY") if str.respond_to? :force_encoding
  if str =~ /\A_(.*)_\z/ and Gem::Version.correct?($1) then
    version = $1
    ARGV.shift
  end
end

gem 'asciidoctor', version
load Gem.bin_path('asciidoctor', 'asciidoctor', version)
```

Debian puts our asciidoctor script directly into /usr/bin (or, at least, that's what our package is doing).

```ruby
#!/usr/bin/ruby

require 'rubygems' if RUBY_VERSION < '1.9'

require File.join File.dirname(__FILE__), '../lib/asciidoctor'
require 'asciidoctor/cli'

invoker = Asciidoctor::Cli::Invoker.new ARGV
GC.start
invoker.invoke!
exit invoker.code
```

This is not really the Ruby way. We can work around it, but that's where the problem comes in. Most gems assume that the executable is in a bin folder relative to the lib folder. If not, a shim is supposed to be used to bootstrap the script.

**Comment by mojavelinux** [comment]
The real concern for me is that by using `require 'asciidoctor'`, we break local testing out of the repository.

How about we first check for the existence of the relative path. If it's there, we use it. Otherwise, we assume things are setup to find it automatically. That way, local testing works and it should work fine when installed as well.

```ruby
if File.exist?(asciidoctor_lib_path = File.join(File.dirname(__FILE__), '../lib/asciidoctor'))
  require asciidoctor_lib_path
else
  require 'asciidoctor'
end
```

Could you check if this allows all tests to work? I think this is the way to go.

**Comment by mojavelinux** [comment]
There is a slight risk that we load a random version of Asciidoctor that just happens to load this path, but we had that problem before anyway, so it's not like we are changing an assumption here. We are just allowing the bin script to be in a different relative location when installed and relying on require to sort out the path.

**Comment by Mogztter** [comment]
The following is working:

```ruby
if File.exist?(asciidoctor_lib_path = File.join(File.dirname(__FILE__), '../lib/asciidoctor'))
  require asciidoctor_lib_path
else
  require 'asciidoctor'
end
```
I've also done the same for `require 'asciidoctor/cli'`

**Comment by mojavelinux** [comment]
Perfect. Let's move forward with that change. Do you want to do the honors of sending the pull request?

**Comment by Mogztter** [comment]
Sure :)
