### ISSUE TITLE
Q: how to make a new pygments language available?

### ISSUE THREAD

**Issue by wolandscat** [asciidoctor/asciidoctor#1382]
I have added a new highlight language to pygments, and built it so that it is listed when i do the following:

```
$ pygmentize -L lexers | grep adl
* adl:
    ADL (filenames *.adl, *.adls, *.adlf, *.adlx)
* cadl:
    cADL (filenames *.cadl)
```

The highlighter is working when tested with an HTML formatter. I also know pygments is working within asciidoctor, because code blocks that have `[source, lang]` where `lang` is a previously known language (like python), highlighting occurs as expected in the HTML output. But if I specify my new language in the adoc source, no highlighting happens.

Is there some step missing where asciidoctor figures out what pygments languages there are available, and compiles a private list?

_Update_: I think I have found the problem: in the pygments.rb installation, the 'lexers' file which appears to be a cache of lexer information needs to be regenerated using the file `cache_lexers.rb`. I managed to figure out how to run that in `irb`, and it appears to have regenerated the lexer cache. I suspect my highlighter is running, but has bugs, because it doesn't return (this I have observed in earlier testing).

It would be nice if the instructions to add a new language were added to the asciidoctor user guide. Essentially they are:
- develop and test a new language highlighter using the [pygments guide](http://pygments.org/docs/lexerdevelopment/)
- install the working changes with (I think the following is needed - I did it and it didn't break anything), from the pygments.rb install area:

```
$ cd vendor/pygments-main
$ python setup.py install
```
- rebuild the lexer cache file:

```
$ cd ../../  # get back to pygments.rb install root
$ irb
# in irb, do require './cache-lexers.rb'
```

This is my best guess for now.

**Comment by mojavelinux** [comment]
I'm glad you raised this question @wolandscat because how Pygments is integrated is something that we need to be clear about in the documentation.

The pygments.rb gem bundles its own version of Pygments and thus doesn't use the system installation of Pygments. (It also seems to be an unreleased version of Pygments; see https://github.com/tmm1/pygments.rb/blob/master/vendor/pygments-main/pygments/__init__.py#L29). The only prerequisite to using pygments in Asciidoctor is that you have Python installed on your machine.

This means, by default, Asciidoctor doesn't utilize any modifications to the system-wide Pygments, which is what is tripping you up. In order to apply your modifications, you need to set an environment variable named `PYGMENTS_PATH` that points to your own Pygments installation (or the one on the system). See https://github.com/tmm1/pygments.rb/blob/master/lib/pygments/mentos.py#L6-L7. Give that a try and see if it works for you.

---

As an alternative to Pygments, we're perusing the integration of Rouge into Asciidoctor (starting with Asciidoctor PDF). Rouge is a pure Ruby gem and thus the integration is a lot less complex. Rouge is catching up with Pygments in terms of languages supported and it should be reasonable to port a language in Pygments to Rouge if it's missing.

**Comment by mojavelinux** [comment]
> It would be nice if the instructions to add a new language were added to the asciidoctor user guide. 

I agree.

**Comment by mojavelinux** [comment]
In addition to what I mentioned, flushing the cache may also be required as you have observed. I haven't experimented with that part yet. My feeling, though, is that it's probably better to get Pygments working how you want it somewhere, then point the `PYGMENTS_PATH` environment variable at it. That way, you can have better control over the Pygments setup.

**Comment by mojavelinux** [comment]
This kind of feels like it should be a dedicated tutorial instead of integrated into the Asciidoctor user manual. This is way too advanced for the general-purpose documentation, IMO. In fact, I really don't recommend Pygments for users unless they know what they are doing with it. I think casual users should use CodeRay or, in the future, Rouge.

**Comment by wolandscat** [comment]
I hope we can still use it - I just spent 2 days creating a new lexer for it ;-)

I actually think the installation approach could be improved, including not using the static copy of vendor drop buried inside pygments.rb. But it does all work - well ok, I'm a software guy so although not properly Python or ruby literate, I can hack my way into it. One thing I did was to replace the static copy of Pygments with the current latest.

**Comment by mojavelinux** [comment]
For what it's worth, I actually disagree with how Pygments is being managed in pygments.rb. Bundling an external library is not a very friendly idea. Ideally, it would download a version managed in the config upon first use if not just use what's on the path. But pygments.rb is really far outside of our control, so we have to make due with what it gives us (or find an alternative).

**Comment by wolandscat** [comment]
Well as far as I can tell, the additional content in pygments.rb is really very minimal - it's some sort of Ruby - Python calling glue. I think a better version of the same thing could be made as part of Asciidoctor. From my work so far, Pygments itself is pretty powerful and well designed. So it seems useful to be able to include it. And the Pygments.rb Ruby/Python calling function does actually work, and it doesn't make asciidoctor run slowly as such. So I think just re-using Pygments in a cleaner way within Asciidoctor would make sense.

**Comment by jaredmorgs** [comment]
For the record, I believe the notes about pygments.rb bundling it's own version are covered already in http://asciidoctor.org/docs/user-manual/#pygments

Is there something I'm missing in the minutia of this issue, @mojavelinux ?

**Comment by mojavelinux** [comment]
@jaredmorgs You are correct that we identified and documented how to use a custom path to Pygments. What we probably need to add is a pointer to the Pygments docs about how to define a new language in that installation. Then, it is up to the user to do the rest (as we aren't in the business of making or documenting how to make lexers for Pygments).

I do think we should pull out the information about `Pygments.start` out of the admonition and put it into a subsection named "Using a custom Pygments installation".

So the action items here are:

* split out information about Pygments.start into a subsection
* add a pointer to docs about adding a new lexer to Pygments (probably in the same subsection)

Regarding a change to core, we could automatically call `Pygments.start` with the value of the `pygments-path` attribute, if set. If that's worth doing, we'd need a separate issue for that in core.

**Comment by mhaberler** [comment]
I've managed to build a docker container with custom lexers by brute force ;) based on @wolandscat ' hints - certainly less than elegant but works for now:

https://github.com/mhaberler/docker-jekyll-asciidoctor/blob/master/jekyll-asciidoctor-base/Dockerfile#L76-L85

did not get PYGMENTS_PATH to work so used a symlink

**Comment by mojavelinux** [comment]
This topic is now covered in the docs. See https://docs.asciidoctor.org/asciidoctor/latest/syntax-highlighting/pygments/#use-a-custom-pygments-installation

It's also now possible to develop a custom syntax highlighter adapter, which is another route to using your own version of Pygments. See https://docs.asciidoctor.org/asciidoctor/latest/syntax-highlighting/custom/#extend
