### ISSUE TITLE
Fenced code block with no syntax highlighting

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor#1389]
Is there a way to disable syntax highlighting with fenced block ?

I know I can use listing block:

```
----
cp /home/guillaume/documents/test.adoc  /home/guillaume/asciidoctor/
----
```

But I would expect that the following produce the same result:

``````
```
cp /home/guillaume/documents/test.adoc  /home/guillaume/asciidoctor/
```
``````

**Comment by wolandscat** [comment]
I have also noticed this one. It's minor, but it would be good to know what is happening there.

**Comment by mojavelinux** [comment]
The fenced code block is implicitly a source block, so it's the equivalent of typing:

```
[source]
----
cp /home/guillaume/documents/test.adoc  /home/guillaume/asciidoctor/
----
```

That activates the syntax highlighter on the block. highlight.js tries to be too smart about the language, so often times it gets the language wrong when no explicit language is set.

One quick way to solve the problem is to set the language to bash:

    ```bash
    cp /home/guillaume/documents/test.adoc  /home/guillaume/asciidoctor/
    ```

We could agree that if a language is not set (and there is no default language set on the document), then it becomes a listing block instead of a source block.

This is also loosely related to #1117.

**Comment by mojavelinux** [comment]
Btw, how I recommend entering commands is as follows:

```
 $ cp /home/guillaume/documents/test.adoc  /home/guillaume/asciidoctor/
```

(or a leading `$>`). These are not source blocks and therefore a different syntax should be used, IMO.

**Comment by mojavelinux** [comment]
To disable syntax highlighting in a fenced code block, you'd need to set the language to text.

    ```text
    no syntax highlighting here
    ```
