### ISSUE TITLE
user manual of ascii doctor is not available in PDF form on the website

### ISSUE THREAD

**Issue by zaxebo1** [asciidoctor/asciidoctor#1391]
asciidoc-syntax-quick-reference.pdf and asciidoc-writers-guide.pdf are available in the PDF form , But user-manual is NOT available in PDF format

I tried to build it myself using asciidoctor-pdf , but it failed to build the pdf

Note that on phablet and tablets, it is easier to store and carry manuals in PDF format, and read them at leisure; compared to locally storing and reading html files on tablets.

So, Please PDF version of user manual available on the mainwebsite for downloading.

**Comment by mojavelinux** [comment]
I agree. This has been a goal of the effort to bring Asciidoctor PDF to stability. We're getting very close to it finally happening.

Could you reopen this issue in the [asciidoctor.org](https://github.com/asciidoctor/asciidoctor.org) repository since that's where the code change needs to happen?

Also, could you provide details there about why the PDF generation fails? It may be something we can get sorted out in Asciidoctor PDF straight away...or update the user manual if something about the document is breaking the converter.

**Comment by zaxebo1** [comment]
thanks for the quick reply, i reopened this issue at https://github.com/asciidoctor/asciidoctor.org/issues/407

**Comment by mojavelinux** [comment]
Thanks!
