### ISSUE TITLE
Meta: Gitter Channel 

### ISSUE THREAD

**Issue by sirinath** [asciidoctor/asciidoctor#1396]
Can you create a gitter channel?

**Comment by mojavelinux** [comment]
There already is one: https://gitter.im/asciidoctor/asciidoctor

Personally, I find working through GitHub to be more efficient and it keeps the communication closer to the code.

**Comment by mojavelinux** [comment]
Note that we can't use the "organization" channel  https://gitter.im/asciidoctor as that requires people be in the organization on GitHub. So if we document it, we should document the repository-specific URL as written in my previous comment (somewhat misleading since it's not just for that repository, but that's just how we'll have to do it).

If you'd like to propose an update to the README, I'll gladly merge it in.
