### ISSUE TITLE
Five colons in a row causes crash (affects Asciidoctor.js, but the change has to happen to core)

### ISSUE THREAD

**Issue by takapa** [asciidoctor/asciidoctor#1408]
Writing five colons in a row in AsciiDocFX crashes/hangs the program however @mojavelinux asked me to open the issue here as it is very likely due to an underlying bug in AsciiDoc core.

>  It seems like the regular expression for a dlist is matching differently in the JavaScript environment than it does in the Ruby environment.

Originally filed here :

https://github.com/asciidocfx/AsciidocFX/issues/94

**Comment by mojavelinux** [comment]
As mentioned in the AsciidocFX issue, Opal is turning `do...while` loops (written as `begin...while` in Ruby) into `while` loops. This, in turn, leads to an infinite loop in Asciidoctor.js.

The change to core is to avoid the use of the `do...while` loop and instead write it as a `while` loop. As it turns out, the code lends itself to this change already, so it's really not a problem and adds some clarity to the code at the same time.

**Comment by mojavelinux** [comment]
Patching Asciidoctor.js is going to be kind of tricky in this case. I wonder if it would be better to do a 1.5.2.1 hot fix release. Or can we wait for Asciidoctor 1.5.3 (tentatively scheduled for the end of the month)?

**Comment by mojavelinux** [comment]
I've sent a PR to core to switch the loop.
