### ISSUE TITLE
Include:: does not work as expected

### ISSUE THREAD

**Issue by nwmcsween** [asciidoctor/asciidoctor#1415]
In C, C++ include literally includes the file before any actions occur, this is expected.
In asciidoc?(tor) include is processed after styles.

ex.

```
[syntax, c]
----
include::some_file.c[]
----
```

Is there a way to pass directly to asciidoc instead of applying styles to the text? 
pass:: doesn't work either

**Comment by mojavelinux** [comment]
I'm not sure I understand the situation you are trying to describe. Includes are handled by the preprocessor. Specifically, the include is processed as the lines are read. In this case, the contents of the include are added to the document, then passed to the source block handler which runs the syntax highlighter on those lines. Is this not what you expect?

It might be helpful if you provide the output that you are expecting so that we can better understand what you are trying to achieve.

**Comment by nwmcsween** [comment]
the example is above doing:
[syntax, c]
----
include::some_file.c[]
----
doesn't include the file, the asciidoc syntax is applied as if it that was just a string.

**Comment by mojavelinux** [comment]
You are probably hitting the safe mode setting problem. See http://asciidoctor.org/docs/user-manual/#running-asciidoctor-securely

The include directive is disabled when the safe mode is secure (the default when using the API).

**Comment by mojavelinux** [comment]
Were you able to get that work?

**Comment by nwmcsween** [comment]
I ended up just copy pasting the content.

**Comment by mojavelinux** [comment]
Are you calling Asciidoctor from the API or the commandline?

**Comment by nwmcsween** [comment]
Through the api specifically on github I was hoping to include a test file to show api usage of my software.

**Comment by mojavelinux** [comment]
Includes do not work on GitHub. They should work fine on the commandline, assuming that the file can be resolved. If you use the Asciidoctor Ruby API, then you have to set the safe mode to `:unsafe`, `:safe` or `:secure`. Usually `:unsafe` does the trick. The default on the commandline is `:unsafe`.

**Comment by mojavelinux** [comment]
> Includes do not work on GitHub.

Because GitHub's policy is that they forbid it. This also affects files retrieved via the GitHub api.
