### ISSUE TITLE
How to use GNU source-highlight with asciidoctor?

### ISSUE THREAD

**Issue by msc-** [asciidoctor/asciidoctor#1437]
I have been using GNU source-highlight with asciidoc. It produces very pretty and colorful output. I have tried the all the asciidoctor source highlighters, except pygments which produces an error about circular requirements, and find them all dull by comparison.

Is there any way to use GNU source-highlight with asciidoctor?

Alternatively, is the styling of the highlighted source code related to asciidoctor.css? Perhaps if I can figure out how to use the flask theme (see issue #1436) then the source highlight will look like I want it to look.

**Comment by mojavelinux** [comment]
I'd prefer not to add any additional source highlighters to Asciidoctor because we already have so many and testing them is difficult as it is (since there are so many permutations). If we did add an additional one, I'd strongly consider replacing one we already have. (Having said that, I am considering adding Rouge).

Pygments is probably the most accurate syntax highlighter. The simplest to use is CodeRay (because it's a standalone gem) or highlight.js (because it has a very broad range of support).

You can supply a custom theme file for Pygments or CodeRay. For Pygments, you can use one of the built-in themes by setting the `pygments-style` attribute:

```
:pygments-style: monokai
```

You can also just use the docinfo feature to add a new stylesheet to the header. See http://asciidoctor.org/docs/user-manual/#docinfo-file

Having said all that, it is still possible to add the GNU source-highlighter without changing core. You can either create a custom template for the listing block (see https://github.com/asciidoctor/asciidoctor-backends/blob/master/slim/html5/block_listing.html.slim) or you can use a Treeprocessor to find source blocks and apply highlighting to them (see https://github.com/asciidoctor/asciidoctor-extensions-lab). A change to core is not the only way.

**Comment by msc-** [comment]
Thanks for the information. I will look at some of your suggestions when I have time. 

I did try pygments but get the warnings shown in issue #1439 and the source is not highlighted. Where can I find information about the styles available with pygments?

**Comment by mojavelinux** [comment]
Let's try to get to the bottom of that error you are seeing.

> Where can I find information about the styles available with pygments?

This is covered in the user manual. Type `pygmentize -L` styles in your terminal to see a list of the Pygments styles you have installed.

http://asciidoctor.org/docs/user-manual/#pygments

Keep in mind that the gem uses a bundled version of Pygments, so you don't actually need it installed on your system. To invoke the version of pygmentize that is bundled, use:

```
 $(dirname $(gem which pygments.rb))/../vendor/pygments-main/pygmentize -L
```

**Comment by msc-** [comment]
In trying the above command I found that I did not have a command called "python2". I had "python" which was in fact python 2.7.6. Anyway I downloaded and installed the latest python 2 from python.org and was able to get the list of styles. I'll try some of the styles and see which ones I like. Thanks for the help.

Regarding the warnings, I'll comment on those over in issue #1439.
