### ISSUE TITLE
Ability to use custom text for internal cross-reference

### ISSUE THREAD

**Issue by seanosterberg** [asciidoctor/asciidoctor#1468]
One of the only missing formatting features with Asciidoctor is the ability to provide custom text for an internal cross-reference link. 

The most common case where I would like to do this is for links to sections. It seems intuitive to be able to do the following:

```
For more information about why Asciidoctor is great, 
see <<Asciidoctor is really awesome but this section title is super long, the section below>>

== Asciidoctor is really awesome but this section title is super long
```

The output would be:

"For more information about why Asciidoctor is great, see **the section below**."

I know it might be problematic to parse this, as a heading can have commas, but something along these lines which overloads the default `<<Section Title>>` functionality would be nice. The built-in functionality to do this isn't reasonable -- creating x-refs that point to html-generated IDs, adding an anchor, etc. I would love to see this feature added.

**Comment by seanosterberg** [comment]
Also saw this post in the forums from someone else who wants the same thing: http://discuss.asciidoctor.org/Internal-links-td217.html

**Comment by mojavelinux** [comment]
@seanosterberg I have good news for you. The example you posted does work (at least with the latest master).

The only caveat is if the target section title contains a comma. We don't currently support a way to enclose the section title in quotes so that it can be escaped. For example, the following doesn't work:

```
<<"Asciidoctor is really awesome, but this section title is super long", "the section below">>
```

Somewhere there's an open question about whether we should recognize quotes around section titles in the xref.

Having said that, I feel strongly that for formal documents, you should be using fixed section ids to ensure long-term stability. The option to reference the target section title by it's full name is intended for simple documents as a convenience.

For example, here's how I recommend handling this situation:

```
For more information about why Asciidoctor is great, 
see <<_awesome_asciidoctor, the section below>>.

[#_awesome_asciidoctor]
== Asciidoctor is really awesome, but this section title is super long

...
```

That way, a change to the section title won't mess things up...where as IDs tend to be something you don't change.

**Comment by seanosterberg** [comment]
Awesome news! We're eagerly awaiting this feature. Thanks Dan, also for the best practice advice.
