### ISSUE TITLE
Recognize CommonMark, Markua, MediaWiki, Textile, reStructuredText, etc. formats

### ISSUE THREAD

**Issue by sirinath** [asciidoctor/asciidoctor#1482]
AsciiDoctor supports MD but it would be great if you can recognise a subset other formats when it does not conflict with ASciiDoc (current or potential future features). Also block out a certain section to be from another format which can include conflicting features.

**Comment by mojavelinux** [comment]
Supporting additional markup languages is not the focus in Asciidoctor. We support a small subset of Markdown only because it is so prevalent and the syntax is so close to AsciiDoc already. I don't intend to support syntax from other languages. The only case we'd support it is if we decide that a certain syntax is so intuitive that it should become a core part of AsciiDoc.

> Also block out a certain section to be from another format which can include conflicting features.

This is a great idea and already supported by Asciidoctor extensions. You can find an example of a block that uses Slim syntax in the extensions lab. See:

* https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/lib/slim-block.rb
* https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/lib/slim-block/extension.rb

**Comment by sirinath** [comment]
Maybe you can support some other common formats as extension blocks. Sometimes AsciiDoc format is more verbose than what others offer.

**Comment by mojavelinux** [comment]
> Sometimes AsciiDoc format is more verbose than what others offer.

Then we need to improve AsciiDoc. We want AsciiDoc to be the most concise and intuitive language as we can make it (striking the balance is the key).

As I mentioned, it is already possible to introduce blocks that switch to a separate syntax already using extensions. Such an extension could be published as a gem so that it is easy to consume (it doesn't doesn't have to live in the lab).

**Comment by sirinath** [comment]
I guess in which case the best starting point is to research on what others are doing and in this light where AsciiDoc can improve. I think you might need some radical changes in some places.

**Comment by mojavelinux** [comment]
The thing to keep in mind about AsciiDoc (which even I have to tell myself) is that an incredible number of people find it very intuitive the way it is. It's what brought me to AsciiDoc and it is what has made the adoption quicker than I ever expected. What I'm trying to say is that we have to be mindful not to disrupt that magic, that draw.

I'm fully aware that there are inconsistencies that still need to be resolved, and more expressiveness is needed in places where it's expected. To cite a more specific example, reference labels need to be more powerful. There are loads of other ideas like that in the issues. Some we can do for AsciiDoc. Others will need to be part of the emerging UniDoc (in the case that they depart too much from the existing syntax). Either way, we'll keep things forward.

**Comment by mojavelinux** [comment]
Supporting other syntax is out of scope for Asciidoctor. Asciidoctor is focused on parsing and evolving the AsciiDoc language. If you want to support other languages in an AsciiDoc document, you can take advantage of the extensions API.
