### ISSUE TITLE
Github xref?

### ISSUE THREAD

**Issue by jasonkuhrt** [asciidoctor/asciidoctor#1483]
```
<<readme#filter, Filter>>
```
Becomes:
```
.../readme.html#filter
```
But I expected:
```
.../readme.adoc#filter
```

**Comment by mojavelinux** [comment]
There is a way to resolve this, though I'll admit it's not the cleanest solution atm. Here's how you do it:

```
= Document Title
ifdef::env-github,env-browser[:outfilesuffix: .adoc]

<<readme#filter, Filter>>
```

This trick needs to make it's way into the documentation (at least until we have a better strategy). The challenge is that GitHub just works differently because you don't link to the HTML output but rather the raw source. We may want to have another environment attribute that indicates this type of environment (source-to-source).

**Comment by mojavelinux** [comment]
Now documented in the user manual: http://asciidoctor.org/docs/user-manual/#navigating-between-source-files and the FAQ.

**Comment by mojavelinux** [comment]
We'll need to work with GitHub to set the outfilesuffix to `.adoc` by default in that environment. I'll make a note of it.

**Comment by lefou** [comment]
This info is much appreciated. :+1:
