### ISSUE TITLE
CSS for printing

### ISSUE THREAD

**Issue by jxxcarlson** [asciidoctor/asciidoctor#1484]
The current stylesheet renders awesomely beautiful HTML on screen, but leaves something to be desired for print.  In particular, the margins are too narrow and the font size is too big.  I've hacked this in Asciidoctor-LaTeX by inserting the following after the regular style sheet:

```
<style>
media print{@page{margin:2.25cm 2.75cm}
    body{ font-size: 0.75em; text-align: justify; }}
</style>
```

As an illustration of the output one gets when one prints the HTML file, see
[this PDF file](http://vschool.s3.amazonaws.com/public/noteshare_up_and_running.pdf).

As you will see, there are other issues, e.g, since I normally print in black and white,
the section headings are too light.  Also, certain elements such as poetry and quotations,
came out way too big.  I will continue hacking away at this, but it might be good to
put something along these lines in the core.  The current state of this
CSS can be found in the [Asciidoctor-LaTeX source](https://github.com/asciidoctor/asciidoctor-latex/blob/master/data/extras.css#L137).

One more thing ... the links in the index of the PDF file (and elsewhere) are not responsive.
It would be good if there were an optional way of making them so, since one can use
a print version of an HTML file as a way of getting PDF output.  At the moment this is the
only way to do so for Asciidoctor-LaTeX that contains math markup or blocks like
[env.theorem].

**Comment by mojavelinux** [comment]
The challenge here is that there's no single way to make print styles that satisfy all the requirements. Some people use print styles to make a PDF. Others send it to a printer. Some printers are black and white. Others are color. So I think any change we make will have a counter request to change it the other way.

I think the right solution here is to have a solid starting point in core that handles the basic stuff like making sure objects don't break over a page and stuff like that, then use docinfo or a custom stylesheet to get exactly the output you want. Remember that the default styles are just a starting point. I would imagine that anyone using Asciidoctor for a period of time would have their own enhancements, not only to suit their preferences but to match their own branding / style.

I do think that we can focus on problems that just don't look good at all. For that, though, it's important that we first select a stable document we can work with so that we can study the impact of each change. I think the example document in Asciidoctor PDF may work well for this. See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/examples/chronicles-example.adoc.

**Comment by danyill** [comment]
Incidentally #1410 is related.

IMHO 75% works a lot better and would be a reasonable compromise.

**Comment by danyill** [comment]
This should possibly (?) be a separate issue...

In general the Asciidoctor stylesheet prints marvellously.

When I scale down using the solution from #1410, some elements like the title of tables or figures do not scale down appropriately.

As I understand it, `rem` elements are relative to the root html element whereas `em` units are relative to the nearest (see [here](https://j.eremy.net/confused-about-rem-and-em/)) 

If I understand it `html { font-size:75% }` will cause a scaling down of the rem elements.
However the solution in #1410 will not.

Perhaps the problem is in this part of the stylesheet:

```css
.admonitionblock td.content>.title, .audioblock>.title, .exampleblock>.title, .imageblock>.title, .listingblock>.title, .literalblock>.title, .stemblock>.title, .openblock>.title, .paragraph>.title, .quoteblock>.title, table.tableblock>.title, .verseblock>.title, .videoblock>.title, .dlist>.title, .olist>.title, .ulist>.title, .qlist>.title, .hdlist>.title {
    text-rendering: optimizeLegibility;
    text-align: left;
    font-family: "Noto Serif", "DejaVu Serif", serif;
    font-size: 1rem;
    font-style: italic;
```
Should these be `em` or `rem`?

Example as per attached:

[page38.pdf](https://github.com/asciidoctor/asciidoctor/files/1430019/page38.pdf)

**Comment by mojavelinux** [comment]
I recently realized why I got the print styles so wrong. After switching to a HiDPI monitor, I had changed the scaling setting in Chrome to 75%. That's why it looks so right at 75% ;)

I'm going to schedule this for the next version now that I understand the problem.

**Comment by mojavelinux** [comment]
(I'm at least going to fix the scaling issue).

**Comment by mojavelinux** [comment]
> Should these be em or rem?

rem is the direction we have been moving. If we upgrade to Foundation 6, we'll have to switch everything to rem as that is all Foundation now supports. There are places for em (such as when compounding is desirable), but generally rem is what should be used to avoid compounding.

rem is controlled by font-size on html.

**Comment by mojavelinux** [comment]
I tried both 75% and 80% and it feels like 80% is the right choice here. Feedback welcome.

Are there any elements that are missed?

See #2576.

**Comment by mojavelinux** [comment]
I'm going to move forward with my proposal of 80% font size so people can test this out. We can reopen if necessary.
