### ISSUE TITLE
Indexterm Promotion Problem

### ISSUE THREAD

**Issue by eskwayrd** [asciidoctor/asciidoctor#1487]
I'm converting DocBook documents into AsciiDoctor syntax, and I'm trying to replicate the contents of <indexterm> tags with ((())) syntax. To create HTML/PDF, I use AsciiDoctor to create DocBook which is then transformed with my DocBook-based toolchain.

In DocBook, I might have:

```
Place the foo<indexterm>
  <primary>widgets</primary>
  <secondary>foo</secondary>
</indexterm> in the bar.
```

This generates an entry in the rendered index like:

```
widgets
   foo
```

With AsciiDoc syntax:

```
Place the foo(((widgets,foo))) in the bar.
```

This creates multiple entries in the index:

```
foo
widgets
  foo
```

The bare "foo" entry should not exist, but does because the `<secondary>` term gets 'promoted' to `<primary>`.

I see that in lib/asciidoctor/converter/docbook5.rb, lines 537-558, the logic is based on the number of terms provided. If provided with three terms, it emits an `<indexterm>` with all three terms, and then an `<indexterm>` with the last two terms, and an `<indexterm>` with the last term.

I can understand if some number of authors prefer `<secondary>` and `<tertiary>` promotion if that is their style of indexing. But since it is not mine, I cannot use ((())) syntax because it causes that promotion.

If promotion were disabled, authors preferring promotion would need to manually promote their `<secondary>` and `<tertiary>` terms. For example:

```
(((widgets,foo)))(((foo)))
```

But that's less odious than having to pass through the much more verbose DocBook source:

```
pass:[<indexterm><primary>widgets</primary><secondary>foo</secondary></indexterm>]
```

Finally, it would also be awesome if O'Reilly's AsciiDoc indexing customizations were included so that `<see>`, `<seealso>`, and `<sortas>` customizations worked natively. See:

http://chimera.labs.oreilly.com/books/1234000001578/ch02.html

**Comment by mojavelinux** [comment]
Asciidoctor implements the behavior of AsciiDoc Python, so what we are talking about here is a change to how AsciiDoc is converted to DocBook. Since the index term promotion has always been a part of AsciiDoc, we'll need to introduce a flag in order to disable it (on by default).

I propose the name of the flag to be `promote-indexterms`. It can then be disabled using:

```
:promote-indexterms!:
```

We clearly need to support this mode so you aren't forced to use a non-portable and very verbose passthrough.

> it would also be awesome if O'Reilly's AsciiDoc indexing customizations were included so that <see>, <seealso>, and <sortas> customizations worked natively.

I'm okay with supporting these custom attributes in the `indexterm` macro. However, I don't like that O'Reilly is departing from traditional AsciiDoc syntax by introducing attributes inside of shorthand. Consistency is a key strength in AsciiDoc and I want to preserve it.

It would look something like:

```
indexterm:[3-D, sortas=three-d]
```

But let's look at that in a separate issue.

**Comment by mojavelinux** [comment]
I changed the attribute to `indexterm-promotion`, so to disable it you'd use:

```
:indexterm-promotion!:
```

Let me know what you think.

Also, could you file a separate issue for the additional attributes like sortas?

**Comment by mojavelinux** [comment]
See PR #1497.

**Comment by mojavelinux** [comment]
Does `indexterm-promotion` seem like the right attribute name to you @eskwayrd?

**Comment by mojavelinux** [comment]
The more I think about this, the more I think that this isn't a global setting but rather a semantic part of the content. How the index terms get expanded is going to affect how you define them. Therefore, I think we should consider a slightly different syntax when the intent is to not automatically promote them.

```
indexterm:[widgets > foo]
```

or

```
((widgets > foo))
```

The `>` indicates a strict hierarchical relationship between terms and not an "anything goes, just index it". This is similar to `!` in LaTeX (except I think that the `>` is more self-explanatory). It also builds on the pattern we've establishes of menu items in the menu macro.

For this reason, I'm going to reschedule for 1.5.4 so that we can get it right.

**Comment by eskwayrd** [comment]
`indexterm-promotion` does seem to be better than `promote-indexterms`. Thanks for implementing a fix so quickly!

I do like your suggestion of a new syntax for expressing whether promotion is involved for each indexterm instance, and also that you can potentially re-use parsing already established for menu macros.

When I get a chance, I'll file a new issue covering enhancing the syntax to permit see and seealso.

Thanks!

**Comment by mojavelinux** [comment]
Thanks!

**Comment by andrewcarver** [comment]
I'm gonna give it as my opinion that the original AsciiDoc thing of "promoting" the indexterms was a large and surprising departure from DocBook's semantics. So large, in fact, I was sure it must be a bug in Asciidoctor!! Glad to hear "it wasn't a bug, it was a feature" in Asciidoctor--but, I'd strongly, maybe even vehemently recommend it be removed, period. Or, at the very least, that non-"promotion" be the default. If people want "promotion", they can always get exactly what they want, under better control, with another entry or two.
Thus, I'd recommend forgetting about the added syntax, too.
As for "see" and "seealso", the implementation I have of those, and of all the other index-markup abstract syntax in DocBook, is perhaps worth at least a look: 
https://github.com/asciidoctor/asciidoctor-extensions-lab/pull/87

**Comment by andrewcarver** [comment]
In fact, one serious problem with this indexterm promotion is precisely that it's semantically _incompatible_ with 'see' and 'seealso': for if we assume such forcing is proper, and there be a secondary and a tertiary in a given indexterm, and you had a <see> or <seealso> in it as well, it would be ambiguous, to which "promotion" that <see>, or to which level that <seealso>, is to apply.

**Comment by andrewcarver** [comment]
In short, give up promotion or give up having sensible 'see' / 'seealso'.

**Comment by andrewcarver** [comment]
It makes semantic havoc also of "sortas". Each "sortas" applies to a specific entry in the index, at a particular level. To which entry, at which level, does it apply if we assume every indexterm is to be 'promoted'??

**Comment by bimlas** [comment]
In my opinion, promotion gives you a "dynamic" table of content. I'm not sure about the behaviour, but take a look at an example:

```asciidoc
(((browser,chrome,plugin,asciidoctor)))
Asciidoctor.js Extension

(((ruby,gem,asciidoctor)))
Asciidoctor
```

![image](https://user-images.githubusercontent.com/7034200/39663465-32edd182-5074-11e8-8aff-ac29739c681b.png)

If you want to find everything about Asciidoctor, then you can use `Ctrl-F`, but it's not an elegand solution.

I think about indexterms as hashtags: labeling the document with keywords to let me find the parts I'm interested in rapidly.

Here's a real example: http://www.sphinx-doc.org/en/master/genindex.html Search for `coverage_ignore_classes`: it is listed as a standalone entry, having `configuration_value` as a subentry (because the linked "paragraph" related to both terms), besides this it's a subentry of `configuration_value`. Thus the user can found the link easily regardless of the order of the terms.

**Comment by andrewcarver** [comment]
Thank you for explaining further. And yes, I see your point. But of course, you don't need any elaborate contraption like automated "promotion" to solve the simple index-markup problem of your coverage_ignore_classes thing. Indexing folk have always solved that with two entries, quite easily.

On re-reflection, though, your reply helped me see that the extent of my horror at the way "promotion" makes nonsense of 'see' and 'seealso', was actually at *the way I was originally misreading* how the AsciiDoc indexterm-multiplication worked. Here's an example of what I mean:

You enter this:
`(((Big cats,Tigers,Bengal Tiger, see=Wolpertinger)))`

DocBook will give you an entry like:

Big cats
   Tigers
        Bengal Tiger
             *see* Wolpertinger

But your system is very sophisticated, wants to help the user. So it "promotes" this index entry, only now there's a question what to do with the "see": did the "see" intend, or not intend, the reader to be redirected to "Wolpertinger" from the following entries:

Tigers
        Bengal Tiger
             *see* Wolpertinger

 Bengal Tiger
         *see* Wolpertinger

Well, that at least makes some sense of the "see"--much more sense than these entries would make (i.e., how I was originally misreading AsciiDoc's "promotion" to work):

Big cats
   Tigers
      *see* Wolpertinger

Big cats
    *see* Wolpertinger

So I apologize for that conflation on my part: my horror about 'see' and 'seealso' has now been greatly mitigated. (With your help ;) I would still make NON-"promotion" the default, though. 

But I'm seeing now (also with your help) what Dan's most recent concern is about. And he's actually brought out an important issue with semantics in indexes: what the term means can depend on the context (as is true in non-index discourse). I think his point is well-taken as an objection against *global* promotion. But in language, it is so much the NORM, that meaning depends on context, that to me it puts *any* global semantics, even of "do promotion *except where I've indicated a strict* hierarchy", in serious doubt.

So, although you've helped me see more clearly what the concern was that gave rise to the "promotion" contraption, I feel this is a case of getting a bit "too cute", to the point of muddying the "[conceptual integrity](https://en.wikipedia.org/wiki/The_Mythical_Man-Month#Conceptual_integrity)" of the system: 

> A novel idea by someone may not be included if it does not fit seamlessly with the overall system design. In fact, to ensure a user-friendly system, a system may deliberately provide fewer features than it is capable of.

**Comment by andrewcarver** [comment]
"Seealso" http://www.safnet.com/writing/tech/2011/11/mythical-man-month-conceptual-integrity.html

**Comment by andrewcarver** [comment]
If we want to respect Fred Brooks' dictum of conceptual integrity, I think we need to remind ourselves, sometimes, what AsciiDoc was created to be: a lightweight frontend for writing DocBook.

**Comment by mojavelinux** [comment]
@bimlas I don't think what Sphinx is doing is the same. It seems like Sphinx is just creating commutative entries (A > B) and (B > A). What Asciidoctor is doing is actually promoting secondary and tertiary entries to primary entries. So if you specify (A, B, C) you get (A > B > C) and (B > C) and (C). (But you don't get commutative entries). This is what @andrewcarver is saying is unexpected. Having studied it more, I'm inclined to agree.

Since the index is not created in any of the built-in converters, and thus likely only in a docs pipeline, I'm happy with disabling this by default and requiring the option to reenable the behavior. That makes the default behavior more sane but still provides a way for users to preserve existing behavior. It's also worth nothing that indexterm promotion isn't implemented in Asciidoctor PDF. All the more reason to enable an option purely for backwards compatibility.

**Comment by mojavelinux** [comment]
For the record, I consider see/seealso to be a separate concern/enhancement (though certainly muddied by the promotion behavior we're talking about here). Let's discuss in #2047.
