### ISSUE TITLE
Allow nested checklist

### ISSUE THREAD

**Issue by cinhtau** [asciidoctor/asciidoctor#1491]
You can write checklist like that:

```
- [ ] Hardware
- [ ] System
- [ ] Network
- [ ] Database
- [ ] Application
```

It gives me this:

- [ ] Hardware
- [ ] System
- [ ] Network
- [ ] Database
- [ ] Application

What if I want to indent or nest network or database to illustrate that it belongs to System. I tried this:

```
- [ ] Hardware
- [ ] System
-- [ ] Network
-- [ ] Database
- [ ] Application
```
but the rendering didn't work.

**Comment by mojavelinux** [comment]
The problem here isn't lack of support for nested checklists, but rather how you are defining your nested list. The hyphen can only be one level deep (usually the top-level). If you want to use nested levels, you need to use repeating asterisks.

```
* [ ] Hardware
* [ ] System
** [ ] Network
** [ ] Database
* [ ] Application
```

If you enter it that way, you should see that it works.

**Comment by cinhtau** [comment]
![2015-10-01 07_50_06-clipboard](https://cloud.githubusercontent.com/assets/7956174/10213727/2893e0bc-6811-11e5-9e2f-c0fc829acc40.png)

Check the output of html and pdf generation! :sunny: Thanks for the clarification and support.

**Comment by mojavelinux** [comment]
\o/
