### ISSUE TITLE
AST: Subsequent list should not have the previous list as parent

### ISSUE THREAD

**Issue by ysb33r** [asciidoctor/asciidoctor#1519]
Consider the following snippet.

```
== Chapter With Simple Lists

* UList #1
* UList #2
** UList #2 #1
** UList #2 #2
* UList #3

. OList #1
. OList #2
..OList #2 #1
.. OList #2 #2
. OList #3
```

The parent of `UList #1` is the section (chapter). , but the parent of `OList #1` is the previous `UList`.
I would argue that the parent should be the section as well. 

This happens regardless of the number blank lines between the two lists. 

(I am seeing this indirectly with asciidoctorj-1.6.0)

**Comment by mojavelinux** [comment]
I don't think this is an AST issue, I think this reflects how it is being parsed. I'm almost 100% sure that the ordered list is being added as a child of the last unordered list item. So the AST only speaks the truth.

This is a common problem in AsciiDoc because it is *extremely* difficult to decide when a list is truly complete. It looks clear in this case, but it's in the eye of the beholder (not the parser).

One way to get lists to separate is to use the following list terminator trick.

```
* UList #1
* UList #2
** UList #2 #1
** UList #2 #2
* UList #3

//break
. OList #1
. OList #2
..OList #2 #1
.. OList #2 #2
. OList #3
```

I know this isn't pretty, but you only need to use it when lists are directly adjacent.

**Comment by ysb33r** [comment]
Mmmm.... Usage of the comment works. Probably should document this somewhere.

**Comment by mojavelinux** [comment]
There's a sidebar about it in the manual.

http://asciidoctor.org/docs/user-manual/#unordered-lists

I'm going to give it an id so we can link to the sidebar directly.

**Comment by mojavelinux** [comment]
http://asciidoctor.org/docs/user-manual/#separating-lists
