### ISSUE TITLE
Make heading for colophon and dedication optional

### ISSUE THREAD

**Issue by shahryareiv** [asciidoctor/asciidoctor#1521]
At the moment both colophon and dedication styles need to be followed by a heading, otherwise it complains "invalid style for paragraph: dedication" and of course wrong rendering (docbook) . It seems it was a requirement from Asciidoc, but most of the time none of the colophon or dedication has any heading. 

So all these should be valid:

```
[dedication]
Some dedication
```

```
[dedication]
= Dedication Chapter
Some dedication
```

Even this if a blank heading gives more sense can be an option

```
[dedication]
= 
Some dedication
```

**Comment by shahryareiv** [comment]
Using `.{zwsp}`  fixes the thing but probably not a nice solution.

**Comment by mojavelinux** [comment]
A dedication and colophon must defined using a section (or else we have to change some fundamental assumptions in the parser). But I understand that a title is not always needed. What we could do is follow the convention we use in the HTML slideshow backends and allow a value of "!" to indicate that there is no section title.

```
[dedication]
= !

Dedication text goes here.
```

An empty value isn't possible because then we can't detect the line as a section heading (it would just be normal content of an `=` sign).

There are other ways to achieve this in the interim.

One way is to create a custom block extension that recognizes the `dedication` and `colophon` block style and automatically creates the appropriate section in the AST.

An even simpler way is to use a custom Slim template for section that drops the title for dedication and colophon despite them being in the source document. (Starting point for DocBook output https://github.com/asciidoctor/asciidoctor-backends/blob/master/slim/docbook45/section.xml.slim).

**Comment by mojavelinux** [comment]
I've proposed a PR which adds support for the `concealed` option on special sections in the DocBook converter. See https://github.com/asciidoctor/asciidoctor/pull/2461

```
[dedication%concealed]
= Dedication
```

It's important to still assign a title as it may be used in a cross reference scenario. But the presence of the `concealed` option means it won't be included in the output.

I'm also considering the following alternative names for this option:

* covert
* veiled
* incognito

Please note that support for a dedication paragraph must be something that is handled by an extension.

**Comment by mojavelinux** [comment]
Let's go with "untitled". It's clear and to the point. If a title is provided, it is effectively ignored.

**Comment by mojavelinux** [comment]
Let's start with this feature just on special sections for DocBook output. If this experiment goes well, we can extrapolate this to section titles in general.

```asciidoc
[dedication%untitled]
= Dedication
```

**Comment by shahryareiv** [comment]
Perfect!

**Comment by graphitefriction** [comment]
@mojavelinux How does this impact what I have to document:

> Please note that support for a dedication paragraph must be something that is handled by an extension.

Because when I read this sentence I interpret it as, "while the `untitled` option can be set on a special section, the user will still need to create a custom extension to apply a result to that value when using the DocBook backend"  ... see where I'm going with this :wink: ? So is a custom extension needed or not?

**Comment by rmschindler** [comment]
is there any reason why this does not work if the doctype is `book`? :

> ```
> [dedication%untitled]
> = Dedication
> ```

the documentation says ‘DocBook only’ — how come? . as a book author, am I forced to have a title for my dedication section?
