### ISSUE TITLE
Local path with file:// protocol are resolved as relative paths

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor#1561]
Local path with file:// protocol are resolved as relative paths.

When running Asciidoctor.js in a browser environment, local paths starting with `file://` should be resolved as local path.

One use case is to be able to read csv file for the chart extension:

```
chart::sample.csv[line]
```

Exception when running in Asciidoctor.js and safe mode = `UNSAFE`:
```
Exception : asciidoctor: FAILED: : Failed to parse source, (intermediate value)(intermediate value)(intermediate value).$readable? is not a function
```

Exception when running in Asciidoctor.js and safe mode = `SAFE` or `SERVER`:

```
SecurityError : asciidoctor: FAILED: : Failed to parse source, Jail is not an absolute path: ...
```

**Comment by mojavelinux** [comment]
Context of discussion and history can be found in #1354.

**Comment by mojavelinux** [comment]
I've worked out the precise matrix that describes the failure.

```
|===
|base_dir     |safe mode < :safe   |safe mode >= :safe

|.            |succeed             |fail: Jail is not an absolute path .
|file:///...  |fail: invalid path  |fail: Jail is not an absolute path file://...
|====
```

The upper-right quadrant is supposed to fail because it's not permissible in :safe mode or above to resolve a file system path when the jail is relative. We're really focused on the bottom two cells, when the base_dir is set to a file:/// URL.

For the record, where this fails in the chart block macro extension is in the call to `normalize_asset_path` to resolve the source data (i.e., target). It uses:

```ruby
normalize_asset_path target, 'target'
```

which in turn calls:

```ruby
normalize_system_path target, @document.base_dir, nil, ...
```

What it comes down to is the `is_root?` call in PathResolver. That method needs to recognize `file:///` as a root in the Opal environment.

We should not, however, apply this outside the Opal environment because I worry that it will be perceived as a security vector, even if it isn't.

**Comment by mojavelinux** [comment]
We'll also check for the browser environment.

**Comment by Mogztter** [comment]
> What it comes down to is the is_root? call in PathResolver. That method needs to recognize file:/// as a root in the Opal environment.

Yes that's exactly what I found

> I've worked out the precise matrix that describes the failure.

This is another issue but I think we should also clarify the error message to explain the context and how to solve the error. Something like:

"fail: . is not an absolute path. For security reason, macros/includes are only allowed with absolute path. To change this behavior set safe mode to UNSAFE"

Wdyt ?

**Comment by mojavelinux** [comment]
> This is another issue but I think we should also clarify the error message to explain the context and how to solve the error.

:+1: 

> "fail: . is not an absolute path. For security reason, macros/includes are only allowed with absolute path. To change this behavior set safe mode to UNSAFE"

Let's open a separate issue for that one. But good idea. The message is very cryptic as it stands.
