### ISSUE TITLE
ifeval in header does not work

### ISSUE THREAD

**Issue by gdolle** [asciidoctor/asciidoctor#1585]
Hi,
I use separate file for headers and I just include it in all my asciidoc notes
```cpp
ifeval::[{leveloffset} == 0]
Name <mail@mail.com>
v1.0, 2015-11
:toc: macro
:icons: font
endif::[]
```
The evaluation `Ifeval` is working with asciidoctor 1.5.2, but since version 1.5.3, the header is not processed. I guess it's a bug, but maybe it's the wanted behaviour now ?

**Comment by mojavelinux** [comment]
Due to the following change in 1.5.3, an undefined attribute is no longer equivalent to 0. (The `leveloffset` attribute is not set initially).

https://github.com/asciidoctor/asciidoctor/commit/9728af3ecb4bb61952130c1a814ff0751b8665e8#diff-9f52e64185d6eaeea012017fc43a9fa0

This was done for compliance with AsciiDoc Python. See #1387.

"A missing attribute in the ifeval expression should always resolve to an empty string."

I'll go ahead and add a test for 0 equality just to be sure this behavior is explicitly tested.

Since the `leveloffset` attribute is not set by default, you should assign it a default value before your `ifeval`.

```
ifndef::leveloffset[:leveloffset: 0]
```

Then you should be covered.

It does raise the question about whether leveloffset should be set to 0 initially. 0 is the fallback value, but not explicitly assigned. I'd be open to considering that if it's important.

**Comment by mojavelinux** [comment]
The `ifndef` assignment is a very powerful tool :)

**Comment by mojavelinux** [comment]
Test added.

**Comment by gdolle** [comment]
Ok thanks for the explanation, it works :)

**Comment by mojavelinux** [comment]
\o/

**Comment by mojavelinux** [comment]
Thanks for testing!
