### ISSUE TITLE
Document title doesn't render when immediately followed by table with title

### ISSUE THREAD

**Issue by leif81** [asciidoctor/asciidoctor#1587]
This will produce a document without a document title.

    :DocTitle: foobar
    
    .table title
    |===
    |foo
    |bar
    |===

Tested with asciidoctor 1.5.3

**Comment by leif81** [comment]
I just found a workaround. It works if you specify the title as a section instead of an attribute:

    = foobar

**Comment by mojavelinux** [comment]
You are right, this is non-compliant behavior. What's happening is that the title on the table is triggering a premature return from the header parser here: https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/parser.rb#L94-L96

I can see what we need to do. We need to take that early exit only if the next line is an explicit doctitle.

In truth, we need to be more strict about the document header because there is a lot of crazy logic in there that is unnecessary. This issue only reminds me of that. However, we can certainly fix this case for now.

**Comment by mojavelinux** [comment]
Nice catch, btw!
