### ISSUE TITLE
manpage: \ inside `...` and listing/literal block should be verbatim in manpage too

### ISSUE THREAD

**Issue by ds26gte** [asciidoctor/asciidoctor#1604]
Occurrences of `\` (backslash) inside \`...\` and listing/literal blocks are currently being sent as-is to the manpage output. Man however treats backslash as an escape, so what the user sees depends on whatever character happens to follow the backslash. (Typically, the backslash gets swallowed, so `\input` becomes `input`.)

This is in contrast to the HTML backend of asciidoctor, where the backslash in such contexts is treated as a verbatim backslash (i.e., it typesets as itself).

E.g., the following document fragment gets treated differently between the HTML and manpage backends:

````
TeX uses `\input` to include files.  For example,

   \input otherfile

----
\input otherfile
----
````

Let me know if you agree this is a bug. I have a fix for this that makes the manpage output align with the HTML output (which I consider to be correct).

**Comment by mojavelinux** [comment]
Anytime you see the manpage display something differently than what HTML is doing, then I'd consider that a bug. The HTML output is the reference.

One way to look at backslash in the manpage backend is to treat it in the same family as the XML special characters (`<`, `>`, etc). But that's really tricky since backslash also has meaning in AsciiDoc.

I think in the end, we're going to end up guessing a bit to get this right...and there are going to end up being things that get converted when they shouldn't....a bit of a whack-a-mole.

Having said that, if it's in a literal context (inline code, literal or listing), then I think it's probably save to escape the backslash for typesetting.

**Comment by mojavelinux** [comment]
...another way to determine when you are looking at a bug is to convert it to DocBook, then convert it to manpage using a2x. That at least gives us another reference. In this case, the manpage backend for DocBook properly escapes these backslashes.

**Comment by mojavelinux** [comment]
```
asciidoctor -b manpage command.adoc
a2x -f manpage command.xml
man ./command.1
```

**Comment by ds26gte** [comment]
Yes, the current bug has only to do with how backslash is treated within \`...\` and literal and listing blocks. I don't yet know if there are subtle differences in the way AsciiDoctor and man treat backslashes in *other* contexts, but I'll keep my eyes peeled. In any case, that issue isn't made worse by this bugfix.

PR submitted.

**Comment by mojavelinux** [comment]
:+1: Thanks!
