### ISSUE TITLE
idprefix attribute not recognized when passed on CLI in v 1.5.3 

### ISSUE THREAD

**Issue by rdhyee** [asciidoctor/asciidoctor#1605]
I'm able to set the `idprefix` with the following command

```
asciidoctor -a toc,idprefix=xx_,version=$VERSION -b xhtml5 -T ./asciidoctor-htmlbook/htmlbook-autogen/
  -d book book.asciidoc -o book.html
```

with asciidoctor version `1.5.2` but not in the most recent version `1.5.3`

For version `1.5.3`, the default `idprefix` is used.

**Comment by mojavelinux** [comment]
We decided to drop the feature of defining multiple attributes with a single `-a` flag because it interfered with many of the values being passed (as part of #405). AsciiDoc Python does not support this arrangement, so technically it wasn't a requirement for compliance. We may reintroduce it in the future with more well-defined rules.

You need to specify the attributes using individual `-a` flags.

```
asciidoctor -a toc -a idprefix=xx_ -a version=$VERSION
```

**Comment by rdhyee** [comment]
Thanks @mojavelinux for your clarification!

**Comment by mojavelinux** [comment]
I've added this to the release notes.

Technically, we shouldn't have broken this in the 1.5.3 release, but in generally 1.5.3 was bigger than it should have been. We're hoping to be more true to semver after 1.6.0 is out.
