### ISSUE TITLE
asciidoc(tor): stop generating the "last updated" time in the end of the doc

### ISSUE THREAD

**Issue by pinggit** [asciidoctor/asciidoctor#1621]
how to stop generating the "last updated" time in the end of the doc?

![image](https://cloud.githubusercontent.com/assets/2038044/11911295/81b7d05c-a5df-11e5-90a5-9cee5ea9dced.png)

I'm trying to maintain a CV, and this line looks annoying...

**Comment by mojavelinux** [comment]
The easiest way to to disable the footer in the document header:

```
= Document Title
:nofooter:
```

**Comment by pinggit** [comment]
thanks Dan.
I compared the nofooter and :last-update-label!:
and I like `last-update-label!` better 😁

regards
ping

**Comment by mojavelinux** [comment]
:+1:

**Comment by jannikmi** [comment]
Neither of the two settings `:last-update-label!:` and `:nofooter:` helped in my case (i put them in the header as shown above).
Also passing them in the conversion CLI command (`asciidoc -a nofooter ...`) does not work as expected.
Is there anything I missed?

My last resort would be a postprocessing script.

**Comment by ggrossetie** [comment]
Hey @jannikmi, you probably won't get many replies on an issue that was closed 10 years ago. I suggest asking your question on the community chat: https://asciidoctor.zulipchat.com/
It looks like you're using `asciidoc` (Python) rather than `asciidoctor`. It should work if you use a recent version of Asciidoctor. Please note that AsciiDoc.py is the legacy AsciiDoc processor.

**Comment by mojavelinux** [comment]
nofooter is the correct attribute. If you need assistance, as Guillaume mentioned, please ask in the project chat at https://chat.asciidoctor.org.
