### ISSUE TITLE
kbd macro does not handle , or + well.

### ISSUE THREAD

**Issue by jjaderberg** [asciidoctor/asciidoctor#1660]
## Short and sweet

`kbd` macros can only render a `,` or `+` literally when it is the final 'attribute' char, and there is no way to escape the char to force literal rendering.
## What I did

Using Vim, I have `,` set as `<LocalLeader>`. In the readme for my asciidoc plugin I want to document some mappings. It's too long to write `kbd:[<LocalLeader>te]` and similar everywhere, so I want to declare my local leader and write the mapping as `kbd:[,te]`.
## What I expected

I expected the output to be a key string of `,te`.
## What happened

The output is: 
![kbd1](https://cloud.githubusercontent.com/assets/6028968/12131270/70384858-b411-11e5-99be-8d1942999e26.png)
## Comments

Additional variations of the macro:

```
. kbd:[\,te]
. kbd:[, te]
. kbd:[,+te]
. kbd:[te,]
. kbd:[t\,e]
. kbd:[+te]
. kbd:[te+]
. kbd:[t+e]
. kbd:[+te]
```

![kbd2](https://cloud.githubusercontent.com/assets/6028968/12131286/822f3d96-b411-11e5-98ce-6219722a9c04.png)
## Conclusion

It looks like the `kbd` macro can't handle a literal `,` or `+` except when they are the last character in the 'attribute'.

I would like to be able to render a key string like `,te`, to explain that this is what to type to mark the visual selection or the word under cursor as _emphasized_ in my Asciidoc Vim plugin.

**Comment by mojavelinux** [comment]
I think we may be able to be smart about when a character is a delimiter vs when it is content. It may not cover all cases, but we can at least hit the obvious stuff. If one of the positions ends up blank (as in your case), we know it wasn't a delimiter.

The other option is to allow the string to be quoted so that it is taken literally.

Until then, the workaround is to use a character entity instead of the literal character. It will still look the same in the output.

```
:ll: &#44;

kbd:[{ll}te]
```

You can also use an inline passthrough (not to be confused with kbd delimiters):

```
kbd:[+,te+]
```

Both get you the desired output.

**Comment by mojavelinux** [comment]
Here are two examples that I think we could get working in their raw (unescaped) form.

```
kbd:[,te]
kbd:[Ctrl+,+.]
```

Btw, the universal way to escape things in AsciiDoc is to use a passthrough. Backslashes only work under very special circumstances.

**Comment by jjaderberg** [comment]
Thanks for suggesting pass through, I can now use `,` in a kbd macro the way I want!

I wasn't aware that `,` is a delimiter in this context. The manual gives the kbd macro syntax as `kbd:[key(+key)*]` and the examples in the manual and quick reference use `+` to delimit keys. Same goes for #172. But when I [look at the code][1], it seems `,` and `+` are equally valid delimiters.

Do `,` and `+` do the same thing in this context? Is there a place where I can read more about the kbd macro than what is in the manual or in the linked issue?

The only place I've found where `,` is used to delimit keys in a keyboard macro is  [this (older) issue][2], linked from the one above, discussing `key` and `keycombo` macros.

[1]: https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor.rb#L883
[2]: https://code.google.com/p/asciidoc/issues/detail?id=17

**Comment by mojavelinux** [comment]
I'm glad to hear it works!

> I wasn't aware that , is a delimiter in this context.

I implemented comma it as an alternative delimiter to plus but did not document it. They do the same thing. I'm still trying out the idea (hence why these are still experimental macros). It felt comfortable to me at the time, but I'll admit it looks more natural with the +.

>  Is there a place where I can read more about the kbd macro than what is in the manual or in the linked issue?

The code :) If the user manual doesn't mention something, then you can assume its not documented.

**Comment by jjaderberg** [comment]
I'll read the code as soon as I've finished my current Tom Clancy novel :)

Are the "keys" passed to the kbd macro attributes in an attribute list (as defined here [1][1], [2][2])? If that is the case, then I think it would be better to use `,`, since that is how attributes are delimited in attribute lists for other macros. It can also be confusing that `+` is used both for pass through and delimiter.

[1]: http://www.methods.co.nz/asciidoc/userguide.html#_macros
[2]: http://www.methods.co.nz/asciidoc/userguide.html#X21

**Comment by mojavelinux** [comment]
"Short" inline macros, like this one, don't have attributes (attributes aren't parsed) and it's assumed that the value inside the brackets is the target. So the comma doesn't have another meaning here. Having said that, it probably makes the most sense to pick one of the delimiters and stick with it rather than having two options. So this is really a user (writer) experience decision. Should the writer have to use `+` or should we continue offering the `,` delimiter. Given that the comma separates attributes in other context, it might not be a good idea to be overloading it here. It's also much more intuitive for people to write `kbd:[Ctrl+T]` than `kbd:[Ctrl,T]`.

**Comment by jjaderberg** [comment]
The output would usually presented with a `+` so I absolutely agree that it would more intuitive for the user. What about the overloading of `+` in this context for both delimiter and pass through? Would you consider allowing `\` escapes and turning off pass through, making `+` single purpose?

**Comment by mojavelinux** [comment]
> Would you consider allowing \ escapes and turning off pass through

The passthrough escape is already handled by the passthrough handler. There's nothing the kbd macro has to (or can) do in this scenario. The passthrough is handled as an inline preprocessor, so the kbd macro never sees the passthrough nor does the passthrough see the kbd macro (since it's context free). Keep in mind, however, that the escape can only be used if there is a pair in the line. Otherwise, it comes through as a literal backslash (just the way AsciiDoc works atm). In fact, I'd say at this point that AsciiDoc doesn't really support backslash escape at this point except in very special circumstances. That's something for the future.

You are correct that we end up overloading the meaning of `+` here, but I think in this case there's enough context that it's understandable. Though, it may have been why I opted to add a comma as an alternative. The issue here isn't really with the kbd macro, but rather inline parsing in general. It's just tricky when you have to incorporate symbols that have meaning elsewhere. See #61.

**Comment by mojavelinux** [comment]
Having said that, we could check that the delimiter is not escaped...if it makes it that far.

**Comment by mojavelinux** [comment]
```
kbd:[Ctrl+,+.]
```

This case is now supported. We look for the first `+` or `,` and then use that character as the delimiter.

**Comment by mojavelinux** [comment]
> The `,` felt comfortable to me at the time, but I'll admit it looks more natural with the `+`.

I now remember why I introduced `,` as an alternative delimiter. There are actually two reasons. When `+` is one of the keys, it's simpler to use `,` as the delimiter. The second reason is that `+` is used as a delimiter for passthough content and therefore can sometimes be problematic. In those cases, `,` offers an escape hatch.

**Comment by mojavelinux** [comment]
```
kbd:[,te]
kbd:[te,]
```

These cases are now handled. The parser treats a leading or trailing delimiter as a literal character.

**Comment by mojavelinux** [comment]
What remains is some way to escape the delimiter. Consider this case:

```
kbd:[t,e]
```

This is a pretty rare circumstance. What looks to the human as a key combination of `t + e` is actually mean to be a run of literal characters. We could introduce a backslash escape, though that would complicate parsing considerably. We could say that for this case, you have to use a character reference to represent the comma:

```
kbd:[t&#44;e]
```

If it's really important to have a way to escape the comma, then I will certainly reconsider.

**Comment by mojavelinux** [comment]
I'm going to propose a pull request that resolves this issue. If we decide that we still want to add additional escaping, then let's either reopen or create a follow-up issue.
