### ISSUE TITLE
Output index when using PDF backend

### ISSUE THREAD

**Issue by vogella** [asciidoctor/asciidoctor#1661]
As suggested via #450 by @mojavelinux , there should be a separate issue for creating an index for the PDF output.

I'm new to asciidoctor but my understanding is that creating an index without extending asciidoctor currently requires to output DocBook and convert DocBook to PDF. Would be great if asciidoctor support the direct creation of the index. AFAICS this is the only feature missing to avoid creating DocBook for PDF creation.

**Comment by mojavelinux** [comment]
Your understanding of the current situation and what needs to be done is
exactly correct.

**Comment by jxxcarlson** [comment]
I've implemented an index feature as part of the asciidoctor-latex package, an extension which is used in [noteshare.io](http://noteshare.io)-- see [this example](https://vschool.s3.amazonaws.com/manuscripts/456.html) and scroll down to the index.  More to the point, I've broken out the indexing code in [this file](https://github.com/jxxcarlson/noteshare/blob/master/lib/noteshare/modules/document_index.rb) where is used to produce a standalone index.  I think it could be evolved into something that would do what you want to do.  I'd be happy to help in this regard is so desired.

**Comment by mojavelinux** [comment]
Thanks for sharing Jim.

The standalone index generator certainly fills a gap we have at the moment, but for the long term solution, we must use the AsciiDoc parser to extract the terms. Just like XML, we can't simply parse AsciiDoc with regexp alone because it lacks the essential context to know it is extracting information from the right places. For instance, is the match in a literal block, a comment or a passthrough?

As it turns out, if you run the Asciidoctor parser all the way through conversion, the resulting document object does contain all the index terms (in the Document#references[:indexterms] table). It may be missing some essential information about where those index terms came from, so there's still some work we need to do. But the key point is that the parser does know how to find the terms.

What I'm confident about is that we have enough information now to add an index section in Asciidoctor PDF.

**Comment by mojavelinux** [comment]
Ooops, this issue needs to be filed in the Asciidoctor PDF repository. I'll reopen it there and link to it.

**Comment by mojavelinux** [comment]
See https://github.com/asciidoctor/asciidoctor-pdf/issues/386.
