### ISSUE TITLE
Combining anchors and definition lists doesn't work.

### ISSUE THREAD

**Issue by ghost** [asciidoctor/asciidoctor#1675]
I have tried several combinations and they seem to fail in different ways.

```
anchor:id[Name]
`Name`::
Description of the name.

With a reference to <<id>>.
```

Doesn't produce correct HTML 5. The reference to the anchor is correct, but the text replacement is `[id]`.

Placing a blank line after the anchor line resolves the issue, but then when producing docbook a bunch of extra blank lines seem to be placed into the final output.

**Comment by mojavelinux** [comment]
The problem you are running into is that Asciidoctor only catalogs (stores in the reference table) inline anchors that are in paragraph text. While the following syntax will create a working reference:

```
[[id,Name]]`Name`::
Description of the name.

With a reference to <<id>>.
```

the link text will be `[id]` instead of the expected `Name`.

You can workaround this issue by moving the anchor to the description.

```
`Name`::
[[id,Name]]Description of the name.

With a reference to <<id>>.
```

Note that the description list label/term must be a single line. Your example was creating extra blank lines because it wasn't being interpreted as a single description list.

The fix here is that we should be cataloging anchors in the list label (as well as the primary list text for any list).

**Comment by beastham** [comment]
That matches what I am currently doing, with the caveat that the anchor in the HTML points to the paragraph, not the term. If you select a reference to a location above you then the browser puts the paragraph at the top of the screen and the label off screen.

**Comment by mojavelinux** [comment]
> If you select a reference to a location above you then the browser puts the paragraph at the top of the screen and the label off screen.

Yep, that is the downside of this workaround. That's why it is just a workaround until we have a proper fix.

Another approach is to put the anchor in the proper position with the xreflabel you want, but then manually insert the xreflabel at the reference point until the issue is resolved.

```
[[id,Name]]`Name`::
Description of the name.

With a reference to <<id,Name>>.
```
