### ISSUE TITLE
Support nested <em>

### ISSUE THREAD

**Issue by andya9** [asciidoctor/asciidoctor#1691]
In html we can nest `<em>` elements:

```html
<p>Some normal text <em>Emphatic text <em>with an emphatic word inside</em> and other emphatic text</em></p>
```

This way we preserve the semantic info that `<em>with an emphatic word inside</em>` is emphatic, that instead we lose when doing:

```
Some normal text _Emphatic text_ with an emphatic word inside _and other emphatic text_
```

**Comment by bk2204** [comment]
This can be done if you write it like this:

```asciidoc
Some normal text _emphatic text, __quite__ emphatic indeed_.
```

The current stylesheet doesn't render it properly (which can be fixed, obviously), but it should work for two levels at least.

**Comment by mojavelinux** [comment]
Are you saying that the emphasis should be reversed when nested?

**Comment by mojavelinux** [comment]
We'll need to make this modification in the stylesheet factory as well. Since it's minor, I don't mind handling it here then porting the change upstream. Just a reminder.

**Comment by bk2204** [comment]
Yes, the typical presentation is roman text when emphasizing italicized text.

**Comment by bk2204** [comment]
I'll submit an appropriate patch against the stylesheet factory.

**Comment by bk2204** [comment]
I've opened asciidoctor/asciidoctor-stylesheet-factory#34 to address this.

**Comment by mojavelinux** [comment]
The first part of this issue is a support request, the second part is implementing the styles given that we know how to mark up nested emphasis.

The solution/workaround that @bk2204 provides will work in many cases, but there will be exceptions it won't cover. Namely, it won't be able to handle the case when you need the use the unconstrained formatting at both boundaries.

Another solution is to use a span of text for the inner emphasis:

```
Some normal text _emphatic text, [.em]#quite# emphatic indeed_.
```

Of course, the HTML wouldn't be semantic and you'd need to provide the necessary styles for the `em` class.

Unfortunately, there's no good way for Asciidoctor to currently support arbitrary nesting of formatting marks. That would only be possible once #61 is completed...and even then we'd really have to think about what was allowed.

Since there's a workaround documented, I'll leave this issue closed. But I think the question of where nested formatting marks can be used is an interesting discussion for UniDoc.

**Comment by andya9** [comment]
Thank'you for the work on this – I think @bk2204 's solution is already a huge gain
