### ISSUE TITLE
Is there a Live Preview (of Asciidoc) plugin for Emacs or Vim?

### ISSUE THREAD

**Issue by IbnSaeed** [asciidoctor/asciidoctor#1700]
Hello

Is there a Live Preview (of Asciidoc) plugin for Emacs or Vim?

**Comment by mojavelinux** [comment]
I am not aware of one, though it's possible to use the guard plugin to detect a change in the file and refresh the browser.

Could you ask this question on the mailinglist instead since it's a general question about tooling and not about this library. You'll likely get more participation that way as well. Thanks.

http://discuss.asciidoctor.org
