### ISSUE TITLE
Unregistration of selected Extensions

### ISSUE THREAD

**Issue by lefou** [asciidoctor/asciidoctor#1701]
It would be nice to have some API to unregister extensions. This is a prerequisite for a clean solution for https://github.com/asciidoctor/asciidoctorj/issues/359

**Comment by mojavelinux** [comment]
Agreed. I had been gravitating towards the idea of registering extensions under group names so that the group can later be removed. That resolves the problem of how to get a reference to the extension you want to remove (since it's not always easy to refer to it). I'll dive into where I was with this idea and see if we can move it forward.

**Comment by mojavelinux** [comment]
Actually, there is such an API. Asciidoctor::Extensions.unregister_all. Perhaps do you mean being able to unregister extensions individually? If so, my idea would be that all extensions would be added to a group (which is sort of the case now) and you can unregister by group. It's very hard to match a specific extension without having a reference to the internal object...but groups would give us that control.

**Comment by lefou** [comment]
Yes, I meant to unregister each extension individually. If that means, I have to generically create a new group for each extension I register, that would be OK.
In general, holding a handle or internal object or some kind of extension reference is no problem, as the mechanism that registers and unregisters the extension is stateful. Without deep knowledge of the asciidoctor internals, I can't tell if having per-extension groups is a miss-use.

**Comment by mojavelinux** [comment]
Per extension groups would be an intended use.

If I remember correctly, there are certain objects that we can't hold references to because they are either proxied or cloned internally. (Some cases work, others don't). That's why I like the group idea. It acts really as a label to the underlying object, and we don't have to worry about what type it is. I just haven't quite finished this part of the API...so that should be the focus here.

**Comment by mojavelinux** [comment]
I added a method to unregister extension groups by name (`Extensions.unregister *names`). The method takes one or more group names (which can be symbols or strings).

See PR https://github.com/asciidoctor/asciidoctor/pull/2265.

Let me know if you think this solution is going to work to satisfy your requirement.

Keep in mind we're referencing the extensions by their group name (or label) since it's the only reliable way to get a handle on an extension (and a bonus that you can use the group to organize them). While it may be possible to pass a class name or even an object to unregister, there's no good way to reference a proc (without passing it around). Therefore, we use the group name as the key to reference the object stored internally, regardless of its type.

**Comment by mojavelinux** [comment]
This is now fixed in core and soon to be part of AsciidoctorJ. @lefou which version of AsciidoctorJ are you using? (We need to determine where this belongs in AsciidoctorJ).

**Comment by lefou** [comment]
It was needed for proper OSGi service integration, which was planned for 1.6.x series. See   https://github.com/asciidoctor/asciidoctorj/issues/297 and https://github.com/asciidoctor/asciidoctorj/issues/359

**Comment by mojavelinux** [comment]
The question is, does it accomplish that goal. Robert is preparing the new
release of AsciidoctorJ. Would you be able to test it?

**Comment by robertpanzer** [comment]
I am just at it :)
AsciidoctorJ-PDF alpha.16 is already on bintray. 
If I should wait, stop me now ;)

**Comment by mojavelinux** [comment]
I think we should proceed with the release, then we'll just iterate if necessary.

**Comment by robertpanzer** [comment]
Just stumbled over JRuby 9.1.12.0 and Windows again with PDF.
Prawn fails to load itself in prawn.rb:11.
But it works with 9.1.8.0.

Should I put 9.1.8.0 into the distribution?
