### ISSUE TITLE
A missing include file is reported as a syntax error in the next included file

### ISSUE THREAD

**Issue by phayz** [asciidoctor/asciidoctor#1704]
Asciidoctor 1.5.2 [http://asciidoctor.org]
Runtime Environment (jruby 1.7.19 (1.9.3p551) 2015-04-16 fffffff on OpenJDK 64-Bit Server VM 1.8.0_71-b15 +jit [linux-amd64]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)
----
I was working on a document made up of multiple parts, so I created a "master" file consisting of sequential `include` statements.

include::topics/Configuration.adoc[leveloffset=+1]
include::topics/Installation.adoc[leveloffset=+1]

However I had not yet created the file `Configuration.adoc` and ran Asciidoctor against the AsciiDoc file.

Asciidoctor reported the following error:

asciidoctor: ERROR: topics/Configuration.adoc: line 1: invalid part, must have at least one section (e.g., chapter, appendix, etc.)

In response to the error I looked closely at the content of the `Installation.adoc` file and couldn't see any incorrect syntax. I finally realised I hadn't created the file mentioned first, and commented it from the master file and re-ran Asciidoctor. This time the Asciidoctor processing completed successfully and no longer reported the "invalid part" error.

**Comment by mojavelinux** [comment]
This is likely due to the unique combination of leveloffset and the secure mode. If the secure mode is secure (the default when using the API), it will turn the include into a link. In certain context, that may be illegal content, such as when a direct child of a part. Can you verify the safe mode setting?

One thing to note is that includes should always be separated by a blank line unless you are joining contiguous lines of content such as in a listing block. That may not fix the error, but it certainly will help avoid other ones.

**Comment by mojavelinux** [comment]
Actually, the leveloffset probably doesn't have anything to do with it in this case (but there are cases when that might be a factor).

**Comment by mojavelinux** [comment]
A more complete example would also help to determine if the processor can do anything to help here.

**Comment by phayz** [comment]
I have closed this issue as I am not able to recreate it.

**Comment by mojavelinux** [comment]
Let me know if it comes up again.

Having said that, I was able to confirm that it does happen when the safe mode is secure and the include becomes paragraph content (a link) directly after a part section. By converting include directives to links, we sometimes break the syntax. That is just a risk to be aware of.
