### ISSUE TITLE
Enable tagging include regions in circumfix comments, beyond line comments

### ISSUE THREAD

**Issue by sanmai-NL** [asciidoctor/asciidoctor#1729]
At least one important programming language, OCaml, [only supports circumfix comment delimitation](https://ocaml.org/learn/tutorials/basics.html#Comments). Asciidoctor currently only allows tagged regions in included content where tags immediately precede the end-of-line marker.

``` ocaml
(* tag::mytag[] *)
let problem = "This code sample will not be included. ";;
(* end::mytag[] *)
```

``` ocaml
(* tag::mytag[]
*)
let problem = "This will include a syntactically incorrect code sample. ";;
(* end::mytag[]
*)
```

I propose that Asciidoctor gets support for including tagged regions even in these cases. One solution is perhaps to reimplement tag detection so that lines with four or less non-whitespace, non-tag characters are accepted as tag markers.

**Comment by mojavelinux** [comment]
True, this is a limitation. Right now, we only support XML circumfix comments using a hack. (See https://github.com/asciidoctor/asciidoctor/blob/v1.5.4/lib/asciidoctor/reader.rb#L950-L951).

> One solution is perhaps to reimplement tag detection so that lines with four or less non-whitespace, non-tag characters are accepted as tag markers.

This wouldn't work for XML since the closing delimiter is `-->`. We'd need to match a few extra characters.

The reason we match in the way we do today is for speed, which for Asciidoctor is paramount. `end_with?` is much, much faster than a regular expression match.

The right solution may be to make the hack more generic. Use `chomp` appropriate for the file extension of the include. For XML, it's `-->`. For OCaml, it's `*)`. That way, we can still use the logic but get the flexibility of smart truncation. It would also speed things up for non-XML languages since we would only `chomp` for certain file types.

**Comment by mojavelinux** [comment]
> At least one important programming language, OCaml

While OCaml is certainly important, I'd argue that XML and CSS provide even more compelling justification for supporting this feature.

**Comment by mojavelinux** [comment]
Note that there's a similar problem with callout numbers in source code listings.

**Comment by mojavelinux** [comment]
I was able to abstract out the logic so that the suffix part of the circumfix comment is ignored if the extension of the include file matches one of the entries in the circumfix comments map. As far as the parser is concerned, the tag looks like:

```
(* tag::snippet[]
```

even though it's written like:

```
(* tag::snippet[] *)
```

The requirement is that there must be exactly one space between the end of the tag directive and the start of the comment suffix.

**Comment by mojavelinux** [comment]
I mapped the following languages:

* css
* html, xhtml, xml, xsl
* ml, mli, nb

You can modify the value of the constant if you need to support other languages. Eventually, we'll probably add some sort of API to control this mapping.

**Comment by mojavelinux** [comment]
The solution will be based on the extension of the filename. If we find that there are additional extensions we need to support, we can add them later.

I'm hopeful that we'll be able to take a similar approach to match callouts numbers behind line comments or inside of circumfix comments in verbatim blocks. However, that will require loading a full dictionary of comments by language alias or file extension. So that's a bit larger of a task.

**Comment by maverickwoo** [comment]
I arrived here also because of OCaml, but due to callouts. It seems there is no open issue (with the word "callouts" in it) that keeps track of this?

**Comment by mojavelinux** [comment]
See #1467.

**Comment by jaskij** [comment]
One more language to add is C - line comments were only added in the C99 spec and there are still large amounts of code (Linux kernel and microcontroller code are the ones I'm aware of) written to the C90/ANSI-C spec. Is it fine to just mention it here, or should I open a new issue?
