### ISSUE TITLE
Input "This is `p4`&ndash;`p5` kW." does render properly in HTML 5

### ISSUE THREAD

**Issue by michael-o** [asciidoctor/asciidoctor#1778]
While trying to render 

    This is `p4`&ndash;`p5` kW.

The output becomes This is `p4`&ndash;\`p5\` kW.

It seem like asciidoctor does not detect the backtick after the semicolon. Tried with asciidoclive.com and 

    $ asciidoctor -v
    Asciidoctor 1.5.4 [http://asciidoctor.org]
    Runtime Environment (ruby 2.2.5p319 (2016-04-26 revision 54774) [i386-freebsd9]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)

**Comment by mojavelinux** [comment]
This is one of those cases where unconstrained (double) formatting marks are required. In this case, p4 and p5 are not discrete words because they are separated by a character entity reference.

```
This is ``p4``&ndash;``p5`` kW.
```

In fact, this case is covered in the user manual specifically. See http://asciidoctor.org/docs/user-manual/#when-should-i-use-unconstrained-quotes

**Comment by mojavelinux** [comment]
If you feel like a better example in the documentation is needed, I'd be happy to accept it.

**Comment by michael-o** [comment]
I already though so, thanks. I wil take a closer look today and will let you know.

**Comment by michael-o** [comment]
@mojavelinux You are absolutely right, my bad. The chapter is quite helpful. Here it is: `&endash;**2016**`. Though, there is not entity `&endash;`, there is only `&ndash;`. You might want to fix that.

**Comment by mojavelinux** [comment]
Thanks for pointing that out. Fixed! I never realized the "e" wasn't included in the entity name for en dash. I guess that did that to make it 4 letters. (Sure enough, em dash is &mdash;)
