### ISSUE TITLE
Support converting to JATS

### ISSUE THREAD

**Issue by shahryareiv** [asciidoctor/asciidoctor#1792]
The Journal Article Tag Suite (JATS) is an XML format for scientific papers with a wide acceptance in life science journals and journal databases. The standard has been developed by National Information Standards Organization since 2003. There are also initiatives in markdown such as Jatdown ([http://www.ncbi.nlm.nih.gov/books/NBK350677/](http://www.ncbi.nlm.nih.gov/books/NBK350677/)).  There is also a pandoc-jats plugin.

Putting JATS in the Asciidoc ecosystem and the possibility to convert to HTML, ePub, Docbook , Latex, PDF, ... can involve scientific journal publishers as new stakeholders.

**Comment by shahryareiv** [comment]
Resources:

- JATS homepage:  https://jats.nlm.nih.gov/

-tags spec: https://jats.nlm.nih.gov/publishing/tag-library/1.1/

- Homepage on NISO: http://www.niso.org/apps/group_public/project/details.php?project_id=133

- JATS for Reuse: http://jats4r.org/

- JATS-con proceedings: https://www.ncbi.nlm.nih.gov/books/NBK65129/

**Comment by shahryareiv** [comment]
@mojavelinux  What is the right way of implementing Asciidoctor to JATS conversion? to define new block-elements or just to add roles? 

What I thought so far:

Semantically Asciidoc block-elements (or inlines) are the counterparts to JATS tags and if there exists a namespace mechanism then we can tag blocks and inlines like this **jats:affs** or this  **jats_affs** to include those tags but avoid a crowded the simple original tag list. The downside with this approach is that it needs a new backend? right?

If we use JATS tags as _roles_ then it does not need any change in the asciidoctor part (well, still it would be easier to do conversions at that level)  and XSLT can convert DocBook to JATS and my impression is that it would be probably easier. The downside with this method is that it can be semantically confusing also the conversion is being done by a third software not a part of simple asciidoctor command calling.

**Comment by mojavelinux** [comment]
I had a feeling this issue was going to come up eventually. I first learned about JATS last year when discussing AsciiDoc with the creator of https://pubref.org. Right away, I knew it would be something the Asciidoctor ecosystem would need to engage scientific journal publishers.

Since AsciiDoc was originally designed with DocBook export in mind, and JATS and DocBook have many similarities, I think this is going to be a natural fit.

The best think to do is to start a project named asciidoctor-jats to host the converter. It's going to look very similar to [asciidoctor-mallard](https://github.com/asciidoctor/asciidoctor-mallard), so you could probably use that as a starting point.

>  to define new block-elements or just to add roles?

I would say try to use the existing structural containers (aka delimited blocks), adding roles where necessary to clarify the semantics.

>  The downside with this approach is that it needs a new backend? right?

We need a new converter either way. Every output format needs its own converter.

>  XSLT can convert DocBook to JATS and my impression is that it would be probably easier

It's much easier to create a new Asciidoctor converter. It cuts out the middleman (and XSLT is one nasty middleman). Plus, there are plenty of examples to draw from, such as asciidoctor-mallard.

**Comment by mojavelinux** [comment]
I'll leave this issue open until the asciidoctor-jats repository is setup.

**Comment by pcj** [comment]
Joining this thread as @shahryareiv reached out to make me aware of it.  I'm available to help in spare cycles.

**Comment by mojavelinux** [comment]
There are now three converters available which could be used as a model for a JATS converter.

* https://github.com/riboseinc/asciidoctor-iso
* https://github.com/riboseinc/asciidoctor-csd
* https://github.com/riboseinc/asciidoctor-rsd

These are all different dialects of XML for specifications. Combined with the built-in DocBook converter, I think that provides plenty of raw material to understand how to create a JATS converter.

**Comment by manuelprinz** [comment]
I came into contact with JATS recently and found this bug. Since it has not progressed for a couple of years I had a go on the issue. You can find the (very preliminary) results in my repository at [manuelprinz/asciidoctor-jats](https://github.com/manuelprinz/asciidoctor-jats).

A little context: I learned Ruby just recently and am not familiar with all of the tools and gems yet. I read the code in the referenced repositories and from the DocBook converter and started to walk from there. (The code is quite ugly, and I plan to take some time to refactor. I just wanted to see if I would get something to work.) I'd appreciate any feedback, especially on missing Ruby idioms, etc. so I can improve my knowledge of the language.

Thanks in advance! And hope you find it useful!

P.S.: Although somewhat familiar with JATS, I'm also no expert in that either.

P.P.S.: I learned Ruby primarily so I could contribute to Asciidoctor in some way. Consider the JATS converter as an incarnation of this motivation. :smile:

**Comment by mojavelinux** [comment]
That's great to hear that you have picked up this imitative. If you want to give it more exposure, you can share it in the project chat or request to have it added to the extensions page on the asciidoctor.org site.

As for this issue, I'm going to close it since there is no plan to add a built-in JATS converter to Asciidoctor core.
