### ISSUE TITLE
Ruby not found after OS and ruby upgrade

### ISSUE THREAD

**Issue by dhinojosa** [asciidoctor/asciidoctor#1799]
After an upgrade of my kernel and depenendencies on linux, Ruby moved to 2.3 so now I have the following error:

```
/usr/local/bin/asciidoctor: bad interpreter: /usr/bin/ruby2.1
```

or

```
/usr/local/bin/asciidoctor-safe: bad interpreter: /usr/bin/ruby2.1
```

**Comment by mojavelinux** [comment]
How did you install asciidoctor? Also, could you paste the contents of /usr/local/bin/asciidoctor?

**Comment by anthonyvdotbe** [comment]
I had the same issue, with Ruby 2.5 on WSL (with Ubuntu 18.04) in Windows 10.

Asciidoctor was installed with `sudo apt install asciidoctor`
`/usr/local/bin/asciidoctor` started with `#!/usr/bin/ruby2.3`
Running `sudo gem update` updated the asciidoctor gem and now `/usr/local/bin/asciidoctor` correctly starts with `#!/usr/bin/ruby2.5`

**Comment by mojavelinux** [comment]
This seems to be an issue with asciidoctor Debian package. Perhaps you can report it there.

**Comment by anthonyvdotbe** [comment]
There are 2 files:
* `/usr/bin/asciidoctor`, which is installed by the [Asciidoctor Debian package](https://packages.debian.org/buster/all/asciidoctor/filelist) and uses the "current" Ruby version: `#!/usr/bin/ruby`
* `/usr/local/bin/asciidoctor`, which is generated by RubyGems when installing the asciidoctor gem and uses a specific Ruby version

Since `/usr/local/bin` comes before `/usr/bin` on the PATH (at least in my case), I don't know if the Debian package can do much about this.

**Comment by mojavelinux** [comment]
You should not be installing gems globally using both methods. Use one or the other. And when you use `gem install`, I *strongly* recommend against installing into the system. You should use RVM to install into your home directory. Otherwise, you are going to get conflicts. That's just a shortcoming of RubyGems itself. This has nothing to do with how this gem operates.

**Comment by anthonyvdotbe** [comment]
Thanks for clarifying. I didn't realize they're 2 methods to do the same thing.

**Comment by mojavelinux** [comment]
As sure as the sun will come up, there will be programmers who give us multiple ways to do the same thing ;)
