### ISSUE TITLE
Monospace text in prose not wrapped properly

### ISSUE THREAD

**Issue by nicorikken** [asciidoctor/asciidoctor#1814]
Monospaced text in an admonition block is not wrapped properly, resulting in long lines extending beyond the admonition block. The same string of text in a paragraph is actually wrapped neatly.

![screen shot 2016-07-06 at 15 27 48](https://cloud.githubusercontent.com/assets/7458098/16619739/bb1ec4ba-438f-11e6-9793-c148e1ead970.png)

**Comment by mojavelinux** [comment]
This issue is not limited to admonition blocks. It applies to any monospaced text within prose.

The reason there is a difference between monospaced text and a literal/listing block is because we cannot assume that the monospaced text is code. The best solution here is to introduce a built-in role that applies the `word-wrap: break-word` property via CSS.

We'll need to decide on a name for this role. Here are some proposals.

* wrap
* breakable
* allow-break
* break-words

Here's how it would get used:

```
[.wrap]`request_authorization%5bwith_history%5d=true&request_authorization%5btags%5d%5b%5d=electricity&request_authorization%5btags%5d%5b%5d=gas`
```

Then we'd add the following CSS to the stylesheet:

```css
.wrap {
  word-wrap: break-word;
}
```

**Comment by mojavelinux** [comment]
After refreshing my memory a bit, I am reminded that the break will only be added as a last resort. First, the whole element will wrap to the next line if that allows it to fit. Therefore, I'm thinking this might not be so harmful as a default after all. If we go in that direction, then we can introduce the inverse role to prevent wrapping.

```css
*:not(pre) > code {
  word-wrap: break-word;
}
*:not(pre) > code.nowrap {
  word-wrap: normal;
}
```

wdyt?

**Comment by mojavelinux** [comment]
I decided to introduce two new roles for monospace phrases:

* nobreak - only allow breaks at break opportunities (a user break, not a forced break)
* nowrap - prevent breaks even at break opportunities
