### ISSUE TITLE
Use a special case to handle "ThreadSafe" when running in a Javascript environment

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor#1820]
Currently users can't `register` a new converter in Asciidoctor.js because the following piece of code is throwing an exception: https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/converter/factory.rb#L45-L55

Here's the compiled version of this piece of code:
```javascript
(function() {if ((($b = (Opal.Object.$$scope.ThreadSafe == null ? nil : 'constant')) !== nil && (!$b.$$is_boolean || $b == true))) {
  return nil
} else {
  return self.$require("thread_safe".$to_s())
}; return nil; })()
  return self.$new(((Opal.get('ThreadSafe')).$$scope.get('Cache')).$new())
} catch ($err) {if (Opal.rescue($err, [Opal.get('LoadError')])) {
  try {
    self.$warn("asciidoctor: WARNING: gem 'thread_safe' is not installed. This gem is recommended when registering custom converters.")
    return self.$new()
  } finally {
    Opal.gvars["!"] = Opal.exceptions.pop() || Opal.nil;
  }
} else { throw $err; }
```

The problem is that Opal is throwing an `uninitialized constant` exception and not a `LoadError` exception: `ThreadSafe: uninitialized constant Object::ThreadSafe`.

Threading in a Ruby environment is different from threading in a JavaScript environment.
I think we should use a special case when running in a JavaScript environment:

```ruby
if ::RUBY_ENGINE_OPAL
  new
else
  # ...
end
```

**Comment by mojavelinux** [comment]
Generally, the way we've handled cases like this, where an external library is required, is to short circuit the require statement by satisfying the guard condition. In this case, it looks for ::ThreadSafe. Therefore, the Opal ext can simply define the ::ThreadSafe module and map ::ThreadSafe::Cache to ::Hash. Since JavaScript is single-threaded (as far as I understand it), this is what it would do anyway.

> Opal is throwing an uninitialized constant exception and not a LoadError exception: ThreadSafe: uninitialized constant Object::ThreadSafe.

You are correct that the current code assumes that the require statement works. Looking a little bit closer, I think we still may want to consider the RUBY_ENGINE == 'opal' guard. I guess either solution proposed would work. wdyt?

**Comment by Mogztter** [comment]
I've done the following in Asciidoctor.js: https://github.com/Mogztter/asciidoctor.js/blob/7d1d98a0b48588fc67b1f717035e9e491509a5c9/lib/asciidoctor/opal_ext/thread_safe.rb

> I think we still may want to consider the RUBY_ENGINE == 'opal' guard. I guess either solution proposed would work. wdyt?

No I think it's fine to define a ThreadSafe module and map ThreadSafe.Cache to Hash in Asciidoctor.js.
The code should stay as simple as possible in core :) 

I'm closing this issue, this will be resolved when  https://github.com/asciidoctor/asciidoctor.js/pull/196 will be merged.

**Comment by Mogztter** [comment]
Thanks for your help 👍👌

**Comment by mojavelinux** [comment]
:+1:
