### ISSUE TITLE
Add docbook inheritnum="inherit" attribute for ordered lists

### ISSUE THREAD

**Issue by kenaken** [asciidoctor/asciidoctor#1842]
I want the inner list's numbering to inherit the outer listitem's number as a prefix.
In DocBook I use this sytanx to do it:

```
<orderedlist>
  <listitem><para>First outer item.</para></listitem>
  <listitem><para>Second outer item.</para>
    <orderedlist inheritnum="inherit">
      <listitem><para>First inner item.</para></listitem>
      <listitem><para>Second inner item.</para></listitem>
      ...
```

This will result in the following print output:

```
1.  First outer item.
2.  Second outer item.
    2.a.  First inner item.
    2.b.  Second inner item.
    ...
```

I can manualy add special role for this in XSLT as workaround. But if Asciidoctor want's to be ["semantically equivalent to DocBook XML"](https://en.wikipedia.org/wiki/AsciiDoc) this function will not be superfluous.

**Comment by lopsotronic** [comment]
I very much second this. The lack of `+inheritnum+` is a barrier to adoption of the asciidoctor-pdf converter for manufacturing, legal, and medical industries. Users in some industries might be locked in to the docbook-based PDF toolchain for the time being.

**Comment by mojavelinux** [comment]
> a barrier to adoption of the asciidoctor-pdf converter

The proposal raised in this issue has nothing to do with Asciidoctor PDF. This is purely about DocBook.

> I want the inner list's numbering to inherit the outer listitem's number as a prefix.

Unfortunately, "inheritnum" is not a kind of numbering supported by CSS, so adding this would be very specific to DocBook (and, even then, only certain DocBook toolchains). If we added such a style, users would immediately ask why it doesn't work in HTML, for which we would have no answer. Since we're not prepared to address that, I don't want to add it into the language.

However, you can achieve the same thing by using a custom converter or template for the olist block. Here's how such a template might look:

```
orderedlist id=id role=role xreflabel=(attr :reftext) numeration=(style != 'inheritnum' && style) inheritnum=(style == 'inheritnum' && 'inherit')
  - if title?
    title=title
  - items.each do |item|
    listitem
      simpara=item.text
      - if item.blocks?
        =item.content
```

Save this file as *olist.xml.slim* and pass the directory in which it resides to Asciidoctor using `-T`.

Now you can write this AsciiDoc:

```
. First outer item.
. Second outer item.
[inheritnum]
.. First inner item.
.. Second inner item.
```

This is well within the design of AsciiDoc and Asciidoctor.

>  if Asciidoctor want's to be "semantically equivalent to DocBook XML" 

I think you're reading too much into that statement. Asciidoctor is giving you the ability to produce the same result as DocBook, but we're not necessarily saying you get that 100% out of the box. But, as I showed, there is a path.
