### ISSUE TITLE
[horizontal] labeled list unavailable in nested structure

### ISSUE THREAD

**Issue by meisterluk** [asciidoctor/asciidoctor#1872]
**Given**

```asciidoc
Hello World
===========

Operating Systems::
  [horizontal]
  Linux::: Linux
  BSD::: BSD

Cloud Providers::
  PaaS::: PaaS
  IaaS::: IaaS
```

**Expected**
On page 2, visually something like
```
Operating Systems
  Linux    Linux
  BSD    BSD

Cloud Providers
  PaaS
    PaaS
  IaaS
    IaaS
```

**Actual**
![labeled](https://cloud.githubusercontent.com/assets/358358/18478242/cd801542-79d0-11e6-8a29-91b71e935374.png)

**Comment by mojavelinux** [comment]
I think you meant to file this in Asciidoctor PDF. But you don't have to worry, there's already an open issue for it. See https://github.com/asciidoctor/asciidoctor-pdf/issues/310.

**Comment by mojavelinux** [comment]
Although Asciidoctor PDF doesn't have support for horizontal labeled lists yet, I realize this issue is different.

The problem is that you are indenting the block attribute list. The block attribute list must always be aligned to the left margin. Thus, your labeled list must be written as follows:

```
Operating Systems::
[horizontal]
  Linux::: Linux
  BSD::: BSD

Cloud Providers::
  PaaS::: PaaS
  IaaS::: IaaS
```

However, it seems like you've uncovered a separate issue in the parser with this use case. The second label is getting caught up as a child of the nested list. To workaround this problem, you can attach the nested list using a list continuation.

```
Operating Systems::
+
[horizontal]
  Linux::: Linux
  BSD::: BSD

Cloud Providers::
  PaaS::: PaaS
  IaaS::: IaaS
```

I'd like to open a separate issue for the parsing problem.

**Comment by meisterluk** [comment]
I can confirm that asciidoctor HTML output looks like the expected one. So it is indeed a asciidoctor-pdf issue.

Thanks for looking into it.

```
meisterluk@linux % asciidoctor -v
Asciidoctor 1.5.4 [http://asciidoctor.org]
Runtime Environment (ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)
meisterluk@linux % asciidoctor-pdf -v
Asciidoctor PDF 1.5.0.alpha.12 using Asciidoctor 1.5.4 [http://asciidoctor.org]
Runtime Environment (ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)
```

**Comment by unlimitedsola** [comment]
any progress on this? @mojavelinux

**Comment by mojavelinux** [comment]
Since this issue is related to Asciidoctor PDF and is already reported in that progress, I'm locking this one. Please follow https://github.com/asciidoctor/asciidoctor-pdf/issues/310 for updates and further discussion.
