### ISSUE TITLE
btn macro style differs from asciidoctor docs

### ISSUE THREAD

**Issue by habamax** [asciidoctor/asciidoctor#1881]
Should one have the same default style that AsciiDoctor has?

![asciidoctor](https://cloud.githubusercontent.com/assets/234774/18987264/9693d6c2-8709-11e6-82f5-c40b2168ad90.png)

In a picture, the red squared area is what I get using btn macro instead of a styled buttons.

**Comment by mojavelinux** [comment]
The appearance on asciidoctor.org is incorrect. It's consider bad practice to put the physical appearance of a button in documentation because it misleads the reader into thinking it's really a button. Hence, we came up with an alternative way of displaying it that still stood out. If you would like a different appearance, I recommend that you customize your stylesheet to your liking.

**Comment by habamax** [comment]
Ok, got it. Thx.

**Comment by mojavelinux** [comment]
We are always open to ideas about another way to present it, as long as it doesn't look like a native button. So if you come across something you like, don't hesitate to suggest it.

**Comment by habamax** [comment]
yep, will think about it.

**Comment by habamax** [comment]
What about simple gray border?

![asciidoctor2](https://cloud.githubusercontent.com/assets/234774/18988934/ba780e52-8711-11e6-815b-6902e467be9d.png)

**Comment by habamax** [comment]
or

![asciidoctor3](https://cloud.githubusercontent.com/assets/234774/18989042/9a12dc90-8712-11e6-98fb-c55450cd086e.png)

which is more like a sketchy button but "clearly" (subjective) not the real one.
