### ISSUE TITLE
Reasons for LoadErrors when loading Ruby libs are swallowed.

### ISSUE THREAD

**Issue by robertpanzer** [asciidoctor/asciidoctor#1884]
As observed in robertpanzer/asciidoctorj-pdf#3 requiring the rouge library fails on Windows when loading the gem from an exploded directory.
As https://github.com/asciidoctor/asciidoctor/blob/93063e2500369612e923c04695fbf6e3054b31ba/lib/asciidoctor/helpers.rb#L30 completely swallows the LoadError it seems like rouge was not available.
In fact the error comes deeper from within the rouge code when it loads polyglot.

It would be nice if the original error backtrace and message would be passed on.

**Comment by mojavelinux** [comment]
This probably takes us back to #44. Sometimes, a load error is part of the normal operation of Asciidoctor (indicating that a feature sure be disabled because the gem is not available). Unfortunately, there's no (easy, portable) way to tell the difference between a missing gem and something wrong with the environment. 9 times out of 10 with AsciidoctorJ, loading a gem fails because JRuby is not isolated from the system gems. Once you start mixing MRI-installed gems with JRuby-installed gems, all bets are off.

**Comment by mojavelinux** [comment]
This is really tricky because most of the times a gem can't be loaded, it's because it's not available / installed. And for the other times, it's hard to know where to stick the message.

There are two options:

1. Include the error message in Asciidoctor's log message, which would at least give you a reason why the gem couldn't be loaded (and perhaps reveal the deeper reason)
2. Include the backtrace at the end of Asciidoctor's log message if verbose mode is enabled.

Since this warning is not something you get under normal operation, (2) does sound like it would be more helpful.

Ideally, it would be possible to turn on trace mode via the API, and then adding the backtrace would be similar to using `--trace` from the CLI. But that's not currently possible.

**Comment by mojavelinux** [comment]
FYI, if you set the $DEBUG global variable to true, you will see all the exceptions that are raised (even if caught).

**Comment by mojavelinux** [comment]
What I'm thinking is that `--trace` will set the $TRACE global variable. If this global variable is true, the backtrace is shown whenever an exception is raised or logged.

**Comment by mojavelinux** [comment]
I've proposed the $TRACE idea is #3196.

**Comment by mojavelinux** [comment]
I'm going to move forward with the enhanced message and defer inclusion of the backtrace to #3196.
