### ISSUE TITLE
Both asciidoctor and string_ex define String#limit()

### ISSUE THREAD

**Issue by gpakosz** [asciidoctor/asciidoctor#1889]
Since asciidoctor started extending the `String` class with a `#limit()` method, one can't use both the `asciidoctor` and the `string_ex` gem at the same time.

See [`stringex/string_extensions.rb`](https://github.com/rsl/stringex/blob/25051fe0c9658c2ff1da72382d2110a498357cbe/lib/stringex/string_extensions.rb#L102-L109).

**Comment by mojavelinux** [comment]
Asciidoctor checks to see if the method is already defined, so all you need to do is require `stringex` first and Asciidoctor will use that implementation (as designed). Does that work for you?

(The implementation is slightly different, but the same would be true if you redefined the limit method any other way).

We could consider renaming the method to `limit_bytesize` since that's actually how it's implemented.

**Comment by gpakosz** [comment]
I'll try to dance with `require` order. Still...

**Comment by gpakosz** [comment]
In fact, does it **really** have to be an extension method? Question of course applies to both projects

**Comment by gpakosz** [comment]
What about prefixing your extensions to core classes?

**Comment by jirutka** [comment]
What about using refinements instead of wild monkey patching of core classes? You can use [corefines]( https://github.com/jirutka/corefines/blob/master/README.adoc#compatibility-mode ) if you need some backward compatibility for ancient Ruby versions.

**Comment by mojavelinux** [comment]
The patches are mostly to port features to older versions of Ruby (to allow me to use the methods). This is one exception. I prefer to implement this as `limit_bytesize` for now.
