### ISSUE TITLE
menu macro doesn't work with non-english words

### ISSUE THREAD

**Issue by habamax** [asciidoctor/asciidoctor#1891]
```
. menu:Действия[Добавить отчет] doesn't work
. menu:Action[Добавить отчет] works
```

**Comment by mojavelinux** [comment]
Both of these work when I try them. Can you clarify what your execution environment is by pasting the output of `asciidoctor -v`? Also, can you tell me if the file is encoded in UTF-8?

**Comment by habamax** [comment]
This is windows 10. All my files are in UTF-8 and this one is too.

`asciidoctor -v`

```
Asciidoctor 1.5.5 [http://asciidoctor.org]
Runtime Environment (ruby 2.3.1p112 (2016-04-26 revision 54768) [x64-mingw32]) (lc:IBM866 fs:Windows-1251 in:- ex:IBM866)
```

**Comment by habamax** [comment]
I have tried again...

The issue is not in asciidoctor -- it works for it. It actually doesn't work for firefox plugin that interprets raw asciidoctor files.

So I guess this should be closed, sorry.

**Comment by mojavelinux** [comment]
I had a feeling it had to do with Asciidoctor.js. At the moment, Asciidoctor.js does not recognize non-Latin letters due to the fact that JavaScript does not support these character classes in its built-in regular expression system. We have plans to extend this support, either by using another library, or by waiting on these character classes to be implemented in JavaScript. See https://github.com/asciidoctor/asciidoctor.js/issues/43.

**Comment by mojavelinux** [comment]
In other words, it's a known limitation with any tool that depends on Asciidoctor.js.

**Comment by habamax** [comment]
Got it, thanks!

**Comment by mojavelinux** [comment]
This is now resolved in Asciidoctor.js 1.5.6-preview.1 and will be part of the Asciidoctor.js 1.5.6 preview release.
