### ISSUE TITLE
Asciidoctor And Google Tag Manager Extremely Cumbersome

### ISSUE THREAD

**Issue by davidfavor** [asciidoctor/asciidoctor#1893]
GTM requires a head snippet + body snippet.

:docinfo1: though cumbersome allows injection of the head snippet.

include::gtm-body.html[] before the initial = (H1) tag produces the dreaded...

asciidoctor: ERROR: index.adoc: line 3: only book doctypes can contain level 0 sections

Adding a -d book seems to include the file + normalization is still done.

There seems to be no way to disable normalization + no way to include content directly after the body tag, rather than inside the first paragraph.

I can achieve this by writing a wrapper script + --no-header-footer nonsense + this seems a huge amount of overkill.

Seems like a bug to have no way to inject raw html anywhere in a document.

Maybe the answer is something like :body-top: + :body-bottom: for injecting raw snippets into a file without normalization.

**Comment by mojavelinux** [comment]
The correct way to achieve adding extra HTML to the output is to use docinfo. It goes very much against the spirit of AsciiDoc to insert HTML by putting it in the AsciiDoc itself (such as `include::gtm-body.html[]`). The AsciiDoc should be the content, not the framing (as I call the HTML template).

Other ways to achieve insertion of auxiliary HTML is to pass a custom document template or to write an extension (postprocessor, treeprocessor, etc).

> Maybe the answer is something like :body-top: + :body-bottom: for injecting raw snippets into a file without normalization.

We already have this capability via extensions or a custom document template (the extension would have to implement it of course). It doesn't make sense in core since that's very specific to one backend and not others. This is a user enhancement.

**Comment by mojavelinux** [comment]
I'm closing this as I believe that docinfo is the appropriate way to add GTM to the generated document.
