### ISSUE TITLE
epub3 gem not installing

### ISSUE THREAD

**Issue by GRU-framework** [asciidoctor/asciidoctor#1904]
well I am not a ruby expert but I get this when installing epub3 "gem"
____________________________________________
Fetching: nokogiri-1.6.8.1.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing asciidoctor-epub3:
	ERROR: Failed to build gem native extension.

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/rbconfig.rb:213: warning: Insecure world writable dir /opt in PATH, mode 040777
mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/include/ruby.h

_________________________________________________
what can I do?
thanks

**Comment by mojavelinux** [comment]
In order to install nokogiri, you need to have the Ruby development libraries installed. I'm not sure how this is done on OSX, but you could probably find the answer on StackOverflow.

**Comment by GRU-framework** [comment]
I have been trying for hours with different versions
described here: http://www.nokogiri.org/tutorials/installing_nokogiri.html <http://www.nokogiri.org/tutorials/installing_nokogiri.html>

in the end what I get on OSX Sierra 10.12 (as su) is
____________________
sh-3.2# gem install nokogiri
Building native extensions.  This could take a while...
/Library/Ruby/Site/2.0.0/rubygems/ext/builder.rb:76: warning: Insecure world writable dir /opt in PATH, mode 040777
ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted - /usr/bin/nokogiri
____________________________

really upset!
help!

thanks

**Comment by mojavelinux** [comment]
Aha. I can help you. You are trying to install gems globally. This practice is highly discouraged. You should instead using something [rvm](rvm.io). That will ensure gems are installed in your user directory. There are similar options as well.

**Comment by GRU-framework** [comment]
sorry I don’t understand : if I run without su I have this:
———————————————————
macBear2:Bin bamade$ gem install nokogiri
Fetching: nokogiri-1.6.8.1.gem (100%)
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.

(what does 'rvm' means? )
how to install gems locally? (I do not know a thing about ruby ;-( )

thanks

**Comment by mojavelinux** [comment]
I recommend reading rvm.io. I can't really explain it better than the website does.

**Comment by GRU-framework** [comment]
well
you need to be a black belt to understand what to do ….
the site rvm is not really easy for a newbie
exemples:
- no gpg command to start with (let’s skip that one)
-then it is explained that things should be run locally BUT
/usr/local/bin/brew: /usr/local/Library/brew.rb: /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby: bad interpreter: No such file or directory
/usr/local/bin/brew: line 23: /usr/local/Library/brew.rb: Undefined error: 0
ERROR: '/bin' is not writable - it is required for Homebrew, try 'brew doctor' to fix it!


I just want to install epub3 package on OSX … sorry but magic procedure not found ….
should I learn Ruby, then all the nifty install details … some people are familiar with these details but just imagine how complex it is for someone that does not know anything about all this magic …. (sorry but the rvm site is clear only for those who know the context)

thanks

**Comment by mojavelinux** [comment]
Here's a page that could help you better.

http://asciidoctor.org/docs/install-asciidoctor-osx/

**Comment by GRU-framework** [comment]
same problem (after following the described procedures) this step fails :

gem install asciidoctor
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.

**Comment by mojavelinux** [comment]
Then I recommend using the [AsciidoctorJ distribution](https://bintray.com/asciidoctor/maven/asciidoctorj/1.5.4.1#files/org/asciidoctor/asciidoctorj/1.5.4.1). That way, all you need is Java. You can use the `asciidoctorj` command instead of `asciidoctor`.

A prerequisite for using Asciidoctor Ruby is being able to install gems. If you are unable to do that for some reason, then you can use AsciidoctorJ which provides exactly the same functionality.

(You can also use AsciidoctorJ by way of the Gradle or Maven plugin).

**Comment by mojavelinux** [comment]
Here's a direct link to the AsciidoctorJ distribution:

https://bintray.com/asciidoctor/maven/download_file?file_path=org%2Fasciidoctor%2Fasciidoctorj%2F1.5.4.1%2Fasciidoctorj-1.5.4.1-bin.zip

**Comment by GRU-framework** [comment]
but asciidoctor ruby was working fine (thanks by the way! the pdf generation is brilliant)
Oops does not work any more ….

the only problem is to download for epub3 generation
is AsciidoctorJ able to deal with epub3? (do we just apply he same command by just changing asciidoctor to asciidoctorJ?)
for the moment i just get a huge stacktrace as being unable to process...

thanks

**Comment by abelsromero** [comment]
Sorry to step in, but I've been following the topic and I think I can help with it.
First, some info to clarify. AsciidoctorJ is a Java "wrapper" for the Asciidoctor Ruby implementation, internally it runs the same gem, but using jRuby to execute it and a Java JAR library to distribute it (gem is embedded in the same jar). So, instead of installing gems, you only need to set up a Java classpath with the proper JARs.
Said that, the most popular extensions like pdf, diagram or epub are also published as Jars to ease the distribution and usage from Java. Other extensions may not be available as Jar. For those cases, some additional work is necessary.

Now, back to the topic, AsciidoctorJ includes a command line interface, so you can use it from the shell. To do so:
a) Download the jar(s) (+ extensions like epbug) and run them manually with the standard `java -jar -c epub.jar asciidoctorj.jar -b ....` command
b) or, you can use sdkman to install it. At this point, you may be bothered with so many tools, but this is worth it. I (almost) never have issues with it (I use it on Mac, Linux & Windows.). Follow instructions here: http://sdkman.io/install.html, then just run `sdk install asciidoctorj` and restart the shell. It will also install the pdf, diagram and epub3 extensions by default, so to convert something just do `asciidoctorj -b pdf example.adoc` or `asciidoctorj -b epub3 example.adoc`. Just tested it myself and worked.

Lost option, I think is the easiest quickest way to run asciidoctor from Java, if you want a long term option, you can use maven or gradle to set up a project. Here is a gradle [example](https://github.com/asciidoctor/asciidoctor-gradle-examples/tree/master/asciidoc-to-epub3-example).
For Maven, you can copy this [example](https://github.com/asciidoctor/asciidoctor-maven-examples/tree/master/asciidoctor-pdf-example), add the epub dependency bellow theasciidoctorj- pdf one with this
```
<dependency>
    <groupId>org.asciidoctor</groupId>
    <artifactId>asciidoctorj-epub3</artifactId>
    <version>1.5.0-alpha.6</version>
</dependency>
```
and set the backend to "epub3".

**Comment by mojavelinux** [comment]
Thanks @abelsromero!

As Abel mentioned, the epub3 converter is provided in the AsciidoctorJ distribution. The good news is, you don't even have to setup the classpath. The distribution comes with a bin script named asciidoctorj that does that for you. But I also recommend sdkman as that's the easiest way to manage an AsciidoctorJ installation.

**Comment by GRU-framework** [comment]
the sdk install goes smoothly
running asciidoctorJ : ok
running asciidoctorJ -b pdf : ok
running asciidoctorJ -b epub3 : fails
———————————————————
asciidoctorJ -b epub3 *2.adoc
nov. 03, 2016 8:16:00 AM org.asciidoctor.internal.JRubyAsciidoctor renderFile
GRAVE: (NoMethodError) undefined method `to_ios' for #<Asciidoctor::Epub3::Packager:0x72001c71>
Exception in thread "main" org.asciidoctor.internal.AsciidoctorCoreException: org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `to_ios' for #<Asciidoctor::Epub3::Packager:0x72001c71>
……

???
thanks

**Comment by audiofanatic** [comment]
Another thing you can try is to install the Xcode development tools. I got here with a similar problem and `xcode-select --install` plus updating my pkg-config to a more recent version (via homebrew) made the asciidoctor-epub3 gem install for me on Yosemite 10.10.5

**Comment by mojavelinux** [comment]
Installation is not the issue here. This is a runtime error. When you get the `.to_ios` error, it almost always means that the structure of the document is not correct. Please refer to the following section:

https://github.com/asciidoctor/asciidoctor-epub3#structuring-your-manuscript

**Comment by mojavelinux** [comment]
@audiofanatic You are correct that to install the Ruby gem, you must have development tools on your machine. That's a requirement of nokogiri. You don't need them to use the AsciidoctorJ version because it comes bundled with the tools necessary.

**Comment by mojavelinux** [comment]
If you continue to have problems, please open an issue in Asciidoctor EPUB3 (https://github.com/asciidoctor/asciidoctor-epub3). This repository is for the core processor only.
