### ISSUE TITLE
User comments, inline AsciiDoc

### ISSUE THREAD

**Issue by Havoc85** [asciidoctor/asciidoctor#1905]
I want to give my Users the possibility to write comments in AsciiDoc Markup language. I use AsciiDoctor in my Ruby on Rails Application. Is there any easy way to use most (or all) of the AsciiDoc Language inside a Bootstrap Site within a comment section? If i use "header_footer: true" the whole site changes its style to the AsciiDoc style. If i dont use header_footer, it just works with some stuff like h1 and em. But, for example, not with TIP or Codeblocks. It seems that there is no CSS in this gem. Maybe iam missing something?

**Comment by mojavelinux** [comment]
As this is a general question about usage, I would prefer if you ask it on the [discussion list](http://discuss.asciidoctor.org). Can you repost there?

**Comment by mojavelinux** [comment]
To use AsciiDoc in comments, you'd want to convert it to embeddable HTML, which is what happens when the `:header_footer` option is `false`. In that case, you must provide your own styles.

We are working on creating a reusable stylesheet for embeddable HTML (see https://github.com/asciidoctor/asciidoctor-stylesheet-factory/issues/18), but that effort is not yet complete.
