### ISSUE TITLE
Add support for checklists

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#200]
Add support for lists with a checkbox marker. The checkbox can have two states (checked and unchecked). By default, the checkboxes are interactive, but can be marked as readonly using an option.

interactive:

```
[ ] not checked
[*] checked
```

read-only:

```
[options="readonly"]
[ ] not checked
[*] checked
```

Inspired by https://github.com/blog/1375-task-lists-in-gfm-issues-pulls-comments

It is possible to emulate a read-only list using the native AsciiDoc syntax. See https://gist.github.com/mojavelinux/5071052

**Comment by dsisnero** [comment]
Is it possible to add support for checks in a table

== Minimum EOSH Requirements
[cols= "80,10,10"]
|===
3+h| Project Plan Minimum EOSH Checklist
.2+h|Facility Procedures 
2+h|Applicable?
h|Yes*
h|No

|Asbestos Contingency Plan|[x] |
|Hazard Communications | [x] | 
|Lock Out/Tag Out| [x] | 
|Work Permits (e.g. Confined Spaces, Energized Electrical)| | [x]
|Emergency Plans (e.g. Occupant Emergency Plan)|  | [x]
|Impacts to Fire Alarm and Suppression Systems|  | [x]
|Confined Space Entry|  | [x]
|Restricted Areas Due to OSH|  | [x]
|Blood borne Pathogens|  | [x]
|Restricted Areas Due to OSH|  | [x]
|Fall Protection| [x] | 
|Arc Flash Analysis| | [x]
|Personal Protection Equipment (PPE)|[x]  | 

|===

**Comment by mojavelinux** [comment]
I'd recommend just using the underlying characters that the checklist uses. That's one of the following:

* icon:check[]
* \&#10003;
* +++&lt;input type="checkbox"&gt;+++

You can assign these as an attribute to make it easy to reference.

```
:y: &#10003;

{y}
```

We do something similar in the Asciidoctor user manual. http://asciidoctor.org/docs/user-manual/#asciidoctor-vs-asciidoc
