### ISSUE TITLE
handle quoted CSV tables properly

### ISSUE THREAD

**Issue by jexp** [asciidoctor/asciidoctor#2008]
if you have a CSV table like this it will break

```
[format="csv", options="header"]
|===
Name,Description
JONATHAN MECHANIC, """a real-estate attorney who was involved in [Kushner's] retail-space negotiations,"" per New York Magazine"
Foo,Bar
|===
```

Full example

```
:org_org_url: https://docs.google.com/spreadsheets/u/1/d/1Z5Vo5pbvxKJ5XpfALZXvCzW26Cl4we3OaN73K9Ae5Ss/export?format=csv&gid=634968401

[format="csv", options="header"]
|===
include::{org_org_url}[]
|===
```

**Comment by elextr** [comment]
Your first data line has a comma after "negotiations" which starts a new cell.  The cell separator can't be included in cell content.

**Comment by elextr** [comment]
This one seems to work with Asciidoc Python which seems to handle RFC4180 format.

**Comment by mojavelinux** [comment]
I implemented the absolute minimum possible CSV parser in order to avoid loading extra libraries and to maximize conversion speed (as you know, I'm keen on Asciidoctor being fast). So you could say that my goal at the time was not RFC4180-compliance, but rather to cover 9/10 use cases.

However, Ruby does come with a compliant CSV parser out of the box. If I determine the performance impact is minimal, perhaps we should just switch to using that.

See http://ruby-doc.org/stdlib-2.4.0/libdoc/csv/rdoc/CSV.html

**Comment by mojavelinux** [comment]
Actually, it's not the quote escaping that is the problem here, but rather the comma in the quoted text. The comma inside the quoted text should be treated as text, not a table delimiter.

**Comment by mojavelinux** [comment]
Actually, it goes even deeper than that. The problem is that the escaped quote inside the quoted text is confusing the parser. So it isn't the comma at all, but rather the sequence of quotes that starts the cell.

**Comment by elextr** [comment]
@mojavelinux Asciidoc Python uses the Python CSV library functions for CSV, so using the Ruby ones is probably the way to go for Asciidoctor.

**Comment by mojavelinux** [comment]
It turns out, I may have done more work than I had realized. The fix seems fairly straightforward. Just sorting out some details.

**Comment by jexp** [comment]
Yay! Thanks so much @mojavelinux
