### ISSUE TITLE
DocBook: Converting monospaced text which is bold or italicized

### ISSUE THREAD

**Issue by HT2313** [asciidoctor/asciidoctor#2014]
Hi,
I'm using asciidoctor 1.5.5 to create docbook 5 files from `.adoc` file.

Asciidoctor allows applying several text transformation on single word (or paragraph), i.e. it allows monospaced text to be bold and italicized.

Following is the command for creating the DocBook file:
`asciidoctor test.adoc --backend=docbook5 --doctype=article`

When creating the DocBook file from following content:
``` adoc
= Combined text formatting

`*Lorem ipsum dolor sit amet*`, `_consectetur adipisicing elit,_` sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua.
```

Generated DocBook file content is:
``` xml
<?xml version="1.0" encoding="UTF-8"?>
<?asciidoc-toc?>
<?asciidoc-numbered?>
<article xmlns="http://docbook.org/ns/docbook" xmlns:xl="http://www.w3.org/1999/xlink" version="5.0" xml:lang="en">
<info>
<title>Combined text formatting</title>
<date>2017-01-31</date>
</info>
<simpara><literal><emphasis role="strong">Lorem ipsum dolor sit amet</emphasis></literal>, <literal><emphasis>consectetur adipisicing elit,</emphasis></literal> sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua.</simpara>
</article>
```

Problem with this is that asciidoctor puts `<emphasis>` elements in `<literal>` elements, which is
**not** allowed by [DocBook 5 standard](http://tdg.docbook.org/tdg/5.0/literal.html).
Allowed child elements for `<literal>` are alt, anchor, annotation, biblioref, indexterm, indexterm,
indexterm, inlinemediaobject, link, olink, phrase, remark, replaceable,
subscript, superscript and xref.
So maybe instead of `<emphasies>` element, `<phrase>` element should be used in
`<literal>` element, just for following DocBook standard. E.g.:
``` xml
<?xml version="1.0" encoding="UTF-8"?>
<?asciidoc-toc?>
<?asciidoc-numbered?>
<article xmlns="http://docbook.org/ns/docbook" xmlns:xl="http://www.w3.org/1999/xlink" version="5.0" xml:lang="en">
<info>
<title>Combined text formatting</title>
<date>2017-01-31</date>
</info>
<simpara><literal><phrase role="strong">Lorem ipsum dolor sit amet</phrase></literal>, <literal><phrase role="emphasised">consectetur adipisicing elit,</phrase></literal> sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua.</simpara>
</article>
```

It is also possible that `<emphasis>` element and `<literal>` element switch places:
``` xml
<?xml version="1.0" encoding="UTF-8"?>
<?asciidoc-toc?>
<?asciidoc-numbered?>
<article xmlns="http://docbook.org/ns/docbook" xmlns:xl="http://www.w3.org/1999/xlink" version="5.0" xml:lang="en">
<info>
<title>Combined text formatting</title>
<date>2017-01-31</date>
</info>
<simpara><emphasis role="strong"><literal>Lorem ipsum dolor sit amet</literal></emphasis>, <emphasis><literal>consectetur adipisicing elit,</literal></emphasis> sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua.</simpara>
</article>
```
Note that this option can not be applied when source `.adoc` file contains formatting similar to this:
``` adoc
`Lorem ipsum dolor sit amet, _consectetur adipisicing elit,_` sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua.
```
This formatted tex is converted into this:
``` xml
<simpara><literal>Lorem ipsum dolor sit amet, <emphasis>consectetur adipisicing elit,</emphasis></literal> sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</simpara>
```

**Comment by mojavelinux** [comment]
That may be true but, in practice, the DocBook toolchain allows it as does the dblatex backend from AsciiDoc.py. I have tested with converting it to PDF both ways and the result is what we would expect. It's even supported by yelp, which is a DocBook viewer for Linux. So really this just comes down to validation of the DocBook output itself.

Unfortunately, the way that the Asciidoctor parser is written, it's not possible to swap tag nesting. The change has to happen at the source level (i.e., in the AsciiDoc). That means the AsciiDoc has to be written as follows:

```
*`Lorem ipsum dolor sit amet`*, _``consectetur adipisicing elit,``_ sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua.
```

We're not going to restrict the syntax the other way around (or issue a warning) since it produces perfectly valid HTML output and Asciidoctor PDF can handle it as well. It's really just a DocBook limitation that the author has to be aware of. If you plan to convert to DocBook, and need that DocBook to validate, perhaps this is best as a rule in your writing style guide.
