### ISSUE TITLE
Quoting of URLs with (c) in it

### ISSUE THREAD

**Issue by ecki** [asciidoctor/asciidoctor#2090]
I am using asciidoctorj (1.5.4.1, jruby 1.7.25) via the Maven plugin (1.5.3) to render the following text. I am unable to avoid the expansion into a copyright sign (but keeping the URL as a link)

    See here: https://en.wikipedia.org/wiki/Crypt_(C)
    See here: https://en.wikipedia.org/wiki/Crypt_\(C\)
    See here: \\https://en.wikipedia.org/wiki/Crypt_(C)
    See here: link:https://en.wikipedia.org/wiki/Crypt_(C)[\\en.wikipedia.org/wiki/Crypt_(C)]
    See here: link:https://en.wikipedia.org/wiki/Crypt_\(C\)[en.wikipedia.org/wiki/Crypt_(\C\)]
    See here: link:\\https://en.wikipedia.org/wiki/Crypt_(C)[en.wikipedia.org/wiki/Crypt_(C)]

(shortened) HTML results - all incorrect:

    <p>See here: <a href="https://en.wikipedia.org/wiki/Crypt_&#169" class="bare">https://en.wikipedia.org/wiki/Crypt_&#169</a>;</p>
    <p>See here: <a href="https://en.wikipedia.org/wiki/Crypt_\(C\" class="bare">https://en.wikipedia.org/wiki/Crypt_\(C\</a>)</p>
    <p>See here: \\https://en.wikipedia.org/wiki/Crypt_&#169;</p>
    <p>See here: <a href="https://en.wikipedia.org/wiki/Crypt_&#169;">\\en.wikipedia.org/wiki/Crypt_&#169;</a></p>
    <p>See here: <a href="https://en.wikipedia.org/wiki/Crypt_\(C\)">en.wikipedia.org/wiki/Crypt_(\C\)</a></p>
    <p>See here: <a href="\\https://en.wikipedia.org/wiki/Crypt_&#169;">en.wikipedia.org/wiki/Crypt_&#169;</a></p>

**Comment by mojavelinux** [comment]
Special characters in URLs have to be escaped. See http://asciidoctor.org/docs/user-manual/#complex-urls

There's already an open issue to bypass formatting in URLs. See #1326.

In this case, however, you have hit a corner case of a corner case. A trailing ) is not treated as part of the URL, since many times it means that the text is in round brackets. We really have no way of determining which case it is, so you have to be explicit. That's why the following won't work:

```
See https://en.wikipedia.org/wiki/Crypt_\(C)
```

In this case, I recommend using URL encoding for the brackets:

```
See https://en.wikipedia.org/wiki/Crypt_%28C%29
```

(In general, I recommend also defining URLs as attributes. It won't help you in this case, but it's still a good practice).

I'm closing this issue since I've bundled the corner the case to the linked issue.
