### ISSUE TITLE
Inline SVG not displayed

### ISSUE THREAD

**Issue by sirjorj** [asciidoctor/asciidoctor#2095]
I noticed an issue with this so I made a simple test case.  Take the following .adoc file:

```
= SVG Bug?

|===
| Regular
| image:lo5.svg[width="100%"]
|===

|===
| Inline
| image:lo5.svg[width="100%",opts="inline"]
|===
```

I exported a LibreOffice Draw document as an svg and named it lo5.svg.  [(zipped up here)](https://github.com/asciidoctor/asciidoctor/files/861663/lo5.svg.zip)

The top one displays just fine, the bottom one is empty.  Looking at the source, the svg looks to be there.  Am I doing something wrong or is there some weird thing about how LO generates svgs that breaks this?

I'm running 1.5.5 from gem on debian jessie.

**Comment by mojavelinux** [comment]
Both cells appear exactly the same for me when I view the generated HTML page in both Chrome and Firefox. Can you confirm you are converting to HTML? Can you confirm which browser you are using to view the page.

By it's nature, the inline SVG does require more browser support than the normal (image) mode. That's because the SVG is inserted directly into the document. You might also try to use `data-uri` document attribute instead of inline, which adds the base64 data to the page, but still links to it as an image.

**Comment by sirjorj** [comment]
I was just using a really old (v49) version of chromium.  After updating it, it works fine!  Thanks!

**Comment by mojavelinux** [comment]
That's great news. I'll go ahead and make the point I made in the user manual so that users are aware.
