### ISSUE TITLE
xrefs vs files included from different directories does not detect internal/external xrefs correctly

### ISSUE THREAD

**Issue by ztmr** [asciidoctor/asciidoctor#2108]
Let's say you include `../doc-b/doc-b.adoc` from `/tmp/doc-a/doc-a.adoc` and then try to xref `doc-b` from `doc-a`. Since `doc-b` is included, it should automatically detect it and make only internal link rather than external. The problem is how `document.references[:includes]` is built -- it does not contain full paths, so when we check this in `substitutors.sub_inline_xrefs`, it does not always work:
```@document.attributes['docname'] == path || @document.references[:includes].include?(path)```
...because `path` can be pointing to the same file but can be relative from somewhere else.

The problem with relative paths is addressed in #2107 but is not enough alone.

I did an experiment modifying the test as follows:
```
require 'pathname'
includes_full = @document.references[:includes].map! {|x| (Pathname.new x).cleanpath.to_s}
path_full = (Pathname.new path).cleanpath.to_s
if @document.attributes['docname'] == path || @document.references[:includes].include?(path) || includes_full.include?(path_full)
```
...what worked but I'd rather see a method like `@document.include?(path)` that would do this on the background -- I am not sure if we can start storing full paths in `@document.references[:includes]` as it is used for some other purposes but we should be able to have at least another set like `:includes_full` or store something like tuple (relative and absolute paths) or so.

**Comment by mojavelinux** [comment]
I now understand why the PathResolver#relative_path isn't sufficient. It doesn't handle the case when the relative path leaves the base directory. There's a somewhat narrow case here, because it depends highly on where you are running the processor from. But we could lazy-load Pathname in this case to compute the relative path. But the xref would still need to match that resolved path. I'll propose a PR and we can discuss.
