### ISSUE TITLE
CSS: use bold for menus

### ISSUE THREAD

**Issue by owenh000** [asciidoctor/asciidoctor#2148]
Menus seem to be a lot easier to read with `font-weight:bold`. Buttons are already bold, but in that case it is implemented by using a `<b>` tag in the HTML. I suppose CSS or the HTML `<strong>` tag would be more suitable in both cases.

An example:
![Rendered HTML](https://cloud.githubusercontent.com/assets/5339120/25365383/eaca65b4-292d-11e7-9331-4b0713ab84c7.png)

The AsciiDoc source:
```
:experimental:

. _This is a short menu example with normal font weight._
+
Click on menu:File[Open], then save the file.

. _Here is #1 again, a short menu example, with bold font weight._
+
Click on *menu:File[Open]*, then save the file.

. _This is a longer menu example with normal font weight._
+
Click on menu:System & Hardware[Power Saving] and scroll to
*Displays*.

. _Here is #3 again, a longer menu example, with bold font weight._
+
Click on *menu:System & Hardware[Power Saving]* and scroll to
*Displays*.

```

**Comment by mojavelinux** [comment]
I could get behind this. I studied various documentation sites to see how menus references are styled. Both the IntelliJ IDEA help and the Google Developers docs use bold.

* https://www.jetbrains.com/help/idea/2017.1/menus-and-toolbars.html
* https://developers.google.com/web/tools/chrome-devtools/

In other places, menu references are styled in monospaced, which makes no sense to me. You are right that the bold makes it stand out.

> Buttons are already bold, but in that case it is implemented by using a <b> tag in the HTML

We only use `<b>` in that case so that the button doesn't appear as plain text on GitHub. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/b#Usage_notes explains the reasoning behind it. Since we have the arrow for menus, that's enough for the "no style" style that GitHub provides. We should prefer to control the style via CSS.

**Comment by mojavelinux** [comment]
I suppose a case could be made for using `<b>` in place of span. But the stylesheet should still control how it actually appears.

**Comment by mojavelinux** [comment]
I'd like to offer a counter proposal (see #2164).

The color of the body text is dark gray. Therefore, we can make the menu reference stand out by making the text black. (In fact, this was the original intent, but the color got calculated incorrectly in the build).

I think darker text is more visually balanced than bold. If you feel strongly that it doesn't stand out enough, I'd also consider making the text italic. My last choice is bold since you don't think of bold text when you think of a menu.

**Comment by mojavelinux** [comment]
I used the following example to test:

```
= Sample Document
:experimental:
:uri-wolpertinger: http://en.wikipedia.org/wiki/Wolpertinger

Click on menu:System & Hardware[Power Saving] and scroll to menu:Displays[].

You may not be familiar with these {uri-wolpertinger}[ravenous beasts].
Trust us, they'll eat your shorts and suck loops from your code.

To reset the zoom level, select menu:View[Zoom > Reset] from the main toolbar.

The werewolves haven't returned from their rendezvous at Bier Central.
They've either eaten each other or fallen victim to the Wolpertingers roaming the streets of Antwerp.
Quick, select menu:File[Quit] and let's bail out of here!
```

Here's how it appears:

![result](https://cloud.githubusercontent.com/assets/79351/25568777/cb8e3ccc-2dc7-11e7-8b11-c00f1f9e6ca8.png)

**Comment by mojavelinux** [comment]
It effectively comes off as bold, but just not so drastic.

**Comment by owenh000** [comment]
I think your proposal looks very good. I am in favor of merging #2164 and closing this issue.

**Comment by mojavelinux** [comment]
Great.

I've taken this a step further and allow the the caret to be controlled by CSS. I rolled the proposed change here into that issue. See #2165.

**Comment by owenh000** [comment]
Nice work, thanks!

**Comment by mojavelinux** [comment]
Awesome. I'm going to merge this in stages, so you might get multiple notifications about it being resolved.

**Comment by mojavelinux** [comment]
As a bonus, menus will look styled on GitHub (once they upgrade to 1.5.6).
