### ISSUE TITLE
Enable noheader, nofooter attributes for docbook backend

### ISSUE THREAD

**Issue by asknet** [asciidoctor/asciidoctor#2155]
I see asciidoctor attribute noheader has no effect for docbook backend( in my setup). I tried both at CLI & within document. But -s option suppresses header. Can anyone please confirm if this is an issue or I'm doing something wrong
For my use case, I don't want root info tag in my docbook xml when noheader attribute is specified.

Thanks a lot

**Comment by mojavelinux** [comment]
This makes sense. I propose that the noheader attribute just drops the `<info>` element. Would you agree?

I don't think the nofooter attribute really applies since the DocBook converter doesn't add anything at the bottom.

> But -s option suppresses header.

It's more correct to say that the `-s` option creates an embeddable document, which means it eliminates the document (root) element and related metadata.

**Comment by mojavelinux** [comment]
I've sent a PR.

https://github.com/asciidoctor/asciidoctor/pull/2177

Would you say there's anything else that should be suppressed?

**Comment by asknet** [comment]
Looks good, thanks a lot.
