### ISSUE TITLE
Column spacing not enforced if content has no spaces

### ISSUE THREAD

**Issue by janicecmt** [asciidoctor/asciidoctor#2186]
It appears that the content inside a table cell can override the specified column widths (either proportional or percentage-based). I am using tables inside reference documentation and the first column is typically the name of whatever I'm discussing in the row. The last column is typically a description or notes with the vast majority of the content. I have been using proportional spacing in each table to maximize the width of the description column. However, the width instructions are ignored if that means the content in one of the smaller columns would need to wrap on something other than a space. I got the same results when I switched to percentage-based column widths.

For example, a name like foo[x].bar.foobar won't wrap even if takes up 90% of the available screen width). 

I realize wrapping this may not always the desired behavior, but someone who doesn't want it to wrap can set the column widths so that no wrapping occurs. The reverse is not true. If I specify relative column widths they should be obeyed - if I wanted more natural wrapping/widths I could either adjust my settings or remove them and allow the table to use automatic sizing.

**Comment by mojavelinux** [comment]
Could you provide a sample AsciiDoc document that demonstrates the problem. I'm having a hard time seeing what you mean.

**Comment by janicecmt** [comment]
See attached files.

**Comment by mojavelinux** [comment]
You're correct that column widths are not always enforced. Think of them more as a suggestion than a hard requirement. That's just how HTML tables work (by default). The content can push the column wider than specified when there are no break opportunities).

There is a newer feature of CSS that makes column widths strict. See https://css-tricks.com/fixing-tables-long-strings/. You could add this to your CSS. However, keep in mind that while it solves some problems, it causes others.

We could consider making the table layout strategy configurable via a block attribute. Another idea we are considering are responsive tables. See #1713. That would allow the table to scroll side to side instead of overflowing the bounds. I'm going to add this suggestion to that issue and close this one.
