### ISSUE TITLE
including a tagged portion of y.adoc breaks any links y.adoc from the same origin file

### ISSUE THREAD

**Issue by hossman** [asciidoctor/asciidoctor#2200]
Consider the following source files...

`x.adoc`
```
= X Title

X X X X X X X X

Please consult <<y.adoc#_details,Y's Details>> for other details...
____
include::y.adoc[tags=abstract]
____

X X X X X X X X
```

`y.adoc`
```
= Y Title

== Abstract

// tag::abstract[]
y y y y y y
// end::abstract[]

== Details

Y Y Y Y Y Y Y Y Y
```

This is what the `html5` backend generates for the relevant section of `x.html`...
```
..
<div class="paragraph">
<p>Please consult <a href="#_details">Y&#8217;s Details</a> for other details&#8230;&#8203;</p>
</div>
<div class="quoteblock">
<blockquote>
<div class="paragraph">
<p>y y y y y y</p>
</div>
</blockquote>
</div>
...
```

Please note that the "link" which should have an `href="y.hmlt#_details"` is instead simply `href="#_details"`.

It seems the existence of `include::y.adoc` in `x.adoc` causes all links to `y.adoc` to be rewritten as if they were part of the same page, even though the `include` is paramaterize to only include a specifically tagged portion of `y.adoc`

(tested via `asciidoctor-ant 1.6.0-alpha.3`)

**Comment by mojavelinux** [comment]
I agree this is a problem. Thanks for filing. The issue is that the interdocument cross reference feature predated including content by lines / tags. There was an assumption at the time that the reference in that file would be incorporated when the include was processed. That assumption no longer holds. So we'll need to think harder about the interplay between these two features and what we can assume.

**Comment by mojavelinux** [comment]
What I'm proposing is that if you include a fragment of a file, as far as the xref system is concerned, you didn't include the file at all. I'll do that by setting the `fragment-option` attribute to the attributes passed to Reader#push_include so that the document is not added to the `includes` collection (in other words, it's not listed as a file which has been included into the current one).

**Comment by elextr** [comment]
@hossman did you really want the link to point to the `y.adoc` file? Shouldn't it point at the HTML file?

**Comment by hossman** [comment]
> did you really want the link to point to the y.adoc file? Shouldn't it point at the HTML file?

I'm concerned i may not be fully grasping your question, since the term "link" can be vague (are you refering to the "link markup in the source x.adoc" or the "generated `<a href>` link in the x.html output file" ?

in the original issue report i said...

> Please note that the "link" which should have an `href="y.hmlt#_details"` is instead simply `href="#_details"`.

..refering to what i expected the "generated `<a href>` link in the x.html output file" to be given the "link markup in the source x.adoc" of: `<<y.adoc#_details,Y's Details>>`

**Comment by mojavelinux** [comment]
As @hossman points out, the interdocument xref automatically links to the output file (in this case HTML). But due to the fact that the same file is also being included, it's instead attempting to find the reference in the current document. This would work if the whole file were to be included. However, in this case it's not. Thus, this extra intelligence should be disabled (thus allowing it to become a normal link).

**Comment by elextr** [comment]
@hossman I meant the generated `href`.  The `x.adoc` source points to a `y.adoc` file, but Asciidoctor doesn't know how you are going to process that file.  It might not turn into a `y.html` file, it might be used to produce a PDF or Docbook which is then processed into chunked HTML which has multiple names.  You need to tell Asciidoctor what the result is going to be.  The link target might be included into a totally different file, who knows.  The assumption that `y.adoc` makes `y.html` is a bad one.

@mojavelinux it should never be necessary to point at the `y.adoc` should it?  If the link target is included it must be unique, so can just be pointed to by id.  If the link target is not included the link needs to be to the _output_ file it is going to be in, since Asciidoctor doesn't know what that will be.

**Comment by elextr** [comment]
> Asciidoctor looks at what you are making and creates an appropriate link
exactly so you don't have to worry about the output file extension.

Thats useful, if the target source file is listed on the command line to be processed, then Asciidoctor knows what to do (at least for HTML and the internal PDF generator, but not for docbook).  So in this case its a good idea to encourage.

If the target source is not listed on the command line Asciidoctor is making assumptions that the target source will be processed the same as this source. And assumptions ... [usual saying about assume].

As for the case where only part of the target source is included, hmmm, its ambiguous, you might include the target, either in this include or in another one, and you might not.  I guess the best solution would be to look if the target id was included and then make it a local link, otherwise make it an interdocument link.  How hard that is for the Asciidoctor implementation I don't know.

**Comment by mojavelinux** [comment]
> If the target source is not listed on the command line Asciidoctor is making assumptions that the target source will be processed the same as this source. 

Not necessarily. It's just assuming that it will be available where the current file is published. And that's exactly the point of the interdocument reference feature. If you don't have that case, then you wouldn't use this feature.

It's way too high of a cost to process included fragments (when you don't include the whole file). Therefore, we'll just treat it as though you did not include it. There's no harm in that...the inner-document link is only a nice-to-have feature anyway. You can always go the long way around and just reference the file. This was mostly intended for PDF anyway, so IMO the solution is quite straightforward.

**Comment by mojavelinux** [comment]
There are actually three changes here. First, we were tracking non-AsciiDoc include files, yet at the same time stripping the file extension, so there was even more room for conflict. Now we only track AsciiDoc files (files either with a known extension or no extension). Secondly, if the file is included partially, we now set the partial-option on the attributes passed to push_include. We still track that the file was included, but we mark it as only being included partially. Finally, we only consider files which have been included completed when determining whether to consider the included file coalesced with the current file. Now there's no risk that including a file partially (or including a non-AsciiDoc file) will mess up the inter-document xref.
