### ISSUE TITLE
Link Rendering Bug

### ISSUE THREAD

**Issue by Jotschi** [asciidoctor/asciidoctor#2269]
The following source string:
```
link:http://some.domain.tld/?blub=123...456[link]
```

Gets converted via `asciidoctor -o - test.adoc` to:
```
<p><a href="http://some.domain.tld/?blub=123&#8230;&#8203;456">link</a></p>
```

The dots in the link should not be converted to `&#8230;&#8203;` since those are unreserved characters. See https://tools.ietf.org/html/rfc3986#section-2.3 for more details.

Version info:

```
 ~/tmp$ asciidoctor --version
Asciidoctor 1.5.5 [http://asciidoctor.org]
Runtime Environment (ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)
```

**Comment by mojavelinux** [comment]
Any characters in a URL that have special meaning in AsciiDoc have to be "passed through". This use case is documented in the user manual. Please see: http://asciidoctor.org/docs/user-manual/#complex-urls

The solution to this problem is to treat the link macro as an implicit pass macro. This proposal is covered in the following issue: #1326.

**Comment by mojavelinux** [comment]
To answer you directly, this is how you currently have to type it:

```
link:++http://some.domain.tld/?blub=123...456++[link]
```

or you can b) use an attribute reference, c) escape the three dots with a backslash, or d) URL encode the dots using %2E.

**Comment by Jotschi** [comment]
Thanks!
