### ISSUE TITLE
Use <quote> element in DocBook backend

### ISSUE THREAD

**Issue by aksdb** [asciidoctor/asciidoctor#2272]
Currently quotes are written unmodified ('"' stays '"') into DocBook. In my understanding, these should be replaced with proper `<quote>...</quote>` elements: http://tdg.docbook.org/tdg/5.0/quote.html
Otherwise it is currently not possible to the downstream processors to properly handle the quotes (according to the selected language).

**Comment by bk2204** [comment]
This is very easy to do if we do indeed want to do it.  It's a two-line change, although we lose the ability for people to override the default DocBook stylesheet behavior.  I think that's okay, though, since we gain better internationalization and more semantic markup.

I think it's a good idea, so I'm going to submit a pull request and see what @mojavelinux thinks about it.

**Comment by mojavelinux** [comment]
This is a fantastic idea! It's one of those ideas that I can't believe we overlooked until now.

This actually solves a much larger conceptual problem too. Here I was thinking about how we could represent quotes in different languages using the AsciiDoc syntax when we already had the abstraction we needed. It was just a matter of changing the converter. Moving forward, I think we could make a similar change in the HTML converter using the `<q>` tag (or the appropriate character reference based on the lang attribute).
