### ISSUE TITLE
Problem with Ascidoctor 1.5.6 and asciidoctor-pdf 1.5.0.alpha15

### ISSUE THREAD

**Issue by JBR69** [asciidoctor/asciidoctor#2330]
I post this issue in `asciidoctor` but I don't know if is a bug in `asciidoctor 1.5.6` or in `asciidoctor-pdf`.

In my adoc file, I have chapters including icons like this
```
[[add-elements-host]]
== image:{iconsdir}\linux.png[image,width=25,height=25] Add host element(s)
blablabla...
```
The conversion is Ok in HTML with asciidoctor 1.5.5 or 1.5.6
The conversion is Ok in PDF with asciidoctor-pdf 1.5.0.alpha15 and asciidoctor 1.5.5
But, the conversion is **KO** in PDF with asciidoctor-pdf 1.5.0.alpha15 and asciidoctor **1.5.6**

I have this error
```
E:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/asciidoctor-pdf-1.5.0.alpha.15/lib/asciidoctor-pdf/prawn_ext/extensions.rb:785:in `scratch?': asciidoctor: FAILED: F:/Documentations/asciidoc/sources/fr/documents/Linux/myDoc.adoc: Failed to load AsciiDoc document - undefined method `store' for nil:NilClass (NoMethodError)
        from E:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/asciidoctor-pdf-1.5.0.alpha.15/lib/asciidoctor-pdf/converter.rb:2004:in `convert_inline_image'
        from E:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/asciidoctor-pdf-1.5.0.alpha.15/lib/asciidoctor-pdf/converter.rb:120:in `convert'
```
When I put a trace in `converter.rb` (of **asciidoctor-pdf**) at line 2004, I see that variable `target` contains `{iconsdir}\linux.png` , the variable `iconsdir` was not substituted.

Pending a correction, I found a temporary workaround in `inline.rb` (of **asciidoctor 1.5.6**), line 23
```
    @target = opts[:target]    
    
    # JBR - Workaround (undefined method `store' for nil:NilClass (NoMethodError) si image dans titre)
    if !@target.nil? and @target.include? "{iconsdir}"
       @target = opts[:target].gsub("{iconsdir}", "#{attr 'iconsdir'}")
    end   
```

Jérôme

**Comment by Mogztter** [comment]
I think `asciidoctor-pdf` should be added in the dependent projects list: https://github.com/asciidoctor/asciidoctor/blob/master/Rakefile#L138-L143

Is that possible to add a few tests on `asciidoctor-pdf` ?

**Comment by mojavelinux** [comment]
@Mogztter That's the chicken-egg problem. We can't test it until we have tests. And we can't leave alpha until we have tests. So, tests are critical.

But I want a good test suite. I want it to based on RSpec like jekyll-asciidoc. I've just been lacking in the time to do it.

**Comment by mojavelinux** [comment]
This traces back to the following change in 1.5.6.

https://github.com/asciidoctor/asciidoctor/commit/38478c396efb74cece9781fb76e556b328c29967#diff-6f7bf4d593caf333c1e0f6ca3c95085cR666

We stopped substituting attributes in the target of an image macro since attribute substitution is usually already handled. The problem comes with titles (section titles and block titles), which change the normal substitution order. I've long talked about this being a problem in AsciiDoc. See #1173.

What's happening is that in 1.5.6, the image target is resolving to `{iconsdir}/linux.png` (notice the unresolved attribute). Asciidoctor PDF tries to generate a warning, but fails. The stacktrace is actually coming from a bad assumption in the scratch? method. It happens any time any image used in a title can't be found. If that were fixed, then you'd just get a warning instead of a failure.

(You'd see the same warning if you ran `asciidoctor -a data-uri`).

In order to swap the substitution order, you'd need to change to:

```
== pass:n[image:{iconsdir}/linux.png[linux,width=25,height=25\] Add host element(s)]
```

But I'm inclined to say that we should resolve any unresolved subs in the target of the inline image for backwards compatibility...until we get the title substitution order corrected.
