### ISSUE TITLE
Allow \ character in a kbd macro

### ISSUE THREAD

**Issue by miltador** [asciidoctor/asciidoctor#2343]
`kbd:[\]` macro just prints out itself.
Tried to escape it like `kbd:[\\]`, `kbd:[/\]` but achieved the same result.
It turned out that regexp for `kbd` macro forbids a `\` character.
Any reason it should be forbidden? Or how to workaround it?

**Comment by mojavelinux** [comment]
Due to how parsing is implemented, this case cannot be supported as is without introducing ambiguity when there's more than one kbd macro in a line (trust me, I tried a dozen different ideas). Therefore, to have the kbd macro output a backslash, you must put a space between the backslash and the closing bracket:

```
kbd:[\ ]
```

There's a test for this case. See https://github.com/asciidoctor/asciidoctor/blob/1e206615d57573dfacb5cf22dc30adf7edf6567d/test/substitutions_test.rb#L1229-L1232

**Comment by miltador** [comment]
Thank you! kbd:[\ ] works fine. Couldn't find any information on this. Would be nice to have it documented somewhere in the user manual.

**Comment by mojavelinux** [comment]
Good suggestion. This was a new restriction in 1.5.6 (to fix separate bug). I just added it to the user manual as an example.

http://asciidoctor.org/docs/user-manual/#keyboard-shortcuts
