### ISSUE TITLE
Unable to format text after colon

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctor#2348]
Seen in:
* _v. 1.5.6.1, Window 7, using Ruby 2.4, cmd shell_
* _Preview in IntelliJ AsciiDoc plugin (uses Asciidoctorj 1.5.5)_

Hi,
I found that formatting after a colon is ignored.
The second part of the following text is show as-is in the generated HTML.
```
* `[hostPort]`:`[containerPort]`
* `[hostPort]`:*[containerPort]*
* `[hostPort]`:_[containerPort]_
```
![image](https://user-images.githubusercontent.com/5781153/28812135-81ab5ae4-7693-11e7-895c-10a78398a748.png)

If add a space after the semicolon, it works, but this means adding some unnecessary text.
```
* `[hostPort]`: `[containerPort]`
* `[hostPort]`: *[containerPort]*
* `[hostPort]`: _[containerPort]_
```

Could it be the parser is interpreting this as a macro or something else?

**Comment by robertpanzer** [comment]
I think anytime the formatting is not at word boundaries you have to use the "unconstrained formatting": http://asciidoctor.org/docs/user-manual/#unconstrained-quotes :
```
* `[hostPort]`:``[containerPort]``
* `[hostPort]`:**[containerPort]**
* `[hostPort]`:__[containerPort]__
```

**Comment by mojavelinux** [comment]
That's absolutely correct. A colon is not a word boundary (at least, not when to the left). The documentation is actually missing this case, so I'll update it.

See http://asciidoctor.org/docs/user-manual/#when-should-i-use-unconstrained-quotes

**Comment by mojavelinux** [comment]
To be honest, I still think those explanations are confusing. Generally speaking, unless the word or phase you want to format is surrounded by a whitespace or line boundary on both sides, you should use unconstrained marks. The exceptions come when the formatted text is followed (or adjacent to) standard phrasing punctuation (e.g., `*tiger*, a big cat`). As a result, all these crazy exceptions got added.

So perhaps we can amend it to say, unless the word or phrase you want to format is surrounded on both sides by whitespace, a line boundary, or standard punctuation (comma, period, hyphen, etc), you should use unconstrained marks.

In UniDoc, we're going to make the rules much simpler so that they are easier to think about.

**Comment by mojavelinux** [comment]
(some of those crazy exceptions come from nesting formatting, a problem which goes away once we parse using recursive descent)

**Comment by abelsromero** [comment]
I think the explanations are really clear, except for when it says:
`Is there a space directly inside of the formatting mark?` ->  The later example helps, but it's not clear to me at first hand that the spaces need to be adjacent to the mark.

My confusion came because it's odd that not all punctuation symbols require this, but I understand is for AsciiDoc Py compatibility.

This issue can be closed.
