### ISSUE TITLE
Small list and default stylesheet for html5

### ISSUE THREAD

**Issue by tho-** [asciidoctor/asciidoctor#2407]
Hi,

I think the default stylesheet prevents to render "small" lists. This code:
```
[.small]
 * Item
 * Other item
```

Produces the html5 code:
```
<div class="ulist small"><ul><li><p>Item</p><li><p>Other item</p></li></ul></div>
```

The default CSS has:
```
.small { font-size: smaller; }
```
But this is resetting the font size inside the `div`:
```
p, blockquote, dt, td.content, span.alt { font-size: 1.0625rem; }
```

Shouldn't it be `1.0625em` instead of `rem`?

**Comment by mojavelinux** [comment]
You'll need to make your style rule more specific.

> Shouldn't it be 1.0625em instead of rem?

That's a separate change that will happen when the stylesheet is upgraded to Foundation 5 or 6. See https://github.com/asciidoctor/asciidoctor-stylesheet-factory/issues/19

I like to use a mix of em and rem because I see the purpose for having both. But we can discuss that in the linked issue.

**Comment by mojavelinux** [comment]
> `.small { font-size: smaller; }`

This declaration is intended to be used for a phrase (e.g., `[.small]#stuff#`), not a list.

**Comment by tho-** [comment]
On Tuesday 12 Sep 2017, at 06:36, Dan Allen wrote:
>     .small { font-size: smaller; }
>
> This declaration is intended to be used for a phrase (e.g.,
> [.small]#stuff#), not a list.
>

OK, but then there is no way to render a small list with the default
stylesheet?

**Comment by mojavelinux** [comment]
No, not at the moment. That is not a feature that was designed into the default stylesheet.

**Comment by tho-** [comment]
OK, too bad, but let's close this issue, then.
Thanks for the feedback!
