### ISSUE TITLE
Add default styling for button in HTML output 

### ISSUE THREAD

**Issue by vogella** [asciidoctor/asciidoctor#2447]
Would be nice to have a default styling in the HTML output.
For vogella we use the following output:

https://screenshots.firefox.com/gvRGphNxCZXWA6wD/www.vogella.com

Our css for the button is the following

````
kbd {
    font-family: "Droid Sans Mono","DejaVu Sans Mono",monospace;
    display: inline-block;
    color: rgba(0,0,0,.8);
    font-size: .65em;
    line-height: 1.45;
    background-color: #f7f7f7;
    border: 1px solid #ccc;
    -webkit-border-radius: 3px;
    border-radius: 3px;
    -webkit-box-shadow: 0 1px 0 rgba(0,0,0,.2),0 0 0 .1em 
}
````

**Comment by mojavelinux** [comment]
The current styling is intentional. It's considered poor usability to style a button reference to look like a real button in documentation. It's too easily confused for an interactive element. The recommended way to style a button reference is to use bold text. We decided to also surround it in square brackets, which provides a hint of its shape.

One resource the recommends this formatting is https://developer.salesforce.com/docs/atlas.en-us.salesforce_pubs_style_guide.meta/salesforce_pubs_style_guide/style_buttons.htm.
