### ISSUE TITLE
xref inline macro regex is too greedy

### ISSUE THREAD

**Issue by lnewson** [asciidoctor/asciidoctor#2450]
https://github.com/asciidoctor/asciidoctor/commit/b60cd052365df6bbc86e509d7f7c784edf9383bf introduced a regression/issue where the cross reference macro (InlineXrefMacroRx) is now too greedy if there are two xrefs on the same line. As such this is impacting AsciiDoctor 1.5.6 or higher.

As an example, if you have some markup like so:

    See xref:some-id[] other content xref:some-other-id[].

Then instead of matching `xref:some-id[]` and `xref:some-other-id[]` separately it instead matches it as `xref:some-id[] other content xref:some-other-id[]` which in turn ends up producing a link like so:

    <a href="#some-id">] other content xref:some-other-id[</a>

**Comment by lnewson** [comment]
I believe this could potentially be fixed by making the `[^\\]` match zero or once instead of having to match at once, in InlineXrefMacroRx. ie:

    InlineXrefMacroRx = %r(\\?(?:&lt;&lt;([#{CC_WORD}#/.:{]#{CC_ALL}*?)&gt;&gt;|xref:([#{CC_WORD}#/.:{]#{CC_ALL}*?)\[(#{CC_ALL}*?[^\\]?)?\]))m

**Comment by mojavelinux** [comment]
Oh wow, I can't believe that slipped through. Thanks for reporting. There was no test for this case, which is why it slipped through. (In the end, only the tests can save us).

I submitted a patch with a test. I'm still thinking if that's the right solution, but all tests pass, so I know it's going to a solution.

This is a good example of where regular expressions are sometimes too blunt of a tool for parsing, at least when trying to parse a whole line. This situation has actually come up before in other macros. What I figured out is that you can first tell it to match for nothing, then match for something. The downside is that it captures the nothing as an empty string, which is what I was trying to avoid. But we're just going to have to do it or else the greedy rules kick us.

**Comment by mojavelinux** [comment]
> I believe this could potentially be fixed by making the `[^\\]` part match zero or once instead of having to match exactly once

Thanks for the suggestion. However, it's already doing that, as indicated by `?` that follows it. The problem is, we are saying "match any character if the next character is not an escaped backslash, maybe". So it says, well, `]` is not an escaped backslash, so I'll match that. Except, that's not what we want.

So we can start by saying, first, try to match nothing. That gives us a hit.

**Comment by mojavelinux** [comment]
To clarify what I mean, if we put `?` on the backslash, then it fails to parse this:

```
xref:section-a[[foo\]bar]
```

**Comment by lnewson** [comment]
Ahh, good catch I hadn't thought of that :+1:  Thanks Dan! :smile:

**Comment by jirutka** [comment]
My solution that I wrote before I found that it’s already fixed, but unreleased:

```ruby
%r(\\?(?:&lt;&lt;([#{CC_WORD}#/.:{]#{CC_ALL}*?)&gt;&gt;|xref:([#{CC_WORD}#/.:{]#{CC_ALL}*?)\[([^\]]*?[^\\])?\]))m
```
