### ISSUE TITLE
First heading should determine if Markdown compliance should be on or not

### ISSUE THREAD

**Issue by ds26gte** [asciidoctor/asciidoctor#2471]
If the first header of the document is AsciiDoc-style (i..e, with `=`s), do _not_ turn on Markdown compliance. This allows writers to continue using `#`, `*`, `-`, `>` without having to work around to avoid special behavior.

Mentioned in #2074.

**Comment by ds26gte** [comment]
Implementing this is easy enough: In `parser.rb`, just after

```
    if Compliance.markdown_syntax ? ((line1.start_with? '=', '#') && ExtAtxSectionTitleRx =~ line1) :
        ((line1.start_with? '=') && AtxSectionTitleRx =~ line1)
```

add

```
      if (line1.start_with? '=')
          Compliance.markdown_syntax = false
      end
```

However, a bunch of tests (`bunch exec rake`) that check for Markdown compliance need to be rewritten, because Markdown compliance won't happen anymore without an `=` header.

**Comment by ds26gte** [comment]
My PR (#2482) was OK on a `bundle exec rake`, but seems to fail the Travis CI build. Any thoughts, @mojavelinux?

**Comment by ds26gte** [comment]
Any movement on this? I offered a PR: the implementation itself is straightforward, but some tests need a rewrite and I don't know to temporarily force Markdown-compliance in the tests for Markdown-compliance.

**Comment by mojavelinux** [comment]
I apologize for the delay, @ds26gte. I've been insanely busy recently getting Antora into shape.

I think this change takes the idea too far. It's perfectly legitimate to use an AsciiDoc-style document title and still use Markdown compliance. I do that all the time.

We also can't have a document change the static state of Asciidoctor. That violates thread safety and would introduce some hard to understand bugs in programs. Compliance settings are meant to be changed when you load Asciidoctor.

The reason I use a static property (essentially a constant) is because it's extremely fast and we can access it from anywhere. If we changed to using a document attribute (kind of like compat-mode), then it's slightly slower and could be out of reach at times (though I have to check that).

Is it possible for you to change the compliance setting manually when loading Asciidoctor?

**Comment by ds26gte** [comment]
Thanks, I see what you're saying and have probably learned to work around any surprises by now. 

However, regarding thread safety: I wonder if the cat isn't out of the bag. If the first header in a document is setext-style (two lines) rather than atx- (with flanking `=`s), Asciidoctor accepts some AsciiDoc syntax (notably single quotes for italics) that is otherwise disallowed. (Not that I think you should nix this conditionality: Having to rewrite single quotes in one's documents in order to avoid italics would be a major headache.)

**Comment by mojavelinux** [comment]
> If the first header in a document is setext-style (two lines) rather than atx- (with flanking =s), Asciidoctor accepts some AsciiDoc syntax (notably single quotes for italics) that is otherwise disallowed.

Yes, but it doesn't change a static variable to do so. Instead, it continuously checks for the compat-mode attribute on the document (so it's scoped).

I still think Markdown compliance should be controlled statically / globally. The one place we could improve is to add a CLI option, since it's not very convenient at the moment to control this compliance setting when using the CLI. I'd be open to that.

Personally, I consider the Markdown compliance that we've chosen to be part of AsciiDoc. We took good ideas from Markdown that didn't conflict with the AsciiDoc syntax and incorporated them. It's consistent with AsciiDoc being a language built strongly on conventions.

**Comment by elextr** [comment]
>  We took good ideas from Markdown that didn't conflict with the AsciiDoc syntax and incorporated them.

Asciidoc will grow over time, that some of the extended syntax happens to be markdown markup (markupdown??:) compatible is a bonus.

Though is the horizontal rule __so__ important that there should be 6 different syntaxes for it :grin:

**Comment by mojavelinux** [comment]
> I consider the Markdown compliance that we've chosen to be part of AsciiDoc. We took good ideas from Markdown that didn't conflict with the AsciiDoc syntax and incorporated them. It's consistent with AsciiDoc being a language built strongly on conventions.

...and it's possible that during the language formalization process, we pull back drastically and only adopt some of it. I'm no longer convinced at this point it really makes much sense to support Markdown-style headings, for example. But most people like the Markdown-style quote block since it long predates Markdown. The thematic breaks (horizontal rules)...well, that's just really hard to wrangle because there are so many competing conventions there. We may even just say "look, here's a bundle of thematic-like symbols all in a row...looks like a break to me" or maybe we don't. That discussion will take place.

Regardless, we're not changing the behavior right now in Asciidoctor because it would break documents with no clear line in the sand as to why it just happened.
