### ISSUE TITLE
Allowing newlines in asciimath stem block

### ISSUE THREAD

**Issue by hgiesel** [asciidoctor/asciidoctor#2497]
This is basically a continuation of #2484. At the moment a stem block which utilizes AsciiMath (which is the default) like this:

```
[stem]
++++
f: bbb"N" -> bbb"N"
f: x |-> x + 1
++++
````

...is parsed like this:

```html
<div class="stemblock">
<div class="content">
\$f: bbb"N" -&gt; bbb"N"
f: x |-&gt; x + 1\$
</div>
</div>
```

However this will display both lines on the same line. [AsciiMath does not support linebreaks in formulas](https://github.com/asciimath/asciimathml/issues/49). However this is confusing to the AsciiDoc user, because stem blocks aim to facilitate multiline input for code segments, or similiar.
I could think of three solutions for this:

1. 
We simply parse the above AsciiDoc like this:
```html
<div class="stemblock">
<div class="content">
\$f: bbb"N" -&gt; bbb"N"\$<br/>
\$f: x |-&gt; x + 1\$
</div>
</div>
```
..., which will display two lines. This is the simplest solution and fits with the minimalist approach of AsciiMath, however users being used to this will then most likely be surprised, if they do this:

```
[stem,latexmath]
++++
f: \mathbb{N] \to \mathbb{N}
f: x \mapsto x + 1
++++
```

... and get everything on a single line (because you need the `\\` to mark a newline in MathJax)

2.
We extend the AsciiMath by a token like `\\`, however I don't know how much work this will incur, and it seems to me it's the least appealing approach.

3.
Ask the team behind MathJax to implement something like AsciiMath blocks. However this does not really seem necessary, because in the issue I linked above, the AsciiMath team basically says it does not want to concern itself with the layout aspects. This is easily done in HTML, because you can use `br` tags, however you can't do this in AsciiDoc, because it is abstracted away.

**Comment by dimztimz** [comment]
Double backslash `\\` is taken in Asciimath. Single newline is deliberately ignored.

I was thinking about this and come up to 2 possible solutions.

1. **Double new line** should mark a new line in asciimath block. With double new line I think that the intent for new line is clearly stated. This is analogous to writing double new line for new paragraph.
2. If we want a more tightly packed ascii input, allow **backlash newline** to break. Currently that translates to "backslash space" in the html which is rendered as forced space (e.g. if you want multiple spaces not to get collapsed into one, you prefix them with backslash to get forced space).

The second solution is somewhat debatable, but the first should be a no-brainier.

**Comment by hgiesel** [comment]
For me backslash newline translates to nothing at all. I don't know how you get a forced space this way? For me a **backslash space** only translates to a forced space if there are more characters following. 

That said, I would very much prefer the second one. The first would make the latex input more compact than the asciidoc, which is supposed to be its main drawing point.

**Comment by dimztimz** [comment]
> I don't know how you get a forced space this way?

Actually I was testing without math support, the `:stem:` attribute at the begging. That way if I write backslash newline, in the output I see backslash space. With the attribute, backslash newline has no effect.

Basically, **backslash newline** has no effect too. It is not taken so it can safely be used as a newline indicator.

**Comment by dimztimz** [comment]
Ok did  some investigation, and the simplest way to implement this is in the converters. The following enables it for html5. One has to write for docbook too to complete it.

```diff
diff --git a/lib/asciidoctor/converter/html5.rb b/lib/asciidoctor/converter/html5.rb
index b24af465..7a1893a8 100644
--- a/lib/asciidoctor/converter/html5.rb
+++ b/lib/asciidoctor/converter/html5.rb
@@ -635,7 +635,15 @@ Your browser does not support the audio tag.
       title_element = node.title? ? %(<div class="title">#{node.title}</div>\n) : ''
       open, close = BLOCK_MATH_DELIMITERS[node.style.to_sym]
 
-      unless ((equation = node.content).start_with? open) && (equation.end_with? close)
+      equation = node.content
+
+      slash = @void_element_slash
+      br = %(<br#{slash}>)
+      if node.style == 'asciimath'
+        equation = equation.gsub(/(\R|\\)\R+/, %(#{close}#{br}#{open}))
+      end
+
+      unless (equation.start_with? open) && (equation.end_with? close)
         equation = %(#{open}#{equation}#{close})
       end
 
```

**Comment by mojavelinux** [comment]
I like both proposals. I like the double backslash because that matches LaTeX. I like the newline sequence because that matches AsciiDoc.

While we could consider the AsciiDoc line break (space followed by plus), I think that could get misinterpreted in this context, and it doesn't match LaTeX...which is the stronger correlation here.

I tried to see if I could split the equation in the parser instead of the converter. The problem is, there isn't really a way in the model to pass on a collection of equations and still have custom AsciiDoc substitutions be applied. Therefore, we'll have to stick with doing it in the converter for now (even if I don't love it). But we could also pull that up in the future.

**Comment by dimztimz** [comment]
Double backslash is valid asciimath http://asciimath.org/ look for backslash
setminus.

**Comment by mojavelinux** [comment]
Oh, I see. So are you saying we should look for a single backslash at the end of the line instead?

**Comment by dimztimz** [comment]
Yes, seems reasonable and it is not taken by asciimath.

**Comment by mojavelinux** [comment]
Got it. I'll update my PR.

**Comment by mojavelinux** [comment]
I wonder if we should do it the other way around. A `\` at the end of a line suppresses the newline, which would be treated literally if not escaped. wdyt?

**Comment by mojavelinux** [comment]
I've added a second commit to PR #2579 that preserves the line break *unless* it is escaped. I even preserve sequential line breaks so that you can add extra space in the equation. Let me know if you like this proposal.

**Comment by mojavelinux** [comment]
Thoughts about this proposal?

**Comment by elextr** [comment]
As a comment from the uninvolved, it seems the right way to do it in general, its common with many other apps.  Of course Latex and Asciimath disagree on the double backslash so its also good to avoid that "discussion" :)

**Comment by dimztimz** [comment]
I think that single new line was deliberately ignored by the asciimath parser in case that you have a long formula that you want to split in two input lines.

**Comment by mojavelinux** [comment]
> I think that single new line was deliberately ignored by the asciimath parser in case that you have a long formula that you want to split in two input lines.

Exactly. That's why I'm proposing that you must escape the endline with a backslash, exactly like you do in the terminal (and in the value of an AsciiDoc attribute entry).

**Comment by mojavelinux** [comment]
In other words, backslash at the end of the line means, "continue this line, I'm not done yet"

**Comment by dimztimz** [comment]
Personally, I find this backslash for continuation better because it has the same meaning as shell, python, make and many others.

But that way it is a backward compatibility breaking. It could be that people expected that single newline has no meaning, like when writing asciimath directly in html. One has to know how many people actually use asciimath blocks.

**Comment by dimztimz** [comment]
Lets try with examples. E.g. I want output to be hello world.

```
hello \
world

output: hello world
```

```
hello wo\
rld

output: hello world
```


```
hello wo \
rld

output: hello wo rld
```

In bash or make whenever I put backslash for continuation I put whitespace before it, and there that generally has no effect, but here it has.

**Comment by dimztimz** [comment]
My bad. Simple spaces have no meaning in asciimath, they have to be prefixed with \ to have meaning (to output space).

Thus we should analyze 3 cases, with examples. Just saw that asciimath has additional feature quoted text so that has to be taken into account. We should see which variant is most natural, and does not breaks expected/current functionality.

1. When there is no way to break.
2. When backslash newline breaks.
3. When simple newline breaks, and backslash newline continues.

I will post later, can't right now.

**Comment by mojavelinux** [comment]
> Simple spaces have no meaning in asciimath, they have to be prefixed with \ to have meaning (to output space).

That alone is enough to convince me that the right decision is to use \ in front of a newline to preserve it. While it would be nice to be consistent with AsciiDoc (or Bash), it's more important to be consistent within the same language. AsciiMath has established a strong meaning here for backslash, so we should build on that.

I'll update the PR.

Btw, since a space at the end of a line has no visual meaning, we don't have to worry about spaces in front of the backslash at the end of a line.

**Comment by mojavelinux** [comment]
PR updated.

Here's what we have now.

a) Newline not preserved

```
a
b
```

b) Newline preserved

```
a \
b
```

c) Repeating newlines preserved

```
a \
\
b
```

d) Double newline preserved

```
a

b
```

e) Repeating newlines preserved

```
a


b
```

The first newline is created by splitting the equation. Repeating newlines are preserved by using multiple `<br>` elements.

**Comment by mojavelinux** [comment]
Not that a paragraph-style break will appear as a paragraph break, not just a hard newline. I think that's logical.

**Comment by dimztimz** [comment]
Looks good, I like it this way.

**Comment by mojavelinux** [comment]
\o/
