### ISSUE TITLE
Asciidoctor parses include instructions in code blocks

### ISSUE THREAD

**Issue by sindzicat** [asciidoctor/asciidoctor#2499]
Hello!

My `test.adoc` file:

```
= Test doc
:nofooter:

....
test:

include::filename.adoc[]
....


[cols="2*^"]
|===

| Action
| How to

| Include file
|
....
include::filename.adoc[]
....

|===
```
Result:
![image](https://user-images.githubusercontent.com/33900895/33261896-7a3a38d6-d375-11e7-8f53-1ee0ed01603a.png)

It's strange, that asciidoctor parses `include` in code blocks.

OK, I try to find workarround. Just type `\` before `include`:

```
= Test doc
:nofooter:

....
test:

\include::filename.adoc[]
....


[cols="2*^"]
|===

| Action
| How to

| Include file
|
....
\include::filename.adoc[]
....

|===
```
Result:

![image](https://user-images.githubusercontent.com/33900895/33262008-d71e9358-d375-11e7-9157-b294cbc3a98a.png)

It seems, my workarround works only outside table.

Is this a bug?

Best regards,
Andrey.

**Comment by mojavelinux** [comment]
This is by design. Includes are predecessor directives. They are parsed before any of the structure of the document has been examined. There's no way to know at that time that the include is inside of a code block. Therefore, you must escape the directive using a backslash if you don't want it to be interpreted.

See http://asciidoctor.org/docs/user-manual/#include-directive for a statement about how (and more importantly, when) the include directive is processed.

**Comment by mojavelinux** [comment]
Your table example isn't working since you haven't marked the cell as an AsciiDoc table cell.

**Comment by sindzicat** [comment]
Interesting. Thank you very much, @mojavelinux!
I'm newbie yet at asciidocs. Sorry for the stupid question.
Now all works for me.

**Comment by mojavelinux** [comment]
:+1:
