### ISSUE TITLE
Attribute substitution does not work as expected in table's cols attribute

### ISSUE THREAD

**Issue by meznom** [asciidoctor/asciidoctor#2533]
When using an attribute inside the cols attribute of a table, more elaborate column definitions do not work as expected. Examples:

This "works":

```
:table-cols: .^15, .^52, .^15, .^18
[cols='{table-cols}', options="header"]
```

However, this does not "work":

```
:table-cols: .^15, .^52, >.^15, >.^18
[cols='{table-cols}', options="header"]
```

This does not "work" either (only difference is missing spaces):

```
:table-cols: .^15,.^52,.^15,.^18
[cols='{table-cols}', options="header"]
```

"Not working" here means that the column definition is not picked up by AsciiDoctor, i.e. in the "not working" cases we get a table with only one column (instead of four, as intended in the examples).

This is with Asciidoctor 1.5.6.1; same with Asciidoctor-PDF 1.5.0.alpha.16.

**Comment by mojavelinux** [comment]
The problem you're running into is that unexpected substitutions are being applied to the colspec value (namely the escaping of specialchars and superscript).

First, you need to disable substitutions from being applied to the value of the attribute entry since you want the value to be kept as is.

```
:table-cols: pass:[.^15, .^52, >.^15, >.^18]
```

Next, you need to make sure that the attribute reference is expanded, but no additional substitutions are applied:

```
[cols='pass:a[{table-cols}]']
```

Then it will work as expected. However, there's an even simpler way.

Attribute references are always expanded in the block attribute line. So you can simplify that line to:

```
[cols="{table-cols}"]
```
