### ISSUE TITLE
Nested items of a normal list item in a checklist are not indented further than the normal list item.

### ISSUE THREAD

**Issue by crocket** [asciidoctor/asciidoctor#2550]
```
* [ ] ABC
* [ ] BCD
* DEF
** ABC1
** BCD1
```

ABC1 and BCD1 should be indented further than DEF, but they are on the same level as DEF.

**Comment by mojavelinux** [comment]
We drop the indentation on the checklist to make room for the check boxes. I could see how that means that we have to compensate for a nested list so it goes back to its normal position.

**Comment by bzgec** [comment]
I have a similar problem, but I want to nest `Note_1` and `Note_2` under `Element_3`. So that `Note_1` and `Note_2` are indented under `Element_3`.

<img src="https://user-images.githubusercontent.com/34318921/116371342-9900b880-a80b-11eb-9c7f-e95b13307869.png" alt="image" width="200"/>

Do you have any plans to enable indentations for cases like this?

**Comment by mojavelinux** [comment]
I now understand the problem. The way in which the stylesheet is shifting the items in the checklist to make way for the checkbox is causing the nested blocks to lose the indentation (at least in part).

Here's a workaround you can add to your stylesheet:

```css
ul.checklist {
  margin-left: 1.5em;
}
ul.checklist > li > p:first-child {
  margin-left: -0.875em;
}
```

I'll go ahead and apply this to the default stylesheet for an upcoming release.

**Comment by crocket** [comment]
Bravo.
