### ISSUE TITLE
Error "only book doctypes can contain level 0 sections" reported too often

### ISSUE THREAD

**Issue by blueyed** [asciidoctor/asciidoctor#2572]
Given `t/t-asciidoctor.asciidoc`:
```asciidoc
[role='lead']
This is a demonstration of {library}. And this is the preamble of this document.

== First Steps with http://asciidoc.org[AsciiDoc]

=== Lists Upon Lists

= One
```

`asciidoctor t/t-asciidoctor.asciidoc` produces the same error 3 times - apparently related to the number of wrong sections above:
```
asciidoctor: ERROR: t-asciidoctor.asciidoc: line 8: only book doctypes can contain level 0 sections
asciidoctor: ERROR: t-asciidoctor.asciidoc: line 8: only book doctypes can contain level 0 sections
asciidoctor: ERROR: t-asciidoctor.asciidoc: line 8: only book doctypes can contain level 0 sections
```

```
Asciidoctor 1.5.6.1 [http://asciidoctor.org]
Runtime Environment (ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)
```

**Comment by mojavelinux** [comment]
Looks like we're thinking alike on this one. I checked my notes and found a TODO list item to file an issue about this. Since the parser can visit lines multiple times, it can sometimes end up reporting the same issue. I'll add a flag that it's already reported so we don't see the same message over and over.

**Comment by mojavelinux** [comment]
As it turns out, the warning was in the wrong place in the code. I've fixed it.
