### ISSUE TITLE
interpret include::file[] as include::file.adoc[]

### ISSUE THREAD

**Issue by janicesignalfx** [asciidoctor/asciidoctor#2616]
I realize that other types of files can be included, but it would be nice if include::file[] was treated as shorthand for include::file.adoc[] as that is the default file type most of the time.

This is a nice to have and lower priority for me than other requests I've made.

**Comment by mojavelinux** [comment]
I don't see this as an improvement. I say that because I think dropping the extension makes it the intent more obtuse for another writer. It's also because the include directive is used heavily for non-AsciiDoc files, so it makes even less sense to drop such an critical piece of information.

With Antora, we're beginning to advocate strongly for keeping the file extension in all cases, even in xrefs. Not only does being explicit make it more clear that it's a reference to another source file, it also allows tools to find the source file more easily (since they don't have to guess). (This is a change from my original position on this, which was to hide the file extension).

**Comment by elextr** [comment]
Agree with @mojavelinux and also point out that if no extension is specified the parser doesn't "guess", it has to try several things, no extension, `.adoc`, `.asciidoc` and backwards `.txt` at least.   This searching can be slow, particularly on remote filesystems.  And what if there are several of those, which does it pick?  Better to be explicit.

**Comment by janicesignalfx** [comment]
Okay, fair enough. I thought that .adoc was the defacto default for the majority of files with other extensions being significantly less common, but if that's not the case generally then I totally see why this would be a bad idea. I'll live with the irritation of the errors (maybe it'll make me remember the extension the first time more often :) )
