### ISSUE TITLE
Allow custom macro name to contain a hyphen

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#2620]
It would be useful to allow the use of a hyphen in a custom macro name (block or inline). If for no other reason, this would allow names to be namespaced (e.g, `acme-image`). The only way to do this currently is to use an underscore, but that feels less natural.

(Another idea would be to allow a forward slash, for example `acme/image`. But we can't use a colon as that symbol already has too strong of a meaning).

**Comment by elextr** [comment]
> The only way to do this currently is to use an underscore, but that feels less natural.

Would disagree that underscore feels less natural, its the standard idiom in many languages.  I guess it simply depends on your background.

**Comment by mojavelinux** [comment]
It's a fine way to separate words, but it's not conventional to use it as a namespace. If you have an example of where this is the case, I'd love to know about it.

**Comment by elextr** [comment]
Nearly every C library for starters, `xxx_blah()` is the usual approach to namespacing function `blah` in library `xxx` in C since it doesn't have real namespaces.  

Also all the macro and structure member symbols in the kernal API as well, for [example](https://linux.die.net/man/2/stat) where all the structure fields start with `st_` and the macros with `S_`. 

And see the set of Gnome namespaces [here](https://developer.gnome.org/references) each library has one, and boy aren't the GTK guys possessive of their single character `g_` namespace :)

Like I said it depends on your background.

Better if it was a real namespacing syntax something only for namespaces like the `::` syntax of C++ or the : of XML namespacing.

Then that would only be used for namespacing, rather than adding a character to macro names and hoping its use is restricted to namespacing by idiom, thats going down the same road as C.

Then a character like dash or backslash that is not legal in a macro name would be the right thing for the namespace separator.

I agree colon is already too used in Asciidoc, my count put it at 26 constructs based on colon :)

**Comment by mojavelinux** [comment]
Yep, the colon is definitely out of the question.

I see your point about the C usage.

What I'd conclude is that hyphen and underscore are both extremely popular to namespace something (hyphen used more often in filenames than functions, since functions don't allow underscore).

Since underscore is already possible, what we're talking about here is serving that other half-ish of people who reach for the hyphen to namespace...but find that the macro gets ignored. For me, that's very unexpected.

**Comment by elextr** [comment]
On the other hand, although your plans for Asciidoctor world domination are no doubt well advanced, I guess its unlikely that Asciidoctor custom macros will get to the ubiquity of C or similar libraries.  So maybe I'm worrying too much, and just C like prefixes are fine for that application and certainly just adding a character to the legal names is much simpler.

**Comment by mojavelinux** [comment]
I thought about two more reasons why a hyphen in a block macro name is consistent with the AsciiDoc syntax. First, the hyphen is a valid ID character, so it's often used in IDs. Second, it appears in several built-in AsciiDoc attribute names (e.g., `source-highlighter`). Given that this character appears so frequently in names in AsciiDoc, it feels oddly restrictive not to allow it in a block macro name too.
