### ISSUE TITLE
:doctype: book  is converting include:: to link:

### ISSUE THREAD

**Issue by blueray453** [asciidoctor/asciidoctor#2647]
I need to use ":doctype: book" but it is giving some problem.

```
= My Book
:doctype: book //<1>
:toc:
:toc-title: Table of Contents of {doctitle}
:toclevels: 1
:sectnums:
:sectnumlevels: 1
:imagesdir: _assets/images
:compat-mode!:

:leveloffset: +1

include::Hello World.adoc[]

include::Elements.adoc[]

include::Macros.adoc[]

:leveloffset: -1
```
**With the following Header the document looks like** 

```
My Book

link:Hello World.adoc[]

Elements.adoc

Macros.adoc
```

The TOC is not generated

**If i remove <1> it works as expected**

```
My Book

Table of Contents of My Book
1. Hello World
2. Elements
3. Macros

1. Hello World
....... The content works here

2. Elements
....... The content works here
.
.
.
```

What am I missing about ":doctype: book"?

**Comment by blueray453** [comment]
I actually compiled the main file with asciidoctor. 

`asciidoctor _Book.adoc`

**There is no problem with asciidoctor.** I am using AsciidocFX. The problem is there.

**Comment by mojavelinux** [comment]
If the include is becoming a link, then it means the safe mode is not being set properly (it must be unsafe, safe, or secure for an include to work). See https://asciidoctor.org/docs/user-manual/#running-asciidoctor-securely

Since this is an issue with AsciidocFX and not the core processor, I ask that you please file the issue there. See https://github.com/asciidocfx/AsciidocFX
