### ISSUE TITLE
Inconsistent behavior with {empty} and anchors/references?

### ISSUE THREAD

**Issue by mako4** [asciidoctor/asciidoctor#2659]
The general behavior of `{empty}` is that it will break up any command sequence patterns, like a line with `{empty}== H2` will not render a heading, `*{empty}*bold**`will render \***bold**\*, etc. 

However, `[[anchors]]` and `<<cross-references>>` are somehow not affected by this, and will still function even with an `{empty}` added (e.g. `[{empty}[a]]` or `<{empty}<ref>>`).

Is this intended behavior?

**Comment by mojavelinux** [comment]
Yes, this is intended behavior.

The examples you provided are all very different use cases.

In the first case (`{empty}== H2`), you are disrupting the backbone of the document structure, which is strict.

In the second case (`*{empty}*bold**`), you are relying on substitution order. The quote (i.e., formatting) substitution happens first, so the attribute reference disrupts the formatting pattern.

In the third case, (`[{empty}[a]]`), the substitution order does not influence the syntax since attribute substitutions happen before macro substitutions.

But the bottom line is, using an attribute reference is not the appropriate way to escape. Escaping should be done using the passthrough.

```
You can escape +**bold text**+ with a passthrough like this.

You can escape +[[anchors]]+ with a passthrough like this.

You can escape +<<ref>>+ with a passthrough like this.
```

The first case will continue to work just because it doesn't have to do with substitution order at all.
