### ISSUE TITLE
Allow ids to start with numbers?

### ISSUE THREAD

**Issue by neurocline** [asciidoctor/asciidoctor#2777]
Although it doesn't say this anywhere, Asciidoctor doesn't think IDs are allowed to start with numbers. The Asciidoc docs in section 21.1.2 just say "<id> is a unique string that conforms to the output markup's anchor syntax". However, the HTML spec says "Identifiers are arbitrary strings but must be unique within the HTML document".

To whit, if I have this as Asciidoc

```
[[X2018-05-01]]
= 2018-05-01

[[X1045]]
== 10:45
```

and run asciidoctor, I get this in the viewed HTML output

```
[[2018-05-01]] = 2018-05-01

[[1045]] == 10:45
```

indicating that the Asciidoctor parser didn't think `[[2018-05-01]]` is an id, but if I prefix my ids with `X` before converting, I get the HTML I expect (e.g. with `<h2>` and etc). Actually, it's more troubling that the subsequent title markup is not actually treated as a title but emitted as text; I'm assuming this is due to some issue with the regexes that Asciidoctor uses to parse the text with.

My Asciidoc files actually came from Pandoc, so for now this is a Pandoc bug. But I imagine the Pandoc folks, reading the Asciidoc spec, assumed they were making valid IDs.

Is there a reason why IDs can't start with numbers? I'm ok either way; these are internal idenfiers, after all. I just want to know what the long-term answer is.

**Comment by elextr** [comment]
For Docbook (which is XML) Ids indeed cannot start with digits.  

Its good that Asciidoc implementations limit IDs to the lowest common denominator to allow docs to be processed by all backends, but maybe the docs could make that clearer.

**Comment by mojavelinux** [comment]
The HTML spec is looser than the XML spec. Since AsciiDoc is designed to export to multiple formats, we must agree on a common denominator. So we disallow a number at the start of an ID in a block anchor.

If you want to use arbitrary characters in an ID, you can use the shorthand ID syntax, which is much more lenient (and designed for HTML output).

```
[#1045]
== 10:45
```

> it's more troubling that the subsequent title markup is not actually treated as a title but emitted as text

This is the correct behavior. If the line is not a valid block anchor line, which in the case you cited it isn't, then it's treated as normal text. Since the next line is adjacent to a normal line of text, it's also treated as a normal line of text. The processor does not try to detect close-to-but-not-quite-valid syntax. It only looks for valid syntax. (This is where a validator would come in).

> Asciidoc files actually came from Pandoc

I advise against using pandoc to create AsciiDoc because it does a very poor job. My recommended path is to convert to DocBook, then to AsciiDoc using [docbookrx](https://github.com/asciidoctor/docbookrx).

**Comment by neurocline** [comment]
OK, thanks for the feedback.
