### ISSUE TITLE
github gist asciidoc line break problem

### ISSUE THREAD

**Issue by lostdinar2** [asciidoctor/asciidoctor#2803]
Hello everyone. I have line break problem on my GitHub asciidoc documents.

> line1
> line2 
> line3

Still, render in one line on .asciidoc file.
In the past, there were issues that closed but not fixed.
https://github.com/github/markup/issues/78
https://github.com/github/markup/issues/108

(I can fix this by converting \n to \n\n. But solving the root of the problem is better. Any help aprreciated).Does this problem arise from github markup or asciidoc? :

**Comment by elextr** [comment]
Works for me.

Note that the links you have posted above are for Github, not Asciidoc.  Github manipulates the HTML it gets from markup languages, thats its problem.

**Comment by lostdinar2** [comment]
Thank elextr , Where do you render asciidoc files?

**Comment by elextr** [comment]
Asciidoctor

**Comment by mojavelinux** [comment]
You are describing the intended behavior of AsciiDoc. If you want hard lines breaks, you have to enable them. See https://asciidoctor.org/docs/user-manual/#line-breaks

**Comment by mojavelinux** [comment]
(this has nothing to do with GitHub).

**Comment by mojavelinux** [comment]
#108 is a seriously old issue and has long been resolved. I'm not exactly sure what the exact AsciiDoc is in this issue since it was presented in a Markdown quote block. But I suspect the question is about hard line breaks in prose, which has never been supported in AsciiDoc without an explicit option.

But just to be sure, I'll put a sample document up we can point to. See https://github.com/opendevise/asciidoc-samples/blob/master/hard-line-breaks.adoc

**Comment by elextr** [comment]
> But I suspect the question is about hard line breaks in prose

Oh, ok, @lostdinar2 should clarify then.

[PS the referenced `#108` is an issue in `github/markup` not Asciidoctor]

**Comment by mojavelinux** [comment]
I was referring to the issue in github/markup. GitHub just got overzealous with linking.
