### ISSUE TITLE
Option to render timestamp in footer as UTC offset instead of time zone name

### ISSUE THREAD

**Issue by stijnherreman** [asciidoctor/asciidoctor#2834]
Is it possible to add an option to have the timestamp in the footer render as an UTC offset, instead of a time zone name? Especially because in some cases, the time zone name is an uncommon variant: I had to look up "Romance Daylight Time" to find out that it's the same as the more common "Central European Summer Time (CEST)".

UTC offsets are just easier, all you need to remember is the offset for your own time zone. No need to look up the offset for some time zone halfway across the world.

**Comment by mojavelinux** [comment]
There's an ongoing discussion about switching to %z in a pending issue / pull request. See https://github.com/asciidoctor/asciidoctor/issues/2770#issuecomment-389432307

The only reason we output the timezone string is because that's what AsciiDoc Python does.

> I had to look up "Romance Daylight Time" to find out that it's the same as the more common "Central European Summer Time (CEST)".

For some strange reason, this is what Ruby does on Windows (and perhaps other OSes?). It's very atypical, but arguably it's a Ruby bug.

In the meantime, you can control what displays in the footer by passing it to the doctime attribute. (See https://asciidoctor.org/docs/user-manual/#env-attributes). For example:

    $ asciidoctor -a doctime=whenever document.adoc

**Comment by stijnherreman** [comment]
I looked into it a bit more. It's *probably* a Windows thing, with Romance Standard Time and Romance Daylight Time being Microsoft inventions: https://plus.google.com/+AndyBryant/posts/2FBpcbfAmJR

Should this issue be closed then, since it's a duplicate?

**Comment by mojavelinux** [comment]
You can leave it as is. I keep duplicates open for reference during development.

**Comment by mojavelinux** [comment]
You can also set the TZ environment variable when invoking Asciidoctor.

```
TZ=UTC asciidoctor input.adoc
```

This workaround is now mentioned in the User Manual.

> UTC offsets are just easier

Agreed. UTC offsets will be the normal behavior in 1.5.8.
