### ISSUE TITLE
Crash in substitution code in conversion

### ISSUE THREAD

**Issue by zelivans** [asciidoctor/asciidoctor#2882]
One of two bugs in `substitutors.rb` found with the fuzzer.

## Raw crash
```
/home/ariel/afl-kisaten/private/sandbox/asciidoctor/asciidoctor/lib/asciidoctor/substitutors.rb:350:in `block in restore_passthroughs': undefined method `[]' for nil:NilClass (NoMethodError)
	from /home/ariel/afl-kisaten/private/sandbox/asciidoctor/asciidoctor/lib/asciidoctor/substitutors.rb:347:in `gsub'
	from /home/ariel/afl-kisaten/private/sandbox/asciidoctor/asciidoctor/lib/asciidoctor/substitutors.rb:347:in `restore_passthroughs'
	from /home/ariel/afl-kisaten/private/sandbox/asciidoctor/asciidoctor/lib/asciidoctor/substitutors.rb:128:in `apply_subs'
	from /home/ariel/afl-kisaten/private/sandbox/asciidoctor/asciidoctor/lib/asciidoctor/block.rb:112:in `content'
	from /home/ariel/afl-kisaten/private/sandbox/asciidoctor/asciidoctor/lib/asciidoctor/converter/html5.rb:725:in `paragraph'
	from /home/ariel/afl-kisaten/private/sandbox/asciidoctor/asciidoctor/lib/asciidoctor/converter/base.rb:38:in `convert'
	from /home/ariel/afl-kisaten/private/sandbox/asciidoctor/asciidoctor/lib/asciidoctor/abstract_block.rb:75:in `convert'
	from /home/ariel/afl-kisaten/private/sandbox/asciidoctor/asciidoctor/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	from /home/ariel/afl-kisaten/private/sandbox/asciidoctor/asciidoctor/lib/asciidoctor/abstract_block.rb:84:in `map'
	from /home/ariel/afl-kisaten/private/sandbox/asciidoctor/asciidoctor/lib/asciidoctor/abstract_block.rb:84:in `content'
	from /home/ariel/afl-kisaten/private/sandbox/asciidoctor/asciidoctor/lib/asciidoctor/document.rb:1230:in `content'
	from /home/ariel/afl-kisaten/private/sandbox/asciidoctor/asciidoctor/lib/asciidoctor/converter/html5.rb:278:in `embedded'
	from /home/ariel/afl-kisaten/private/sandbox/asciidoctor/asciidoctor/lib/asciidoctor/converter/base.rb:38:in `convert'
	from /home/ariel/afl-kisaten/private/sandbox/asciidoctor/asciidoctor/lib/asciidoctor/document.rb:1162:in `convert'
	from tst.rb:6:in `<main>'
```

## Explanation

This crash is caused by an uncaught `NoMethodError` exception that is raised in the `restore_passthroughs` function when `passes[$1.to_i]` resolves to nil. I considered fixing with a naive check of `pass != nil` but I think in this case it is better if you find out the context of this bug and fix it appropriately.

It can be reproduced with the following input:
```
[']\+++++++++This++++++++++++
```

I also uploaded two of the original non-binary crash files my fuzzer produced, see [this gist](https://gist.github.com/zelivans/9d87bc4926cab1dd6e21692fd333ef98), different crash files might take a different path but all crash on this same line.

**Comment by mojavelinux** [comment]
The culprit is the following line:

https://github.com/asciidoctor/asciidoctor/blob/36e2a757dc12ed6e2df296f006e50aeff93c5e81/lib/asciidoctor/substitutors.rb#L358

The problem is that there can be nested calls to apply_subs via parse_attributes (if an attribute value is enclosed in single quotes). These calls to apply_subs cause the passthrough stack to be cleared. As a result, when an attempt is made to restore the passthroughs, it fails, often in unexpected ways.

One of two things needs to happen:

1. Don't allow parse_attributes to call apply_subs
1. Don't clear the passthrough stack after restoring passthroughs

I think (1) is the correct behavior since substitutions are already applied universally across the inline content.

**Comment by mojavelinux** [comment]
This is essentially the same bug as #2883, only it triggers a different error.
