### ISSUE TITLE
Starting line numbers not shown in docbook conversion

### ISSUE THREAD

**Issue by gilgamaze** [asciidoctor/asciidoctor#2915]
I apologize if this has previously been covered!

When I convert my asciidoc book to docbook, the starting line number of my code listings is not shown in the docbook output. The code listing specifies the language my asciidoc code is in, but not the line number.

Apart from hard-coding my docbook output, is there any way around this?

**Comment by mojavelinux** [comment]
Could you clarify what you mean when you say "starting line number". Do you mean line numbers in general, or do you mean that you specified a starting line and that isn't getting passed through?

Currently, AsciiDoc doesn't support a starting line number for source listings. But I do see that DocBook has a startinglinenumber attribute. So we could define a `start` attribute on the source block (much like on ordered lists), then map that value to the startinglinenumber attribute.

This is related to #1742. I'll keep this one separate since it pertains directly to DocBook.

**Comment by gilgamaze** [comment]
```
:source-highlighter: rouge
:rouge-style: pastie
= Chapter 2: Layout management

Layout management refers to the manner in which we position widgets on the application window. We can place our widgets using absolute positioning or with layout classes.

== Absolute positioning

The code below is contained in a file named _position.py_.

[source, python, linenums, start=15]
----
        label1 = QLabel(parent=self)
        label1.setText('Don\'t')
        label1.move(80, 50)

        label2 = QLabel(self)
        label2.setText('use')
        label2.move(90, 80)

        label3 = QLabel('this positioning technique in real life!',self)
        label3.move(100, 110)
----
```
When rendered as a pdf, I can get the starting line number(i.e a snippet of code from a certain file that starts at line no x) of the above code to show.

**Comment by mojavelinux** [comment]
I forgot that we had implemented that in Asciidoctor PDF. Thanks for reminding me. Then, by all means, we should support it for DocBook output, at the very least. I will proceed in doing so.
