### ISSUE TITLE
Add different types of tables | remove tableblock and other css classes

### ISSUE THREAD

**Issue by deftmaster** [asciidoctor/asciidoctor#2976]
Hello!

I am looking for an opportunity to redefine the css styles for the tables.

This sample will add a 'custom' class to class attribute.
I would like to have only one class 'custom' and remove 'tableblock' for selected tables.

[.custom]
.Title of table
|===
|Col A |Col B
|===

I'll get

table class="tableblock frame-all grid-all spread custom"

I would like to have such a table

table class="custom"

**Comment by mojavelinux** [comment]
If you want to modify the HTML that is generated, you can do so using a custom converter. Since the converter for tables is rather complex, I recommend the convert templates (as covered in https://github.com/asciidoctor/asciidoctor.org/issues/80).

As for what CSS classes are used by default, that's a discussion for #242.
