### ISSUE TITLE
Multiline stem block equations with latexmath

### ISSUE THREAD

**Issue by ZWMiller** [asciidoctor/asciidoctor#2981]
This should be a similar issue to #2497 

I'm attempting to write multi-line equations inside a stem block at present the stem block is pointed to latexmath at the top of the file like so: `:stem: latexmath`

Now I get to my equations and have tried all these variations:

```
[stem]
++++
blah-blah
yada-yada
++++
```

```
[stem]
++++
blah-blah\
yada-yada
++++
```

```
[stem]
++++
blah-blah \
yada-yada
++++
```

```
[stem]
++++
blah-blah \\
yada-yada
++++
```

```
[stem]
++++
blah-blah

yada-yada
++++
```

And all of them, when rendered to PDF using asciidoctor-pdf and asciidoctor-mathematical, result in 

```
blah-blahyada-yada
```

I'm not sure if I misunderstood the result in #2497 or if there's some breaking issue happening. 

I just updated to asciidoctor-1.5.8 to make sure I had the newest version as well.

**Comment by mojavelinux** [comment]
asciidoctor-pdf and asciidoctor-mathematical are different projects. Therefore, a similar change that was made in core must be made in those projects as well (likely just asciidoctor-mathematical) in order for this to work. Since this doesn't apply to core, I'm closing this issue. But I encourage you to reopen in the appropriate repository.
