### ISSUE TITLE
Callouts needs to be *after* special characters

### ISSUE THREAD

**Issue by nik9000** [asciidoctor/asciidoctor#2988]
It looks to me like `callouts` needs to be declared after `specialcharacters` or it won't work. For example, this doesn't make a callout:

```
[source,java,subs="callouts,specialcharacters"]
----
System.err.println("example"); // <1>
----
<1> thing
```

But this does:

```
[source,java,subs="specialcharacters,callouts"]
----
System.err.println("example"); // <1>
----
<1> thing
```

It is a bit counter-intuitive that the ordering of the substitution matters in the list.

**Comment by elextr** [comment]
Well, substitutions are what it says on the tin, one character sequence is substituted by another, and the fact that they are applied in order is stated [here](https://asciidoctor.org/docs/user-manual/#subs).  So a subsequent substitution can change the result of a previous substitution, for example a special character substitution can change `<` and `>` that are part of HTML generated by a previous substitution.  And thats why special characters are first by default.

This order dependency is an artefact of the current implementations, and IIUC is something thats potentially going to change when the implementation changes to fully parse the input before any substitutions are made.  In the meantime, allowing the order to be specified is a workaround to such side effects as you noted.

**Comment by mojavelinux** [comment]
I agree with @elextr that dependence on substitution order has always been a part of AsciiDoc and is core to how it works. While we may be able to define certain substitutions as being independent (this case in particular), other substitution lists only work because they follow a certain order.

I've stressed many, many times that you should almost never specify the substitution list explicitly, but rather use [incremental substitutions](https://asciidoctor.org/docs/user-manual/#incremental-substitutions). That's because it does give us the ability to rearrange them to match intent. In other words:

```
[source,java,subs="attributes+"]
----
System.err.println("{message}"); // <1>
----
<1> thing
```

But in the case you cited, why are you even specifying the subs? Both specialcharacters and callouts are already included in the substitutions for source blocks.

**Comment by nik9000** [comment]
Sorry for the late reply here.

My problem is that I have a ton of files that are essentially historical that I'd love to be able to build with asciidoctor instead of python asciidoc. I can't really modify my input files because many of them are historical. In some cases I suspect python asciidoc forced us into some of these modifications. In other cases we just did it out of ignorance.

I can certainly make folks *start* writing new files in the right way by logging warnings from asciidoctor if they do things wrong, but I can't do anything with those warnings if the files haven't been touched for years.

**Comment by mojavelinux** [comment]
In brief, it was a bug (in AsciiDoc Python) that those files ever worked correctly. The substitution order is very important, so the fact that AsciiDoc Python was accepting that order is incorrect.

The right thing to do is fix the source (either directly, using a patch, or using a tree processor). What the source is asking doesn't make any sense. If you apply specialcharacters after callouts, it will corrupt the callouts (since they contain special characters).

You can use a tree processor to rewrite the substitution list, so there's a very reasonable fix available.

**Comment by nik9000** [comment]
Indeed, I fix it with a tree preprocessor. Thanks!
