### ISSUE TITLE
Code in Tables Not Highlighted

### ISSUE THREAD

**Issue by tajmone** [asciidoctor/asciidoctor#2990]
I'm working on an AsciiDoc document which uses Highlight as an external syntax highlighter (via the [Highlight Treeprocessor Extension]). Code block in the main document are being highlighted fine, but blocks inside tables not.

I have some tables with a column set as ADoc (`[cols="<1m,<6a"]`) and some cells in that column contain code blocks. Although in the final HTML document the block is correctly shown as a code block, with the proper language, nevertheless the code is not highlighted.

For some reason, it seems that code blocks inside tables are being ignored by the Treeprocessor extension.

Is it an Asciidoctor bug? or is it just a problem with the Highlight Treeprocessor Extension?

[Highlight Treeprocessor Extension]: https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/lib/highlight-treeprocessor.rb

**Comment by mojavelinux** [comment]
Tree processors do not get called separately for AsciiDoc table cells. It's up to the extension to descend into the table, find the AsciiDoc table cells, and descend into those.

You can use the mathematical extension as a reference. See https://github.com/asciidoctor/asciidoctor-mathematical/blob/master/lib/asciidoctor-mathematical/extension.rb#L45-L59

This is something we need to make easier in Asciidoctor, but that's a separate issue.

**Comment by tajmone** [comment]
Thanks for the clarification.

Would this also affect code blocks inside admonitions?

> This is something we need to make easier in Asciidoctor...

Indeed, it would make sense that source code is treated the same in respect to syntax highlighting, regardless of whether it appears in the main body of text or inside tables, admonitions, etc.

**Comment by mojavelinux** [comment]
Asciidoctor 2.0 introduces a new API for registering a syntax highlighter adapter. I recommend that you use this for your highlight extension. Here's an example:

https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/syntax_highlighter/coderay.rb

Instead of having to find nodes in a tree processor extension, the adapter gets called by the processor to highlight the relevant nodes, contribution markup to the output, and write a custom stylesheet.

You can find the API docs here: https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/syntax_highlighter.rb

I look forward to your feedback.

**Comment by mojavelinux** [comment]
> Would this also affect code blocks inside admonitions?

To answer your question, no. Although admonition blocks are laid out using tables, they are not themselves table nodes.

**Comment by mojavelinux** [comment]
Please open a new issue if you have follow-up questions or feedback.
