### ISSUE TITLE
Some attributes don't apply to content

### ISSUE THREAD

**Issue by nik9000** [asciidoctor/asciidoctor#2993]
Attributes defined in a block look like they are only used in headers. Have a look at this:

```
$ cat bad.asciidoc 
:inheader: foo

= Test

--
:outheader: bar
--

[id="{inheader}-{outheader}"]
== Header

<<{inheader}-{outheader}>>
$ asciidoctor -v bad.asciidoc
asciidoctor: WARNING: invalid reference: foo-{outheader}
$ grep foo- bad.html 
<h2 id="foo-bar">Header</h2>
<p><a href="#foo-{outheader}">[foo-{outheader}]</a></p>
```

It looks like attributes defined inside blocks are applied to the section ids but are not applied to the contents. This is unexpected and incompatible with python asciidoc which applies the attributes to both the section ids and the contents.

**Comment by mojavelinux** [comment]
The problem is the open block has no other content other than the attribute entry. In that scenario, Asciidoctor will ignore the attribute entry (since it has nothing to attach it to). That's a nuance of how Asciidoctor stores attribute entries during processing. As long as they have a place to land, they will be used. Try adding `{blank}` under the `outheader` entry.

**Comment by mojavelinux** [comment]
There's no reason to enclose the attribute entries in the open block. Is there are reason you are doing that?

**Comment by nik9000** [comment]
> There's no reason to enclose the attribute entries in the open block. Is there are reason you are doing that?

AsciiDoc was having a ton of trouble parsing these without the block. Once I switch entirely to Asciidoctor I can drop the block.

**Comment by mojavelinux** [comment]
So it's not really an Asciidoctor issue, then.

**Comment by nik9000** [comment]
> So it's not really an Asciidoctor issue, then.

I get that you don't want to be compatible with AsciiDoc when AsciiDoc is doing something weird but in this case I'm not particularly sure why Asciidoctor behaves differently. I can and have worked around it though.

**Comment by mojavelinux** [comment]
I've already explained why Asciidoctor is different from AsciiDoc Python in this case. Document attributes defined in the body get attached to the next block of content. If there is no next block, there is no where to attach the attributes and thus they get dropped. But I still don't see why you would have to be wrapping the attribute entries in a block anyway. They should work fine without wrapping them.

There are tons of reasons why parsing behavior in Asciidoctor and AsciiDoc differ because AsciiDoc Python stream parses whereas Asciidoctor parses to a model. I've worked hard to minimize these differences, but that doesn't change the fact that the strategy is different.
