### ISSUE TITLE
Assume any shorthand interdocument xref is a source-to-source reference

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#3021]
Always assume the target of a shorthand interdocument xref (e.g., `<<asciidoctor.1#,asciidoctor>>` is a reference to another source document (thus inferring an implicit AsciiDoc extension), regardless of what file extension is present on the target. This means the processor will append the value of the outfilesuffix attribute (after stripping any known AsciiDoc file extension) (e.g., `href="asciidoctor.1.html"`).

This was the behavior of Asciidoctor < 1.5.7. However, the documentation about how non-AsciiDoc, non-empty file extensions are handled in this scenario was unclear before and after the change. Additionally, the previous behavior can be safely restored without affecting other use cases.

It's important to emphasize that, with this change, the behavior of the shorthand xref will further deviate from the behavior of the formal xref (e.g., `xref:asciidoctor.1.adoc[asciidoctor]`). The formal xref only recognizes the target as another source document if the target ends in the file extension `.adoc`. For all other extensions, the file extension of the target is left as is (meaning the outfilesuffix is not appended).

**Comment by mojavelinux** [comment]
I'd also like to point out that the use of the shorthand xref to make a source-to-source reference without an AsciiDoc file extension should be considered deprecated. If the target is an AsciiDoc file, then the target should contain that file extension (e.g., `<<asciidoctor.1.adoc,asciidoctor>>`. So while this change is being made for compatibility reasons, it's still not the recommended syntax. The documentation should be updated to call attention to this point.

**Comment by mojavelinux** [comment]
cc: @gdamore

**Comment by gdamore** [comment]
I'm of mixed minds about even doing this.  Deprecating it at least  seems wise.  The legacy usage was already broken, so bring it back may be helpful -- the questions in mind about this are:

a) Was anyone else affected by the lost behavior, or just me?  (If just me, then I can adapt, it's kind of painful, but at the same time, I can make the chance once and then forget about it.)

b) Spending cycles to restore the behavior, vs. cycles spent more usefully elsewhere.

c) Does persisting the old behavior create a promise & associated tech debt.  At a 2.0.0 release it would make sense to *drop* legacy undesirable behaviors IMO.

e) Time to v2.0.0 delivery -- if this is going into v2.0.0, but not in any earlier release, how long do I have to wait? (Basically I need a fix pretty soon, or else I need to fix my nonconforming documents.  I have control over the latter, but you have control over the former.  If I'm the only consumer, once I do the latter, then the issue is moot IMO.)

(Now conversely, if you were to restore the existing behavior in a 1.5.9 and then drop it in 2.0.0 -- with advance warning -- that *might* make sense.  But again, if I'm the only one affected by this, then it isn't worth the effort, and doing a special release for this or other fixes would only make sense if v2.0.0 was a bit further off.)

**Comment by mojavelinux** [comment]
> if this is going into v2.0.0, but not in any earlier release, how long do I have to wait

There's no earlier release than v2.0.0. I have v2.0.0 scheduled for Jan 31, but I really want it out earlier than that. But that's definitely a hard deadline.

> Does persisting the old behavior create a promise & associated tech debt.

I'm going to give it some more thought, but after having reviewed the code, I now believe that restoring the behavior actually makes it more consistent. It actually encourages the use of the formal xref macro for inter-document cross references (still optional), which is the outcome I want.

I'm going to give it a bit more thought and will report those findings here.

**Comment by mojavelinux** [comment]
I've given this quite a bit more thought. Given the colorful history of this syntax and some ambiguity both in the documentation and implementation, any change requires a careful and measured approach. With that in mind, I have an updated proposal.

When using the xref shorthand (i.e., the angled bracket syntax), we'll enforce the following assumptions:

* the target is promoted to an inter-document xref if `#` is present
* if a known AsciiDoc extension is present, it will be replaced with the value of the relfilesuffix attribute
* the inter-document target is assumed to be another AsciiDoc document (i.e., source-to-source)

The shorthand xref will be translated into an href as follows:

| xref | href |
| ---- | ---- |
| <<name#>> | name.html |
| <<name.adoc#>> | name.html  |
| <<name.1#>> | name.1.html |
| <<name.1.adoc#>> | name.1.html |

This matches the pre-1.5.7 behavior. The preferred syntax, however, is to include the explicit .adoc extension (rows 2 and 4).

It's not possible to make an xref to a non-AsciiDoc document using the shorthand xref. This is for historical reasons, but also because we don't want the shorthand xref to be used for this purpose.

The behavior of the xref macro will be slightly different. That's because it's designed primarily to support inter-document as well as inter-resource references.

When using the xref shorthand (i.e., the angled bracket syntax), we'll enforce the following three assumptions:

* the target is promoted to an inter-document xref if `#` is present **or** `.` is present (the latter being the start of a file extension)
* if the .adoc extension is present, it will be replaced with the value of the relfilesuffix attribute; **otherwise, the file extension will be preserved**
* the inter-document target is **not** assumed to be another AsciiDoc document

The xref macro will be translated into an href as follows:

| xref | href |
| ---- | ---- |
| xref:name#[] | name  |
| xref:name[] | #name |
| xref:name.adoc#[] | name.html |
| xref:name.adoc[] | name.html |
| xref:name.1#[] | name.1 |
| xref:name.1[] | name.1 |
| xref:name.pdf#[] | name.pdf |
| xref:name.pdf[] | name.pdf |
| xref:using-.net-services[] | using-.net-services |
| xref:#using-.net-services[] | #using-.net-services |

In general, the xref macro behaves more like you'd expect, while the shorthand xref is a little more presumptuous. But I think that's okay, because the xref macro is preferred for making inter-document and inter-resource xrefs, whereas the shorthand macro is primarily intended for jumping to an anchor.

The one tricky edge cases in the xref macro is when the ID has a dot (e.g., `using-.net-services`). In this case, it's necessary to add a leading `#` to explicitly tell the processor the target should be interpreted as a fragment and not a path.

Despite the length of this proposal, the behavior isn't actually changing that much. We're really just clarifying how it works. The main difference is that we'll revert to the pre-1.5.7 behavior if the target of the shorthand inter-document xref has a file extension (e.g., `<<name.1#>>`. We're also allowing the target of an xref macro to have any file extension (aka an inter-resource reference) (e.g., `xref:name.pdf[]`).

p.s. I'm open to discussing how `xref:name#[]` should be interpreted. Should we assume that's a source-to-source reference, or a reference to an extensionless resource?

**Comment by gdamore** [comment]
What about an interdoc reference using a fragment … e.g. xref:otherfile.adoc#section[Section Title] -- will that work as one would expect?

**Comment by mojavelinux** [comment]
Of course.

**Comment by jirutka** [comment]
> p.s. I'm open to discussing how xref:name#[] should be interpreted. Should we assume that's a source-to-source reference, or a reference to an extensionless resource?

Asciidoctor 1.5.x converts `xref:name#[]` to href `name.html` (when out `outfilesuffix` is `.html`). Now it’s converted to `name`. This is a very serious **breaking change** for me. I have thousands of documents that will be converted incorrectly in Asciidoctor 2.0+.

I very much welcome changing `xref:name.adoc[]` to `name.html` instead of `#name.adoc`, but changing `xref:name#[]` to `name` doesn’t make any sense to me, just breaks compatibility.

**Comment by mojavelinux** [comment]
It's important to acknowledge that no matter what move we made, it was going to break some documents because, throughout time, we've supported behaviors that are, by their nature, mutually exclusive. In light of that, my goal was to break **as few** documents as possible. We may need to consider a different compromise that lives up to this goal. I can think of at least one possible path forward.

Please open a new issue for this so that we can address it properly. I'll certainly consider it for the 2.0.x release line.
