### ISSUE TITLE
Dots in square brackets - inconsistent logic

### ISSUE THREAD

**Issue by john-cj** [asciidoctor/asciidoctor#3031]
I'm not sure is it a bug or not, but if you add dot in `[class1]`, the list will not be properly styled.

Likewise, if you remove dot in `[class2]` it will break CSS in the same way. (Well, I like dots, actually.)

Why so magic?

```
[class1]
* list item
* list item

[.class2]
red text

++++
<style>
.class1 { list-style: none; }
.class2 { color: red; }
</style>
++++
```

**Comment by mojavelinux** [comment]
The first positional attribute value with and without a dot are two very different things. The leading dot is a shorthand notation for the role attribute value, inspired by the syntax for a CSS class selector (e.g., `.rolename`) (a syntax also adopted by many template languages such as Slim, Haml, and Pug).

When the dot is absent, the value is the block style (aka type). In the case of lists, the style controls which marker is applied to the list items.

Thus, for lists, you can control the marker using the block style, as in:

```
[square]
* one
* two
* three
```

Or you can give the list a role (aka a CSS class name) and thus use the default marker:

```
[.colorful]
* one
* two
* three
```

Or you can do both:

```
[square.colorful]
* one
* two
* three
```

That's equivalent to:

```
[square,role=colorful]
* one
* two
* three
```

The following from your example is an illegal block style:

```
[class1]
```

For more details about this shorthand syntax, see https://asciidoctor.org/docs/user-manual/#block-assignment-2.

> Why so magick?

It's not magic. It's brevity. If you don't like it, you can write the role using a long-hand attribute assignment (e.g., `role=rolename`).

**Comment by john-cj** [comment]
Well, I don't want to waste your time (because I believe as project lead you have more interesting things to do), but some things are still unclear.

In the case of list: dotted syntax adds class to parent div, whereas dotless syntax adds class to parent div *and* element itself. 

```
[.class1]                  | [class1]
* list item                | * list item
* list item                | * list item

                        will be:

<div class="ulist class1"> | <div class="ulist class1">
<ul>                       | <ul class="class1">
<li>                       | <li>
<p>list item</p>           | <p>list item</p>
</li>                      | </li>
<li>                       | <li>
<p>list item</p>           | <p>list item</p>
</li>                      | </li>
</ul>                      | </ul>
</div>                     | </div>
```

However,

In the case of regular paragraph: dotless syntax, for some non-understandable for me reason, doesn't intended to work.

```
[.class2]                      | [class2]
red text                       | red text

                            will be:

<div class="paragraph class2"> | <div class="paragraph">
<p>red text</p>                | <p>red text</p>
</div>                         | </div>
                               |
                               | AsciiDoctor warning:
                               | "Invalid style for
                               | paragraph: class2"
                               |
                               | Expected:
                               |
                               | <div class="paragraph class2">
                               | <p class="class2">red text</p>
                               | </div>
```

**Comment by mojavelinux** [comment]
Since every block element can have a title, Asciidoctor always adds the roles as classes on the enclosing div. This allows both the content and the title to be styled (and CSS supports addressing each component of the block individually). (The placement of the class for the role is something we can revisit as part of #242).

The block style for lists also gets added directly to the list element to make it more compatible with CSS frameworks (like the one used for the default stylesheet) and in environments where the stylesheet is not available. That's really more of an internal class.

The behavior is consistent within the constraints we have. But, as I suggested, the placement of classes is something we can revisit as part of #242 (which will get it's own stylesheet).

**Comment by mojavelinux** [comment]
To given a example, a paragraph can have a title. Consider:

```
[.rolename]
.Title of paragraph
Content of paragraph
```

produces:

```
<div class="paragraph rolename">
<div class="title">Title of paragraph</div>
<p>Content of paragraph</p>
</div>
```

As you can see, the placement of the role makes it possible to style both the title and the paragraph. That's why it's not added directly to the paragraph element.

You can find a proposal for a new way of doing it that avoids the div wrapper in #242. The current HTML5 converter is not going to change (for compatibility reasons). But the new converter gives us room to reevaluate and innovate.

**Comment by john-cj** [comment]
Oh, thank you very much. Very detailed explanation, and now I understand. So, I close this issue.

**Comment by mojavelinux** [comment]
:+1:

If you're interested, I await your participation and input as we get #242 underway (post Asciidoctor 2.0.0).
