### ISSUE TITLE
Don't distribute the test suite in the gem

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#3044]
As the number of tests grow, so does the size of the gem. But it's unlikely anyone is installing the gem to get access to the tests. The tests are always available in the repository under the tag from which the gem is built. And it includes the other materials necessary to run the test suite. So there's no reason to be bundling these files.

**Comment by mojavelinux** [comment]
@aerostitch Is this going to cause a problem for the Debian package? Can you get the tar.gz from GitHub instead?

cc: @Mogztter

**Comment by aerostitch** [comment]
If I don't have the tests in the gem I would have to switch to the .tar.gz in github, yes and that means totally re-doing the way the packaging is done on the Debian side as it's going to be different tools to handle them, so thanks for the heads up.
Let me know when you've release the version without tests and I'll change the packaging.

**Comment by mojavelinux** [comment]
Hmm. We don't have to make this change. Do you think it's the wrong move? Would it over-complicate things on your side? Do other gems you've worked with distribute the test suite? My understanding is that most don't.

**Comment by aerostitch** [comment]
The few ones I've worked with in the past did.
I'm not sure how it's handled in other distros like fedora, but if size is really a problem for your gems, I don't really see another way to do it.
I can see other ruby Debian packages having to use the github releases tarballs because the tests are not there, it's really a mix. The change should only take me a few hours, so it's really up to you.

**Comment by aerostitch** [comment]
To be honest, I'm totally fine working from the tarball directly, so I'd say go ahead with that change, it's not a really big deal on my side. I just need to remember to change the source (and do the related changes) when packaging the next version.
It is indeed cleaner for almost everybody to not have to download the extra files needed by the tests.

**Comment by mojavelinux** [comment]
Awesome. Then we'll plan for this to be part of the 2.0.0 release (which is in progress). That's easy to remember too ;)

**Comment by mojavelinux** [comment]
It's done. As I mentioned, plan for this change starting with 2.0.0.

**Comment by tmzullinger** [comment]
As an addendum, the Fedora packages do use the gem file.  When I looked at updating to 2.0.0 just now I stumbled on the lack of the test dir in the gem.

I don't regularly package ruby bits anymore (not since my days maintaining puppet, which predates most of the Fedora Ruby packaging guidelines), so I'll have to read the guidelines about how to best handle this.  I could simply prepare a tarball of the test dir, similar to what was done in [62c46b2 ("Fix FTBFS.", 2017-06-05)](https://src.fedoraproject.org/rpms/rubygem-asciidoctor/c/62c46b).  I'll only do that if using a tarball of the full source is more tedious though.

**Comment by mojavelinux** [comment]
Since none of the files get compiled or move around, I would recommend just building the RPM from the tarball pulled from the tag (https://github.com/asciidoctor/asciidoctor/archive/v2.0.0.tar.gz). That's actually better anyway for Fedora policy (I would think) because it's the full source.
