### ISSUE TITLE
Code block in the start of quote block breaks the parsing

### ISSUE THREAD

**Issue by john-cj** [asciidoctor/asciidoctor#3060]
Tested on Asciidoctor 1.5.8, looks like a bug.

When we have code block placed directly after opening of the quote block, the rendering isn't correct. Here is an example:

```
WARNING: asciidocbug.adoc: line 9: unterminated quote block
```

```
text

____
----
code
----

text
____

text
```

As a workaround I use `{blank}`:

```
____
{blank}
----
code
----

text
____
```

**Comment by mojavelinux** [comment]
This is true for any delimited block that uses the same delimiter as a two-line section title when it's placed directly inside of a quote block (even a blank line would fix it).

The problem is that the underscores look like the text of a section title and the delimited block the section underline. In other words, this is what the parser sees:

```
____
----
```

(This is one of the many reasons I really dislike two-line section titles...they are a hazard for parsing).

We might be able to detect this situation and bypass the two-line section title logic in this case.

**Comment by mojavelinux** [comment]
Another workaround is to increase the length of the quote block delimiter:

```
______
----
source code
----

paragraph text
______
```

**Comment by mojavelinux** [comment]
Aha! This is actually an easy fix. The regular expression for an setext title is wrong. It should be requiring at least one alphanumeric character when it is only enforcing that there is at least one word character. An underscore is a word character, so four underscores is slipping through. I'm glad this was caught before 2.0!
