### ISSUE TITLE
Inter-document references with relative pathes in includes

### ISSUE THREAD

**Issue by lennartfricke** [asciidoctor/asciidoctor#3070]
Using an inter-document reference starting with ../ in an included files
interprets the inter-document path as relative to the including/root file.

Here is a gist illustrating the situation
https://gist.github.com/lennartfricke/6f37913777e16fb93d98c21490f8572d

I do not know if this is expected behavior but struggled with it.
I'd be happy if you tell me if the current behavior is intended or not. Thank you

**Comment by elextr** [comment]
https://asciidoctor.org/docs/user-manual/#include-resolution says its intended.

**Comment by lennartfricke** [comment]
As in the gist, I refer to the `xref:../b/b#anchor[]` in file `a/a.adoc`, that I expected to generate a link to section "B".

Moreover if I write `include::c.adoc` in file `a/a.adoc` to include `a/c.adoc`, the includes are resolved just fine. That seems opposite to what the documentation, you linked, says.

For illustration purposes I add `c.adoc` and a README.md (clarifying the folder structure)  to the gist .

**Comment by elextr** [comment]
> Moreover if I write `include::c.adoc` in file `a/a.adoc` to include `a/c.adoc`, the includes are resolved just fine. That seems opposite to what the documentation, you linked, says.

It seems to me to be exactly the same.

It says "If the include directive is used in a file that has itself been included, the path is resolved relative to the including (i.e., current) file."  so including `c.adoc` inside `a.adoc` looks for `c.adoc` in the directory containing `a.adoc`, which is what you said happened.

The link is something completely different, I'm not sure they work the same in github rendering as they do in the "real world".  Also I remember something about changing that for version 2.0.0 @mojavelinux ?

**Comment by mojavelinux** [comment]
There's no relationship between the include directive and paths, aside from how the include directive itself works. How I like to describe it is that you have to consider what the AsciiDoc file looks like once all the includes have been dumped into the current document. Flattened. That's what the parser works on. A stream of lines.

We've spoken many times about the need for a subdocument macro that would change the directory context of the content (so that xrefs could be relative to the current document). Please search the issue tracker for that term to uncover those discussions.

**Comment by lennartfricke** [comment]
Thank you very much for your insight.
So I'll consider this issue closed, as there are more issues around the subdocument idea.
