### ISSUE TITLE
Striped tables: are they really good as default?

### ISSUE THREAD

**Issue by john-cj** [asciidoctor/asciidoctor#3110]
I know, someone could say that it's very personal preference (and it will be correct), but I'm sure that it's better to have stripes disabled by default.

There were some researches about striped tables, and they show that about 50% people doesn't find them useful - but distracting. Also, there was the same research in notable Edward Tufte books, where he criticize striped tables.

It's not problem for me to use "stripes=none" each time (or custom CSS), though. So this issue isn't really an issue - just something, what I feel right to be said.

**Comment by mojavelinux** [comment]
I'm inclined to agree. This wasn't originally something you could configure. We then added the option without changing the default behavior. But you're correct that the striping should be something you add, not take away. Since we're about to do a major release, this would be a good time to make this switch.

**Comment by mojavelinux** [comment]
While we're at it, we might as well add the hover option for stripes [like in Bootstrap](https://getbootstrap.com/docs/4.3/content/tables/#hoverable-rows).
