### ISSUE TITLE
Automatic partintro conflicts with docbook titleabbrev

### ISSUE THREAD

**Issue by nik9000** [asciidoctor/asciidoctor#3132]
We have a few things that look like:
```
= Some big funky title that looks good here but isn't good in the toc
+++++
<titleabbrev>Short title</titleabbrev>
+++++
```

These work fine in AsciiDoc because not in Asciidoctor. It looks like the trouble is that Asciidoctor [automatically](https://github.com/asciidoctor/asciidoctor/commit/73ba91b74b4176920b2f59f427097af30a175d84) styles children of a chapter as `partintro` in lots of cases which is super helpful for normal content but breaks our attempt to set a `titleabbrev`.

Is this something that Asciidoctor should work around somehow? Can it already do it and I'm just not seeing it? Should I make a plugin to fix this? It isn't a particularly common need, I expect. But this strategy works fine for Chapters so it feels weird that I'd have to do something "special" at this level.

**Comment by mojavelinux** [comment]
I strongly recommend against embedding DocBook tags directly into AsciiDoc. That's a bad practice because it couples the document to the output format (hence eroding the portability of the document) and clutters up the document. It would be far better to define a dedicated attribute, then use that attribute in a custom converter or output template.

```
= Some big funky title that looks good here but isn't good in the toc
:titleabbrev: Short title
```

The problem with looking for passthrough content to skip is that it would require making assumptions about the document. Now, instead of there being a single partintro block, that node would now have a sibling which the converter would have to deal with. It's a slippery slope to go down.

**Comment by nik9000** [comment]
I'm not particularly happy about the coupling either. I'll see about migrating to a custom converter. Thanks.

**Comment by mojavelinux** [comment]
> I'll see about migrating to a custom converter.

Keep in mind creating a custom converter is going to be super easy in 2.0.
