### ISSUE TITLE
xref:name#[] is not interpreted as source-to-source reference since 2.x

### ISSUE THREAD

**Issue by jirutka** [asciidoctor/asciidoctor#3231]
Asciidoctor 1.5.x converts `xref:name#[]` to href `name.html` (when out `outfilesuffix` is `.html`). Now it’s converted to `name`. This is a very serious **breaking change** for me and I don’t even see any reason for it. I have thousands of documents that will be converted incorrectly in Asciidoctor 2.0+.

Related to #3021

**Comment by mojavelinux** [comment]
I think a reasonable compromise would be to assume the path is an AsciiDoc rootname (the filename minus the file extension) if the target ends with `#` and the path does not contain a period. The only thing this logic would block is using the xref macro to link to a file that has no file extension at all. But there are other ways of handling that edge case...if we even want to support it.

If a period is present in the path, no matter what, we make no assumptions.

Does that seem correct?

The focus here is on preserving backwards compatibility with something we once offered (e.g., `xref:name#[]`). That scenario should still be considered deprecated because it's depends on too much magic.

**Comment by jirutka** [comment]
>...and the path does not contain a period (e.g., name#).

So `xref:path.to/name#[]` would not be considered as source-to-source reference? That would be very counter-intuitive. Also I don't see any reason for such arbitrary limitation. Why not just consider period in the file name part (i.e. no assumptions for `xref:path/to/name.ext`)?

**Comment by mojavelinux** [comment]
I should have clarified. We're only talking about the dot in the final path segment (the logic of File.extname).

**Comment by mojavelinux** [comment]
I think that means we have the same understanding.

**Comment by jirutka** [comment]
> I think that means we have the same understanding.

Yes.

**Comment by mojavelinux** [comment]
Great. I'll proceed with a PR so that we can review the code change.

**Comment by mojavelinux** [comment]
PR is up. It was really as simple as adding an elsif condition to handle the case.
