### ISSUE TITLE
Issue with square brackets within inline macro

### ISSUE THREAD

**Issue by 0xDiddi** [asciidoctor/asciidoctor#3251]
I am on macOS mojave 10.14.4, using ruby 2.3.7p456 and have tested this with asciidoctor 1.5.8 as well as 2.0.6 (the latest as of writing this).

See [this gist](https://gist.github.com/0xDiddi/6d233b6dde2b340fd7bf940afd3465fc) for the asciidoc source, asciidoctor extension used and the output I got.

The first example you see in the gist is just for reference.

The second one shows how it *is* possible to get square brackets into an inline macro (in this case a footnote), by escaping only the closing inner bracket.

The third case shows the failure state: when not escaping the inner closing bracket, it is interpreted to close the footnote, with the rest of what is intended to be the footnote remaining in the paragraph.

The fourth case has a result similar to the third case, but highlights a problem: the problematic closing bracket is inserted by a nested macro. The issue here is that there is no way for the nested macro to do it right: if it doesn't escape the bracket, we get the broken footnote. But while it works inside the footnote when the macro escapes the bracket (see example 5), now there's an extra backslash when using it outside of a macro (example 6).

----

As nested macros work just fine, I assume that asciidoctor counts brackets when it detects that they are part of a macro. Thus I suggest to do the bracket counting even when no nested macros were found.

I also suggest to make that opt-in (maybe a document attribute), as requiring all square brackets to be matched may break existing stuff.

EDIT: what may also work as a fix would be to handle escaping outside of macros as well, so that nested macros can safely escape any closing square brackets they insert, without worrying about whether they'll be used inside or outside of a macro.

**Comment by mojavelinux** [comment]
What you're observing is known issue with AsciiDoc parsing that traces back to AsciiDoc Python. Neither processor works in the way you're describing. Rather, each macro is substituted independently in serial. Therefore, if a custom macro outputs square brackets, it must be sure to do so in a way that won't interfere with subsequent substitutions. The best solution here would be to output the closing square bracket as `&#93;` (and perhaps do the same with the opening square bracket).

The other way to work around this would be to surround the footnote text in passthrough marks:

    4 aaa footnote:[pass:m[bbb macro:[\] ddd]] eee

This cannot be resolved in a cleaner way until #61. That's currently being held up because it will affect compliance and thus must be dealt with at a language design level first.
