### ISSUE TITLE
Grid overlaps the text using a pass block in a table

### ISSUE THREAD

**Issue by jjoslet** [asciidoctor/asciidoctor#3256]
Affect versions after 1.5.6.

Since the fix for https://github.com/asciidoctor/asciidoctor/issues/2568, the following snippet does not render properly.
```
[grid="all",cols="1a"]
|===
|
++++
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam rhoncus pulvinar enim ut sollicitudin. Aliquam at urna hendrerit, interdum nisi vitae, faucibus elit. Aenean feugiat augue a nunc bibendum, ultrices faucibus velit pretium. Integer lacus augue, sodales eget erat eget, dictum sodales sem. Suspendisse molestie ipsum ligula, ut pretium dolor blandit vitae. Cras at posuere nisi, sed condimentum elit. Cras suscipit mi leo, sit amet mollis metus imperdiet bibendum. Quisque at ante aliquam ante vehicula pharetra. Suspendisse potenti. Proin condimentum justo non nibh faucibus, a luctus risus posuere. Morbi tempor pellentesque tincidunt. Sed ac ultrices ante. Cras lacinia faucibus nisi placerat mollis. Fusce varius venenatis ipsum eget pellentesque. Donec nec varius quam. In vitae dictum velit.
++++
|===
```

**Comment by mojavelinux** [comment]
We're starting to hit the limits of the combinations that can be addressed with CSS. But I see a window that could work here:

```
td.tableblock>.content>:last-child{margin-bottom:-1.25em}
```

That way, we ignore "raw" cells. This is still going to be a problem if the passthrough block is mixed with other blocks because it doesn't get wrapped. You could place it inside an open block to give it a container, though.

Regardless of whether we can find a solution for this case, at some point, you just have to start taking these exceptions into your own stylesheet. We can't cover everything.

**Comment by mojavelinux** [comment]
Replacing the current margin collapsing rule with these, we can handle most cases:

```css
td.tableblock>.content>:last-child{margin-bottom:-1.25em}
td.tableblock>.content>.sidebarblock:last-child{margin-bottom:0}
```

The one remaining exception is when a passthrough block comes after a non-passthrough block inside an AsciiDoc table cell. In this case, the passthrough block will bump up against the previous block. But there's no way to fix that in the default stylesheet. The passthrough block will have to output a wrapper div that gets recognized as the last child.
