### ISSUE TITLE
Italics don't get rendered in the same paragraph as cross-reference 

### ISSUE THREAD

**Issue by andreipoe** [asciidoctor/asciidoctor#3278]
Hello,

If I try to use a cross-reference to a section ID containing underscores and I have _italic_ text on the same paragraph, the first constrained italics don't get rendered properly.

For example, the following block

```
This is a <<otherfile#_section_id,link>>.
This _italics_ doesn't get rendered.
```

...produces the output

```html
<p>This is a <a href="otherfile.html#<em>section_id">link</a>.
This _italics</em> doesn&#8217;t get rendered.</p>
```

Note the `<em>` inside the link and the `_` which is not parsed to start an italics section.

If I escape the first underscore in the section ID as follows

```
This is an <<otherfile#\_section_id, escaped link>>.
This _italics_ doesn't get rendered, in a different way.
```

...then the result is different but still not correct:

```html
<p>This is an <a href="otherfile.html#_section_id">escaped link</a>.
This _italics_ doesn&#8217;t get rendered, in a different way.</p>
```

Note that _both_ underscores are now left _as-is_, and the `<em>` is gone from the generated link.

If I remove the link, everything works file. If I replace the italics with unconstrained quotes (`__`), then it will be rendered properly, but I need to do it for the rest of the paragraph (otherwise the literal `_` will apply to the first constrained block).

I'm using Asciidoctor 2.0.8 and ruby 2.3.7 running on OS X 10.13.6. Let me know if I can provide any other details that would be useful.

Thank you!

**Comment by mojavelinux** [comment]
This just happens to be one of the limitations of the Asciidoctor parser atm, and the AsciiDoc language in general (which we hope to soon address). Thus, the unconstrained formatting is required in this case.

We could do the following, though. Since underscore (`_`) is such a common ID prefix, and it appears directly after a hash (`#`) in a deep link, we could consider `#` to not be a leading word boundary for constrained emphasis. That would solve this very likely case. wdyt?

Btw, backslash escaping in AsciiDoc is currently highly contextual and thus rarely works to prevent valid syntax from from being interpreted.

**Comment by andreipoe** [comment]
Thanks for your reply.

> We could do the following, though. Since underscore (_) is such a common ID prefix, and it appears directly after a hash (#) in a deep link, we could consider # to not be a leading word boundary for constrained emphasis. That would solve this very likely case. wdyt?

This sounds very reasonable to me. I'll use unconstrained italics for now as a workaround, but a fix for this would help with consistency.

**Comment by mojavelinux** [comment]
Rather than add another hack, we are working hard to define the inline grammar in the AsciiDoc Language. That will clear up a lot of these unexpected formatting matches.
