### ISSUE TITLE
AsciiDoc Backend (AsciiDoc 2 AsciiDoc) for preprocessing

### ISSUE THREAD

**Issue by tajmone** [asciidoctor/asciidoctor#3312]
## REQUESTED FEATURE

Add native support for AsciiDoc output backend (i.e. AsciiDoc 2 AsciiDoc) to allow creation of preprocessed ADoc source files.

```
asciidoctor -t asciidoc
```

> __NOTE__ — see also #1906, by @shahryareiv (same request, different motivation).

## RATIONALE

Currently GitHub and GitLab offer limited support for AsciiDoc previews (READMEs and other repo documentation), and they ignore any `include::` directive. This is problematic in project which rely on Asciidoctor for generating its documentation or the repository website (e.g. via GitHub pages, statically), for it interferes with contents reusability.

As a practical example, I run some project which have AsciiDoc README files in each subfolder, which are then converted to HTML in the `docs/` folder served on GitHub pages. Basically, I strive to use the same documents both for online preview on GitHub (i.e. ADoc previews generated by GitHub) as well as for local previews via the HTML converted documents inside `docs/` (or in the same folder, sometimes).

When the various documents reuse tagged regions from each other, then I'm forced to create a markdown version for the README files in project folders, for all the included sections would not be shown on GitHub.

Here's an example of one of these projects:

https://github.com/tajmone/pmotion-assets

On the other hand, if Asciidoctor could create a preprocessed version of every source document, I could then put all the source documents in a `docs_src/` folder and then use a script to auto-generate the (preprocessed) ADoc READMEs in the various folders, which would then show up correctly on GitHub previews — and also convert them to HTML in the GitHub Pages `doc/` folder, as usual. Or I could just keep both document versions side by side, in the same folders, using the `.asciidoc` extension for the source docs and `.adoc` for the pre-processed version (or the other way round, whichever extension has higher priority on GitHub previews in presence of same-named README file):

```
README.asciidoc --> source doc (with 'include::' directives)
README.adoc     --> preprocessed version, for previewing on GitHub
```

This would be much more practical than having to resort to a markdown replacement for every doc that relies on `include::` directives, for there aren't any good AsciiDoc to markdown converters right now (at least, none that support advanced features of Asciidoctor).

Besided, in huge projects where every file includes snippets/regions from other files, it would be convenient to be able to produce a standalone pre-processed AsciiDoc version which can be shared with others without having to also attach numerous other source files (possibly belonging to complex folder structures).

**Comment by mojavelinux** [comment]
This is not technically a backend. That's because the parser does not currently store enough information to reproduce the original source document. But that's what the preprocessor reader is for.

You can find a script that uses the preprocessor reader in this way here: https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/scripts/asciidoc-coalescer.rb

**Comment by tajmone** [comment]
Thanks for the link, that's precious to me!

Wouldn't it be possible to include this script into Asciidoctor bundle, so it's always within reach and (most important) always guaranteed to work with the current release?

**Comment by mojavelinux** [comment]
It's in the lab for a reason. It's not fully evolved yet. If someone is willing to take it completion, it could become a candidate for core. I don't have the time right now.

**Comment by tajmone** [comment]
The `asciidoc-coalescer.rb` script worked like a charm:

https://github.com/tajmone/awesome-interactive-fiction/tree/master/docs_src

it enabled me to split up a very long Awesome List document into smaller chuncks (one file per section) and at the same time preserve the document preview on the repository landing page by creating a preprocessed version.

Again, thanks for the precious tip @mojavelinux! (Asciidoctor has such a huge echosystem that discovering life-changing assets is like finding a needle in a haystack.)

I'm posting here a couple of notes, for the benefit of others reading this thread...

- Invocation of `asciidoc-coalescer.rb` with custom attributes (`-a` option) also allowed me to finalize into the preview document GitHub-specific hacks (e.g. admonitions with emoji icons, TOC shown via macro in a specific location, etc.), and leaving out conditional blocks that didn't apply to the context. 

    This is an added benefit in case someone needs to reuse the preprocessed AsciiDoc file elsewhere, instead of copying all the (multiple) source files, for the prepocessed document will be free from conditional blocks targetting other formats or platforms.

- Developer notes can be enclosed in the source files within never-matching conditional statements:

    ```asciidoc
    ifeval::[0==1]
    ////
    This comment won't show up in the preprocessed document.
    ////
    endif::[]
    ```

    and they won't be included in the preprocessed doc — which is an added bonus that allows to exploit collaborative notes and inline TODOs without cluttering the final doc.

This type of workflow is currently the best workaround for GitHub not supporting `include::` directives. Hopefully, they'll be supported soon (see [#1095]).


[#1095]: https://github.com/github/markup/issues/1095

**Comment by shahryareiv** [comment]
@mojavelinux 
Just wanted to add a note for possible future references:
Asciidoc is a human readable and target format of itself. It is a good idea to have an archive version (similar to PDF/A) which is guaranteed to be readable and intact after a long time (when possibly some of the the third-party macros/plugins are dead or there are major compatibility leaps between Asciidoctor versions). To achieve this goal, we need a preprocessing mechanism that expands all attributes and macros, and respects some core long-lasting standards in the format.

**Comment by aisbergde** [comment]
I have the same issue - I want to generate readme files in asciicode for github, resolving all the includes.

I am not a specialist for the programming language which is used by asciidocor, but I just use doctoolchain which does a good job converting asciidoc documentation into some formats, but not into asciidoc with solved includes. Furthermore, I don't have to understand how doctoolchain is programmed, but I can just use it as it is. This is great.

Here I can read: there is a script, written in any unknown for my language (*.rb - I think this could be ruby), which could solve my issue. But I have no idea how I should or could use this script and how I could or should integrate it into the doctoolchain workflow.

Maybe it is easy for a Ruby programmers to use this kind of scripts. But maybe there are other GitHub users like me, which aren't Ruby programmers, but who likes asciidoc and just are looking for an easy way to create GitHub compatible readme files in asciidoc. Maybe there could be an easy solution for this GitHub users to make asciidoc more popular.

**Comment by mojavelinux** [comment]
I have good news. I have a better version of the coalescer script that is a lot more accurate. I'll make a note to myself to publish that asap. It will still require using Ruby, that's unavoidable at the moment. But it will do a lot better job at what it does.

As for GitHub not supporting includes, there's very little we can do about that. If it is that important to you, then you can use GitLab instead, which does support includes as well as a whole host of other AsciiDoc features. We have no shortage of AsciiDoc users and I'm not going to be persuaded by the notion that we are losing users because GitHub won't display AsciiDoc to its fullest. That's partly because we are not GitHub and we have no say over its actions. Instead, I will advocate for platforms like GitLab that actually do support the features we expect.

**Comment by mojavelinux** [comment]
I should add that I'm also open to documenting this script in the offical docs (once I update it) so that there are clearer instructions for how to apply it. Seems like a very reasonable request to me.

**Comment by mojavelinux** [comment]
I also want to add that once I publish the new version of the coalescer, I will strongly consider graduating it to a separate extension. That will make it easier to install and load. It's not something I want to put into core as it goes beyond the scope of what core should provide (meaning it makes core too complex). But it would make a perfect extension.

**Comment by tajmone** [comment]
> I will strongly consider graduating it to a separate extension. That will make it easier to install and load. 

That would be great, so users only have to install it once and forget about it (as opposed to have to manually include it in every repository that  uses it, and then updating each copy of it).

Whenever I create a book repository, I tend to keep the ADoc sources split into one file per chapter, which makes it easier to work on the sources while editing/updating the document; but I usually also build a single-source coalesced version of the book for third parties how might wish to include it in another project (e.g. a books collection), since for them is more convenient to host it as a single file.

**Comment by mojavelinux** [comment]
> That would be great, so users only have to install it once and forget about it (as opposed to have to manually include it in every repository that uses it, and then updating each copy of it).

Absolutely. I've always said that the lab is just a place for experiments. It's not meant to be used for production code. And by that logic, it should be it's own project.

**Comment by aisbergde** [comment]
I want to explain how I found asciidoc.
- Until last week I used Markdown everywhere
- My target is to use Azure Boards to manage all my projects there (I do this for many years)
- Azure DevOps missed an easy way to enter issues like GitHub
- But Azure Boards can integrate with GitHub
- I decided to use GitHub for a new open source project instead of Azure DevOps. I only connect Azure Boards
- I found that GitHub can't create automated toc per document as I can do in Azure wiki
- I found that this is requested for a long time but will not be implemented in GitHub
- one user wrote, that he is tired about this and he started to use asciidoc instead of Markdown
- "asciidoc"? So I investigated about this asciidoc and found out, that this is exactly what I am looking for - since many years. And finally I found. This is exactly what I need! It was like a late Christmas gift. And I will use and promote asciidoc from now where ever I can. (Still miss a tool for using it on Android for notes taking in asciidoc instead of markdown)

GitHub did and does a great job in promoting asciidoc. And as a lazy BI architect and developer I just try to find an easy way to use, what is possible to use in GitHub.

**Comment by tajmone** [comment]
> Still miss a tool for using it on Android for notes taking in asciidoc instead of markdown

You can easily convert your markdown notes to AsciiDoc using pandoc:

https://pandoc.org/

It's a FOSS standalone binary tool that support conversion to and from many formats formats, including _from_ (but not _to_) AsciiDoc. 

By the way, pandoc can also generate TOCs, and I've used in the past to auto-generate TOCs for markdown docs on GitHub by simply (converting from GFM (GitHub flavored markdown) to GFM with the TOC option. But AsciiDoc is definitely a better solution since the TOC is generated dynamically at preview time, whereas the pandoc trick requires keeping a separate source doc to prevent piling up multiple TOCs at each build.

**Comment by aisbergde** [comment]
@tajmone 
I know Pandoc and I use it to convert from Markdown to docx. For example my id profile is in Markdown, but headhunters request word files. Pandoc works fine. I even thought about converting from asciidoc to DocBook with doctoolchain, and then from DocBook to asciidoc with Pandoc. But that doesn't seem to be the right way to me.

As for Android, I don't want to translate everything from MarkDown to asciidoc first, but edit (and create) notes on both desktop and Android alternately.

'Markor' is my favorite android editor. But asciidoc is not yet supported:
https://github.com/gsantner/markor/issues/808
If I would / could program in Java, then maybe I could contribute there. However, I leave the Java programming better to those who are good at it, instead of messing around myself.

**Comment by tajmone** [comment]
> But that doesn't seem to be the right way to me.

I believe than pandoc doesn't support all the features of AsciiDoc and Asciidoctor, but just a subset, mainly because it's a PEG-based parser that builds a full AST, which makes it complicate (although not impossible) to handle all possible AsciiDoc syntax variants. But I thought it was worth mentioning it in the context of notes, which usually are not complex documents.

I'm not sure what features you're expecting from an Android AsciiDoc editor (i.e. just syntax highlighting or advanced editing features like snippets, etc.), but there are some web-based AsciiDoc editors available online — e.g.:

- https://asciidoclive.com/

The above is more of a live previewer than a full-fledged editor, but some online editors are starting to offer rather advanced editing features nowadays, so chances are that there's a JS based editor that could (or already does) support AsciiDoc editing in the manner that dedicated desktop editors do (e.g. like [Asciidoc FX](https://asciidocfx.com/)), with all the cool features of modern code editing, but within the browser. Adding an AsciiDoc syntax in these type of editors might not even require programming, but just creating some configuration files for the syntax highlighter, autocompletions, snippets, etc., just like it's done in many modern editors (Kate, VSCode, ST, etc.), so it might be worth looking into it.

I'm not a smart phones/tablets enthusiast, so I'm not really into these kind of apps and services.

**Comment by dsisnero** [comment]
did you publish the new script?

Thanks

**Comment by mojavelinux** [comment]
The asciidoc-coalescer.rb script has been redesigned and published as the [asciidoctor-reducer](https://github.com/asciidoctor/asciidoctor-reducer). It has also been released to RubyGems.org as a gem named **asciidoctor-reducer**. You can find installation instructions in the README for that project.
