### ISSUE TITLE
Line break in URL text with attribute cuts off text

### ISSUE THREAD

**Issue by henribru** [asciidoctor/asciidoctor#3331]
Version info: https://gist.github.com/henribru/bd5582b5f9e7099f3f390b3914218682

```
https://foo.com[[.c]#Foo 
bar#]
```
is rendered as 
```<a href="https://foo.com"><span class="c">Foo</span></a>```
I would have expected
```<a href="https://foo.com"><span class="c">Foo bar</span></a>```
Given that both
```https://foo.com[[.c]#Foo bar#]```
and
```
[.c]#Foo 
bar#
```
work as expected, this behavior seems surprising.

**Comment by mojavelinux** [comment]
That is indeed very bizarre. Nice catch! I'll see what's going on.

**Comment by mojavelinux** [comment]
I think I figured it out. The converted HTML in the link text is being recognized as an attribute list and is being parsed as such. But this is failing since the attribute parser doesn't consider newlines. I'll need to make this more robust. And in this case, the text should be left as is since there are no attributes to parse.

**Comment by mojavelinux** [comment]
When the logic was added to automatically detect and parse attributes in the link and xref text, we inadvertently broke the parsing in several ways. First, there are cases when the attribute signature is present, but no attributes are found. In this case, we now preserve the original text. Second, the attribute parsing assumes there's only a single line. So prior to parsing the attributes, the newlines need to be folded. We do this everywhere else, but forgot this case.

I have applied those changes. Once released, links and xrefs should just work as they always did.

Now, there's still a bit of a fragile scenario that we had not considered when adding the automatic parsing of attributes (when an equals sign is present in the text). If the text has formatting, it may be seeing an equals sign in HTML. Fortunately, in this case, it seems to think it found no attributes and returns the text as is, which is what we want. (It's because an attribute name can't have a space in it). But, like I said, that feels a bit fragile. One more strong case for that inline parser to be implemented.
