### ISSUE TITLE
Use asciidoctor with Python 3

### ISSUE THREAD

**Issue by sharpaper** [asciidoctor/asciidoctor#3340]
Is there a way to use asciidoctor from a Python module? I'd like to convert an asciidoc string to HTML from Python but all I could find is asciidoctor, which is written in Ruby :(

**Comment by mojavelinux** [comment]
I think you answered your own question. Asciidoctor is written in Ruby and is available for Ruby, Java, and JavaScript. You could use any of those options to bridge to Python, but otherwise there is no direct support for running Asciidoctor in Python.

The asciidoctor command does support piping to and front standard input, so you could use that approach to call into it.

**Comment by AriaMoradi** [comment]
or use [asciidoc-py3](https://github.com/asciidoc/asciidoc-py3)

**Comment by mojavelinux** [comment]
@AriaMoradi Correct, asciidoc-py3 is the legacy implementation ported to Python 3.

The AsciiDoc specification brings promise to a new set of implementations based on a well-defined standard. It means you'll be able to process AsciiDoc on any platform of your choosing without worrying that it will be interpreted differently. See https://projects.eclipse.org/proposals/asciidoc-language
