### ISSUE TITLE
Callout comments not consumed if :icons: is unset

### ISSUE THREAD

**Issue by rquinio** [asciidoctor/asciidoctor#3346]
I've noticed this behavior with callouts on Asciidoctor 2.0.8 with html backend:

Sample .adoc:
```adoc
[source,java]
----
public class HelloWorld { // <1>
----
<1> The class name
```

If icons attribute is not set, the comment sequence // will not be consumed when callout is rendered as text (so when copy-pasting the comments will be kept). It looks like:

```
public class HelloWorld { // (1)
(1) The class name
```

When using `:icons: font` and the font does not contain the glyph, the comment sequence // is properly consumed when callout is displayed with fallback text. It looks like:

```
public class HelloWorld { (1)
(1) The class name
```

I've seen this with both highlightjs and coderay highlighters, so I assume it's a behavior of asciidoctor ?

Using `:icons: font` when you don't have the glyphs has a side effect: admonitions don't use fallback text (so you can't differentiate a Note from Warning, at least not without extra css), hence not setting :icons: attribute is a simpler alternative in such case, if not for this issue of stray callout comments.

References:
* https://asciidoctor.org/docs/user-manual/#icons
* https://asciidoctor.org/docs/user-manual/#copy-and-paste-friendly-callouts
* https://asciidoctor.org/docs/user-manual/#attribute-catalog - says default value of :icons: is not set (image), but for callouts it's actually more (fallback text).

**Comment by mojavelinux** [comment]
The described behavior is intentional and is described in this section of the docs: https://docs.asciidoctor.org/asciidoc/latest/verbatim/callouts/#copy-and-paste-friendly-callouts

The idea is that leaving behind the callout (not replacing it with an icon) would potentially make the code example invalid. So preserving the comment is necessary to keep it protected. If the comment were to be removed, the syntax highlighting would trip on it and produce error spans.
