### ISSUE TITLE
Table cell content overflows

### ISSUE THREAD

**Issue by sercanu** [asciidoctor/asciidoctor#3370]
The content in a table cell overflows. Fix is related to this [issue](https://github.com/asciidoctor/asciidoctor/issues/2568) but it doesn't work anymore. Selecting last-child breaks the things. Official documentation uses older version of CSS so it looks working but when I run the example below code blocks overflow the table cells. 

asciidoctor.org uses
`td.tableblock>.content{margin-bottom:-1.25em}`

latest asciidoctor.css
`td.tableblock>.content>:last-child{margin-bottom:-1.25em}`

https://asciidoctor.org/docs/user-manual/#cell

```
|===
|Source Code 1 |Source Code 2

a|
[source,python]
----
import os
print "%s" %(os.uname())
----

a|
[source,python]
----
import os
print ("%s" %(os.uname()))
----
|===

```

**Comment by mojavelinux** [comment]
The change in behavior is due to the fix for #3256.

I see what the problem is. We're missing the margin on the content div that's being collapsed. Now, adding that will bring back the bottom margin in the case when the AsciiDoc table cell contains no blocks (the case in #3256), but unfortunately there's just no way to handle all the cases with the built-in style rules. So we'll have to live with that. But at least there will be no risk of content running outside the cell.

**Comment by mojavelinux** [comment]
Btw, the real solution to this problem is to switch to top margins instead of bottom margins for the whole stylesheet, which are way easier to target using CSS selectors. But we're holding off on that until #242 is resolved.

**Comment by mlsvrts** [comment]
I just ran into this, and as far as I can tell v2.0.11 hasn't dropped yet. However, I was easily able to 'fix' it for my local install by implementing the two line change from commit 7a72fa4.

For my gem installed version of asciidoctor, `asciidoctor-default.css` was located in: `/var/lib/gems/2.5.0/gems/asciidoctor-2.0.10/data/stylesheets/asciidoctor-default.css`
