### ISSUE TITLE
Double quotes around URL macro prevent it from being converted

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#3376]
Enclosing a URL or URL macro in double quotes prevents it from being recognized and converted. For example:

```
"https://asciidoctor.org[Asciidoctor]"
```

However, it's acceptable to put double quotes around an explicit link macro or xref macro.

```
"link:https://asciidoctor.org[Asciidoctor]"

"xref:index.adoc[Home]"
```

The behavior should be consistent.

**Comment by Mogztter** [comment]
> The behavior should be consistent.

As in, we should allow double quotes around URL macro?

**Comment by mojavelinux** [comment]
Yes.

**Comment by Mogztter** [comment]
What is the exhaustive list of allowed enclosing characters?
In my opinion, when using an implicit link, we should only support a strict list of prefixes and suffixes:

```
"https://asciidoctor.org" is the project page for AsciiDoc.
<https://asciidoctor.org> is the project page for AsciiDoc.
[https://asciidoctor.org] is the project page for AsciiDoc.
(https://asciidoctor.org) is the project page for AsciiDoc.
'https://asciidoctor.org' is the project page for AsciiDoc.
```
When we detect a valid prefix (i.e. `[`, `(`, `<` or `"` or `'`), we should search for the matching suffix and remove it (if found).

| AsciiDoc | Link (href) | Comments |
| ---- | ---- | ---- |
| `<https://asciidoctor.org>` | `https://asciidoctor.org` | `<` is a valid prefix, <br/> the last character of the target is a valid suffix `>` |
| `[https://asciidoctor.org"` | `https://asciidoctor.org"` | `[` is a valid prefix,  <br/>`]` was expected as a suffix, since `"` does not match, <br/>we consider this character as part of the URL |
| `]https://asciidoctor.org[` | - | `]` is not a valid prefix |

Not sure about the second, maybe we should consider that this is not a valid link since the suffix is not in compliance with the prefix? It's more strict but might avoid some confusions.

Implementation wise, I think it might the right time to fix the following "FIXME", otherwise, the regular expression and the associated code will be hard to grasp. 

```rb
# FIXME revisit! the main issue is we need different rules for implicit vs explicit
```

**Comment by mojavelinux** [comment]
I'm not interested right now in considering all permutations. I want to stay focused on the inconsistency at hand.

**Comment by mojavelinux** [comment]
What it probably should be is that the URL protocol as macro name should be treated the same way as the link macro. But there are various reasons why that is not easily supported as the code currently stands. So it may be something we look at in the spec. Until then, just allows the URL protocol to be prefixed with a quote goes a long way.

**Comment by mojavelinux** [comment]
> Implementation wise, I think it might the right time to fix the following "FIXME", otherwise, the regular expression and the associated code will be hard to grasp.

That needs to wait until at least a minor release (and maybe even a major one).

**Comment by mojavelinux** [comment]
```
"https://asciidoctor.org"
```

The reason this one is not supported is because of the way substitutions are currently done in AsciiDoc. This would end up catching href attributes returned by partially converted text and would wreck havoc on the result.
