### ISSUE TITLE
Quotes: text justification looks unexpectedly

### ISSUE THREAD

**Issue by john-cj** [asciidoctor/asciidoctor#3381]
```
[quote]
____
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
____
```

Excerpt from the current stylesheet:

```
.quoteblock blockquote, .quoteblock p {
    text-align: justify;
}
```

To my opinion, `text-align: justify` looks a bit unexpectedly. Typically, we expect `text-align: justify` in books and newspapers and `text-align: left` in websites. I never saw these typographic styles to be mixed.

Another reason to get rid of `justify` is the word spacing. In books and newspapers justification goes together with hyphenation. In websites, we don't use hyphenation, and therefore justification will lead to irregular word spacing.

The irregular word spacing will be even more evident in languages like German, i.e. the languages with a large amount of long and very long words.

**Comment by mojavelinux** [comment]
Presenting quote blocks in this way is the design call we made for the default stylesheet, and it has been broadly liked. Justified text is a style that's often used on quoted text to make it stand out, and I think it has that effect here.

If you prefer a different style, you're free to customize the CSS or provide your own stylesheet. After all, it is just a design choice for the default stylesheet, not something that is baked into the language.

In a future release (perhaps 2.1.0), it will be possible to override the justification on the paragraphs using the text-* alignment roles. For example:

```
[.text-left]
____
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
____
```

Due to a precedence bug in the default stylesheet, this doesn't work as of Asciidoctor 2.0.20.
