### ISSUE TITLE
Inline code in tables: missing background

### ISSUE THREAD

**Issue by john-cj** [asciidoctor/asciidoctor#3384]
```
[%header]
.Variables and values
|===
| Variables  | Values
| `a`       a| `x`

Sometimes the value could be `z`.

| `b`        | `y`
|===
```

Excerpt from the current stylesheet:

```
p.tableblock>code:only-child {
    background: none;
    padding: 0;
}
```

Background is present for "x" and "z", but not for "a", "b", and `y`.

To my opinion, it looks unexpectedly, and the background should be present for all of them.

**Comment by lread** [comment]
We stumbled upon this one today and were confused by it too.

It's easy enough for me to change CSS to address, but am wondering if anyone might remember a rationale for this rule. There might be a really good reason for it, but I don't see it yet.

The example in the issue demonstrates it well but in English: If there is only one `` `code` `` element in a table cell, then it does not get a background color (or padding, but that's less interesting to me personally), but if there are more than one `` `code` `` elements in a cell then use the default background `` `code` `` element color.

**Comment by mojavelinux** [comment]
This is by design. If we keep the background color on the `code` tag inside a table cell, then the monospace table cell looks ridiculous. However, there's no easy way to differentiate between the content of a monospace cell and a monospace span inside a paragraph in a normal table cell. So we came up with this compromise. If you don't prefer it, you're free to customize the stylesheet to your liking. We are not planning on changing the default stylesheet at this time. (See https://docs.asciidoctor.org/asciidoctor/latest/html-backend/default-stylesheet/#customize-the-default-stylesheet).

**Comment by lread** [comment]
Thanks for the rationale @mojavelinux, much appreciated!
