### ISSUE TITLE
New default admonitions

### ISSUE THREAD

**Issue by Nadano** [asciidoctor/asciidoctor#3424]
As discussed here:
https://discuss.asciidoctor.org/Asciidoctor-pdf-Custom-admonition-icons-td5850.html

Creating new custom admonitions is possible, but I believe that many will agree with me that some admonitions should be included by default:

QUESTION: icon: question mark
TODO: icon: "work in progress"?
(TO)REVIEW: icon: "eye"?

At least the 'question' and 'todo' will help a lot during presentations or when reviewing documents with my colleagues.

**Comment by boerngen-schmidt** [comment]
Hello,

I really would like to see QUESTION and TODO as additional admonitions.

Question's intend should be to high light a question that will be answerd by the documentation in the following chapters.
Todo's intend should be to indicate, that a documentation/text is not ready yet, thus when the page is rendered a waring could be logged indicating, that a document is not yet done.

The other idea with Review I do not like very much, since it could be accomplished with VCS where one can see what has changed in the document. Also the reviewer then would have to change the document after review and might do nasty things.

**Comment by Mogztter** [comment]
Since the AsciiDoc specification is underway, I think we won't add new admonitions types into core at this time.

> You can implement your own admonitions using a block extension. See https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/lib/custom-admonition-block/extension.rb. We won't be adding anymore types directly into core at this time (as it requires a language change, and we're not doing language changes right now).

https://github.com/asciidoctor/asciidoctor/issues/3537#issuecomment-573891670

**Comment by mojavelinux** [comment]
> Since the AsciiDoc specification is underway

It's not quite underway yet, though we're gearing up for it. With that in mind, it's true that all new language changes will go through the working group, or at least floated there first. Then we can decide what to do in Asciidoctor (as the spec will give us freedom to experiment since the concerns will be separated).

> I really would like to see QUESTION and TODO as additional admonitions.

I don't agree that TODO is admonition. TODO is a writer notation and should take some some other form, likely a variation on a comment.

QUESTION is something that may be needed in technical writing, but it's not an admonition. An admonition is an instruction to the reader, hence the name. DocBook defines these types: https://tdg.docbook.org/tdg/5.1/note.html (refer to "See Also"). DITA defines these types: (note | tip | fastpath | restriction | important | remember | attention | caution | notice | danger | warning).

So a question block may be needed, but it's not an admonition.

**Comment by mojavelinux** [comment]
Feel free to open two separate issues for a TODO block type and a QUESTION block type and we can catalog some ideas and bring those ideas to the working group (once it's up and running). But since these aren't admonitions, this issue doesn't have the correct focus.
