### ISSUE TITLE
The catch-all term for Include, Image, Video and Audio

### ISSUE THREAD

**Issue by john-cj** [asciidoctor/asciidoctor#3427]
According to Asciidoctor User Manual, `include::` is a directive.

From some point of view it could be said that `image::`/`image:`, `audio::` and `video::` (and even `icon:`) are something similar to `include::`.

* Does it exist some catch-all term for `image::`/`image:`, `audio::`, `video::`?
* Does it exist some catch-all term for `image::`/`image:`, `audio::`, `video::` and `include::`?

**Comment by elextr** [comment]
And http: and https: and .....

**Comment by mojavelinux** [comment]
> From some point of view it could be said that image::/image:, audio:: and video:: (and even icon:) are something similar to include::.

Although they share the same syntax for consistency, they are distinctly different. `include` is a preprocessor directive (runs before parsing). The others are macros.

This distinction is specifically addressed in the documentation. https://asciidoctor.org/docs/user-manual/#processing

> Does it exist some catch-all term for image::/image:, audio::, video::?

Block and inline macros.

> Does it exist some catch-all term for image::/image:, audio::, video:: and include::?

No, because the only thing they have in common is the syntax (for consistency). I suppose we could name the syntax itself, but I have yet to think of anything.

These types of questions are better to ask on the discussion list, so please post there if you want to discuss at greater length.

**Comment by john-cj** [comment]
Just for the clarity, when I mentioned the similarity between these things, I mean that all of them somehow incorporated in the document during the processing. Not just the similarity in their syntax.

The question is completely answered, though.

**Comment by mojavelinux** [comment]
Fantastic!
