### ISSUE TITLE
More operators for ifeval

### ISSUE THREAD

**Issue by jroessel** [asciidoctor/asciidoctor#3441]
Right now `ifeval` only supports equality and relational operators. When working with conditionals with different options this can result in sort of an explosion of boolean attributes to cover every single flag. For such cases something akin to _contains_ or _match_ might be useful. So instead of having a dozen attributes of the form `:setting-foo: true` one could have something like `:settings: foo,bar,baz` and could query this via `ifeval::["{settings}" contains "foo"]`.

Admittedly, a pure textual contains may pose problems with substrings contained in larger "options", but could be good enough to work well. Otherwise, treating the left side as a list-like value would be more complicated, but also more robust.

**Comment by eallais** [comment]
Any updates regarding this issue ? 
I need something like that also.

Thank you.

**Comment by mojavelinux** [comment]
If this change were to happen, it must happen in the AsciiDoc Language. That means a formal proposal must be submitted. However, I'm not keen on supporting it because I don't want AsciiDoc to become a programming language. I think we should stick to simple comparison operators. The complexity should be shifted to the preparation of attributes for comparison.

There is an open issue to allow combinations, something that Asciidoctor's predecessor supported. See #4246.
