### ISSUE TITLE
Leverage AsciiDoctor to parse adoc-based custom markup and produce paginated output

### ISSUE THREAD

**Issue by lenormf** [asciidoctor/asciidoctor#3455]
Hi,

I'm using a custom asciidoc-based markup format, and want to parse it and generate PDF files out of it.

Extensions to the markup include things like `>text<` centers "text" on the page, entirely capitalized text surrounded with empty lines should be rendered in bold automatically… many things also depend on whether the tokens are located at the beginning of the line/file. And the resulting PDF files should have specific margins and font.

How easily would it be to extend the built-in parser in this repository to support all those extensions? I didn't find any documentation in the wiki, would I have to implement additional routines in some Ruby script?

Thanks!

**Comment by mojavelinux** [comment]
Interesting question. Though this question is really better suited for the mailinglist. https://discuss.asciidoctor.org.

My gut reaction is to say that's not really what this parser was designed to do. It's not a general purpose text parser. Rather, it's highly specialized for parsing the AsciiDoc syntax, and often "cheats" to speed up processing because it knows what to expect in advance. So you're time would be better invested making a new parser for what you need to parse, though of course you could use this parser as a reference.

**Comment by lenormf** [comment]
Thanks for the quick reply! What do you recommend I use, not necessarily in Ruby? I had hoped not to have to re-code an entire asciidoc parser, but if I had to I would like the process to be as fast as possible (I'm not stressed about speed).

What worries me is all the context-awareness (start of file, start of line, consecutive lines etc), it seems that using PEG for that plus the regular asciidoc syntax would be horribly painful?

**Comment by mojavelinux** [comment]
I have started a parser in JavaScript indented for validation that might be a useful starting point. https://github.com/opendevise/textlint-plugin-asciidoc

There is a way to extend AsciiDoc already. I can't encourage the creation of a divergent language that goes beyond that (and it certainly can't be called AsciiDoc), which is why I don't think this discussion belongs here. This is more about reusing Asciidoctor code to start a different initiative...which is perfectly fine, but not something that we're entertaining here.

**Comment by lenormf** [comment]
Thanks!
