### ISSUE TITLE
Code highlighter CSS added in the body tag

### ISSUE THREAD

**Issue by krOoze** [asciidoctor/asciidoctor#3462]
Why is the code highlighter CSS style block added at the end of `<body>`? I would expect it in `<head>`.

Test source:
```
:source-highlighter: coderay

= Document Title

[source,ruby]
---- 
require 'sinatra'

get '/hi' do
  "Hello World!"
end
----
```

Output (`asciidoctor -b html5 test.adoc`):
```
<!DOCTYPE html>
<html lang="en">
<head>
...
</head>
<body class="article">
...
<style>
/* Stylesheet for CodeRay to match GitHub theme | MIT License | http://foundation.zurb.com */
...
</style>
</body>
</html>
```

**Comment by mojavelinux** [comment]
JavaScript and auxiliary stylesheets are loaded at the bottom of the document for performance reasons.

See http://www.html5rocks.com/en/tutorials/speed/script-loading/ as to why. Since syntax highlighting only colorizes the text, there's no risk of a reflow, so it won't negatively impact rendering. In fact, it will likely make it appear faster.

It's possible to change this behavior by extending and re-registering the syntax highlighter adapter.

**Comment by krOoze** [comment]
The link talks about JavaScript. `<style>` tag is [illegal](https://html.spec.whatwg.org/multipage/semantics.html#the-style-element) inside `<body>`.

**Comment by mojavelinux** [comment]
That's not true. HTML5 doesn't have any schema rules. It's perfectly valid
to put it there. In fact, the head tag isn't even technically required.

**Comment by mojavelinux** [comment]
Hmm It does seem like the validator doesn't like it. In that case, we could
move it up to where the other styles are defined.

**Comment by krOoze** [comment]
Right, that what I meant. And the link to spec says which contexts are expected for the tag.

Technically HTML 5.2 seems to allow it, then again it is from W3C, but WHATWG is listed as developer of HTML. There probably is some (all?) browser support. though I fail to find a source that lists browser support.

**Comment by mojavelinux** [comment]
> Right, that what I meant.

Go it. We want the document to validate according to those rules at least, so that's the driving factor.

> There probably is some (all?) browser support.

I'm confident all major browsers support it because browsers have always had extremely lenient rules (and because I have tested it). It's the validator we need to make happy. So we will proceed accordingly.
