### ISSUE TITLE
Underscores in index terms unexpectedly leaking across end, escaping won't work

### ISSUE THREAD

**Issue by zwaldowski** [asciidoctor/asciidoctor#3465]
See https://gist.github.com/zwaldowski/2ed45400be3ab72a73e5f2111ce26f0c and the associated raw markup [here](https://gist.github.com/zwaldowski/2ed45400be3ab72a73e5f2111ce26f0c/raw/74ba4b950bc8849c84cbf32076c66a9bf9d8efb4/leaking-index-term.adoc).

**Comment by zwaldowski** [comment]
OK, so on the plus side `pass:m[(((…)))]` functions as a workaround, albeit an unsightly one.

**Comment by zwaldowski** [comment]
Dug a little and it's triggered by the unconstrained emphasis regex.

Some observations:

* The match data from the unescaped version: `#<MatchData "(_:))))\nA [term]_method_" 1:"(" 2:nil 3:":))))\nA [term]_method">`
* The match data from the escaped version: `#<MatchData "\\_:))))\nA [term]_method_" 1:"\\" 2:nil 3:":))))\nA [term]_method">`
* Matching an escaped `\_` doesn't try and re-process the text that occurs after the `_`.

I don't know what the ideal behavior is here. IMHO it seems like the inside content of macros shouldn't undergo the quotes pass _ever_, but I don't think changing the order is tractable. It also doesn't seem right for the. The lowest-hanging fruit may be some recursive processing for quotes?

**Comment by mojavelinux** [comment]
Due to how AsciiDoc is currently implemented in Asciidoctor, markup is interpreted inside of an index term and must be escaped just as though it were not inside the boundaries of an index term.

We are addressing this shortcoming in AsciiDoc in the AsciiDoc Language specification such that formatting will not escape the boundaries of an inline element, such as in index term. While text formatting will likely still be applied (at least in part), it will not form unbalanced matches. Until then, the behavior in Asciidoctor is as designed.
