### ISSUE TITLE
Cell background color in nested tables not working as expected

### ISSUE THREAD

**Issue by bachp** [asciidoctor/asciidoctor#3476]
I'm trying to have cells with colored backgrounds in a nested table. Using the same method as I would in the outer table:

```
[cols="1a"]
|===

|
[cols="1,2,2"]
!===
! Color
! Name
! RGB

! {set:cellbgcolor:#4169E1}
! RoyalBlue{set:cellbgcolor!}
! `#4169E1`


! {set:cellbgcolor:#FF4500}
! OrangeRed{set:cellbgcolor!}
! `#FF4500`

! {set:cellbgcolor:#32CD32}
! LimeGreen{set:cellbgcolor!}
! `#32CD32`
!===

|===
```

However the result is completly wrong.

![image](https://user-images.githubusercontent.com/333807/68386653-cb70ae80-015c-11ea-81ac-338ff84958cc.png)

It seems that the `{set:cellbgcolor!}` is not properly recognized.

Changing `{set:cellbgcolor!}` to `{set:cellbgcolor}` produced the expected result.

![image](https://user-images.githubusercontent.com/333807/68386738-f65b0280-015c-11ea-8c27-e8a30ed09715.png)

I assume it has something to do with `!` being used for nested tables too.

Is this the expected behaviour? I think it might be less suprising if `{set:cellbgcolor!}` would work.

Version used:
```
Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```

**Comment by mojavelinux** [comment]
That's correct. You'll need to escape the delimiter or otherwise avoid the conflict.

Here are 3 solutions:

1. Escape the delimiter using a backslash: `{set:cellbgcolor\!}`
   \* NOTE: You'll need to put the unassignment on its own line or it will wipe out the content in the cell
2. Use the color `transparent` to reset the color: `{set:cellbgcolor:transparent}`
3. Use an alternate delimiter for the nested table as recommended in the docs: https://asciidoctor.org/docs/user-manual/#escaping-the-cell-separator

**Comment by dwscott-nz** [comment]
Must background colors be in nested tables? I have not been able to reproduce this not in a nested table...

**Comment by mojavelinux** [comment]
Setting the background color on a cell using cellbgcolor is deprecated in Asciidoctor (and no longer part of the AsciiDoc language). This functionality will likely be removed in a future release. It will be replaced by a role on a cell, but that's still a ways off.
