### ISSUE TITLE
Some Warning in ASCIIDOCTOR

### ISSUE THREAD

**Issue by hhlp** [asciidoctor/asciidoctor#3482]
I've had a fun of Question about this warning?

* What is this mean?
* How Can I know, What file is content the warning?
* How to trace it? I'm under container

asciidoctor: WARNING: skipping reference to missing attribute: majorosver
asciidoctor: WARNING: skipping reference to missing attribute: context

NOTE: I've had a bunch of files....

Regards.,

**Comment by Mogztter** [comment]
Hello @hhlp 

It means that `majorosver` and `context` attributes are undefined. You most likely have a reference in your files `{majorosver}` and `{context}`. Since the processor can't replace the reference with the actual value, it issues a warning.

Please note that you can configure the behavior when the processor finds a reference to a missing attribute: https://asciidoctor.org/docs/user-manual/#handle-missing-or-undefined-attributes

I hope it helps 😃

**Comment by Mogztter** [comment]
> How can I know, What file is content the warning?

In theory, we could add the source location on the log but it's really useful? I mean, you can already find every occurrences of the attribute using `grep` (or something similar).
In this case, I think what you want to know is why the attribute named `majorosver` is undefined but unfortunately the processor can't help you with that.

**Comment by Mogztter** [comment]
> How to trace it? I'm under container

I would try to find if `:majorosver:` is present somewhere. Maybe you are using a file where all the attributes are defined but this file is not included?

**attributes.adoc**
```
:majorosver: 1.2.3
```

**document.adoc**
```
Please use {majorosver}
```

Since *attributes.adoc* is not included in *document.adoc*, `majorosver` is undefined.
And here's how to fix this issue:

**attributes.adoc**
```
:majorosver: 1.2.3
```

**document.adoc**
```
include::attributes.adoc[]

Please use {majorosver}
```

**Comment by mojavelinux** [comment]
And btw, these warnings are opt in. The fact that you are getting them indicates that you have attribute-missing=warn set (or you are using Antora, which enables that setting by default).

**Comment by hhlp** [comment]
thx for point me out in the right direction

regards
