### ISSUE TITLE
Add a tl;dr Admonition

### ISSUE THREAD

**Issue by leonard84** [asciidoctor/asciidoctor#3537]
It would be nice to have `TLDR:` as an admonition macro. To provide a concise summary for the following text or the text above. Alternatively a generic macro for custom admonitions.

**Comment by mojavelinux** [comment]
You can implement your own admonitions using a block extension. See https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/lib/custom-admonition-block/extension.rb. We won't be adding anymore types directly into core at this time (as it requires a language change, and we're not doing language changes right now).

**Comment by leonard84** [comment]
Ok, I understand, unfortunately not all Asciidoctor environments allow the usage of extensions, e.g., Github.

**Comment by mojavelinux** [comment]
Since the rendering of GitHub is out of our control, we view it as offering a basic preview, nothing more. There are many features that still don't work there properly, and those constraints will likely always exist. If that is your primary publishing target, then you do have to keep the document simple.

If you want to unlock all the features of Asciidoctor, you need to publish using GitHub Pages or similar mechanism. And then you can use those extensions.

And to clarify, I'm not necessarily saying no more admonitions ever, I'm saying we can't do it right now and in this forum. It has to go through the spec process.
