### ISSUE TITLE
Add CI for JRuby on Windows

### ISSUE THREAD

**Issue by slonopotamus** [asciidoctor/asciidoctor#3550]
Subj. This is a very problematic environment and possibly requires some fixes.

asciidoctor-pdf issue: asciidoctor/asciidoctor-pdf#1520, current state on JRuby+Windows: ~[920 examples, 316 failures](https://github.com/slonopotamus/asciidoctor-pdf/runs/408612060?check_suite_focus=true#step:5:17)~ after a bit of fixing, [920 examples, 5 failures](https://github.com/slonopotamus/asciidoctor-pdf/runs/408999273?check_suite_focus=true#step:5:53)

asciidoctor-epub3 issue: asciidoctor/asciidoctor-epub3#254, current state on JRuby+Windows: ~[13 examples, 6 failures](https://github.com/asciidoctor/asciidoctor-epub3/pull/255/checks?check_run_id=407964124#step:6:173)~ fully passes its test suite

**Comment by mojavelinux** [comment]
I'd like to start by using GitHub Actions with only JRuby on Windows. We can then gradually add more environments as needed. But I don't want to go full sail on GitHub Actions here yet.

**Comment by slonopotamus** [comment]
Hey, I didn't say anything about GitHub Actions here!)

**Comment by mojavelinux** [comment]
hehehe I should have been more clear. It seems AppVeyor doesn't provide JRuby as an option. So it might be our only hope ;)

**Comment by mojavelinux** [comment]
Now that the Windows CI jobs have been successfully migrated to GitHub Actions, I'm ready to proceed with this change. I will prepare a PR.

**Comment by mojavelinux** [comment]
From the first attempt, we've learned there are problems with the CLI tests on JRuby for Windows. I've captured the following comment from that PR:

I either need to switch away from IO.popen or just disable the CLI tests that are failing (on JRuby Windows). The reason I'm using IO.popen is because there was a bug in popen3 that was causing the test to fail in some version of JRuby. But that could be outdated now. So I need to reevaluate.

**Comment by mojavelinux** [comment]
What we do know is that we have to disable the Pygments tests on JRuby for Windows since that version of JRuby hangs when running pygments.rb.

**Comment by mojavelinux** [comment]
For some reason, the conditional checks around the tests are not working on JRuby for Windows. For example:

```rb
test 'description' do
end unless windows?
```

What's strange is that `windows?` returns true. It even fails if I nest the test in an unless conditional (instead of using the postfix syntax).

**Comment by mojavelinux** [comment]
I figured it out. It was a mixup between an instance method and a class method. The method missing fallback was making it look like the method was called when in fact it was not.

**Comment by mojavelinux** [comment]
We're down to 7 failing tests on JRuby 9.2 on Windows. These are very clearly bugs in JRuby since these tests work on JRuby on Linux and on C Ruby on Windows. But they seem to be errors in the test itself rather than the behavior of Asciidoctor. So I'm willing to rework the test harness as necessary to get them working.

**Comment by mojavelinux** [comment]
The only tests that fail on JRuby 9.1 for Windows are the tests that use run_command, which in turn use IO.popen. I don't understand the reason why IO.popen is failing in this case. But since there are only 6 uses of it, it seems reason to replace it with something else. But I'm going to defer that to a separate issue so we can get the rest of the tests running.

**Comment by mojavelinux** [comment]
While getting these tests running, I discovered a bug in JRuby for Windows. Time.now and Time.at honor the TZ environment variable, but IO#mtime does not. But I found a workaround by running the result through Time.at.
