### ISSUE TITLE
The anchor name rule maybe have an error.

### ISSUE THREAD

**Issue by diguage** [asciidoctor/asciidoctor#3565]
I had a document like as following:

```
[[0001]]
[source,{java_source_attr}]
----
include::{sourcedir}/MyCode.java[]
----
```

The anchor was not rendered well.

Then I change the anchor to `src-0001`, it is OK.

```
[[src-0001]]
[source,{java_source_attr}]
----
include::{sourcedir}/MyCode.java[]
----
```

[What are valid values for the id attribute in HTML? - Stack Overflow](https://stackoverflow.com/a/79022)

For [HTML 4](https://www.w3.org/TR/html4/types.html#type-id), ID and NAME tokens must begin with a letter; 

[HTML 5](https://html.spec.whatwg.org/multipage/dom.html#the-id-attribute) is even more permissive, saying only that an id must contain at least one character and may not contain any space characters.

**Comment by mojavelinux** [comment]
The legacy syntax (e.g., `[[idname]]`) does not allow the anchor to begin with a number (since AsciiDoc originally targeted XML-compliant output like DocBook and XHTML). HTML5 does not impose this restriction, so the modern syntax (e.g., `[#idname]`) does not enforce it either.

This is covered in the docs: https://asciidoctor.org/docs/user-manual/#anchordef
