### ISSUE TITLE
Allow sourcemap option to be switched via CLI

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#3569]
Allow the sourcemap option to be switched on using the CLI, specifically a CLI flag. Although the sourcemap option is not needed by the CLI, it may be used by extensions.

We will need to decide on both a short and long name that does not conflict with any existing flags.

**Comment by mojavelinux** [comment]
As a workaround the sourcemap can be enabled by requiring the following extension from the CLI: https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/lib/enable-sourcemap-preprocessor.rb

For example:

```
asciidoctor -r ./enable-sourcemap-preprocessor.rb doc.adoc
```

**Comment by mojavelinux** [comment]
Since the short flags are rather crowed and overloaded, perhaps we should only have a long flag for this option.

**Comment by hackingotter** [comment]
Using only a long flag only sounds good. I made the change to the pull request.

I saw the extension to enable the souremap just after this issue was created. I didn't find it when I was trying to get it enabled initially.
I think having it available as a flag and having that flag documented will highlight that it is something that needs to be explicitly enabled.
