### ISSUE TITLE
Compile asciidoctor to asciidoctor

### ISSUE THREAD

**Issue by clbarnes** [asciidoctor/asciidoctor#3572]
Bit of a weird one, but it might be nice for the tool to be able to use asciidoctor as a backend. This would basically just fill in `include` statements and variable substitutions, and remove comments. Line length could optionally be normalised (and/or, ideally, split lines wherever it looks like there's a full stop). Tables could potentially be converted into the standard asciidoctor form.

The motivation is that while developing, it's nice to split things out into multiple files, but if you wanted to distribute your document in plain text it would be preferable to have it all in a single normalised file. Markdown had "publishable as-is" as a design goal, and while I'm not sure whether asciidoc does as well, taking markdown's lunch money is always nice.

**Comment by mojavelinux** [comment]
I don't think it's weird at all. This has been requested numerous times, in various ways.

There are several meanings to what AsciiDoc to AsciiDoc would be. In one case, it means expanding includes. There's a script available in the extensions lab that will do that for you. See https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/scripts/asciidoc-coalescer.rb

Another case would be to clean up the document. That's possible by implementing a custom converter. However, outputting the inline syntax properly can be a bit of a challenge. We see that manifest in [kramdown-asciidoc](https://github.com/asciidoctor/kramdown-asciidoc). If you can manage to produce the model that kramdown-asciidoc uses, that gives you a path back to AsciiDoc.

Yet another case is preserving the source document in its original form (a full round trip). That's not easily achievable or even possible right now since the parser throws away all non-visible source information. Capturing the information in the model is something we'd need to address in the AsciiDoc spec.

And finally, there's the case of making surgical edits to the source document. That can be achieved by loading the document with the sourcemap option enabled, navigating to the node in the document model you want to modify, locating the line number where the node exists in the source, then updating the equivalent lines in the raw source. You can then write the raw source bad to disk. So you're using the DOM to map nodes to line numbers.

**Comment by mojavelinux** [comment]
The asciidoc-coalescer.rb script has been redesigned and published as the [asciidoctor-reducer](https://github.com/asciidoctor/asciidoctor-reducer). It has also been released to RubyGems.org as a gem named **asciidoctor-reducer**. You can find installation instructions in the README for that project.
