### ISSUE TITLE
Is xref inline macro regex still too greedy?

### ISSUE THREAD

**Issue by rolfedh** [asciidoctor/asciidoctor#3578]
Asciidoctor version 2.0.10 produces malformed xrefs  like:
`<a href="#some-id">] other content xref:some-other-id[</a>`

This seems to be the same issue described in [xref inline macro regex is too greedy #2450](https://github.com/asciidoctor/asciidoctor/issues/2450).

**Comment by rolfedh** [comment]
Here is a printout of our JIRA on this issue.
[[#CCS-3238] Update asciidoc to current version.pdf](https://github.com/asciidoctor/asciidoctor/files/4225005/CCS-3238.Update.asciidoc.to.current.version.pdf)

**Comment by mojavelinux** [comment]
Can you please provide an example (in text) that shows where it produces malformed output?

Given how the parser is currently implemented, there are going to be edge cases. (It's a trade-off of being able to use the shorthand of lightweight markup). You may very well be hitting one of them. What we need to determine is whether that is an expected edge case, or a common scenario that it's interpreting incorrectly.

**Comment by rolfedh** [comment]
For a live example, please see [](https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.3/html-single/administration_guide/index#Importing_Networks).
I've renamed the corresponding html file with a txt extension and attached it here.
[index.txt](https://github.com/asciidoctor/asciidoctor/files/4227244/index.txt)

**Comment by mojavelinux** [comment]
As far as I can tell, with Asciidoctor 2.0.10, this renders fine.

```
See <a href="#Adding_an_OpenStack_Network_Service_Neutron_for_Network_Provisioning">Adding an OpenStack Networking (Neutron) Instance for Network Provisioning</a> or <a href="#Adding_an_External_Network_Provider">Adding an External Network Provider</a> for more information.
```

So there's something else going on here. Perhaps an interaction with an extension or a problem elsewhere in the toolchain? The output you are showing is produced by DocBook, so there are definitely additional steps in the conversion. It's hard to say without knowing more.

Btw, for internal references, I recommend the syntax `<<Adding_an_OpenStack_Network_Service_Neutron_for_Network_Provisioning>>` instead of `xref:Adding_an_OpenStack_Network_Service_Neutron_for_Network_Provisioning[]`. This is generally a best practice we've recommended in Asciidoctor. The xref is reserved for page to page references (even though it works both ways).

**Comment by mojavelinux** [comment]
I'm not convinced you're using Asciidoctor 2.0.10. If I try this with Asciidoctor 1.5.6, I get the output you are showing. But if I use Asciidoctor 2.0.10, it works fine. That's where I'd focus my attention if I were you.

If that doesn't solve it, you'll need to submit a reproducible test case that's failing with 2.0.10 so that I can debug it.

**Comment by jboxman** [comment]
@mojavelinux, found this by accident, but FWIW you are correct, the version of asciidoctor in use is quite ancient, and ~ 1.5.6 sounds about right.
