### ISSUE TITLE
Large Landscape (%rotate) Tables do not Break across Pages

### ISSUE THREAD

**Issue by NanoBillion** [asciidoctor/asciidoctor#3594]
I'm using asciidoctor for docbook 5, then PDF creation.
I have somewhat longer tables in landscape mode that span more than one page.
The docs tell me to use `options="breakable"`, which is what I do, but the table does not break.
To reproduce, see test.txt below, and process it with

```
asciidoctor -b docbook5 -d book -o test.xml test.txt
saxon -o:test.fo -xsl:/usr/local/share/xsl/docbook-ns/fo/docbook.xsl -s:test.xml
fop -fo test.fo -pdf test.pdf
```
These are the tool versions:
```
Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.6.5p114 (2019-10-01 revision 67812) [amd64-freebsd13]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
Saxon 9.1.0.8J from Saxonica
FOP Version 2.3
```
`test.txt`:
```
== The Problem

.Long Table in Landscape Mode
[%rotate,cols="50,50",options="breakable"]
|====
|Ascii|Doctor
|Ascii|Doctor
|Ascii|Doctor
|Ascii|Doctor
|Ascii|Doctor
|Ascii|Doctor
|Ascii|Doctor
|Ascii|Doctor
|Ascii|Doctor
---50 more rows here---
|====
```

**Comment by mojavelinux** [comment]
This problem is outside the control of the Asciidoctor processor. Asciidoctor adds a processing instruction to the DocBook file for the DocBook toolchain to honor.

```xml
<table frame="all" rowsep="1" colsep="1" orient="land">
<?dbfo keep-together="auto"?>
<title>Long Table in Landscape Mode</title>
```

It's up to the DocBook toolchain (such as Apache FOP or dblatex) to honor this hint. From my tests, it seems that Apache FOP does not support breaking a landscape table. (I'm not sure about dblatex). So you'll need file this issue with the DocBook project.
