### ISSUE TITLE
Is asciidoctor able to ignore the manpage attributes when converting to PDF, HTML, XML?

### ISSUE THREAD

**Issue by subwaystation** [asciidoctor/asciidoctor#3606]
I am building some documentation with `asciidoctor` and I want to have both man pages and PDF, HTML and XML. https://asciidoctor-docs.netlify.com/asciidoctor/1.5/manpage/convert-to-man-page/#man-page-doctype tells me I need to have special attributes for manpage conversion, which works fine. However, if I convert to PDF, HTML or XML, the attributes destroy the nice formatted pages.
For an example take a look at https://github.com/vgteam/odgi/blob/docs/docs/asciidocs/odgi_docs.pdf.

Thanks for any feedback :)

Best,
Simon

**Comment by abelsalgadoromeroWD** [comment]
The format in the example you provide is not accurate. The Author line can only be present under the document title (level-0, 1 `=` sign) but you are writting it in a level-1 (2 `==`). That's why attributes are shown, see that they also appear in the HTML preview of GitHub*. Also the + is not necessary, this also points to the parser not interpreating it properly.

Seeing your Makefile you are in the right direction. Just need to write the manpages as normal documents starting at level-0(1=), then include them from _odgi_docs.adoc_ increasing the `leveloffset` (https://asciidoctor.org/docs/user-manual/#include-partitioning).

If you still need to remove/add some section based on the backend you can use conditionals like in this example https://asciidoctor.org/docs/user-manual/#anatomy, see the example with "{backend}".

* Don't take that as "GitHub Html preview is perfect"...

**Comment by abelsromero** [comment]
The format in the example you provide is not accurate. The Author line can only be present under the document title (level-0, 1 `=` sign) but you are writting it in a level-1 (2 `==`). That's why attributes are shown, see that they also appear in the HTML preview of GitHub*. Also the + is not necessary, this also points to the parser not interpreating it properly.

Seeing your Makefile you are in the right direction. Just need to write the manpages as normal documents starting at level-0(1=), then include them from _odgi_docs.adoc_ increasing the `leveloffset` (https://asciidoctor.org/docs/user-manual/#include-partitioning).

If you still need to remove/add some section based on the backend you can use conditionals like in this example https://asciidoctor.org/docs/user-manual/#anatomy, see the example with "{backend}".

* Don't take that as "GitHub Html preview is perfect"...

**Comment by mojavelinux** [comment]
@abelsromero is correct, this is invalid syntax for a document header:

```
== odgi (1)
Erik Garrison +
:doctype: manpage +
:release-version: 0.3 +
:man manual: odgi build +
:man source: odgi 0.3 +
:page-layout: base +
```

The first problem is that it's not under a doctitle, but rather a level-1 section. The second problem is that attribute entries cannot end with a hard line break. If they are being displayed, that means they aren't being parsed.

This would be the correct header syntax:

```
== odgi (1)
Erik Garrison
:doctype: manpage
:release-version: 0.3
:man manual: odgi build
:man source: odgi 0.3
:page-layout: base
```

If you want to filter lines so they only get read for a certain backend, you can use a preprocessor conditional:

```
ifdef::backend-manpage[]
:doctype: manpage
endif::[]
```

But keep in mind, the document header cannot have any blank lines.

**Comment by subwaystation** [comment]
Thank you @abelsromero @mojavelinux for the feedback.
I may have left out some important details. If you take a look at https://github.com/vgteam/odgi/tree/docs/docs/asciidocs I have one `.adoc` file for PDF, HTML, XML and in the `man` folder a copy of the corresponding `.adoc` file which has the correct header syntax for a manpage.
My main goal would have been to get rid of that copy pipeline of things.  I have to copy them because level-0 headers are not allowed in an included `.adoc`.

Knowing that I can do preprocessor conditionals will help a lot. I don't see a way to get rid of the copying...

**Comment by mojavelinux** [comment]
>  I have to copy them because level-0 headers are not allowed in an included .adoc.

They are allowed, you just can't have nested doctitles. They become part headings.

**Comment by subwaystation** [comment]
I am just not allowed to have level-0 headers in my file where I have all my includes..... Dumb people ask dumb questions xD
So thanks for the tips and continue the great work!

**Comment by subwaystation** [comment]
So `-b html`, `-b docbook` and `-r asciidoctor-pdf -b pdf` give me the following ERROR line with `asciidoctor`:
`asciidoctor: ERROR: odgi_build.adoc: line 1: level 0 sections can only be used when doctype is book`. The output itself is still nice looking. So I should consider this a warning?
If I would change to book type, the resulting layout in the PDF would be a mess.
The error does not appear with `-b manpage`.

**Comment by mojavelinux** [comment]
Thanks Simon. I'm glad the tips got you moving ahead.

**Comment by abelsromero** [comment]
> `asciidoctor: ERROR: odgi_build.adoc: line 1: level 0 sections can only be used when doctype is book`.

That can be fixed with the "leveloffset=+1" include attribute I mentioned before. This will add on depth level to sections of the included contents. So, lvl-0 is 1, lvl-1 is 2, etc.

```asciidoc
include::odgi.adoc[leveloffset=+1]

include::odgi_build.adoc[leveloffset=+1]

include::odgi_stats.adoc[leveloffset=+1]

include::odgi_sort.adoc[leveloffset=+1]
```

To validate that depth is correct, you can generate the HTML with a table of contents and numbered sections (toc and sectnums attributes). You should see this:
![image](https://user-images.githubusercontent.com/5781153/77751306-c043ef80-7025-11ea-93eb-868ecdfc6988.png)

I could render both manpages and pdf/html without copying foles and without warnings using your repo. If you have any problem, just ask I can push a PR by end of day.

**Comment by subwaystation** [comment]
Awesome @abelsromero ! Now I got everything in place. Thanks again :)
