### ISSUE TITLE
autodoc feature

### ISSUE THREAD

**Issue by feluxe** [asciidoctor/asciidoctor#3610]
Hi there,

I maintain a documentation website for a project which is written in reStructuredText/Sphinx. I came across asciidoc and I'm kind of hooked. I'm thinking about moving the documentation to asciidoc. There is one thing holding me back though. In the Sphinx world, there is a feautre called *autodoc*, which is very powerful for documenting software packages.

Autodoc allows you to import items from a source code file directly into your documentation.

For example if I have a class like this in a Python file:

```python
class Sgr(RenderType):
    """
    Define SGR styling rule.

    More info about SGR parameters: https://en.wikipedia.org/wiki/ANSI_escape_code#SGR

    :param num: A SGR number.
    """

    def __init__(self, num: int):
        self.args = [num]
```

I can import the class directly into `mydoc.rst` via:

    .. autoclass:: mypackage.Sgr

and shinx generates this documentation snippet from it:

![autodoc_example](https://user-images.githubusercontent.com/6545589/78032348-29e53600-7365-11ea-88a3-fbbd2909a6a3.png)

This works for multiple languages via plugins.

I'm wondering if something similar exists in the asciidoc world?

**Comment by Mogztter** [comment]
Hello @feluxe 

> I'm wondering if something similar exists in the asciidoc world?

I don't think it exists (yet) but Asciidoctor is extensible so you can write an extension to do just that. It's also a popular request of the Python community coming from reStructuredText/Sphinx so I think a lot of people will be interested!


You could write the following block macro:

```adoc
pythondoc::path/to/file.py[class=Sgr]
```

The block macro will read the file `path/to/file.py`, parse it and extract information about the class `Sgr`.
Here's an example of a block macro to get you started: https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/lib/tree-block-macro/extension.rb

**Comment by Mogztter** [comment]
Feel free to join https://gitter.im/asciidoctor/asciidoctor if you want to ask questions. I can help you get started.

**Comment by pawamoy** [comment]
I've written [pytkdocs](https://github.com/pawamoy/pytkdocs) to extract documentation from Python files. It's currently used by mkdocstrings (which is an "autodoc" plugin for MkDocs).

Maybe you could use it in such a macro? You'd need to spawn a Python process to run it (pytkdocs is written in Python). It reads input on stdin and outputs structured data in JSON so it would be easy to parse it again in Ruby I guess, and then generate the corresponding HTML (if that's how asciidoctor works!).

If you need more details on how to spawn the process, you can check [mkdocstrings' Python collector class](https://github.com/pawamoy/mkdocstrings/blob/master/src/mkdocstrings/handlers/python.py) or leave a message  on [gitter](https://gitter.im/mkdocstrings/community) :slightly_smiling_face: 

Of course there's always the option to use code from Sphinx's autodoc extension, but I personally was not able to untangle it. And since it's bundled in Sphinx you cannot install *just* the autodoc code.

**Comment by mojavelinux** [comment]
As Guillaume mentioned, this kind of functionality should be done as an extension. You can distribute the extension to make it easy to use (like Asciidoctor Diagram and Asciidoctor Tabs). But this is too specialized for the core language/processor.

Btw, the chat is now at https://chat.asciidoctor.org.

You may also want to use the extension lab for inspiration. See https://github.com/asciidoctor/asciidoctor-extensions-lab
