### ISSUE TITLE
Copy images at build

### ISSUE THREAD

**Issue by koppor** [asciidoctor/asciidoctor#3626]
I am trying to convert <https://github.com/MyLibreLab/user-documentation> using asciidoctor, because GitHub pages doesn't support AsciiDoctor. I went for the [AsciiDoctor docker image](https://github.com/asciidoctor/docker-asciidoctor), as I want to use the [AsciiDoctor GitHubAction](https://github.com/tonynv/asciidoctor-action) to directly publish the result. (Alternatively, I could work with the [AsciiDoctor Jekyll plugin](https://github.com/asciidoctor/jekyll-asciidoc), but I that seems to more complicated to configure)

When trying the convert the `README.adoc`, I get a single HTML file with following image content:

```html
<img src="pics/ex001_pic001.png" alt="ex001 pic001" width="100%">
```

This generated file merged the linked `ex001.adoc` into the html file. This is OK for me. However, the real image is locatd at `../ex001/pics/ex001_pic001.png`. Thus, the sub directory `ex001` is stripped from the image location. The file `ex001.adoc` is just converted and merged into the html - without further conversion.

As quick solution, I would propose that asciidoctor also copies the image to the output directory. I know that the statement is follows

> The processor only converts AsciiDoc to HTML. It does not copy other files around. That's typically left up to a build tool like Gradle, Maven, or [Antora](https://antora.org/).

(Source: https://discuss.asciidoctor.org/Output-to-another-folder-with-image-and-css-links-td6593.html)

My hope is that this opinion changed the last five years. It would make the script more "straight-forward" to use.

Work around for me

```bash
find . -name "pics" -exec cp -r {} out \;
```

where `.` is the directory for the main `.adoc` file. Assumption: pics are always contained in `pics` directory and picture filenames are globally unique.

Refs https://github.com/asciidoctor/asciidoctor/issues/2959 (because of similar title)

Cannot use PanDoc, because of https://github.com/jgm/pandoc/issues/1456.

**Comment by Mogztter** [comment]
Hello @koppor 

> This generated file merged the linked ex001.adoc into the html file. This is OK for me. However, the real image is locatd at ../ex001/pics/ex001_pic001.png. Thus, the sub directory ex001 is stripped from the image location. The file ex001.adoc is just converted and merged into the html - without further conversion.

You are using the `include` *preprocessor* directive to include _ex001.adoc_ into your README.adoc. On GitHub the include directive will be converted to a link because GitHub does not implement the include logic (ie. fetch the content from the git repository).
Anyway, the include directive is a preprocessor, it will be processed when the lines are read, but before the document structure is parsed.

In other words, you will get the same result if you copy/paste the lines from _exo001.adoc_ into _README.adoc_.
The problem is that you are using the following path in _exo001.adoc_:

```
image::pics/ex001_pic001.png[align="center", width=70%]
```

The path is incorrect when _exo001.adoc_ is included in _README.adoc_.
It depends on what you want to achieve, but instead of using a static images directory you could use a "dynamic" `imagesdir`: https://asciidoctor.org/docs/user-manual/#setting-the-location-of-images

```
image::ex001_pic001.png[align="center", width=70%]
```

And then define the `imagesdir` attribute depending on the context.

> The processor only converts AsciiDoc to HTML. It does not copy other files around. That's typically left up to a build tool like Gradle, Maven, or Antora.
> My hope is that this opinion changed the last five years. It would make the script more "straight-forward" to use.

I think this is still true.
The processor is already doing a lot of things but we don't want to include build tool features in Asciidoctor. In fact, we are trying to adhere to the Unix "philosophy": "Make each program do one thing well".

> Work around for me

I think that's a fine solution.
I've been using the Gradle plugin lately and I'm basically doing the same: https://asciidoctor.github.io/asciidoctor-gradle-plugin/master/user-guide/#_processing_auxiliary_files

**Comment by mojavelinux** [comment]
The Gradle and Maven plugin will both copy resources to the appropriate place where they can be used. This is not something the Asciidoctor processor is going to do. You could write an extension that looks for images in the parsed document and copies those images. However, there are so many ways that can be done, it is best kept as an extension IMO.
