### ISSUE TITLE
Link to CSV as source of table content

### ISSUE THREAD

**Issue by powermic** [asciidoctor/asciidoctor#3648]
I'm building a table from CSV like:

[format="csv", options="header"]
|===
include::ethnicity.csv[]
|===

I'd like to have an option to point to CSV file not a local file, but as link, something like:

[format="csv", options="header"]
|===
include::http://mydamain.com/files/ethnicity.csv[]
|===

**Comment by Mogztter** [comment]
Hello @powermic 

I think you can already do that. Since the target of your `include` directive is an URI, you will need to explicitly enable it for security reasons, see: https://asciidoctor.org/docs/user-manual/#include-uri

Does that answer your question?
The best medium for questions is probably the Asciidoctor gitter channel at https://gitter.im/asciidoctor/asciidoctor. If you do have more questions, please feel free to join :smile:

**Comment by powermic** [comment]
thanks @Mogztter , that helped.

for those who want to point to a Google Spreadsheet, here's how to do it:

[format="csv", options="header"]
|===
include::https://docs.google.com/spreadsheets/d/{key}/gviz/tq?tqx=out:csv[]
|===

**Comment by Mogztter** [comment]
Perfect!
Thanks for the follow-up and the tip! :ok_hand: 
Can we close this issue?

**Comment by powermic** [comment]
@Mogztter yes, please

**Comment by Mogztter** [comment]
I actually cannot close this issue, could you please do it :sweat_smile:
And feel free to join the gitter channel :wink:
