### ISSUE TITLE
Short section titles for the TOC?

### ISSUE THREAD

**Issue by nomeata** [asciidoctor/asciidoctor#3675]
I find myself in a situation where I want to have a longish section tite, but a shorter version of it in the table of content. In LaTeX I can write
```
\chapter[toc version]{doc version}
```

I could not find a way to achieve this with `asciidoc`. Is there one? And if not, could that be added?

**Comment by Mogztter** [comment]
Hello @nomeata 

I think you could define a custom attribute on the section:

```
[toctitle="Short title"]
== Longish section title
```

And then use a custom converter to use the value of the attribute `toctitle` (if defined) when converting the `outline`.

Does it make sense?

**Comment by nomeata** [comment]
Thanks! I guess I was hoping I wouldn’t need a custom converter, but it answers my question.

**Comment by mojavelinux** [comment]
I have contemplated using the reftext in the TOC instead of the title. That would allow you to customize the text directly above the section, though that same text would also be used in an xref. I'm not sure if that's the right thing to do. If that's too coupled, then supporting something to tocreftext (similar to what Guillaume proposed) might be the right solution. If you want to see this considered, please file an issue (or reopen this one).

**Comment by StefanSalewski** [comment]
I assume there is no progress yet? Creating a custom converter is still too difficult and too much work for me, sorry. Shorter TOC entries would be nice for the HTML version of my book -- I guess I can edit the final HTML document with a text editor to fix the TOC?

**Comment by mojavelinux** [comment]
The issue is closed, so no, there will be no progress. I'm sorry if creating a custom converter is too complicated, but that's what we currently offer. If you can submit a well-written proposal for new functionality, and that is agreeable to the community, then it may be considered.

> I guess I can edit the final HTML document with a text editor to fix the TOC?

You could use various extensions, including the postprocessor extension.
