### ISSUE TITLE
Quick filter in TOC

### ISSUE THREAD

**Issue by john-cj** [asciidoctor/asciidoctor#3696]
It could be useful to have a quick filter at the very top of TOC. When you have a lot of sections, and you need to quickly move to the section about cats, it's not so easy to find it with just your eyes. Of course, we can use Ctrl+F to use the standard browser search, but dedicated feature may be better.

Before:

```
Table of Contents     │ the contents of the document
┌──────────────┐      │ <-- the sidebar with the TOC and the quick filter
│              │      │
└──────────────┘      │
Cats and dogs         │
Why cats are nice     │
Why dogs are amazing  │
Cat names             │
Dog names             │
```

After:

```
Table of Contents     │
┌──────────────┐      │
│ cat nice     │      │
└──────────────┘      │
Cats and dogs         │
Why cats are nice     │
Cat names             │
```

**Comment by mojavelinux** [comment]
This is a nice idea and something that could be added using docinfo (either from a static file or an extension). We're not going to add this to the built-in converter because there are a myriad of ways it could be done and everyone will want something different and it will make this project more difficult to maintain.
