### ISSUE TITLE
Can I use unconstrained quotes all the time?

### ISSUE THREAD

**Issue by 997293** [asciidoctor/asciidoctor#3699]
I don't think there'll be any problem if I simply use unconstrained quotes (double formatting) all the time.

For example, can I simply write `I love **apples**.` instead of `I love *apples*`?

If the answer is yes, why do you recommend using constrain quotes when applicable? It would be more consistent if all the formatting is written in the same style (unconstrained).

Thank you!

**Comment by Mogztter** [comment]
Yes you can use unconstrained quotes (double formatting) all the time.
I believe that we recommend using constrained quotes because it requires less typing/less markup and arguably you rarely need to use unconstrained quotes. I'm not sure if there are other drawbacks when using unconstrained quoted style exclusively.

But as far as I know there's nothing preventing you from using unconstrained quotes all the time.

If you do have additional questions, please join our Gitter channel: https://gitter.im/asciidoctor/asciidoctor

**Comment by mojavelinux** [comment]
> I believe that we recommend using constrained quotes because it requires less typing/less markup and arguably you rarely need to use unconstrained quotes.

Precisely what I was going to say.

The other drawback is that unconstrained quotes cannot always be nested. You need both constrained and unconstrained to cover those use cases (because the unconstrained variants can match pairs where constrained variants cannot).

As Guillaume said, if it works for you, then you are free to always use unconstrained quotes. But I strongly recommend against it as a general practice because it's not in the spirit of AsciiDoc's conciseness.

**Comment by mojavelinux** [comment]
I also think that unconstrained communicates intent. It shows that something should be formatted where it normally wouldn't be allowed.
