### ISSUE TITLE
skipping reference to missing attribute when writing in math mode

### ISSUE THREAD

**Issue by thomas-saigre** [asciidoctor/asciidoctor#3703]
Hello !
I use asciidoctor (with antora) to write some math with `latexmath` and I'm confronted with an issue when a compile the site. For example, I write `stem:[x^{2}]`, but at the compilation, it gives a warning message `asciidoctor: WARNING: skipping reference to missing attribute: 2`. With all the files, it leads to more than 200 warnings lines, hiding more critical warnings in the log !

To avoid it, I but the attribute `attribute-missing` to `skip`, but if there is somewhere a real attribute which is missing, I won't see it !

Is it possible to disable those warnings only in math mode ?

Thanks !

**Comment by mojavelinux** [comment]
This shouldn't be happening. The stem macro acts as a passthrough with no subs by default. (You would have to write it as `stem:n[x^{2}]` in order for attributes to be replaced, and even then it wouldn't look for `{2}` since that's not a valid attribute reference).

This sounds either like an Antora issue or something with your configuration. Please open an issue in Antora at https://gitlab.com/antora/antora and we will investigate it there.

**Comment by mojavelinux** [comment]
My memory served me incorrectly here and I misspoke. `2` is in fact a valid attribute name. So only *if* subs are enabled, then we would expect the warning.

```
stem:c,a[x^{2}]
```

This issue has been moved here: https://gitlab.com/antora/antora/-/issues/651
