### ISSUE TITLE
Allow to replace text of include directive

### ISSUE THREAD

**Issue by wimdeblauwe** [asciidoctor/asciidoctor#3725]
Suppose you have this Java file:

```
public class User {
  private String name;
  private LocalDate birthday;

  // tag::getters-and-setters[]
  public void setName(String name) {
    this.name = name;
  }

  public String getName() {
    return name;
  }

  public void setBirthday(Birthday birthday) {
    this.birthday = birthday;
  }

  public String getBirthday() {
    return birthday;
  }
  // end::getters-and-setters[]
}
```

I can include this file like this:

```
[source,java]
----
include::User.java[tags=!getters-and-setters]
----
```

Which will output the java class without the getters and setters. But would I would like to have is this:

```
public class User {
  private String name;
  private LocalDate birthday;

  // getters and setters omitted
}
```

Obviously, we would need a way to specify that comment. Maybe something like this:
```
[source,java]
----
include::User.java[tags=!getters-and-setters,exclusion-comment=getters and setters omitted]
----
```

This is just a rough proposal to see if there is interest in this and open the discussion on how the syntax for such a thing could work.

**Comment by mojavelinux** [comment]
You might find this extension that I wrote for the Spring project useful: https://github.com/spring-io/asciidoctor-extensions#code-chomping It's written for Asciidoctor.js, but could be ported to Asciidoctor Ruby. And it may need some additional functionality (such looking for a tag range)

The idea would be to include the whole file, then let the extension remove lines (instead of the include directive) and replace them with a placeholder. To be clear, the extension would be a replacement for the use of the include directive's `tags` functionality.

As for adding a replacement for an excluded region of text into Asciidoctor core, it's just too complex to accommodate all the possible scenarios. That's why I think this is best done using an Asciidoctor extension.

If you need help getting any of that set up, feel free to ask in the project chat at https://chat.asciidoctor.org.
