### ISSUE TITLE
Replace Erubis by Erubi

### ISSUE THREAD

**Issue by voxik** [asciidoctor/asciidoctor#3737]
Erubis is dead upstream almost 10 years, without any response. Ruby on Rails community replaced Erubis by Erubi, which provides mostly similar features, while the code is simpler and faster. Would you consider replacing Erubis by Erubi?

**Comment by voxik** [comment]
BTW, I want to remove rubygem-erubis from Fedora, that is my main motivation, therefore I have opened this Fedora [PR](https://src.fedoraproject.org/rpms/rubygem-asciidoctor/pull-request/4)

**Comment by mojavelinux** [comment]
I have no objection to this change. Erubis is an optional dependency that was introduced because, at the time, it was substantially faster than ERB. That may no longer be true. Regardless, we can either map the request to load Erubis to Erubi, or simply ignore it (since ERB will handle it). It's not critical to how this program functions. I'll explore the options and take action.

**Comment by mojavelinux** [comment]
I went ahead and added support for erubi instead of removing erubis just in case someone is relying on its quirks. But the use of erubis should be considered deprecated, all the relevant tests now use erubi, and erubis has been removed from the gemspec. (Hence, erubis is only a runtime dependency and assumes the user knows what he/she is doing).

**Comment by voxik** [comment]
Nice, thank you. That is precisely what I have been after.
