### ISSUE TITLE
Substitution in CLI attributes with the inline `pass` macro does not work

### ISSUE THREAD

**Issue by ojamond** [asciidoctor/asciidoctor#3744]
It seems that the inline macro pass does not work for CLI attributes.

If I render the following snippet:
```
:foo: crazy
:bar: pass:q,a[{foo} *world*]

hello {bar}
```
I get what I expect: _hello crazy **world**_

But if I pass the two attributes to the CLI (`asciidoctor-pdf -a foo=crazy -a bar='pass:q,a[{foo} *world*]' foo.adoc`), it does not work:
_hello pass:q,a[{foo} *world*]_

**Comment by mojavelinux** [comment]
> It seems that the inline macro pass does not work for CLI attributes.

That is correct. Substitutions are not applied to attribute values defined via the CLI. That is something that the calling application (or user) needs to do.

**Comment by ojamond** [comment]
I am not sure to understand what you mean by 'the calling application (or user) needs to do'...

In my case, I plan to use antora to build the documentation of my software, and I would like to define attributes in the `antora-playbook.yml` or the `antora.yml` to act as 'latex macros'.

Does that mean that it is an issue related to antora, and not asciidoctor?

**Comment by mojavelinux** [comment]
In your case, Antora is the calling application. The ability to use attribute references is related to Antora and also happens to be an open issue. See https://gitlab.com/antora/antora/-/issues/633.

The CLI behavior will still be the same. If you define an attribute from the CLI, the value must be preresolved (since it doesn't have an implicit order relative to other attributes).
