### ISSUE TITLE
Add a texmath processing instruction to docbook output

### ISSUE THREAD

**Issue by nobuta05** [asciidoctor/asciidoctor#3746]
I'm not sure if this should be resolved by asciidoctor or dblatex. So I'm here.

I tried to convert the following adoc file into pdf via dblatex:

```asciidoc
// test.adoc
:stem: latexmath

= test

[stem]
++++
\begin{align*}
  \sqrt{4} = 2
\end{align*}
++++
```

```shell
$ asciidoctor -b docbook5 test.adoc
$ dblatex test.xml
```

The above commands fails when executing dblatex. This is because dblatex automatically insert math mode delimiters( eg. '$', '\\[' ) if dblatex thinks they are missing. The detail is written in [here](http://dblatex.sourceforge.net/doc/manual/ch03s09.html#sec-alttex-delimiters). However, the statement "\begin{align}" is allowed in paragraph mode. In order to avoid inserting the delimiters automatically by dblatex, we need to add [texmath processing instruction](http://dblatex.sourceforge.net/doc/manual/pi-texmath_delimiters.html) to docbook file, which is generated by asciidoctor.

Should I modify "lib/asciidoctor/converter/docbook5.rb" by adding an attribute like `[stem,texmath-delimiters=user]` ? or seek a way to not change the asciidoctor source code?

Thank you!

**Comment by mojavelinux** [comment]
This is the first I've ever heard of this problem. Obviously, we want to produce DocBook that the toolchain can handle. If you know what the correct output is, please submit a PR to make that change and I'll review and test it.

I would prefer to not add any additional attributes. The converter should just know what it needs to output and output it appropriately. However, if it's not something that can be detected, meaning this is a special case, only then would advise adding an attribute. But I would like it to be something less specific / low-level, such as mode=paragraph or something along those lines.

For the record, here's the error I get:

```text
Package amsmath Error: \\begin{align*} allowed only in paragraph mode.\ntest.tex:52: leading text: $\\begin{align*}\nUnexpected error occured\nError: pdflatex compilation failed\n"
```

I don't really know what that means.

(It seems that using `aligned` instead of `align*` fixes the issue).

I'll be honest, this sort of seems like a dblatex problem (or a problem with the equation itself).

**Comment by nobuta05** [comment]
Thank you for your reply!

As you said, this seems like a dblatex problem because it is decided by dblatex whether the delimiters are inserted or not.
I'm not familiar with docbook format and XSLT, but the texmath processing instruction seems be only used in dblatex.

It makes sense that careless additional attributes should not be done. I'll address this problem in dblatex repo.
I'm glad to hear your opinion.

--

The error you got is the same with mine.

> It seems that using aligned instead of align* fixes the issue

I had forgotten that the way can avoid this error. Thank you!
