### ISSUE TITLE
double hyphens in links

### ISSUE THREAD

**Issue by pwright** [asciidoctor/asciidoctor#3777]
```link:https://hp--community.force.com/[]```

renders as a link to https://xn--hpcommunity-zg3f.force.com/

ie the double hyphen messes things up.. I can escape it but trying to avoid having to escape all instances in vscode-didact, see https://github.com/redhat-developer/vscode-didact/issues/231

**Comment by mojavelinux** [comment]
What you are describing is the behavior of AsciiDoc and I cannot change that. Various options to escape the replacement text are described in this section: https://asciidoctor.org/docs/user-manual/#complex-urls The most DRY approach would be to define the link in an attribute.

FYI, the link: prefix is NOT required when the target is a URL. That's because https: is itself a macro prefix. So if you want to avoid typing, I would start there ;)

**Comment by pwright** [comment]
just to note that  using an attribute doesn't resolve this:

```
:link-with-dashes: https://hp--community.force.com/

{link-with-dashes}[test link]
```

**Comment by mojavelinux** [comment]
Ah, you're right. This case is different from what is cited in the docs. Double underscore is text formatting, whereas the hyphen is a post replacement. So the later happens after the attribute reference is resolved.

You could still use an attribute to solve it. You just add the escape mechanism, such as a backslash or character reference, in the attribute value. At least you have centralized the required escaping.

**Comment by mojavelinux** [comment]
If you aren't going to use an attribute reference, then you can either shorthand your solution as:

```
This URL has repeating hyphens pass:m[https://hp--community.force.com/].
```

Or you can use a backslash:

```
This URL has repeating hyphens https://hp\--community.force.com/.
```

Or you can use an inline passthrough after the protocol:

```
This URL has repeating hyphens https://+hp--community.force.com/+.
```
