### ISSUE TITLE
asciidoctor v2.0.11 uses ruby 2.3 constructs

### ISSUE THREAD

**Issue by jwillemsen** [asciidoctor/asciidoctor#3827]
We noticed that asciidoctor [v2.0.11](https://github.com/asciidoctor/asciidoctor/releases/tag/v2.0.11) uses ruby 2.3 constructs, see below for the error when using ruby 2.0. Issue #2764 talks about keeping older ruby 2 support but there is nowhere in the v2.0.11 release notes a remark that now ruby 2.3 is again the minimal ruby version required. Not sure whether this needs an update to the release notes or a change in the code to put back ruby 2.0 compatibility 

```
/lib/asciidoctor/table.rb:242: syntax error, unexpected '.' (SyntaxError)
... = column.style || attributes&.[]('style')) == :asciidoc || ...
... ^
```

**Comment by jwillemsen** [comment]
Looks https://github.com/asciidoctor/asciidoctor/pull/3790 did add the ruby 2.3 construct we encountered

**Comment by Mogztter** [comment]
@jwillemsen Asciidoctor 2.0.0 dropped unsupported versions of Ruby (namely, Ruby < 2.3 and JRuby < 9.1): https://github.com/asciidoctor/asciidoctor/releases/tag/v2.0.0.

In other words, Ruby < 2.3 is unsupported since 2.0.0.
I don't know which version you are using but I would recommend to upgrade as soon as possible.
For reference, support of Ruby 2.3 has ended more than one year ago: https://www.ruby-lang.org/en/news/2019/03/31/support-of-ruby-2-3-has-ended/

**Comment by jwillemsen** [comment]
The 2.0.10 release did work with ruby 2.0 which is the default ruby version on rhel/centos 7. For the moment we use asciidoctor 2.0.10 on these platforms.

**Comment by Mogztter** [comment]
There are several options here.
You can still install a recent version of Ruby on CentOS 7 using at least one of the following methods:
- Add [CentOS Software Collections Repository](https://wiki.centos.org/AdditionalResources/Repositories/SCL) and install a modern version of Ruby
- Install a [Ruby manager](https://www.ruby-lang.org/en/documentation/installation/#managers) to manage Ruby independently of the package manager (yum)

Alternatively, we could restore compatibility with Ruby 2.0, even if we don't official support it, but then we cannot use any language feature introduced in Ruby > 2.0. This issue actually proves that it's a slippery road because we cannot guarantee that Asciidoctor is compatible with Ruby 2.0 if we don't effectively support it (i.e. at least running the tests suite against Ruby 2.0).

And lastly, as you mentioned, you can keep using Asciidoctor 2.0.10, until you upgrade on a newer version of Ruby (or we decide to restore compatibility).

Not sure what @mojavelinux wants to do here...

**Comment by mojavelinux** [comment]
In this case, since it is such a minnor change, I can restore support for Ruby 2.0 in a 2.0.12 patch release, but do note that Ruby < 2.3 is EOL and we follow that schedule. We also announced this clearly in the release notes for Asciidoctor 2.0.0: "It also goes a long way towards modernizing the codebase by dropping unsupported versions of Ruby (Ruby < 2.3 and JRuby < 9.1)

We will definitely be using features from Ruby >= 2.3 in Asciidoctor 2.1.

**Comment by mojavelinux** [comment]
What we should have done was use Ruby 2.3 constructs in Asciidoctor 2.0.0. Since we didn't, that's why I'm willing to restore it in this case.

**Comment by mojavelinux** [comment]
@Mogztter I think the lesson we can learn here is that, if possible, we should use constructs from the minimum version we require as soon as possible so there are no misconceptions about what we're supporting.

**Comment by Mogztter** [comment]
I agree.
I can understand why we've decided to [restore compatibility with older versions of Ruby 2 just before releasing Asciidoctor 2.0.0](https://github.com/asciidoctor/asciidoctor/issues/2764#issuecomment-478324266) but at the same time it sends the wrong signal: "We are not supporting Ruby 2.0 but we are still making sure that it works".

Having said that it will not always be possible to use constructs from the minimum version.
Since we don't want to use `required_ruby_version`, maybe we should add deprecation warnings/errors? I think it would help users understand what is going on.
In this case, Ruby throws a `SyntaxError` but it's not clear (if you are not familiar with Ruby syntax) that the root cause is that you are using an outdated version of Ruby. It's also not clear which version is the minimum version required from the error.
I think it would helpful, if we could issue a warning/error message saying something like:
```
ERROR: Ruby 2.0 is unsupported, please use Ruby 2.3 or greater to run Asciidoctor 2.0.10
```

We could even warn users before a major version or when a version of Ruby is deprecated:

```
WARN: Ruby 2.3 is deprecated and will be unsupported in the next major version of Asciidoctor, please upgrade to Ruby 2.4 or greater
```

Probably with an option to turn deprecation warnings off.
What do you think?

**Comment by mojavelinux** [comment]
> We are not supporting Ruby 2.0 but we are still making sure that it works

Yes, that was, I think, a mistake. But we're walking a fine line because Linux packagers like to repackage gems that are not supposed to run on older version of Ruby so they work with the distribution, which effectively side-steps any `gem install` restrictions.

> Having said that it will not always be possible to use constructs from the minimum version.

True. But in Ruby there are loads of opportunities since the language changes so quickly.

> I think it would helpful, if we could issue a warning/error message saying something like:

I generally dislike nag messages (since, as a user, they make me very upset). But putting something the WARNING level might not be a bad idea. Still, we support so many Ruby runtimes that even that assertion is a tricky thing to get right (for example, JRuby doesn't always support an exact Ruby runtime).

One thing that is really going to help here is the documentation. We will have a page which states the minimum runtime versions and we can refer to that as a stable place to be an arbiter of situations like this.

**Comment by Mogztter** [comment]
> I generally dislike nag messages (since, as a user, they make me very upset)

Yes me too, it's true that a warning message asking you to upgrade is annoying but it also gives a heads up and time to plan for a future upgrade.
That's why we should really add an option to disable deprecation warnings if we decide to add them.

The error message is a bit different because it actually gives a potential solution. If a `SyntaxError` is thrown and the user is running Ruby 2.0 then we can suggest a fix.
It's all about sharing valuable information when something goes wrong. Currently, we only provide a Ruby stacktrace that might be unhelpful.

I guess a first step would be to:

1. catch `SyntaxError`
2. check if we can reliably get the runtime version
3. check if the runtime version is unsupported
4. suggest a possible fix to the user (ie. upgrade to a newer version of Ruby)

Arguably, a user should not report an issue when using an unsupported version of Ruby. So in theory, we could enhance all runtime errors:

**If we cannot reliably get the runtime version of if the runtime version is supported**
```
An unexpected error occurred! You can submit a bug report at: https://github.com/asciidoctor/asciidoctor/issues
```

**If the runtime version is unsupported**
```
An unexpected error occurred! Ruby 2.0 is not supported, please upgrade to Ruby 2.3 or greater before submitting a bug report
```
(just an example, we could use a more friendly/positive/engaging message)

> Still, we support so many Ruby runtimes that even that assertion is a tricky thing to get right (for example, JRuby doesn't always support an exact Ruby runtime).

I think it's fine if we only add it when we can reliably infer the runtime version.

> One thing that is really going to help here is the documentation. We will have a page which states the minimum runtime versions and we can refer to that as a stable place to be an arbiter of situations like this. (Thus far, it hasn't been clear and it's not fair to enforce it because of that).

:+1:

**Comment by mojavelinux** [comment]
>  If a SyntaxError is thrown and the user is running Ruby 2.0 then we can suggest a fix.

There's nothing we can do here because the syntax error is thrown before any code is run. And that's another problem with the nag message (though it could nag very early in the script, maybe before the SyntaxError is reached).

**Comment by Mogztter** [comment]
Ah, right... 😩
Maybe we should continue this discussion in a dedicated issue: "Add a deprecation message when running an unsupported version of Ruby". I think the title gives enough room to discuss how we should implement it.

**Comment by mojavelinux** [comment]
You can open an issue, but I can tell you I'm just not keen on the idea. This sounds like something we should try to solve first with documentation. The code needs to focus on doing the task at hand, not worrying about how it is being misused.

**Comment by slonopotamus** [comment]
I actually don't understand the logic behind using Asciidoctor 2.0.11 combined with _stable_ CentOS 7 and ancient Ruby 2.0. The whole concept of "stability" is that you use time-proven software releases, with each and every bug ~fixed~ documented. But running the latest release of a piece of software makes system no longer _stable_. Wouldn't it make more sense to stick to old Asciidoctor release from the same era as all other software in particular distribution release? I'd even say that combining a single piece of modern software with old other components is even more unstable than combining several modern pieces together (like this issue clearly shows) because developers do not test such combination!

**Comment by mojavelinux** [comment]
@slonopotamus I can't argue with that. All great points.

In this case, I decided to revert the change really for my own reasons. It was not necessary to use this syntax in just one case (when I switch to it I want it to be comprehensive). So I think that decisions should be separate from whether this request is problematic...which for reasons you and others have cited, it is problematic.
