### ISSUE TITLE
Role attribute ignored for inline images and icons in docbook backend

### ISSUE THREAD

**Issue by pela9** [asciidoctor/asciidoctor#3832]
The "role" attribute seems to be ignored in the docbook translation of inline images and icons. I can't see any indications in the manual for this behavior. In any case, the attribute is useful for further, custom translation of the docbook output. And because the "role" attribute is available for all docbook elements it should be easy to pass it to one of the docbook elements involved in the translation. I guess the  inner `<imagedata>` element is the obvious candidate, but passing it to the containing `<imageobject>` or `<inlinemediaobject>` would be OK too.

**Comment by mojavelinux** [comment]
This behavior was never added because it is not present in AsciiDoc Python. But I don't see any problem with adding it now. And it's not just the role attribute. It's all the common attributes.

The appropriate place to add it is the `<inlinemediaobject>` since that is the outer-most container, which is where the converter always adds common attributes.

**Comment by mojavelinux** [comment]
Ah, but we don't pass the id through on inline images. That's a separate issue then. So role it is, then.
