### ISSUE TITLE
Preamble on documents with only title

### ISSUE THREAD

**Issue by gzagatti** [asciidoctor/asciidoctor#3845]
It is usually the case that when converting a document with a title and sub-headers, Asciidoctor will produce a `preamble` section for the paragraphs that come before the first sub-header.

However, when the document does not have sub-headers the `preamble` section is not rendered.

Upon some investigation, I realised that this behaviour is caused by the [following line in the parser](https://github.com/asciidoctor/asciidoctor/blob/9ee28751c2709d939c3e58e6ea4809bc519500ca/lib/asciidoctor/parser.rb#L436):

```rb
if book || document.blocks[1] || !Compliance.unwrap_standalone_preamble
    ...
```
It seems to be the case, that the preamble will only be created if the document has more than one block, so it does not include documents with a single block such as when we only have a main title (ie. `h1`). I believe it would be more desirable if the short-circuit considered `document.blocks[0]` instead of `document.blocks[1]` in order to include these corner cases.

My use case is as following. I create posts for my blog in Asciidoc format. Sometimes posts do not have sub-headers as is a short post. In those cases no preamble section is created. The problem is that my style-sheets assume that there will always be a preamble section which is basically the section that comes after the main title, even if it encompasses the whole text, and the text is divided into sections

Given this inconsistent behavior, I believe this might be a bug as the sectioning should not be dependent on the number of headers.Either the article is sub-divided into sections or not. Unless the reader knows about this distinction, she/he is prone to run in this kind of issues without a clear understanding.

I also find that the `Compliance.unwrap_standalone_preamble` is poorly documented and it is not obvious how to toggle the option in the CLI (or in the adoc metadata) or its impact on the final document.

**Comment by mojavelinux** [comment]
As you have pointed out in your last paragraph, this behavior is controlled by the `Compliance.unwrap_standalone_preamble` and is thus intentional / by design. The documentation on that flag makes this clear.

> Asciidoctor will unwrap the content in a preamble if the document has a title and no sections.

While this default may be inconvenient for you, it is convenient for others. That's why we have defined this setting.

Since this is a global setting, it's not something that can be toggled from the CLI currently. However, you can create a Ruby script that toggles this setting:

disable-unwrap-standalone-preamble.rb
```
require 'asciidoctor'

Asciidoctor::Compliance.unwrap_standalone_preamble = false
```

then require this script when calling Asciidoctor as follows:

```
asciidoctor -r ./disable-unwrap-standalone-preamble.rb doc.adoc
```

I'm not considering changing the default behavior right now. That's because a document which has no sections by very definition has no preamble. But I will keep the compliance setting for when you want to alter that definition.

**Comment by gzagatti** [comment]
Thanks @mojavelinux for your quick response. 

I was already using a custom plugin to render my blog, so it fortunately was quite straightforward to follow your advice.

I am not sure which part of the documentation this is defined, but I did spend quite a bit of time to figure out how to fix this issue and at the end even changed my document type to `book`.

Your proposal is much cleaner and would be great if we could be able to find it more easily in the on-line documentation. It seems like the Compliance module has many options that might be useful to others.

**Comment by mojavelinux** [comment]
> I am not sure which part of the documentation this is defined,

I didn't mean to suggest it was in the user documentation. It's in the source code (see https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor.rb#L139-L142). It should also be included in the API docs, but I cannot sort out how to make that work yet.

We're currently in the process of reworking the user documentation and will consider including a section about the Compliance module. Though it will probably be near the bottom. You're the only person to my knowledge who's ever wanted to change one of those settings. And we still haven't decided exactly how much we want to promote them since they were mostly intended as a bridge from AsciiDoc Python.
