### ISSUE TITLE
Anchor reference are not working in html if put after a link

### ISSUE THREAD

**Issue by Puccet** [asciidoctor/asciidoctor#3848]
- [X] Bug report
- [ ] Feature request
- [ ] Question

**Description**

Anchor reference are not working if put after a `link`

```
[[_anchor_]]
If after a  link:https://ulstandards.ul.com[link,window=_blank] you put a cross reference to an anchor <<_anchor_,Reference text>> e <<_anchor_,Another text>>, in the resulting HTML file the first time the internal link to the anchor is not produced correctly it's #_anchor%3C/em%3E instead of #_anchor_ , the second time it is produced correctly .
```

**Environment information**

* asciidoctor-maven-plugin version: ___
* asciidoctorj version: 1.5.7 and 1.5.8

Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /Users/fabio/.sdkman/candidates/maven/current
Java version: 11.0.7, vendor: Azul Systems, Inc., runtime: /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home
Default locale: it_IT, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.7", arch: "x86_64", family: "mac"

**Comment by Puccet** [comment]
Confirmed also in 2.0.12

**Comment by mojavelinux** [comment]
The problem you are encountering is that you are getting your text formatting mixed up with your reference names. Generally, it's best to avoid having an ID begin and end with an underscore as that has special meaning in AsciiDoc. In this particular case, though, the problem is coming from the use of `window=_blank`. You can solve this by using the shorthand:

```
[[_anchor_]]
If after a https://ulstandards.ul.com^[link] you put a cross reference to an anchor <<_anchor_,Reference text>> e <<_anchor_,Another text>>
```

Though a better solution is to not have an ID start and end with underscore. This is not a bug, but rather a limitation of the AsciiDoc language currently.

btw, you don't need to start a URL macro with link: since https: is already a macro name.

**Comment by Puccet** [comment]
Hi Dan,

Thank you for your support, I'm a newbie and didn't known that

I've fixed the anchor IDs.

Thanks again

**Comment by Puccet** [comment]
Just to let you know, the notification email I've received had the ^ in the wrong place so it was not working, opening the issue in GH and looking to your answer I've noticed it.

Ciao!

![Schermata 2020-11-10 alle 21 37 08](https://user-images.githubusercontent.com/5746022/98730681-f196e300-239c-11eb-9e8f-960d2da3c0ac.png)
