### ISSUE TITLE
If a bare URL is followed by a period and a closing parenthesis, the period should not be treated as a part of the URL

### ISSUE THREAD

**Issue by john-cj** [asciidoctor/asciidoctor#3860]
```
(The homepage for the Asciidoctor Project is https://asciidoctor.org.)
```

The period is treated as a part of the URL.

A workaround that I use:

```
(The homepage for the Asciidoctor Project is link:++https://asciidoctor.org++[].)
```

Probably a bug.

**Comment by mojavelinux** [comment]
Your workaround is excessive. This is a case when you need to use a URL macro instead of an autolink.

```
(The homepage for the Asciidoctor Project is https://asciidoctor.org[].)
```

There are only so many scenarios the autolink can cover. This is one of them that we're not able to anticipate.

**Comment by mojavelinux** [comment]
I reviewed the code and I think it's reasonable to handle this exception. It's common for a bare URL (autolink) to be followed by a period instead of round brackets. It's a very minor check.

**Comment by Mogztter** [comment]
I didn't know but apparently periods can go inside parentheses if an entire sentence is inside the parentheses:

```
Please read the analysis. (You'll be amazed.)
```

Another edge case with punctuations and parentheses would be:

```
Should I ask question on Twitter or in the chat room (https://gitter.im/asciidoctor/asciidoctor)?
```

_In French, it won't be an issue because a space is required before the question mark 😉_

In the above case, Asciidoctor will produce the following link:

```html
<a href="https://gitter.im/asciidoctor/asciidoctor)?" class="bare">https://gitter.im/asciidoctor/asciidoctor)?</a>
```

Having said that, I agree with Dan we need to be careful and there are only so many scenarios the autolink can cover.

**Comment by IvxLars** [comment]
Technically the root dot is implicit in the domain asciidoctor.org(.), but it is rarely used day-to-day.  
So the URL/URI parser in the code is including the dot as per specs, but it was already when RFC was written in '87 'often omitted'

https://tools.ietf.org/html/rfc1034 (section 3.1)

At least worth a mention in the changelogs if the workaround is made, if someone documenting DNS system or the likes a lot.

**Comment by mojavelinux** [comment]
Thanks for the insight, @IvxLars. In that case, the URL macro would be appropriate. The goal of autolinks isn't to detect every URL, but rather to act as a shorthand to save some typing.

**Comment by mojavelinux** [comment]
I think what makes sense is to apply the same exceptions we currently apply without the ) to the cases with the ). That would include period, semi-colon, colon, and question mark. That way, the exceptions are consistent.

**Comment by mojavelinux** [comment]
I did some research on this and it turns out that AsciiDoc.py does not include the end of sentence punctuation in the target of an autolink. Asciidoctor is not as discerning. Asciidoctor handles period correctly, but not question mark or exclamation point. So I'll extend the logic to prevent all three from getting captured.
