### ISSUE TITLE
{indir} and {inputdir} don't work in asciidoctor

### ISSUE THREAD

**Issue by randybias** [asciidoctor/asciidoctor#3925]
In the simplest case possible:

**$ cat test.adoc**

> = My test
> 
> This tests some builtin vars that might be broken:
> 
> {docdir} +
> {indir} +
> {inputdir} +
> {outdir} +

asciidoc renders all of these, but asciidoctor does not handle indir or inputdir.  Is that expected behavior or a bug?  I can't find anything in mailing lists, bug tracking, or elsewhere noticing this behavior, but it's easily reproducible.

**Comment by randybias** [comment]
I see.  Browsing the code it looks like they were deliberately disabled:

> lib/asciidoctor/load.rb:        # NOTE defer setting infile and indir until we get a better sense of their purpose
> lib/asciidoctor/document.rb:      #attrs['indir'] = attrs['docdir']

**Comment by mojavelinux** [comment]
You are correct that the exclusion is intentional. Given the way that Asciidoctor works, implementing it is not possible (without side effects). This is due to the fact that Asciidoctor and AsciiDoc Python work in a fundamentally different way and this feature could not be carried forward. Asciidoctor parses the document into a tree whereas AsciiDoc Python is streaming. We will consider how this might be supported in the AsciiDoc spec. But until then, it is not a feature Asciidoctor will provide.

**Comment by mojavelinux** [comment]
This is also a duplicate of #2608.

**Comment by randybias** [comment]
Got it.
