### ISSUE TITLE
whitespaces should be supported in subscript and superscript

### ISSUE THREAD

**Issue by ielfretter** [asciidoctor/asciidoctor#3951]
Hi, 

The following sample doesn't render to subscript:

~~~
= THE ROBIN

A poem by ~Laurence Alma-Tadema~
~~~

Yet the following does:

~~~
= THE ROBIN

A poem by ~Laurence{sp}Alma-Tadema~
~~~

In the first example it looks as if the white space causes the behaviour to break but I'm not sure whether this is according to design; I based the example on what is written in [paragraph 10.2](https://asciidoc.org/userguide.html#_superscripts_and_subscripts) of the asciidoc manual which suggests that the first example should have been rendered _also_.

**Comment by mojavelinux** [comment]
The current restriction is intentional and by design. Although it may not be obvious at first, if we allow spaces in the text, then the markup characters have the potential to make pairs across a whole paragraph in very unexpected ways. We put the restriction in place to prevent these types of problems.

One way to include a space is to do as you have done, to use an attribute reference. Another, more readable way, so to wrap the text in a passthrough, which groups the words together.

```
A poem by ~+Laurence Alma-Tadema+~
```

For the reasons I stated, this restriction will remain in place.

**Comment by elextr** [comment]
This is another example of the restrictions of the current implementation that hopefully the standardisation process may improve as it evolves, but its certainly important to keep it for the current implementations or existing documents may break.

**Comment by mojavelinux** [comment]
Well said.

**Comment by ielfretter** [comment]
Thanks Dan, for your detailed reply and the alternative solution. And it goes without saying that I love using asciidoctor.

**Comment by mojavelinux** [comment]
Great! And I love to hear that! :gift:

**Comment by chtenb** [comment]
Would it be possible to support the non-breaking-space character in a subscript? I'm in a situation where I make heavy use of subscripts with spaces, and I want to make my source text look as close to the intentional rendering as possible. Having {sp} littered all over the text conflicts with this idea.

However, I have no problem using unicode in my text, and since a non-breaking-space looks fine in plain text too, I figure that would be a nice feature to have, and solve my usecase.

**Comment by mojavelinux** [comment]
> Would it be possible to support the non-breaking-space character in a subscript?

Yes, it already is supported there.

**Comment by chtenb** [comment]
Oh, I'm using asciidoctor.js, and it does not seem to work. Perhaps something that asciidoctor.js is not on-par with asciidoctor yet? Anyhow, thanks for you reply. I'll make an issue in the asciidoctor.js repository.

**Comment by mojavelinux** [comment]
Asciidoctor.js uses exactly the same code as Asciidoctor. I expect it to work.
