### ISSUE TITLE
Linenumbers incorrect when wrapping occurs

### ISSUE THREAD

**Issue by wimdeblauwe** [asciidoctor/asciidoctor#3959]
This issue is triggered by https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/694

When using `linenums`, the line numbers are not shown correctly when wrapping occurs.

To test, assume this test.adoc file:

```
= Test

[source,java,linenums]
.Controller.java
----
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;

import java.util.List;

@Controller
@RequestMapping("/")
public class RootController {

    @GetMapping
    public String index(Model model) {
        model.addAttribute("scientists", List.of("Albert Einstein",
                                                 "Niels Bohr",
                                                 "James Clerk Maxwell"));
        return "index";
    }
}
----
```

Run `asciidoctor -a source-highlighter=rouge test.adoc`

The generated HTML will render as:

![image](https://user-images.githubusercontent.com/1115823/110079444-6bf2d500-7d89-11eb-92dd-088399d8fcc6.png)

If you make the browser window even smaller, then the line numbers no longer align due to the wrapping:

![image](https://user-images.githubusercontent.com/1115823/110079550-89c03a00-7d89-11eb-8ff3-3f63dc1ba02b.png)

**Comment by mojavelinux** [comment]
This is a known issue with using line wrapping and line numbering on a source block with syntax highlighting. The problem actually comes from the HTML produced by the syntax highlighting library, not Asciidoctor. See https://github.com/asciidoctor/asciidoctor/issues/1706#issuecomment-433674917 and https://docs.asciidoctor.org/asciidoctor/latest/syntax-highlighting/rouge/#rouge-attributes. Unfortunately, when using rouge, the inline mode is not yet available. See https://github.com/asciidoctor/asciidoctor/issues/3641. There's an open pull request to implement it, but I haven't had time yet to review it.

So this issue is already covered by existing issues linked above.

**Comment by wimdeblauwe** [comment]
When using reveal.js, the highlight.js syntax highlighter is used. Will #3641 also fix it for highlight.js ?

**Comment by mojavelinux** [comment]
Asciidoctor core doesn't support line numbers for highlight.js. That's something the reveal.js converter adds. I'm not aware of how that highlight.js add-on works. Unless it puts the line numbers on the same line as the code, you will likely run into the same problem. Either way, it's something that has to be dealt with in that converter.
