### ISSUE TITLE
Data-URI Bug for Images with Links inside Tables

### ISSUE THREAD

**Issue by tajmone** [asciidoctor/asciidoctor#3974]
Win 10 x64 | Asciidoctor Ruby 2.0.12 | Ruby 2.7.2p137

I've seen there are various other Issues regarding Data-URIs, but this one addresses a specific bug.

While working on a document, I discovered that the `-a data-uri` command line option would break the following table in the HTML output document (which works fine without `data-uri`), not showing the image in the second column, and messing up the entire HTML structure of the table 8sse below):

```asciidoc
[cols="2*a",options="autowidth"]
|===============================
|
1. List entry.
2. List entry.
3. List entry.
|
link:{imagesdir}/xxx_big.jpg[image:xxx_small.jpg[image]]
|===============================
```

whereas the above table would work as expected if the image line is replaced by:

```asciidoc
[link={imagesdir}/xxx_big.jpg]
image::xxx_small.jpg[image]
```

The first AsciiDoc code produces the following HTML for the image cell:

```html
<td class="tableblock halign-left valign-top"><div class="content"><div class="paragraph">
<p><a href="images/xxx_big.jpg"><span class="image"><img src="data:image/jpg;base64</a></p>
</div></div></td>
</tr>
</tbody>
</table>
<div class=" paragraph"="">
</span></a></p><p><a href="images/xxx_big.jpg">
```
And then the table cells shows many text paragraphs that in the ADoc source are outside the table (after it), with multiple occurences of `<a href="images/xxx_big.jpg">`.

There seem to be a problem with the external image link being parsed multiple times, which also prevents conversion of the document image to Data-URI.

**Comment by mojavelinux** [comment]
First, using the `link` attribute is the right away to add a link to an image. That avoids the complexity that comes with nesting macros.

The reason the link macro fails to parse correctly is because the image macro will have already been converted to HTML by the time it is processed. Here's what the contents of the link macro is going to look like:

```
<span class="image"><img src="data:image/jpg;base64,..." alt="image"></span>
```

The double quotes and commas in the HTML are going to wreck havoc on the parsing of the link macro. Although the parsing may succeed when not using `data-uri`, that's merely by chance.

Apart from using the `link` macro, the other way to solve this is to enclose the image macro in a passthrough. That hides it from the link macro until the parsing is complete, hence avoiding the conflict I just cited.

```
link:big.jpg[pass:m[image:small.jpg[image\]]]
```

Take note of the placement of the backslash as that is important.
