### ISSUE TITLE
Disable mouse events for terminal prompt

### ISSUE THREAD

**Issue by ethanabrooks** [asciidoctor/asciidoctor#3975]
[This example](https://docs.asciidoctor.org/asciidoc/latest/verbatim/listing-blocks/#indent-method) has the lovely property that the `$` terminal prompt is not selectable by the mouse. This can really increase convenience for a user, especially when there is a multiple line shell command in a tutorial that a user is expected to execute:

```shell-session
$ sudo apt update
$ sudo apt install asciidoctor
```

Is there a way to do this with Ascii Doctor? At least I would like it to be the case in my Github-rendered readme.

**Comment by Mogztter** [comment]
> This example has the lovely property that the $ terminal prompt is not selectable by the mouse. This can really increase convenience for a user, especially when there is a multiple line shell command in a tutorial that a user is expected to execute:

If you are using Highlight.js as syntax highlighter and the following content:

```
[source,shell]
$ sudo apt update
$ sudo apt install asciidoctor
```

Then, the `$` prompt will be enclosed in `<span class="hljs-meta">$</span>`.
The trick is to use `user-select: none` to make the prompt not selectable:


```css
code.language-shell .hljs-meta {
  user-select: none;
}
```

> Is there a way to do this with Ascii Doctor? At least I would like it to be the case in my Github-rendered readme.

GitHub is using its own CSS and syntax highlighter, so the only thing you can do is contact GitHub support and hope for the best...

If you want more control, I would recommend to publish your AsciiDoc documents using a static site generator.

**Comment by ethanabrooks** [comment]
Thanks for the response! I will reach out to github. Where exactly would that `code.language-shell` command go? Top of the document? (Sorry I'm new to `asciidocs`).

**Comment by Mogztter** [comment]
It depends on how you are using Asciidoctor but one way to do it is to use a Docinfo file to add custom content to the head of your HTML document:


**docinfo.html**
```html
<style>
code.language-shell .hljs-meta {
  user-select: none;
}
</style>
```

```
$ asciidoctor doc.adoc -a docinfo=shared -a source-highlighter=highlight.js
```

Reference: https://docs.asciidoctor.org/asciidoctor/latest/docinfo/#head

**Comment by mojavelinux** [comment]
I did something similar in the Antora UI for the Asciidoctor docs site. For an example, see https://docs.asciidoctor.org/asciidoctor/latest/install/ruby-packaging/

Here's the CSS I'm using: https://github.com/asciidoctor/asciidoctor-docs-ui/blob/40586335b5b058f1303330916029ad9a3ee5d210/src/css/doc.css#L788-L790

This is not an appropriate change for Asciidoctor core since we don't control the stylesheet for syntax highlighting. For display on GitHub, you are right to reach out to GitHub support. For custom deployment that uses highlight.js, I think highlight.js should consider adopting the snippet referenced above.
