### ISSUE TITLE
Discrepancy between link in footnote, footnoteref in manpage backend

### ISSUE THREAD

**Issue by commonquail** [asciidoctor/asciidoctor#3987]
While trying to update a `footnoteref` to use the recommended `footnote` syntax in a man page I discovered this difference:

```asciidoc
https://foo.example
footnoteref:[one,https://foo.example]
footnote:two[link:https://foo.example[text]]
```

produces

```troff
.URL "https://foo.example" ""
[1]
[2]
.SH "NOTES"
1. https://foo.example
2. \c .URL "https://foo.example" "text"
```

which renders as

```
       https://foo.example [1] [2]

NOTES
       1. https://foo.example 2.
```

in Asciidoctor 2.0.12. Note that the second note doesn't render: something about the escape sequence causes the `.URL` macro to break here.

If I change the markup to

```troff
\c
.URL "https://foo.example" ""
[1]
[2]
.SH "NOTES"
1. https://foo.example
2. 
.URL "https://foo.example" "text"
```

that renders as

```
       https://foo.example [1] [2]

NOTES
       1. https://foo.example 2. text <https://foo.example>
```

(which also looks like footnotes should have something like `.sp` between them).

**Comment by mojavelinux** [comment]
The reason you are seeing a difference is because the two footnotes you are making are not the same. The equivalent footnote for this:

```
footnoteref:[one,https://foo.example]
```

is this:

```
footnote:two[\https://foo.example]
```

Where you are running into a problem is that the manpage converter does not support hyperlinks in the footnote text. So when you don't escape the autolink, you reveal a deficiency in the converter. To avoid confusion, I'm going to file a separate issue for that problem.

Also not that you do not need the link: prefix to make link with text. See https://docs.asciidoctor.org/asciidoc/latest/macros/url-macro/#link-text and https://docs.asciidoctor.org/asciidoc/latest/macros/link-macro/#when-to-use-the-link-macro

**Comment by mojavelinux** [comment]
See #3988 and #3989.

**Comment by mojavelinux** [comment]
This is now fixed in the master branch. Feel free to test it.

**Comment by commonquail** [comment]
```
==  Description

https://foo.example[text]
footnote:f1[autolink, no text: https://bar.example]
footnote:f2[autolink, text: https://baz.example[text]]
footnote:f3[no autolink: \https://qux.example]
```

![image](https://user-images.githubusercontent.com/603326/113666141-1030aa00-96af-11eb-807e-e551b95500b5.png)

Excellent, thank you!

**Comment by mojavelinux** [comment]
You're welcome! I agree, that's looking great. Thanks again for bringing this to my attention!
