### ISSUE TITLE
xrefstyle full for appendix links

### ISSUE THREAD

**Issue by bvwj** [asciidoctor/asciidoctor#4007]
When I use :xrefstyle: full and declare :appendix-caption: Attachment, the appendix links still display "Appendix".

I think it would be better if they picked up the :appendix-caption:

Not an emergency, just thought you would like to know.  Overall, I love asciidoctor and I'm just offering some input.

**Comment by mojavelinux** [comment]
That's because the xreftext does not use the -caption attributes. Rather, it uses the -refsig attributes, allowing you to control them independently. If you want them to use the same value, here's how they need to be defined:

```
= Document Title
:xrefstyle: full
:appendix-caption: Appx
:appendix-refsig: Appx

See <<a1>>.

[appendix#a1]
== My Appendix
```

Then you will see:

> See Appx A, My Appendix.

For details, see https://docs.asciidoctor.org/asciidoc/latest/macros/xref-text-and-style/#reference-signifiers
