### ISSUE TITLE
How to get double space inline?

### ISSUE THREAD

**Issue by CWempe** [asciidoctor/asciidoctor#4050]
I am trying to get a double space inline in a text.

Example asciidoc code:

![image](https://user-images.githubusercontent.com/1270359/117549791-a48a8580-b03c-11eb-9c47-5e81b6de60fc.png)

AsciiDoc (like Markdown) replaces these double spaces with single spaces.

The result looks like this:

![image](https://user-images.githubusercontent.com/1270359/117549818-c97ef880-b03c-11eb-85dd-ffdb63bf84ac.png)

I understand back ticks only create monospace and not verbatim text.
But I cannot find any solution to my issue. And I want that formatted as monospace if possible.

Am I missing something or do we need a new feature for this?

**Comment by mojavelinux** [comment]
Asciidoctor does not collapse spaces in an inline phrase. You can see this by inspecting the HTML. It's the browser that is doing the collapsing (by default, repeating space characters are not significant in HTML).

If you want the appearance of the run of space characters to be preserved, you can add the `pre-wrap` role to the monospaced phrase. This feature was added in the 2.0.11 release. See https://github.com/asciidoctor/asciidoctor/issues/3815

It's best if you could ask usage questions in the community chat at https://asciidoctor.zulipchat.com instead of the issue tracker. Thanks!
