### ISSUE TITLE
Bug in ++++ processing when raw base64 image is embedded

### ISSUE THREAD

**Issue by pd3** [asciidoctor/asciidoctor#4054]
I am trying to embed two images and having them displayed side by side. I wanted to do it like this:
````
++++
<img src="data:image/png;base64,data:image/png;base64,..." alt="x" />
<img src="data:image/png;base64,data:image/png;base64,..." alt="y" />
++++
````
Asciidoctor seems to have a bug and modifies the src string, probably because it misinterprets some substring of the base64 encoded image for markdown sequence.

In the attached test case, both images are completely identical. If one is removed, it works. However, if both are included, no image is displayed [report.adoc.gz](https://github.com/asciidoctor/asciidoctor/files/6459402/report.adoc.gz)

The steps to reproduce:
````
wget https://github.com/asciidoctor/asciidoctor/files/6459402/report.adoc.gz
gunzip report.adoc.gz
asciidoc -b html5 report.adoc
````

I am using asciidoc 8.6.10.

**Comment by mojavelinux** [comment]
This is the Asciidoctor project. You are using AsciiDoc.py. Either switch to Asciidoctor or report the issue here: https://github.com/asciidoc-py/asciidoc-py

What I can tell you is that in Asciidoctor, the passthrough block does not apply substitutions by default, whereas with AsciiDoc.py it does. You can match the behavior when using AsciiDoc.py by adding `[subs=""]` above the block.

**Comment by pd3** [comment]
Duh silly me. Of course I wanted to use asciidoctor, used asciidoc by mistake. In asciidoctor this indeed works. Sorry about that!

**Comment by mojavelinux** [comment]
Great to hear!

**Comment by pd3** [comment]
The inline style of base64 images does not seem to work though even in asciidoctor. Tried the approach suggested here https://discuss.asciidoctor.org/Having-2-images-side-by-side-in-an-HTML-output-td532.html:
````
image:data:image/png;base64,...[title]
````
but what is displayed is only the alternate text. Looking inside the html, the tag seems to be recognized correctly
````
<img src="data:image/png;base64,..." alt="title">
````
so probably the base64 sequence gets modified.

When two images are inserted
````
image:data:image/png;base64,...[title]
image:data:image/png;base64,...[title]
````
the created html puts both inside one `img` html tag like this:
````
<img src="data:image/png;base64,...=[title]
image:data:image/png...=" alt="title">
````

**Comment by mojavelinux** [comment]
You are correct. That's already an open issue. See https://github.com/asciidoctor/asciidoctor/issues/3791

It's really better if you link to the real image and enable the opts=inline attribute to allow Asciidoctor to embed the image data.

**Comment by mojavelinux** [comment]
Actually, I just checked an Asciidoctor seems to already support the data URI target in this case. However, for inline images, it is necessary to enclose the data in a pass macro or else it will try to apply substitutions to it.

For example:

```
image:data:image/png;base64,pass:[IMAGE DATA HERE][alt]
```

However, I still don't recommend putting raw image data in the AsciiDoc document. It is better to write it to the filesystem, reference that path in the image macro, and set the opts=inline attribute so that the processor will embed it.

Please direct follow-up questions to the community chat at https://asciidoctor.zulipchat.com.

**Comment by pd3** [comment]
I just tried the opts=inline and it does not seem to work with png:
````
[opts=inline]
image::test.png[]
````
gives
````
<img src="test.png">
````
in the html body.

**Comment by mojavelinux** [comment]
Sorry about the confusion. I had a long day and I wasn't thinking clearly. The correct attribute is `data-uri`, and it must be set on the document.

```
:data-uri:

image:test.png[]
```

See https://docs.asciidoctor.org/asciidoctor/latest/html-backend/manage-images/#embed-images-with-the-data-uri-attribute

**Comment by pd3** [comment]
That works, thanks very much for your help. Asciidoctor is a great tool
