### ISSUE TITLE
Flag '--failure-level INFO' works only together with '-v'

### ISSUE THREAD

**Issue by lazdmx** [asciidoctor/asciidoctor#4078]
I just found that the `--failure-level` flag works only if the `-v` is set. Here is a test-script:

```sh
cat << EOF > ./test.adoc
= Title

== Chapter
This is <<_unknown_reference>>
EOF

asciidoctor --failure-level=INFO ./test.adoc
echo "w/o -v: $?"

asciidoctor --failure-level=INFO -v ./test.adoc
echo "w/  -v: $?"
```

After executing the script above you should see output like this:

```
w/o -v: 0
w/  -v: 1
```

**Comment by mojavelinux** [comment]
Your observation is correct. That's because the application only logs messages as the INFO level when the `-v` flag is turned on (which is treated like a debug mode). If the `-v` flag is not on, the INFO message is not recorded and thus you can't fail on it.

There's currently no way to set the log level from the CLI.
