### ISSUE TITLE
Docker image failure - No such file or directory - notoserif-regular-subset.ttf not found in GEM_FONTS_DIR

### ISSUE THREAD

**Issue by mxdpeep** [asciidoctor/asciidoctor#4109]
official Docker image latest/1.8.1 fails converting ADOC to PDF:

`docker run --rm -v $(pwd):/documents/ asciidoctor/docker-asciidoctor:1.8.1 asciidoctor-pdf README.md.adoc`
No such file or directory - notoserif-regular-subset.ttf not found in GEM_FONTS_DIR
  Use --trace for backtrace

Docker image 1.7.0 works just fine:

`docker run --rm -v $(pwd):/documents/ asciidoctor/docker-asciidoctor:1.7.0 asciidoctor-pdf README.md.adoc`

(no errors)

**Comment by Mogztter** [comment]
This issue is related to the Docker image which has its own repository: https://github.com/asciidoctor/docker-asciidoctor

It seems that the same issue has already been reported: https://github.com/asciidoctor/docker-asciidoctor/issues/214

Could you please confirm that this is the same issue and if so, close this one?

**Comment by mojavelinux** [comment]
@Mogztter is correct.

Please don't post images about the Docker image in this repository.

**Comment by mojavelinux** [comment]
The issue has been reported again as https://github.com/asciidoctor/docker-asciidoctor/issues/215. It looks like Docker broke something and we are seeing the fallout from it. Please direct further comments to those issues.
