### ISSUE TITLE
Test failure with rouge 3.26.0

### ISSUE THREAD

**Issue by dleidert** [asciidoctor/asciidoctor#4167]
Hi there,

Ruby Rouge did some changes to the PHP lexer. This led to some failures with other projects like jekyll and kramdown as well. It seems now that asciidoctor is affected as well. This is a test build on Debian against ruby-rouge 3.26.0:

```
Finished in 2.516514s, 989.8615 runs/s, 3587.9003 assertions/s.

  1) Failure:
Minitest::Test::TestSyntaxHighlighter::TestRouge#test_should_preserve_cgi_style_options_on_language_when_setting_start_inline_option_for_PHP [/<<PKGBUILDDIR>>/test/syntax_highlighter_test.rb:761]:
Expected "<div class=\"listingblock\">\n<div class=\"content\">\n<pre class=\"rouge highlight\"><code data-lang=\"php\"><span class=\"nf\">cal_days_in_month</span><span class=\"p\">(</span><span class=\"no\">CAL
_GREGORIAN</span><span class=\"p\">,</span> <span class=\"mi\">6</span><span class=\"p\">,</span> <span class=\"mi\">2019</span><span class=\"p\">)</span></code></pre>\n</div>\n</div>" to include "<span class=\"
nx\">cal_days_in_month</span>".
```

**Comment by mojavelinux** [comment]
Thanks for bringing it to my attention. I wouldn't say that Asciidoctor is "affected" since Asciidoctor is merely offering integration with Rouge, so it's only the end user who is affected. However, it does impact our test, which was set up to detect these sorts of subtle changes. Rouge 3.26 was release late last year, so it's surprising we are only seeing this now. But I now realize it's because we are not letting CI test the latest minor release of Rouge. I'll update that CI config and make whatever changes necessary to the test suite to account for these differences.

**Comment by dleidert** [comment]
I just see that you may have fixed that already:

<https://github.com/asciidoctor/asciidoctor/commit/62014851b087071339d19b5313e5676766aabe90>

**Comment by mojavelinux** [comment]
I should have asked which version of Asciidoctor you are building.

> I now realize it's because we are not letting CI test the latest minor release of Rouge

We changed where the rouge dependency is declared. When we did that, it seems we may have inadvertently disabled testing of the minor version. I need to do a closer assessment to see what happened here.

**Comment by dleidert** [comment]
We still have version 2.0.12 in Debian. I was planning on updating it and checked your the test source. But what I missed to realize was that you had already fixed the issue by changing from `assert_include` to `refute_include`. Thus I assumed that the issue is still there. But this changed test logic should work.

**Comment by mojavelinux** [comment]
Please always distribute the latest patch release. That's why we have switched to semver. I'm confident that it will work if you use 2.0.16 because that is what we test in CI. As it turns out, CI is testing Rouge 3.26.0. See https://github.com/asciidoctor/asciidoctor/runs/3561749817?check_suite_focus=true

**Comment by dleidert** [comment]
Duplicate of #3916

**Comment by mojavelinux** [comment]
Thanks for publishing the Asciidoctor 2.0.16 package!
