### ISSUE TITLE
"unterminated listing block" is the 1st included file is not terminated with more than 2 newlines.

### ISSUE THREAD

**Issue by yoonghm** [asciidoctor/asciidoctor#4241]
I used Asciidoctor 2.0.17 with asciidoctor-pdf, asciidoctor-epub3, rouge, coderay.

I cloned an AsciiDoctor template from https://github.com/vysakh0/asciidoctor-book-template.

I modified **`master.adoc`** to add in `font` for `:icons:`

```
= eBook Template
:author: Vysakh Sreenivasan
:email:  email@server.com
:revnumber: 1.0
:revdate:   January 1st, 2012
:doctype: book
:toc:
:icons: font
:data-uri:
:lang: en
:language: javadocript

[preface]
include::chapters/about.adoc[]
include::chapters/preface.adoc[]

== Introduction

include::chapters/introduction.adoc[]
```

The first included file is `about.adoc`.

I used `asciidoctor-pdf master.adoc` to generate a master.file. There is no error.

I removed the extra newlines from `about.adoc`. When re-ran the command: I have the following error:

```
asciidoctor: WARNING: chapters/preface.adoc: line 2: unterminated listing block
```

If I put back the extra newlines (at least 2), then the error went away.

There is no error is if I remove the extra newlines from other files.

**Comment by abelsromero** [comment]
I think it's behaving as expected.
Seeing the HTML generated, the content is being concatenated by the include and interpreted as a listing block because it uses the MD section header underline.

As docs point out includes should be separated to avoid this issue.

![image](https://user-images.githubusercontent.com/5781153/149625530-5c2b7386-dd69-4046-8b37-74809750e3b6.png)

https://docs.asciidoctor.org/asciidoc/latest/directives/include/#include-syntax

Additionally I am seeing other oddities like code blocks with long block delimiters and it uses asciidoctor 1.5.3. I'd personally suggest to take that example with a grain of salt.

**Comment by yoonghm** [comment]
Thank you for the clarification.

**Comment by abelsromero** [comment]
Btw, if you have any question about usage or practices feel free to drop it at https://asciidoctor.zulipchat.com/, it's much quicker and convenient than github issues.

**Comment by yoonghm** [comment]
Thanks
