### ISSUE TITLE
Incorrent parsing of inline code (literal) blocks

### ISSUE THREAD

**Issue by bybor** [asciidoctor/asciidoctor#4262]
For this input

```
. Dataframe, Index (rows): [0:15], Columns: ['Name', 'Birth', 'City', 'Position']. Delete a column
 'IsStudent': {{c1::`frame.drop(['IsStudent'], axis = 1, inplace = False)`}}. This also works for one 
column: {{c2::`frame.drop('IsStudent', axis =1, inplace = False)`}}, 
but using {{c3::`list`}} is more universal.
```

I get incorrect docbook and html output. Here you can see the correct/expected rendering of inline code by github

. Dataframe, Index (rows): [0:15], Columns: ['Name', 'Birth', 'City', 'Position']. Delete a column
 'IsStudent': {{c1::`frame.drop(['IsStudent'], axis = 1, inplace = False)`}}. This also works for one
 column: {{c2::`frame.drop('IsStudent', axis =1, inplace = False)`}}, but using {{c3::`list`}} is more universal.

Here is what happens instead (as if it was written this way)

. Dataframe, Index (rows): [0:15], Columns: ['Name', 'Birth', 'City', 'Position']. Delete a column
 'IsStudent': {{c1::\`frame.drop(['IsStudent'], axis = 1, inplace = False)<code>}}. This also works for one
 column: {{c2::\`frame.drop('IsStudent', axis =1, inplace = False)</code>}}, but using {{c3::\`list\`}} is more universal.

I added some new lines into the output for readability.

### asciidoctor -> docbook

It put the first `<literal>` to instead of the first _closing_ backtick position.

```
<orderedlist numeration="arabic">
<listitem>

<simpara>Dataframe, Index (rows): [0:15], Columns: ['Name', 'Birth', 'City', 'Position']. Delete a column

 'IsStudent': {{c1::`frame.drop(['IsStudent'], axis = 1, inplace = False)<literal>}}. This also works for one column: 
{{c2::`frame.drop('IsStudent', axis =1, inplace = False)</literal>}}, but 
using {{c3::`list`}} is more universal.</simpara>
</listitem>
</orderedlist>
```

### html output

Here is puts `<code>` just in the same position it did for `<literal>` above
```
<ol class="arabic">
<li>
<p>Dataframe, Index (rows): [0:15], Columns: ['Name', 'Birth', 'City', 'Position']. 
Delete a column 'IsStudent': {{c1::`frame.drop(['IsStudent'], axis = 1, inplace = False)<code>}}. This also works 
for one column: {{c2::`frame.drop('IsStudent', axis =1, inplace = False)</code>}}, but using {{c3::`list`}} 
is more universal.</p>
</li>
</ol>

```

**Comment by mojavelinux** [comment]
I'm not actually seeing any use of inline literals in your source. What I see is inline monospace formatting (see https://docs.asciidoctor.org/asciidoc/latest/text/monospace/), which is actually fine for this case. However, since you're applying the formatting in the middle of a word, you need to use the unconstrained variant:

```asciidoc
. Dataframe, Index (rows): [0:15], Columns: ['Name', 'Birth', 'City', 'Position']. Delete a column
 'IsStudent': {{c1::``frame.drop(['IsStudent'], axis = 1, inplace = False)``}}. This also works for one
column: {{c2::``frame.drop('IsStudent', axis =1, inplace = False)``}},
but using {{c3::``list``}} is more universal.
```

In the future, please direct support questions to the #users stream of the project chat at https://asciidoctor.zulipchat.com. Thanks!

**Comment by bybor** [comment]
I didn't realize that I'm in the middle of the word, i used a wrong name for inline monospace formatting, I was sure I found a bug.

Thank you very much for taking time and explaining it to me!

Asciidoctor became a big part of my daily computer related activity. Thank you very much for it.

**Comment by bybor** [comment]
When I see responses to my requests from open-source projects maintainers I understand what a burden you carry doing this work. Being a developer, I still cannot provide / formulate good enough question/request.

Thank you!

**Comment by mojavelinux** [comment]
I'm very glad to hear that Asciidoctor is a big part of your daily work. Thank you for sharing your story and for being part of this community.

As the project maintainer, I'm committed to helping you find solutions to challenges and to connect you with the best information I can. That's why I want to invite you to the project chat. In that chat, you can feel comfortable asking questions of all sorts without having to worry about whether you're using the right terminology or whether you have formulated your questions perfectly. Everyone there is trying to help each other to learn and be successful. And it also allows me to keep the issue tracker organized so I can focus my attention on addressing the bugs and feature requests. I hope to see you in the project chat!
