### ISSUE TITLE
counter use inside a variable definition/assignment

### ISSUE THREAD

**Issue by tobiasdroessler** [asciidoctor/asciidoctor#4304]
Id like to assemble some kind of an identifier... for writing software requirements and there for I'd like to reference and increment variables and counters inside a assembly variable. And i figured out...  it is not working the way I thought.

1) why is it like this? looks like the counter feature is first processed and replaced with static numbers and then is will not work   
2) and is there a way to get this behavior with counting values inside a variable definition ?  

example code .. 
```adoc
// works fine: output is FOOBAR 
:foo: FOO
:bar: BAR
:fb: {foo}{bar}
{fb}

// works fine .. counts and outputs "1" and "2". 
{counter:b}
{counter:b}

//this is not working .. two time a "1" is returned 
:cntr: {counter:c}
{cntr}
{cntr}
```

**Comment by mojavelinux** [comment]
This is not the indented use of a counter and thus the behavior is unspecified. A counter is for making a sequence directly in the content of the document, such as a paragraph, list item, or table cell. This is stated right at the start of the page: https://docs.asciidoctor.org/asciidoc/latest/attributes/counters/

The reason it doesn't work inside of an attribute entry is because the counter is meant to be triggered when the content is rendered. Putting it in an attribute entry breaks this contract.

In the future, please direct questions about usage to the project chat at https://chat.asciidoctor.org. You can learn more about the support policies on the following page: https://docs.asciidoctor.org/about/support/

**Comment by tobiasdroessler** [comment]
Thank you for explanation. 

How I can do this, any ideas? 

I d like to have a short, identically, single 'call' for this identifier creation. I've read about macro substitution..  But I think it's not helping for this kind of problem.

**Comment by Mogztter** [comment]
You could create an inline macro named `c` (short for `counter`) that increments a number and returns the value:

```
// 1
c:[]
// 2
c:[]
```

It would be more generic to pass the counter name as a target and use a more explicit name. So I would recommend to use:

```
// 1
counter:counter-name[]
// 2
counter:counter-name[]
```

As you can see, it's a lot to type but you can define an attribute:

```
:cntr: pass:[counter:counter-name[]]


// 1
{cntr}
// 2
{cntr}
```

But let's continue this discussion at [chat.asciidoctor.org](https://chat.asciidoctor.org/).

**Comment by mojavelinux** [comment]
> But let's continue this discussion at chat.asciidoctor.org.

Exactly. As I said, the right place to ask questions about how to use AsciiDoc and the Asciidoctor processor is the project chat. Having these types of discussions in the issue tracker makes it more difficult to manage the project.

When I have time, I'll reply to your post in the project chat to share my suggestions. Otherwise, Guillaume or some else in the community may be able to give you ideas.
