### ISSUE TITLE
xref to root directory asciidoc file not working

### ISSUE THREAD

**Issue by chen-ni** [asciidoctor/asciidoctor#4313]
I'd like to add a reference to an asciidoc file located in the root directory. Have tried the following syntax:
```
Please refer to xref:/TESTING.asciidoc#_testing_the_rest_layer[this section].
```

where `TESTING.asciidoc` is a file located in the root directory.

However, it's not working in both IntelliJ and on GitHub. You can view it on GitHub here: https://github.com/chen-ni/elasticsearch/blob/issue-88406-tmp/rest-api-spec/src/yamlRestTest/resources/rest-api-spec/test/README.asciidoc#test-execution

I read the [Document to Document Cross References](https://docs.asciidoctor.org/asciidoc/latest/macros/inter-document-xref/), but couldn't find a solution.

Can anyone please help, thanks!

**Comment by mojavelinux** [comment]
The problem is that you are use a) the legacy doctitle syntax, which puts AsciiDoc into [compat mode](https://docs.asciidoctor.org/asciidoctor/latest/migrate/asciidoc-py/#compatibility-mode) and b) the legacy AsciiDoc file extension. If you want to use the interdocument xrefs, you must at least turn off compat mode (`:!compat-mode:`). Ideally, you should be using the .adoc file extension for AsciiDoc files as well.

In the future, please ask questions about usage in the project chat at https://chat.asciidoctor.org.

**Comment by chen-ni** [comment]
@mojavelinux Got it, thanks!
