### ISSUE TITLE
Wrong substitution in link

### ISSUE THREAD

**Issue by rdmueller** [asciidoctor/asciidoctor#4319]
When you link from a document to the compare revisions page of a gitlab repository, the `...` in the url gets replaced with some funny characters (as far as I can see, it even isn't the ellipsis, is it?)

Example:

    https://gitlab.com/project/repo/compare/1.2.3...4.5.6[test]

will be replaced with

    <a href="https://gitlab.com/project/repo/compare/1.2.3...%E2%80%8B4.5.6">test</a>

I think, besides an URL-Encoding, the URL should remain untouched, shouldn't it?

The issue can be circumvented by escaping the `...`, but this is hard to do with auto-generated links.

    https://gitlab.com/project/repo/compare/1.2.3\...4.5.6[test]

ps: there is a similiar issue (#1061), but I think it is different from this one, because the URL should be always untouched.

**Comment by mojavelinux** [comment]
The behavior you have described is the expected behavior. The AsciiDoc language currently stipulates that replacements are applied anywhere in a paragraph that is not inside a passthrough or escaped. Therefore, the link must be written as follows:

```
https://gitlab.com/project/repo/compare/1.2.3\...4.5.6[test]
```

Alternately, you can turn off replacements on the paragraph itself:

```
[subs=-replacements]
https://gitlab.com/project/repo/compare/1.2.3...4.5.6[test]
```

We are considering having the language skip substitutions for the target of a link or URL macro. However, that would be a change to the language and would require approval by the AsciiDoc spec project.

In the future, if you have questions about usage or the language, please direct them to the project chat at https://chat.asciidoctor.org. The issue tracker is for confirmed bugs. That helps us better maintain the project. Thanks!
