### ISSUE TITLE
Double dash in pathname breaks display of images.

### ISSUE THREAD

**Issue by Alberth289346** [asciidoctor/asciidoctor#4328]
I am using a Linux Mint system, and accidentally had a double minus sign in my path. It breaks finding images (and perhaps all files) included in the document.

Reproduction:

- Construct directory with a -- (2 ASCII 45 characters) in it.
  `$ mkdir num--label`

- Copy a random image (named "x.png" here into the new directory.
  `$ cp x.png num--label`

- Make an `y.adoc` file that includes the image.
  ``` adoc
  = Title

  Some text

  image:num--label/x.png[]

  more text
  ```

- Convert to html
  ``` sh
  $ ~/ruby-gems/bin/asciidoctor --version       
  Asciidoctor 2.0.17 [https://asciidoctor.org]
  Runtime Environment (ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8

  $ ~/ruby-gems/bin/asciidoctor y.adoc

  $ firefox y.html
  ```
  Shows an `x` instead of the picture.
  ![Screenshot from 2022-08-11 12-03-35](https://user-images.githubusercontent.com/3254232/184110537-5f2a5bb6-694f-418d-b266-8c2376af3b2d.png)

Reason: The double minus signs in the path are mangled to CJK ideographs.
```
$ grep x.png y.html
<p><span class="image"><img src="num&#8212;&#8203;label/x.png" alt="x"></span></p>
```
My file system doesn't do CJK characters and cannot traverse "num--label" using those characters.

**Comment by mojavelinux** [comment]
What you are describing is the expected behavior. The replaced character is not, in fact, an CJK ideograph, but rather an [emdash](https://www.fileformat.info/info/unicode/char/2014/index.htm). By default, the AsciiDoc processor performs character replacements on paragraph text. See https://docs.asciidoctor.org/asciidoc/latest/subs/replacements/

The simple fix to your problem is to switch from an inline image to a block image. The character replacement subsitution is not applied to the target of a block image.

```
image::num--label/x.png[]
```

If it's necessary for the image to be an inline image, then it it would be necessary to escape the character sequence so it is not replaced.

```
The symbol image:num\--label/x.png[] represents the value to be solved for.
```

In the future, please direct usage questions to the project chat at https://chat.asciidoctor.org. You can find out more about our support policies on the following page: https://docs.asciidoctor.org/about/support/

**Comment by Alberth289346** [comment]
I don't understand *at all* how you can expect a path to be preserved (as in lead to the correct file) if it gets mangled as text.

ie, it's fine if you make a displayable version of it to show in the document, but using the displayable version for accessing the file system doesn't make sense at all to me. File system paths don't have displayable versions at the disk.

This is why I reported it as a bug.

**Comment by mojavelinux** [comment]
That's the way the language is. Asciidoctor implements the language as it is specified. If a change in behavior is required, that will need to be dealt with in the language. When the language changes to use a different inline parsing model (as is proposed), then we could consider special treatment for macro targets that refer to filenames (similar to the block image macro). But that's just not how AsciiDoc works right now.
