### ISSUE TITLE
`--path` flag deprecated in bundle

### ISSUE THREAD

**Issue by KartikSoneji** [asciidoctor/asciidoctor#4338]
The [contributing instructions](https://github.com/asciidoctor/asciidoctor/blob/81e3e772f1294f85a5be7d34d06e132494c44e5b/CONTRIBUTING.adoc#:~:text=bundle%20%2D%2Dpath%3D.bundle/gems) specify running `bundle --path=.bundle/gems` to install dependences.

But running the command results in the following warning:
```
[DEPRECATED] The `--path` flag is deprecated because it relies on being remembered across bundler invocations,
which bundler will no longer do in future versions.
Instead please use `bundle config set --local path '.bundle/gems'`, and stop using this flag
```

The `--path` flag has been deprecated:
([source](https://bundler.io/man/bundle-install.1.html#OPTIONS))
> The --clean, --deployment, --frozen, --no-prune, --path, --shebang, --system, --without and --with options are deprecated because they only make sense if they are applied to every subsequent bundle install run automatically and that requires bundler to silently remember them. Since bundler will no longer remember CLI flags in future versions, bundle config (see [bundle-config(1)](https://bundler.io/man/bundle-config.1.html)) should be used to apply them permanently.

Adding a local bundler config file (in `bundle/config`) should be an easy fix.
```diff
diff --git a/.bundle/config b/.bundle/config
new file mode 100644
index 0000000..1d8a34e
--- /dev/null
+++ b/.bundle/config
@@ -0,0 +1,2 @@
+---
+BUNDLE_PATH: ".bundle/gems"
```

**Comment by mojavelinux** [comment]
I vehemently disagree that Bundler should have deprecated this flag. It's absurd and it adds an extra and unnecessary step which effectively does exactly the same thing. Personally, I ignore it because it's harmless. However, if you'd like to contribute a change to recommend using `bundle config --local path .bundle/gems` first instead, I'll accept it.

**Comment by KartikSoneji** [comment]
Hmm I'm not very familiar with ruby development but the benefit of using `bundle config` seems to be it allows storing the configuration in a file commited to the repo, so the user only has to run `bundle` instead.

Would you accept a PR adding a `.bundle/config` file?

**Comment by mojavelinux** [comment]
I'd rather not have transient development files in the repository. There are different ways of managing gems and by storing those files in the repository, it makes it so that some people and/or packagers have to work around them.

I'm happy to add the extra line I suggest above the `bundle install` command to remove the warning. Even though I disagree with the fact that bundler emits that warning, it's a reality we have to deal with.

**Comment by mojavelinux** [comment]
Btw, thanks for pointing this out.

**Comment by mojavelinux** [comment]
No. I don't want transient config files for development in the repo.
