### ISSUE TITLE
Add a new attribute-missing option - pass-through

### ISSUE THREAD

**Issue by aireilly** [asciidoctor/asciidoctor#4343]
Hi, we are using [Vale language linter](https://vale.sh/docs/topics/scoping/#asciidoc) with asciidoc. Vale uses Asciidoctor as a backend to generate html before linting. Often, we specify conditionals (ifdefs, ifndefs, etc) in individual asciidoc topics and set the context in higher level assembly maps. When we run Vale on such a topic, Vale ignores the conditional content because it doesn't know the context at the level of the topic.      

```asciidoc
ifdef::some-context[]
This is content inside an `ifdef` and we would like to lint it.
endif::[]
```

It would be very useful to have a fifth value for `attribute-missing` attribute - `pass-through` that simply passes through the conditionalized content as is when the context can't be resolved. This would facilitate the Vale linter in more thoroughly linting the text in the topic file. 

https://docs.asciidoctor.org/asciidoc/latest/attributes/unresolved-references/#missing

**Comment by mojavelinux** [comment]
I'm afraid you've misunderstood the purpose of the attribute-missing setting. This attribute controls what happens when an attribute reference cannot be resolved (e.g., `{attribute-name}`), as that usually indicates a problem in the content or configuration.

The whole purpose of `ifdef` is to check whether an attribute is set or not to conditionally include content. If it were not to perform that function, then it would serve no purpose. That's why the attribute-missing setting isn't consulted in this case (as you can see here: https://github.com/asciidoctor/asciidoctor/blob/main/lib/asciidoctor/reader.rb#L903-L935). I don't see a case for changing this behavior. Besides, it would likely break many existing documents.

If you want to have the AsciiDoc processor treat the outcome of all ifdef directives as true, then you need to set all attributes that it checks. One way to do this would be to scan the document and find those checks, then dynamically set the attributes. This could be done programmatically with some help from the Asciidoctor parser or you could do it with custom code. If you need help, please ask in the project chat at https://chat.asciidoctor.org. (We don't use the issue tracker as a support forum).

**Comment by aireilly** [comment]
Added a question here: https://asciidoctor.zulipchat.com/#narrow/stream/279642-users/topic/Automatically.20set.20all.20ifdef.2Fifndef.2Fifeval.20directives.20as.20true

**Comment by mojavelinux** [comment]
Thanks!
