### ISSUE TITLE
2 links containing # lead to invalid html

### ISSUE THREAD

**Issue by frankbenoit** [asciidoctor/asciidoctor#4350]
````
link:https://example.com/#/home[Home] 
link:https://example.com/#/Other[Other] 
````
leads to this html:
````
<a href="https://example.com/<mark>/home">Home</a>
<a href="https://example.com/</mark>/Other">Other</a>
````

Is this a bug? Is there escaping necessary?

When I use a \ at the first # it seems to be OK, but this is quite complicated to examine links pair-wise.
If there are 3 link, what then? If I escape the first 2, in the output the 2nd has \# in it.

**Comment by mojavelinux** [comment]
Yes, escaping is necessary. The two `#` form a formatting pair due to their location at a word boundary. You can escape it using one of the techniques described on this page: https://docs.asciidoctor.org/asciidoc/latest/macros/complex-urls/

I'll mark this down as another use case for the problem in the language referenced in #281 and #625 and #3876.
