### ISSUE TITLE
Absolute path in image macro not recognized on Windows

### ISSUE THREAD

**Issue by jaromieee** [asciidoctor/asciidoctor#4359]
There seems to be a bug where image macro's don't correctly handle absolute paths.
If an `:imagesdir:` attribute is declared, with for example the value _images_, it copies the value of the attribute to the `image macro` paths, whether it is an absolute path or not. According to the documentation, it should ignore absolute paths.
https://docs.asciidoctor.org/asciidoc/latest/macros/images-directory/

For example, when using `:imagesdir: images` in my asciidoc file, `image:C\:Users\<user>\Documents\duck.jpg[]` is translated to
`<img src="images/C:/Users/<user>/Documents/duck.jpg`, which is obviously a faulty path.

I also tried double backslash `\\` and single forward slash `/` as a file seperator, which doesn't make a difference.

**Comment by mojavelinux** [comment]
You're correct that if the target path is absolute, the converter will use it as is. However, I think the problem you're facing is that the syntax of your absolute path is not correct. Here's how it should be written:

```
image::C:\Users\username\Documents\duck.jpg[]
```

Notice that the path begins with `C:\`, not `C\:`. The placement of the `\` in your example is incorrect, likely causing the path to be treated as a relative path instead of an absolute path. It would be even better to write it with forward slashes, which are perfectly acceptable on Windows:

```
image::C:/Users/username/Documents/duck.jpg[]
```

Generally, you should not use absolute paths for images when generating HTML. The only time you would do this is if a) data-uri is set and b) you are generating an output format that embeds images by default like PDF.

If you have further questions about using Asciidoctor, please direct them to the project chat at https://chat.asciidoctor.org. Refer to https://docs.asciidoctor.org/about/support/ for our support policies.
