### ISSUE TITLE
source-highlighter - pygments linenums ERR

### ISSUE THREAD

**Issue by life888888** [asciidoctor/asciidoctor#4379]
```bash
$ asciidoctor -v
Asciidoctor 2.0.16 [https://asciidoctor.org]
Runtime Environment (ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)

$ asciidoctor README.adoc
```

include file , and show linenums

```adoc
[,xml,linenums,highlight=5;10;20;24;28;36]
.fo-pdf.xsl
----
include::fo-pdf.xsl.tc[lines=26..38;56..83]
----
```

![linenums-err-count](https://user-images.githubusercontent.com/101442875/198823792-a577fa23-9a9a-4480-af6c-e0ddb84f061d.png)

Line 20, is one line in source file(fo-pdf.xsl.tc) , 
Maybe code block width limit , so, one string line , show two line,  line 20,21.

Line 25, must set 24, to select line to ighlight 

`[,xml,linenums,highlight=5;10;20;24;28;36]`

line num should mapping to original line one to one.

one line to one line no.

one line string , to line no 20, 21 will make display wrong line no.
Line 25 should be 24.

**Comment by mojavelinux** [comment]
This is because the line numbers are off due to the wrapping. You either need to turn off wrapping on the source block, or you need to switch to the table linenums mode.

See https://docs.asciidoctor.org/asciidoctor/latest/syntax-highlighting/pygments/#pygments-attributes

Please ask usage questions in the chat at https://chat.asciidoctor.org. The issue tracker is reserved for **verifiable** bugs. That makes it possible for us to manage this project.
