### ISSUE TITLE
Support [%interactive] with listing blocks

### ISSUE THREAD

**Issue by ullenboom** [asciidoctor/asciidoctor#4399]
This doesn't seem to work (for HTML export):

```
[%interactive]

* [ ]  A. `pepper salt`
* [x]  B. `salt pepper`
* [ ]  C. +
[source,java]
----
pepper
salt
----

* [ ]  D. salt
```

I am uncertain if my syntax is wrong or this is not possible.

Currently, the rendering will give:

![grafik](https://user-images.githubusercontent.com/5071169/211862379-ddde18ac-2446-4840-986a-f34bba51287c.png)

**Comment by Mogztter** [comment]
Your syntax is incorrect, it should be:

````
[%interactive]

* [ ]  A. `pepper salt`
* [x]  B. `salt pepper`
* [ ]  C.
+
[source,java]
----
pepper
salt
----

* [ ]  D. salt
```

Otherwise, `* [ ]  D. salt` is a new list without the `interactive` option.

Please direct questions about usage to the project chat at [chat.asciidoctor.org](https://chat.asciidoctor.org/). We don't use the issue tracker for support. This policy is stated on the following page: [docs.asciidoctor.org/about/support](https://docs.asciidoctor.org/about/support/) Thanks for understanding. I hope to see you in the project chat!

**Comment by ullenboom** [comment]
Thanks, I tested that before as well; however, it's in the next line, not on the right of the checkbox:

![grafik](https://user-images.githubusercontent.com/5071169/211887044-6780c41f-fad6-41da-aada-4a69ef480704.png)

**Comment by Mogztter** [comment]
> Thanks, I tested that before as well; however, it's in the next line, not on the right of the checkbox:

That's a different issue that can be solved using CSS but let's continue this discussion at [chat.asciidoctor.org](https://chat.asciidoctor.org/)

**Comment by mojavelinux** [comment]
> however, it's in the next line, not on the right of the checkbox:

That's where it should be...though the listing block should be directly below "C" and not the checkbox. The fact that it is to the left indicates to me that your stylesheeet is out of date (perhaps your version of Asciidoctor).

Putting a block element to the right of the primary text of a list item is a customization you'll have to apply yourself as it is not standard / typical. We've been in conversation in the chat, so let's continue there.
