### ISSUE TITLE
test suite failures with rouge 4.1.0

### ISSUE THREAD

**Issue by tmzullinger** [asciidoctor/asciidoctor#4406]
A change in rouge 4.1.0 causes the `should gracefully fallback to default style if specified style not recognized` test to fail.  The CSS produced by rouge no longer matches the regex.  This looks to be due to [6f5aecd2 (Update GitHub theme, add dark mode (#1918), 2023-01-24)](https://github.com/rouge-ruby/rouge/commit/6f5aecd2) in rouge.

This was noticed in Fedora ([bz#2171711](https://bugzilla.redhat.com/2171711)). Here is the [build.log](https://github.com/asciidoctor/asciidoctor/files/10786328/build.log).

**Comment by mojavelinux** [comment]
Argh, the false semantic versioning strikes again :/ I'm pretty busy at the moment. Would you be available to propose a fix? If not, I might be able to look at it later this week.

**Comment by tmzullinger** [comment]
This certainly isn't urgent, so I'm happy if you take a look when you can and come up with a cleaner fix.

**Comment by mojavelinux** [comment]
Thanks for the assistance getting this started. I know understand what needs to happen.

Quite frankly, I'm shocked that Rouge made such a drastic change in a minor release. It should have been a major release. But since the test is just looking that the styles are coming from the theme named GitHub, I think I see a more portable way to write this extension than what we were doing.

**Comment by tmzullinger** [comment]
Thanks for pushing a much more elegant fix for this Dan!  I tested this against Fedora Rawhide and 36 (rouge 4.1.0 and 3.26, respectively).
