### ISSUE TITLE
'bold monospace' text behavior (monospace containing single asterisk *)

### ISSUE THREAD

**Issue by wildcart** [asciidoctor/asciidoctor#4438]
I am not sure if this is known/expected behavior or if it can be considered a bug.

I get, to me, unexpected/different results, when rendering the following text using Asciidoctor / Asciidoctor PDF:
```
text starting here (`*`) until the `next-*` is affected by this behavior
```

The issue is that text between asterisks used in two distinct monospace 'blocks' is rendered either as bold text and `next-` additionally monospace (Asciidoctor to HTML) or as a single monospace  'block' (Asciidoctor PDF).  If I remove the backticks around the first asterisk, Asciidoctor PDF will render bold text, similar to Asciidcotor.

The behavior can be 'fixed' by escaping the first asterisk using a backslash (regardless whether the asterisk is enclosed by backticks or not) or by using the literal syntax.

I know that [text formatting](https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/#text-formatting) options may be mixed but I am still wondering if this is expected behavior or not, especially, because Asciidoctor and Asciidoctor PDF show different behavior.

I've created an [archive](https://github.com/asciidoctor/asciidoctor/files/11290360/asciidoctor-pdf-asterix_monospace_block.tar.gz) (GitHub doesn't allow me to upload Asciidoc files) including a minimal document to reproduce this behavior and the resulting PDF and HTML files.

I am using Asciidoctor PDF 2.3.7 [Asciidoctor 2.0.18]:
```
user@host: ~/tmp $ asciidoctor-pdf --version
Asciidoctor PDF 2.3.7 using Asciidoctor 2.0.18 [https://asciidoctor.org]
Runtime Environment (ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```

I've found a few issues that seem similar #4262, #3624 (unconstrained monospace does not change the behavior), #2020 but I'm not sure if the solutions, if any, are applicable here, especially because Asciidoctor and Asciidoctor PDF behave differently.

Thanks for taking the time to look at this issue and please close it if it is known/expected behavior since it can easily be worked around.

**Comment by mojavelinux** [comment]
What you are looking for is literal monospace. See https://docs.asciidoctor.org/asciidoc/latest/text/literal-monospace/

```
text starting here (`+*+`) until the `+next-*+` is not affected.
```

In the future, please direct usage questions to the chat first as requested by the issue template. If we determine there is a bug, then we can proceed with a new issue. This helps us to better maintain the project.

**Comment by wildcart** [comment]
What I am wondering about and that's the reason I've raised an issue here instead of posting a question in chat is the  difference between the rendered HTML and PDF: "all bold and `next-` as monospace" vs "all monospace". My expectation, on the other hand, is that an Asciidoc document is always rendered the same regardless of the chosen output format.

As stated in my initial post, I know how get the result I want using literal (monospace) syntax or escaping the first asterisk using a backslash. This, however, wasn't the main focus of the issue I tried to described and I am sorry that I didn't point this out more clearly in my initial post.

Again thanks for taking the time and I understand that you've closed the issue as you don't seem to consider the differences in the rendered Asciidoc document to be an issue.

Sorry for creating noise.

**Comment by mojavelinux** [comment]
The reason it is different in Asciidoctor PDF is because Asciidoctor PDF handles invalid HTML differently. The sample AsciiDoc you provided produces this HTML:

```
text starting here (<code><strong></code>) until the <code>next-</strong></code> is affected by this behavior
```

Now it's up to the renderer to figure out how to deal with that invalid output. HTML does things differently than PDF. That's not a product of the converter but rather of the renderer.

It's not guaranteed that valid HTML will be produced from AsciiDoc. There are many ways to make it invalid. We are working to try to limit this behavior in the spec, but the language is powerful enough that there will always be a way. Therefore, there are just certain things you need to know about the syntax in order to produce well-formed output. In this case, literal monospace is that tool.

> I understand that you've closed the issue as you don't seem to consider the differences in the rendered Asciidoc document to be an issue

I closed the issue because I believe the conversation should have happened in the chat, not that I don't care. I do think this discussion would have been appropriate for the chat. However, I was happy to provide some more context in this case since I can see how it looks like a bug.
