### ISSUE TITLE
include inline not work

### ISSUE THREAD

**Issue by Bastilla123** [asciidoctor/asciidoctor#4470]
When i make a include inline then it don't work. When i make include separate from text it works.

I insert a working and a not working version

I use 2.0.10 because in Ubuntu 20.04 it is newest version
[testadoc.zip](https://github.com/asciidoctor/asciidoctor/files/12028949/testadoc.zip)

**Comment by mojavelinux** [comment]
The include directive is a line-oriented preprocessor feature. It cannot be used on a line that contains any other content. This has been a rule in AsciiDoc ever since its inception. See https://docs.asciidoctor.org/asciidoc/latest/directives/include/

If you want to use a placeholder to insert dynamic content within a paragraph, then you would need to use an attribute reference, which includes the content of a document attribute. See https://docs.asciidoctor.org/asciidoc/latest/attributes/reference-attributes/

Another option is to write a custom inline macro which could read content from a file an insert it inline.

If you have further questions about how to use Asciidoctor, please direct them to the project chat at https://chat.asciidoctor.org.
