### ISSUE TITLE
double-dashes in role= attribute of link macro are replaced with em dash

### ISSUE THREAD

**Issue by positron96** [asciidoctor/asciidoctor#4476]
Hello. I'd like to report a behavior that I think is a bug.

I want to have a link with a custom class applied to it in the HTML output. To my knowledge, role attribute is designed especially for that, so my example code is:
```
link:/a/link[this is a link, role="class--name"]
```

I expect to see the output 
```
<a href="/a/link" class="class--name">this is a link</a>
```

However, my class name has double dashes in it, and they get converted into a em dash and zero width space, so the output is
```
<a href="/a/link" class="class—​&ZeroWidthSpace;name">this is a link</a>
```
Obviously, this breaks the styling as there is no such classname. 

I think this is a bug, as I would expect roles to be passed to output as-is without any conversion. 

I am experiencing this in asciidoc-jekyll plugin (which uses asciidoctor) and online editor here: https://asciidoc.org/#try (which may or may not be using asciidoctor). The real-world case of such classes is in this jekyll theme, for example: https://github.com/mmistakes/minimal-mistakes/blob/master/_sass/minimal-mistakes/_buttons.scss

Also, is there a short-term workaround?

**Comment by mojavelinux** [comment]
My first recommendation is to avoid using double dashes in the role name. The behavior is expected because the way the language is defined, this is a valid place for an emdash (though something we are working to fix in the specification).

One way to avoid the replacement is to escape the double dash.

```
link:/a/link[this is a link,role=class\--name]
```

For more information about escaping replacements, see https://docs.asciidoctor.org/asciidoc/latest/subs/prevent/
