### ISSUE TITLE
[docbook] `<quote>` and `<literal>` might get messed up.

### ISSUE THREAD

**Issue by debuglevel** [asciidoctor/asciidoctor#4477]
`asciidoctor --backend docbook5 test.adoc` (2.0.20) will transform this AsciiDoc

```asciidoc
= Test

aaa "`bbb` ccc `ddd`".
eee `fff`.
```

to this invalid XML: 

```
<?xml version="1.0" encoding="UTF-8"?>
<?asciidoc-toc?>
<?asciidoc-numbered?>
<article xmlns="http://docbook.org/ns/docbook" xmlns:xl="http://www.w3.org/1999/xlink" version="5.0" xml:lang="en">
<info>
<title>Test</title>
<date>2023-08-15</date>
</info>
<simpara>aaa <quote>bbb` ccc <literal>ddd</quote>.
eee `fff</literal>.</simpara>
</article>
```

Asciidoctor does also NOT recognize it produced an invalid XML. With due respect, I'd suggest to add a XML-validation step to the transformation. This way one would already know that Asciidoctor just produces something that will not work with most XML-consuming tools (e.g. `pandoc 3.1.2` will fail on this docbook).

**Comment by mojavelinux** [comment]
It's well established that an AsciiDoc processor can be persuaded to produce invalid XML if given the right sequence of markup characters. That is a known risk of using a lightweight markup language, in which any sequence of characters constitutes valid input. If you want to ensure that the output that Asciidoctor produces is valid XML, the onus is on you to add a validation step to your pipeline and fix errors accordingly. This is not something Asciidoctor is going to do.

We are working on defining the specification in such a way that this scenario becomes much less likely, perhaps even impossible. But it is not something that can be changed in Asciidoctor until that specification is complete and Asciidoctor conforms to it. Thus, there is no action to take as of right now.

**Comment by debuglevel** [comment]
Is there anything wrong with the given AsciiDoc at all? I did not even persuade Asciidoctor to produce invalid XML - I'd say that the `docbook5` backend just does not do what it should in this case.

That Asciidoctor should validate it's XML output was only an additional suggestion.
No tool on earth should ever produce invalid XML. That is just not the idea behind such a rigorously defined language like XML.

And yes, of course *some* people can add an additional step to their scripts or even pipelines to be warned about faulty software. But if I were a technical writer without deeper knowledge on XML, I would be highly irritated.

**Comment by mojavelinux** [comment]
> Is there anything wrong with the given AsciiDoc at all?

Unfortunately, yes. This sequence cannot be parsed. That's because the monospace takes precedence over the smart quotes, and since that leaves them interleaved, the result is a corrupt tree.

> No tool on earth should ever produce invalid XML.

Sorry, this is just how AsciiDoc is right now...and has always been. As I mentioned, we are working on rectifying this situation within reason in the specification, but it's incredibly hard work. Mapping a lightweight markup language that has been around for nearly two decades to formal language doesn't just come automatically. There are a lot of things to consider. If that is not acceptable to you, then you are free to use something else.

**Comment by mojavelinux** [comment]
If the goal is to enclose the monospace in straight quotes, it would need to be written as follows:

```
aaa \"``bbb`` ccc ``ddd``".
eee `fff`.
```

If the intent is to end up with curly quotes, I don't even know what the intent is since that leaves the monospace unclosed. Maybe it's supposed to be this?

```
aaa "`bbb`` ccc ``ddd`".
eee `fff`.
```

Either way, using unconstrained formatting is likely needed here to make the boundaries more deterministic.
