### ISSUE TITLE
Missing # sign in <a> tags when using IDs with a period in an xref

### ISSUE THREAD

**Issue by mmuehlfeldRH** [asciidoctor/asciidoctor#4479]
If an xref links to an ID that contains a period, the generated HTML code misses the # sign in the `<a>` tag.  Consequently, the generated link is invalid because it doesn't link to the anchor.

**Steps to reproduce**

1. Create an adoc file with the following content:
```
[id="example"]
= My Title

See the xref:my.id[section] below.


[id="my.id"]
== example

Hello world.
```
2. Run asciidoctor to convert the file to HTML.

**Actual results**

AsciiDoctor generates the following HTML code:
```
...
<p>See the <a href="my.id">section</a> below.</p>
...
<h2 id="my.id">example</h2>
...
```
The link to the anchor in the `<a>` tag misses the # sign in the href attribute. Consequently, clicking this link ends in a 404 error, instead of being sent to the anchor in the same document.

**Expected results**
```
...
<p>See the <a href="#my.id">section</a> below.</p>
...
<h2 id="my.id">example</h2>
...
```
The link in the `<a>` tag contains the # sign in the href attribute.

**Additional information**
The [AsciiDoctor docs](https://docs.asciidoctor.org/asciidoc/latest/attributes/id/#valid-id-characters) spell out that periods in IDs are valid (except as first character of an ID). These docs also link the [Name value definition of the XML specification](https://www.w3.org/TR/REC-xml/#sec-common-syn), which mentions "Note that ..., full stop (period),... are explicitly permitted".

**Comment by mojavelinux** [comment]
Your observation is correct. If you use the xref macro, and the path contains a dot, then it is assumed to be a reference to another document. Therefore, the leading `#` is not added. If you intend for it to be an internal reference, you must include the leading `#`. In other words:

* xref:foo.bar[text] will link to another document
* xref:#foo.bar[text] will link to an anchor in the same document
* <<foo.bar>> will link to an anchor in the same document (the presence of the dot is not considered in this case)

I'll update the documentation to be more clear about this.

Generally speaking, the dot is not recommended in an ID value since it is too easily confused with a file path. It's permitted, but it creates extra work.

In the future, please ask for clarification about the language in the project chat at https://chat.asciidoctor.org.
