### ISSUE TITLE
Localization (l10n)

### ISSUE THREAD

**Issue by ManDay** [asciidoctor/asciidoctor#4486]
This is a feature request for the localization of Asciidoctor.

As by [the documentation](https://docs.asciidoctor.org/asciidoctor/latest/localization-support/), which mentions the issue, there is an old discussion archived [here](https://discuss.asciidoctor.org/Professional-providers-translating-Asciidoc-tt2692.html#none), but I did not find any issue filed.

**Localization** in this case means the usual sense, that the entire software acts in accordance with the environment's locale in all relevant aspects, which, of course, includes the output itself. All without user effort required.

**Comment by ManDay** [comment]
What would, for example, speak against just performing the

```
include::/usr/lib64/ruby/gems/3.1.0/gems/asciidoctor-2.0.18/data/locale/attributes.adoc[]
```

unconditionally in the parser? It seems to realize proper l10n just fine and reliably. So why expect the user to do it manually?

**Comment by mojavelinux** [comment]
This request is already covered by #1129. In fact, my last comment explains that it is still open until this work is complete. https://github.com/asciidoctor/asciidoctor/issues/1129#issuecomment-432935284

If you are willing to propose or contribute an implementation strategy that is portable to all environments, feel free to do so. The only reason we are expecting the user to do it (as explained on https://docs.asciidoctor.org/asciidoctor/latest/localization-support/) is because it hasn't been otherwise implemented.
