### ISSUE TITLE
Support author nicknames in document metadata

### ISSUE THREAD

**Issue by Oblomov** [asciidoctor/asciidoctor#4503]
It is not uncommon for people to use/be known by a nickname that is also used in bylines, where it's commoly put in quotes.

Something along these lines:
```
= Voicing the Boulder
Michael Francis "Mick"  Foley <theboulder@example.com> ; Dwayne D.J. "The Rock" Johnson
```

This is currently not supported in Asciidoctor, and in fact adding any kind of quotes in the author line completely breaks parsing of the author entry, since the string fails to match the `AuthorInfoLineRx` regexp, and not even the email part is recognized.

I  can try my hand at implementing this, but while searching the issue tracker for relevant tickets I came across [this thread](https://github.com/asciidoctor/asciidoctor/issues/4365) that suggests that additional metadata may not be accepted upstream, so I'd prefer to know if such a contribution would be considered for inclusion (and thus I can work on a PR for it) or not (in which case I'd need to look for a way to implement it as an extension, which honestly in this case is going to come out hackier than I would like).

**Comment by mojavelinux** [comment]
First, any changes to the AsciiDoc syntax at this point have to go through the AsciiDoc Language project. Asciidoctor is transitioning to one of any number of implementations and can only make changes to the the syntax if proposed in that project (it could implement the proposal early on a case-by-case basis, but at the very least it must be proposed).

Having said that, the thread you linked accurately reflects our current thinking about author line (and the info lines in general). We don't want to make parsing author names any more complicated than it already is...and it's virtually impossible to consider all possible permutations. So we settled on the parsing described at https://docs.asciidoctor.org/asciidoc/latest/document/compound-author-name/. That's because the author line is meant to be a convenient shorthand for simple documents and we don't want to make the parsing unreasonably difficult. If you want an extra name, it must be combined to one of the three name slots using the `_` character. If you want to capture arbitrary metdata, you can use document attributes (e.g., `author_nickname`)

If you want different information to be displayed, my recommendation would be to extend the converter and/or use custom templates to create a custom document header in the output. In fact, we just merged an extended PDF converter that shows how this can be done. See https://docs.asciidoctor.org/pdf-converter/latest/extend/use-cases/#custom-article-title-with-document-details

Regardless, this is not the suitable issue tracker for this request. If you are only interested in customizing Asciidoctor, you can ask for assistance in the project chat at https://chat.asciidoctor.org.

**Comment by Oblomov** [comment]
Thanks for the extensive explanation @mojavelinux, I'll look more into the AsciiDoc Language project.
