### ISSUE TITLE
Stylesheet: Underline active footnote link

### ISSUE THREAD

**Issue by Larhzu** [asciidoctor/asciidoctor#4530]
Test case:

```
= Title

Foo.footnote:[Bar]
```

The link after Foo is underlined in active state (keeping the mouse button pressed down) but the link before Bar isn't underlined in active state.

The following could be added for consistency with `sup.footnote a:active` (and `#toc a:active`):

```
#footnotes .footnote a:first-of-type:active {
  text-decoration: underline;
}
```

Then the section anchors would be the only links without underline in active state, which looks fine to me.

**Comment by mojavelinux** [comment]
I agree there seems to be some inconsistency here. I checked and it has been like this every since I pushed the first revision of the stylesheet to the repository so I can't recall the reasoning behind it. Probably just an oversight (in an attempt to mimic the wikipedia styles).

If you would like to add the `#footnotes .footnote a:first-of-type:active` to the following selector, I'll merge it.

```
sup.footnote a:active,
sup.footnoteref a:active {
  text-decoration: underline;
}
```

Related to this, we are considering revamping the appearance of footnotes in a future release. See #4517.

**Comment by Larhzu** [comment]
> If you would like to add the `#footnotes .footnote a:first-of-type:active` to the following selector, I'll merge it.

It's #4534. Hopefully it's OK.

> Related to this, we are considering revamping the appearance of footnotes in a future release. See #4517.

Thanks! I don't think I have much to add, I find both C and A to be good choices.

**Comment by mojavelinux** [comment]
Thanks! I'll have a look at it asap.
