### ISSUE TITLE
Inline images don't have a scaledwidth with docbook5 output

### ISSUE THREAD

**Issue by kurthuwig** [asciidoctor/asciidoctor#4552]
If I use `scaledwidth` on an inline image like this.

    image:Png-Logo.png[scaledwidth=2cm]

then the resulting DocBook5 xml lacks the `width` attribute:

    <imagedata fileref="Png-Logo.png"/>

### Longer example:

    image::Png-Logo.png[scaledwidth=2cm]

    image::Png-Logo.png[width=2cm]

    image:Png-Logo.png[scaledwidth=2cm]

    image:Png-Logo.png[width=2cm]

yields

    <imagedata fileref="Png-Logo.png" width="2cm"/>
    <imagedata fileref="Png-Logo.png" contentwidth="2cm"/>
    <imagedata fileref="Png-Logo.png"/>
    <imagedata fileref="Png-Logo.png" contentwidth="2cm"/>

Asciidoctor 2.0.20 [https://asciidoctor.org]
Runtime Environment (ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux-musl]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)

Sample project (you need a PNG to actually run it - any one will work): [inline-image-scale.zip](https://github.com/asciidoctor/asciidoctor/files/14332066/inline-image-scale.zip)

**Comment by mojavelinux** [comment]
The scaledwidth attribute value is, in fact, carried through. However, it gets remapped to the `width` attribute in DocBook, whereas the `width` attribute gets mapped to the `contentwidth` attribute in DocBook. So the behavior is as expected and documented. See https://docs.asciidoctor.org/asciidoc/latest/macros/image-size/#scaledwidth-attribute and https://tdg.docbook.org/tdg/5.1/imagedata. DocBook doesn't have a scaledwidth attribute (it's named `width` and acts as a scaled width).

**Comment by kurthuwig** [comment]
The `scaledwidth` attribute is not carried through, if you use an inline image:

    image:Png-Logo.png[scaledwidth=2cm]

yields

    <imagedata fileref="Png-Logo.png"/>

while the documentation reads

> The scaledwidth attribute in AsciiDoc is mapped to the width attribute on the imagedata tag in DocBook

This behavior breaks pandoc's DOCX export, as it requires the `width` attribute of the `imagedata`. Without it, the images appear unscaled.

**Comment by mojavelinux** [comment]
I see where the confusion is. The scaledwidth is honored for block images, but not for inline images. You can see that the DocBook converter never checks for the scaledwidth attribute when converting an inline image. https://github.com/asciidoctor/asciidoctor/blob/main/lib/asciidoctor/converter/docbook5.rb#L556-L557 The reason this is the case is because Asciidoctor's predecessor (AsciiDoc.py) never supported scaledwidth on inline images. However, Asciidoctor PDF does...so it's reasonable to expect that the DocBook converter does too.

Note that the only time an inline image should be used is when it's in the middle of a paragraph or a normal table cell. It should never be used in place of a block image.

**Comment by kurthuwig** [comment]
My use case is a documentation of an app. I need to add screenshots of the app to show the different features. I like to have them side by side, so that I can put more than 2 screenshots on a page - right now I scale them so that I can put 4 of them in 1 row. This allows me to put the screenshots together with the description text on one page of the DOCX document.

It's internal technical documentation, so we care more about tracking it in Git than the styling. From your answer I understand that I could use tables, but this feels wrong to me. Still, I'll use what is there.

**Comment by mojavelinux** [comment]
I wasn't disagreeing that this should be added. Since you were mixing block and inline images in the example you provided, I thought you were suggesting that scaledwidth was not supported at all. But when I examined it closer, I realized you were making a distinction between the two image macros. I'm going to add support for scaledwidth for inline images in the next point release.
