### ISSUE TITLE
Support Asciidoc in Annotation

### ISSUE THREAD

**Issue by HamidrezaSafari** [asciidoctor/asciidoctor#4558]
Annotations are very handy to contain log snippets. It can be referred to with the [ANNOTATION] tag.

**Comment by ggrossetie** [comment]
This is related to https://github.com/asciidoctor/asciidoctor/issues/1692 and as mentioned by Dan, it's possible to extend the converter to recognize additional admonition styles since the style sits in the custom block macro position. 

At this point, I don't think we are going to add new admonition type.
