### ISSUE TITLE
Indentation breaks ancestor list continuation in the case of nested lists

### ISSUE THREAD

**Issue by m-kru** [asciidoctor/asciidoctor#4575]
```
Asciidoctor PDF 2.3.15 using Asciidoctor 2.0.22 [https://asciidoctor.org]
```

I am not sure whether this issue should be created in this repository or in https://github.com/asciidoctor/asciidoctor-pdf, so forgive me if I am wrong.

While working with lists I like to indent them to improve readability. However, I have observed that indentation breaks nested lists with ancestor continuation blocks. For example, lets consider the following simple example:

```adoc
. One
  * Bullet 1
  +
  --
    ** Bullet 2
  --
  +
  Continuation of bullet 1
```
The output from asciidoctor-pdf looks like this:
![image](https://github.com/asciidoctor/asciidoctor/assets/26227737/fb2122e1-b7d4-4d24-b20d-d6223c71832e)

To get the correct continuation I have to remove indentation. The following snippet
```adoc
. One
* Bullet 1
+
--
** Bullet 2
--
+
```
produces the following desired output:

![image](https://github.com/asciidoctor/asciidoctor/assets/26227737/caf62e6a-fbc6-4583-859d-40830359af05)

I wonder whether it was designed like this or maybe there is some kind of bug? If this is the expected behavior, I wonder whether there is some way to indent nested lists in the .adoc files for better readability and still have ancestor list continuation rendered properly in the generated pdf file.

**Comment by mojavelinux** [comment]
> I wonder whether it was designed like this or maybe there is some kind of bug?

Yes, this is the way the AsciiDoc language is designed. Blocks attached to a list item must be left-aligned. See https://docs.asciidoctor.org/asciidoc/latest/document-structure/#blocks and https://docs.asciidoctor.org/asciidoc/latest/lists/continuation/#list-continuation (Just because indentation is used for list nesting in some languages doesn't mean it applies for AsciiDoc as well).

> I am not sure whether this issue should be created in this repository or in asciidoctor/asciidoctor-pdf, 

The correct place to ask usage-related questions is the project chat at https://chat.asciidoctor.org. This is stated in the issue template.
