### ISSUE TITLE
Monospaced table cell baseline

### ISSUE THREAD

**Issue by sdavids** [asciidoctor/asciidoctor#4596]
## Observed vs. expected behavior

The baseline is incorrect.

![322480361-03db6e82-8d6b-487a-9737-213ea7e3a27b](https://github.com/asciidoctor/asciidoctor/assets/201931/8b509d39-8aed-4101-964d-637a791e37c5)

## Reference

[AsciiDoc - Format Content by Cell](https://docs.asciidoctor.org/asciidoc/latest/tables/format-cell-content/)

## Steps to reproduce

```asciidoc
[%header,cols=",^m,<m,>m"]
|===

|A | B | C | D

|1
|2
|3
|4

|===
```

## Related Issue

> The vertical alignment issue you reported here is part of the CSS stylesheet maintained by the Asciidoctor project.

_Originally posted by @ahus1 in https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/1601#issuecomment-2132256232_

**Comment by mojavelinux** [comment]
This behavior is due to the fonts being different. There is no expectation that a monospaced font will be positioned exactly the same as a non-monospaced font, or even be the same height. Simply put, the cells have different formatting.

If you have a proposal for how the baselines can be better aligned without impacting the appearance of a monospaced cell, you are free to bring that proposal forward. (You are also free to customize the stylesheet if you prefer a different appearance) But as far as I'm concerned, this is not an issue that needs to be resolved.
