### ISSUE TITLE
Asciidoctor produces invalid XML with `*`

### ISSUE THREAD

**Issue by feliksik** [asciidoctor/asciidoctor#4599]
With this asciidoc: 

```
This is a `*` weird `*` bold thing.
```

Asciidoctor produces invalid XML:

```
<p>This is a <code><strong></code> weird <code></strong></code> bold thing.</p>
```

Even though one can argue the given input doesn't make sense (actually I should have done `+*+` instead of `*` -- which gives what I intended), I suppose asciidoctor should never give invalid XML.

**Comment by mojavelinux** [comment]
Asciidoctor is not guaranteed to generate well-formed output. If the AsciiDoc is invalid, so will the output. This is not something that can be easily solved through programming logic as the intent of the author is unclear. When this happens, you need to fix the AsciiDoc source.

If you need help writing AsciiDoc, please direct your question to the project chat at https://chat.asciidoctor.org.

**Comment by feliksik** [comment]
> This is not something that can be easily solved through programming logic as the intent of the author is unclear.

I understand -- I take it that this is invalid AsciiDoc (i'm insufficient expert on the language).  And in this case, you consider it acceptable to output invalid XML; indeed, one can argue that this is better than no output at all, and/or that creating a valid XML gives some implicit semantics you don't want to endorse.  

However, the least asciidoctor could do is **_emit an error or a warning_**. The input is human crafted, so feedback to that human is appropriate.

**Comment by mojavelinux** [comment]
It simply not possible for Asciidoctor to emit and detect a warning as it is creating the output. For one, there are an infinite number of permutations, so it's not possible to account for them all. Two, it's just not how Asciidoctor is implemented because it stream converts the inlines. This is something that will be address in the AsciiDoc language proejct as we are adopting an inline grammar, but that is at least a year out from landing in Asciidoctor.

In the meantime, you are welcome to add a validator to the output after Asciidoctor runs, either as a separate program or as a postprocessor extension.
