### ISSUE TITLE
broken conversion of emphasis + superscript from asciidoc to docbook_xml using asciidoctor

### ISSUE THREAD

**Issue by osamuaoki** [asciidoctor/asciidoctor#4628]
I used asciidoctor (2 versions are tested: docker image=2.0.23 and Debian/stable=2.0.18) for test and I encounter the following broken output for DocBook while HTML doesn't suffer this problem.  See below for test sample data, buggy result, and `Makefile` to reproduce bug.

Input file (test.asc):
```
// vim:set filetype=asciidoc:
= TEST

* B^SUPER^E
* B**^SUPER^**E
* B^*SUPER*^E
* B^**SUPER**^E
```

DocBook conversion result below (the first 2 itemized lines are good, the last 2 itemized lines are bad):
```
<?xml version="1.0" encoding="UTF-8"?>
<?asciidoc-toc?>
<?asciidoc-numbered?>
<book xmlns="http://docbook.org/ns/docbook" xmlns:xl="http://www.w3.org/1999/xlink" version="5.0" xml:lang="en">
<info>
<title>TEST</title>
<date>2024-10-01</date>
</info>
<preface>
<title></title>
<itemizedlist>
<listitem>
<simpara>B<superscript>SUPER</superscript>E</simpara>
</listitem>
<listitem>
<simpara>B<emphasis role="strong"><superscript>SUPER</superscript></emphasis>E</simpara>
</listitem>
<listitem>
<simpara>B^<emphasis role="strong">SUPER</emphasis>^E</simpara>
</listitem>
<listitem>
<simpara>B^<emphasis role="strong">SUPER</emphasis>^E</simpara>
</listitem>
</itemizedlist>
</preface>
</book>
```

You see non-converted-`^`s. 

HTML page doesn't have this problem.

FYI: My `Makefile` :
```
ASCIIDOC := podman run -it -v .:/documents/ \
  docker.io/asciidoctor/docker-asciidoctor asciidoctor
DOCNAME := test
all: test.html test.xml

clean:
	rm -rf *.xml *.html


%.xml: %.asc
	$(ASCIIDOC) --doctype book\
		-b docbook \
		-a 'newline=\n' \
		$<

%.html: %.asc
	$(ASCIIDOC) --doctype book\
		-b html \
		-a toc2 \
		-a 'newline=\n' \
		$<
```

**Comment by mojavelinux** [comment]
Although the result may seem surprising, it is behaving as expected. As stated in "Superscript and subscript have unique boundary constraints in AsciiDoc that are neither constrained nor unconstrained. They are unconstrained with the key restriction that the text must be continuous." The bold formatting, which is converted first, outputs `<emphasis role="strong">`. The space in the tag disrupts the superscript formatting. It's a quirk of the DocBook output since there is no way to express bold text with a bare tag.

In order for this to work, as passthrough is required:

```
B^pass:q[*SUPER*]^E
```

This restriction may or may not be lifted by the AsciiDoc Language project. It's still open for debate. Superscript is really only intended to be used for suffixes such as `4^th^`. Any more advanced usage needs to be cited and defended in order for the language to consider expanding its scope.

**Comment by osamuaoki** [comment]
I now understand the reason why HTML converter worked.
Yes, this is user issue.  (I.e., my problem)

I will use `B^pass:q[*SUPER*]^E`.

Thanks for your kind help.
