### ISSUE TITLE
Multiple inline quoted tags return incorrect text

### ISSUE THREAD

**Issue by benjaminleonard** [asciidoctor/asciidoctor#4629]
In this example I have the inline quoted text selecting text outside of the quote tags if the quote tag for the inline quoted block also occurs before the relevant text. 

The link in the following example was broken with my renderer. Coincidentally this example _does_ technically work with the default HTML5 renderer (if there's no role or ID) but I think thats a fluke, since the text is rendered unchanged.

Sample document:
```adoc
* https://docs.asciidoctor.org/#_anchor_link[Anchor Link] or _inline quoted_
```

`node.text` returns `anchor_link[Anchor Link] or _inline quoted` instead of  what I'd expect:`inline quoted`

**Comment by mojavelinux** [comment]
This is expected behavior given the current state of the language. The underscore in the URL forms a formatted text match and is thus converted as such. Formatting characters in a URL must be escaped properly. See https://docs.asciidoctor.org/asciidoc/latest/macros/complex-urls/

This is a general problem we are addressing in the language by having URLs be protected from formatting and by better restricting the boundaries of the emphasis phrase. However, those changes will not be seen in Asciidoctor until after the first version of the specification is finalized.

If you would like to discuss the syntax further, you are free to do so in the project chat at https://chat.asciidoctor.org. The issue tracker is reserved for verified bugs, which usually is a conclusion we arrive at in the chat. Otherwise, the issue tracker just gets filled up with reports for which there will be no action.

**Comment by benjaminleonard** [comment]
Understood, thanks for taking a look
