### ISSUE TITLE
Add support for math formulas (latexmath or asciimath)

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#492]
Add support for math formulas. In the HTML backend, the approach taken by AsciiDoc is to pass through LaTeXMathML or AsciiMathML formula without apply substitutions, then using a JavaScript library to render them.

Examples:

```
.Block macro
latexmath::[$C = \alpha + \beta Y^{\gamma} + \epsilon$]

.Delimited block
[latexmath]
++++
\[C = \alpha + \beta Y^{\gamma} + \epsilon\]
++++

.Inline macro
latexmath:[$C = \alpha + \beta Y^{\gamma} + \epsilon$]
```

Since it's just a pass through block wrapped in a dedicated template (HTML and DocBook) and a JavaScript library in HTML, it shouldn't be too hard to implement.
- [LaTeXMathML](https://www.maths.nottingham.ac.uk/personal/drw/lm.html)
- [AsciiMathML](http://www1.chapman.edu/~jipsen/mathml/asciimath.html)

We should probably also be looking at [MathJax](http://www.mathjax.org), which is a more modern math renderer library.

**Comment by nh2** [comment]
Question: Now that MathJax is supported, is the `stem=latexmath` syntax still restricted to the syntax that LaTeXMathML supports, or is it anything that MathJax supports?

The [docs say here](http://asciidoctor.org/docs/user-manual/#stem):

> Asciidoctor supports [...] LaTeXMathML formulas and renders them with the MathJax JavaScript library.

I'm asking because LaTeXMathML seems to be more restrictive in what it can handle as compared to MathJax.

**Comment by jxxcarlson** [comment]
Asciidoctor supports anything that you can do in MathJax because Asciidoctor passes math text
on to MathJax for rendering.  The below is a longer answer.  It is Asciidoctor text
that you should read first as-is then render with

  $ asciidoctor -a stem=latexmath foo.adoc

Please let me know if you have further questions.

— Jim

http://www.noteshare.io <http://www.noteshare.io/>

========
== LaTeX plus Asciidoctor

Write inline mathematics like \(a^2 + b^2 = c^2 \).

Write display mathematics like this
\[
\int_0^1 x^n= \frac{1}{n+1}
\]

Render this file using `asciidoctor -a stem=latexmath`.

== Noteshare

http://noteshare.io is an Asciidoctor site designed
by and for mathematicians.  It supports the usual
`$...$` notation for inline mathematics.  See
http://epsilon.my.noteshare.io/section/mathematics-article[this link]
for more info, examples, and how-two instructions.  See 
 http://epsilon.my.noteshare.io/section/introduction[Hodge Theory]
 for a longer document (draft, in progress).
 
Noteshare supports the forthcoming Asciidoctor-latex extensions.
They permit you to write the following for a LaTeX-style
theorem environment (automatically numbered):
 
----
[env.theorem]
--
If $a$, $b$, and $c$ are the sides 
of a right triangle with $c$ the
hypotenuse, then $a^2 + b^2 = c^2$
--
----

For a numbered equation environment, write this:
 
----
[env.equation]
--
\sum_{n=0}^\infty \frac{1}{n} = \infty
--
----

Put the code `:latex:` somewhere in your Noteshare document
to make sure that math rendering is turned on.
 
Noteshare is in beta test.  To get an account, use the 
access code C7092 and go to http://www.noteshare.io/[www.noteshare.io].
Notehsare provides a frictionless way of publishing mathematics
on the web: open up the two-pane editor, type your source in the left
pane, press *update* to save an update the rendered display on
the right, and it is on the web!  (Or use ctrl-U to update).

== Coming soon

Asciidoctor-latex, an extension to Asciidoctor, is under development.
When released, you will be able to use the features described
in the previous section by saying `asciidoctor-latex -b html foo.adoc`.
 


To create content on Noteshare, you need an account.
	
===

**Comment by nh2** [comment]
> Asciidoctor supports anything that you can do in MathJax because Asciidoctor passes math text on to MathJax for rendering.

So `LaTeXMathML` is not used at all any more? Should the reference be stripped from the documentation?

**Comment by mojavelinux** [comment]
> Asciidoctor supports anything that you can do in MathJax because Asciidoctor passes math text on to MathJax for rendering.

Well said, James!

> So LaTeXMathML is not used at all any more? Should the reference be stripped from the documentation?

Perhaps you are confusing AsciiMathML and LaTeXMathML. MathJax supports both. Which of these is used depends on what you specify on the block (asciimath or latexmath) or globally (using the `stem` attribute).

In other words, if you specify `latexmath` on the block (or globally), then MathJax will process the content as LaTeX math. For example:

```
[latexmath]
++++
\int_0^1 x^n= \frac{1}{n+1}
++++
```

As far as I understand, that is the LaTeXMathML you are referring to. Is it not?

**Comment by jxxcarlson** [comment]
The followinng is not quite on topic, but close.

I’ve been using `foo` and’

```
foo, bar
```

a lot.  This is comparable to the mathematician’s $foo^2$, $$foo^2 = foo^3$$, etc.  Great for typing, bad because the beginning and end delimiters are the same.

After conversations with some users, I recently installed the map $$…$$ => \[ .. \] for LaTeX users in Noteshare. The map is not active for “normal” users.


http://noteshare.io

**Comment by nh2** [comment]
@mojavelinux:

> As far as I understand, that is the LaTeXMathML you are referring to. Is it not?

No, what I meant is [this LaTeXMathML](https://www.maths.nottingham.ac.uk/personal/drw/lm.html), an unmaintained Javascript library.

**Comment by mojavelinux** [comment]
Ah, I see. We only support the LaTeX math that MathJax supports. Then again, Asciidoctor doesn't actually touch the LaTeX content, so technically you could load any JavaScript library you want if you don't want to use MathJax. That would require supplying a custom template (see https://github.com/asciidoctor/asciidoctor-backends/tree/master/slim/html5).

Is there a place we mention that we support the JavaScript library you mention? I'm pretty sure it's clear in the Asciidoctor user manual that we are only using MathJax.

**Comment by nh2** [comment]
> Is there a place we mention that we support the JavaScript library you mention? I'm pretty sure it's clear in the Asciidoctor user manual that we are only using MathJax.

Yes, in the link I posted [above](https://github.com/asciidoctor/asciidoctor/issues/492#issuecomment-70819577), where I wrote
> [the docs say here](http://asciidoctor.org/docs/user-manual/#stem)

You link to that page; maybe it was just forgotten to take it out when MathJax replaced it?

**Comment by mojavelinux** [comment]
Aha! I see where the confusion is coming from. I didn't notice the link to the LaTeXMathML page the first time. I'll fix that so it explains the situation accurately. Thanks for pointing it out!

**Comment by mojavelinux** [comment]
Fixed! Let me know if you would like to see further corrections to that section.

**Comment by nh2** [comment]
Thanks!
