### ISSUE TITLE
Extract bibliography references from text and validate them

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#560]
The bibliography references should be identified in the text and cataloged during parsing in the same way anchors are scanned. This references allow text from the bibliography (such as the resource's title) to be displayed inline in the rendered output.

**Comment by tduchateau** [comment]
+1 for cross references. It can happen to refactor the TOC, e.g. reversing the order of sections, and forget to update an anchor. Some kind of error reporting at build time would help a lot.

**Comment by farleylai** [comment]
Is it possible to render the bibliography in the IEEE format?
That is an ordered list with numbers in brackets from the previous example,

[1] Burgundy, Ron, 2004
[2] Mac, Freddie, 2010
[3] Mae, Fannie, 2002

**Comment by mojavelinux** [comment]
The current solution for this is asciidoctor-bib (or its predecessor, asciidoc-bib).

https://github.com/ProgramFan/asciidoctor-bibtex

We do want to eventually have support in core, but the exploration is being done in this gem.

**Comment by farleylai** [comment]
I tried the asciidoctor-bibtex and it works as expected except that the ordered list is in the default style. It seems non-trivial to generate ordered list with numbers in brackets ([1], [2], [3]...). Is it possible to customize the ordered list?

Another related support is about the \ref{marker} notation in latex which always references the correct sequence numbers of figures, listings and so on in case of any rearrangement, additions or removals. It seems like another issue was posted to address this. Will it be included in the next version?

https://github.com/asciidoctor/asciidoctor/issues/858

Lastly, to replace latex, supporting multi-columns and cross-columns float objects (figures and tables...) is quite essential. PubCSS shows it is possible to format HTML in the ACM/IEEE paper format.

https://github.com/thomaspark/pubcss

I am wondering if AsciiDoc plans to provide supporting syntax such that some html/pdf extension backend is able to automate this process.

**Comment by zaxebo1** [comment]
what i finally myself did was that i now write the research papers in a my own hackish markup dialect of asciidoctor. Which when preprocessed with my tool, which generates 
(A) generates pure asciidoctor document . Good for viewing my paper in html files with asciidoctor's css themes, so as to integrate better with my other asciidoctor based documents.
OR (B) generates pandoc+citeproc document.  As citeproc of pandoc, cupports various CSL (citation style https://en.wikipedia.org/wiki/Citation_style_language ) So, i easily get away from curent limitations of asciidoctor.  

This is hackish solution, but works well.  :laughing:  
I had to resort to this hack, because  "new backend writing" of asciidoctor is not documented and also because pretty MS-Word output options of the research paper level document - are pretty nonexistent for asciidoctor.

**Comment by zaxebo1** [comment]
once asciidoctor has CSL( http://citationstyles.org/ )( https://en.wikipedia.org/wiki/Citation_Style_Language)  support; only then we can finally start the work of what scholdoc ( scholdoc.scholarlymarkdown.com ) etc. are doing for pandoc/markdown for academic writing

**Comment by ceefour** [comment]
I am hoping to be able to use Asciidoctor for my current (and future ) dissertation proposal.
However this issue is splitting me between Asciidoctor and scholdoc.
The plan is to ask other researchers and collaborators in our community to move from Word to text based markup with GitBook collaboration. There are challenges with both Asciidoctor and scholdoc so any solution would be appreciated.
Citation management is one.
Any suggestions?

**Comment by mojavelinux** [comment]
This is needed for Asciidoctor EPUB3 so it can validate the reference to the bibliography.

**Comment by mojavelinux** [comment]
The parser happens to be finding bibliography references in normal prose (aka paragraphs). However, that's not a valid location for a bibliography entry. Therefore, we shouldn't be matching those. Instead, we should only be looking for them at the start of list item text in a bibliography list.

**Comment by mojavelinux** [comment]
It's almost pointless to resolve this issue without resolving #1562, so I'll pull that one in to this fix.
