### ISSUE TITLE
Swap the function of the backtick and plus characters

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#718]
The plus character is used for passthrough blocks (`++++`) and inline passthroughs (`+++`). However, single plus (`+`) and double plus (`++`) are used for monospace formatting **without** passthrough semantics.

The AsciiDoc syntax would be easier to understand if the plus character is consistently used for passthrough semantics. This can be accomplished by swapping the function of the backtick and plus characters in inline substitutions.

Given:

```
:app: asciidoctor
:interface: Decorator

+{app}+ resolves to `{asciidoctor}`

++{interface}++s resolves to ``{interface}``s.
```

Expect:

```
<code>{app}</code> resolves to <code>asciidoctor</code>

<code>{interface}</code>s resolves to <code>Decorator</code>s
```

Enable this change only when a special attribute is set. The proposed name for this attribute is `plus-passthroughs`.

This change depends on #714.

**Comment by memreflect** [comment]
This is an unfortunate change for me.
I just tried rendering <code>+$$&#96;echo foo&#96;$$+</code>, which renders as normal text

> &#96;echo foo&#96;

instead of the expected

<code>&#96;echo foo&#96;</code>

Unfortunately, `:compat-mode: legacy` is the only valid workaround to maintain compatibility with asciidoc.py (a.k.a. "legacy AsciiDoc") and Asciidoctor.

And if you happen to see it render oddly in HTML output in your own tests, then it's an issue with the version of "Noto Serif" currently hosted by Google Fonts; i have an updated version installed locally that renders correctly.
See google/fonts#2202 for a related bug with "Noto Sans" and google/fonts#3629 for the existing request to update "Noto Serif".
