### ISSUE TITLE
[[tag]] in section title shouldn't be rendered in TOC

### ISSUE THREAD

**Issue by fishy** [asciidoctor/asciidoctor#840]
Have the following as section title:

```
[[auth]]Section auth
```

It's rendered in TOC as:

``` html
<a href="#__a_id_auth_a_section_auth"><a id="auth"></a>Section auth</a>
```

Because of the a tag inside an a tag thing, the link won't be rendered in Chrome. Also the a tag inside will cause 2 anchors of "auth".

**Comment by mojavelinux** [comment]
Coming back to this, I remembered that if you move the anchor to the end of the section title rather than the beginning, that's the inline way of assigning an id (not an inline anchor point).

```
== Section auth [[auth]]
```

You only use the prefix version when you want to add additional anchor points. And it's in those cases we need to make sure it doesn't show up in the TOC.

**Comment by mojavelinux** [comment]
Here's a specific example I think we should test for. This is a recognized way to assign an id and add an additional anchor point to a section title.

```
== Section A[[origins]] [[section-a]]
```

Here, the id is reasonable (since it's explicit), but a duplicate anchor shows up in the TOC entry, rendering the HTML document invalid.

**Comment by mojavelinux** [comment]
I think in general, we need to clean `<a>` tags from the section title when generating the id and when rendering them in the TOC. That's the actionable item here.

**Comment by mojavelinux** [comment]
I'm reclassifying as a bug since this a) creates a duplicate ID in the document and b) renders the link in the TOC unusable.
