### ISSUE TITLE
[source,indent=0] does not replace tabs with spaces unless the first character is whitespace

### ISSUE THREAD

**Issue by philwebb** [asciidoctor/asciidoctor#841]
It would be useful if `[source,indent=0]` could be used to replace tabs with spaces in source blocks. Unfortunately this only works if the first character is whitespace:

https://github.com/asciidoctor/asciidoctor/blob/3245bcacd49a812a900925f0816e9601a02fe2d3/lib/asciidoctor/lexer.rb#L2560

In other words:
```
[source,java,indent=0]
[subs="verbatim,quotes"]
---
	// this will work
	// line 2
---
```

```
[source,java,indent=0]
[subs="verbatim,quotes"]
---
// this will not work
	// line 2
---
```

**Comment by mojavelinux** [comment]
We're going to implement this right in Asciidoctor 1.5.3 (in fact, I've already done it in Asciidoctor PDF).

As a side note, it is possible to control the tab size in HTML using CSS for the tabs that do slip through in the interim. Set the tab-size property on the pre element. See https://developer.mozilla.org/en-US/docs/Web/CSS/tab-size

**Comment by mojavelinux** [comment]
This is also related to #1170.

**Comment by mojavelinux** [comment]
With the fix for this issue, tabs are always replaced with spaces in verbatim blocks (but not literal paragraphs) if the `tabsize` attribute is set on the document and > 0. It's no longer required to use the `indent` property to enable tab expansion.

If you want to disable tab expansion, don't set the `tabsize` attribute on the document or set the `tabsize` attribute on the block to 0 (or less).

**Comment by mojavelinux** [comment]
Btw, you can also set `source-indent` to 0 on the document to apply `indent=0` to all source blocks. See https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/parser.rb#L841-L843
